### PR TITLE
Fix degiro keys setup and improve 2FA authentication

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

This PR fixes the issue with setting up username and password for Degiro api in `keys` raised in https://github.com/OpenBB-finance/OpenBBTerminal/pull/2143 by @JerBouma. It also adds a new way to login for users with 2FA authentication enabled on Degiro through `login` command in `degiro` sub-menu.

- [x] Summary of the change / bug fix.
- [x] Relevant motivation and context. 

# How has this been tested?

* Go to `keys` and type credentials `degiro -u USERNAME -p PASSWORD`
*  Go to `/portfolio/bro/degiro` and type `login` if no 2FA
*  Go to `/portfolio/bro/degiro` and type `login -otp ONETIMEPASSWORD` if 2FA enabled 

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by montezdesousa** [comment]
> It doesn't matter for me:
> 
> ```
> 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ login
> Error: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> 
> You are now logged in !
> 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ hold
> Error: Connection required.
> 
> 0 position found.
> 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $
> ```
> 
> Even after a completely fresh installation of the terminal.

Can you try leaving and reentering the terminal after setting the keys and then login on degiro menu pls? Just to understand if it's a similar issue I run into today.

**Comment by JerBouma** [comment]
> > It doesn't matter for me:
> > ```
> > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ login
> > Error: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> > 
> > You are now logged in !
> > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ hold
> > Error: Connection required.
> > 
> > 0 position found.
> > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Even after a completely fresh installation of the terminal.
> 
> Can you try leaving and reentering the terminal after setting the keys and then login on degiro menu pls? Just to understand if it's a similar issue I run into today.

Unfortunately doesn't change a thing. I still receive the same error. Could it be my password? It contains all types of symbols (e.g. #!@)

**Comment by montezdesousa** [comment]
> > > It doesn't matter for me:
> > > ```
> > > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ login
> > > Error: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> > > 
> > > You are now logged in !
> > > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ hold
> > > Error: Connection required.
> > > 
> > > 0 position found.
> > > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Even after a completely fresh installation of the terminal.
> > 
> > 
> > Can you try leaving and reentering the terminal after setting the keys and then login on degiro menu pls? Just to understand if it's a similar issue I run into today.
> 
> Unfortunately doesn't change a thing. I still receive the same error. Could it be my password? It contains all types of symbols (e.g. #!@)

If don't mind temporarily changing your password just to rule that out... I actually did tests with a password with special character so should not be an issue. Any ideas on what could be the problem @Chavithra ?

**Comment by JerBouma** [comment]
> > It doesn't matter for me:
> > ```
> > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ login
> > Error: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login
> > 
> > You are now logged in !
> > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ hold
> > Error: Connection required.
> > 
> > 0 position found.
> > 2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Even after a completely fresh installation of the terminal.
> 
> Can you try leaving and reentering the terminal after setting the keys and then login on degiro menu pls? Just to understand if it's a similar issue I run into today.

I tried and it doesn't change a thing unfortunately.

**Review by Chavithra — APPROVED** [review]
Looks good to me.

We need to check @JerBouma issue in another PR

**Comment by JerBouma** [comment]
@Chavithra @montezdesousa 

Found the issue, I input my email instead of username. However, there needs to be a test that checks if it actually works. This can simply be calling `login` (and logging off as well) otherwise troubleshooting is tough.

`│    degiro                 DEGIRO                     defined, not tested `

**Comment by montezdesousa** [comment]
> @Chavithra @montezdesousa
> 
> Found the issue, I input my email instead of username. However, there needs to be a test that checks if it actually works. This can simply be calling `login` (and logging off as well) otherwise troubleshooting is tough.
> 
> `│ degiro DEGIRO defined, not tested `

Nice!! I can look into that, meanwhile this https://github.com/OpenBB-finance/OpenBBTerminal/pull/2143 is already testable with your own ETFs then.

**Comment by xapel** [comment]
I am still not able to login to Degiro. I have 2FA set up. Perhaps it is because originally I used `degiro -u USERNAME -p PASSWORD -s ''`, because I thought I had to provide the s parameter. How do I clear the degiro information so I can start from scratch?

**Comment by montezdesousa** [comment]
> I am still not able to login to Degiro. I have 2FA set up. Perhaps it is because originally I used `degiro -u USERNAME -p PASSWORD -s ''`, because I thought I had to provide the s parameter. How do I clear the degiro information so I can start from scratch?

Hi @xapel, API keys are stored in a .env file in your installation folder. E.g. "C:\Users\username\OpenBB\.env".

You have more instructions on Degiro login with 2FA here: https://openbb-finance.github.io/OpenBBTerminal/terminal/portfolio/bro/degiro/

**Comment by xapel** [comment]
Do you know where I find this file on macOS?

**Comment by xapel** [comment]
I managed to find the file at `/Users/<username>/.env`.
I deleted the degiro entries and then restarted openBB and went into keys menu and did `degiro -u USERNAME -p PASSWORD`. This time there were no error messages. It just said `defined, not tested`
Then I went to the portfolio/bro/degiro menu.
```
2022 Sep 13, 04:57 (🦋) /portfolio/bro/degiro/ $ login -otp 880352
Error: 'NoneType' object is not callable

You are now logged in !
2022 Sep 13, 04:58 (🦋) /portfolio/bro/degiro/ $ hold
Error: 'NoneType' object is not callable

0 position found.
2022 Sep 13, 04:58 (🦋) /portfolio/bro/degiro/ $
```

**Comment by montezdesousa** [comment]
> I managed to find the file at `/Users/<username>/.env`. I deleted the degiro entries and then restarted openBB and went into keys menu and did `degiro -u USERNAME -p PASSWORD`. This time there were no error messages. It just said `defined, not tested` Then I went to the portfolio/bro/degiro menu.
> 
> ```
> 2022 Sep 13, 04:57 (🦋) /portfolio/bro/degiro/ $ login -otp 880352
> Error: 'NoneType' object is not callable
> 
> You are now logged in !
> 2022 Sep 13, 04:58 (🦋) /portfolio/bro/degiro/ $ hold
> Error: 'NoneType' object is not callable
> 
> 0 position found.
> 2022 Sep 13, 04:58 (🦋) /portfolio/bro/degiro/ $
> ```

I can reproduce your error on 1.8. installer, but seems to work fine in the main branch for next release. If this issue still persists we get back to it.

**Comment by xapel** [comment]
I have upgraded to v1.9 now, but the issue is still the same for me. I cannot login to Degiro.

```
2022 Oct 11, 10:19 (🦋) /portfolio/bro/degiro/ $ login -otp 866218
Error: 'NoneType' object is not callable

You are now logged in !
2022 Oct 11, 10:19 (🦋) /portfolio/bro/degiro/ $ hold
Error: 'NoneType' object is not callable

0 position found.

```

**Comment by JerBouma** [comment]
I have the same issue, entered `keys` and entered both username and password as follows:

```
2022 Oct 11, 10:40 (🦋) /keys/ $ degiro -u MY_USERNAME -p MY_PASSWORD
defined, not tested
```

Then went into `portfolio/bro`:
```
2022 Oct 11, 10:40 (🦋) /portfolio/bro/degiro/ $ login
Error: 'NoneType' object is not callable

You are now logged in !
2022 Oct 11, 10:40 (🦋) /portfolio/bro/degiro/ $ hold
Error: 'NoneType' object is not callable

0 position found.
2022 Oct 11, 10:41 (🦋) /portfolio/bro/degiro/ $
```

Could you look into this @montezdesousa?

**Comment by montezdesousa** [comment]
> I have the same issue, entered `keys` and entered both username and password as follows:
> 
> ```
> 2022 Oct 11, 10:40 (🦋) /keys/ $ degiro -u MY_USERNAME -p MY_PASSWORD
> defined, not tested
> ```
> 
> Then went into `portfolio/bro/degiro`:
> 
> ```
> 2022 Oct 11, 10:40 (🦋) /portfolio/bro/degiro/ $ login
> Error: 'NoneType' object is not callable
> 
> You are now logged in !
> 2022 Oct 11, 10:40 (🦋) /portfolio/bro/degiro/ $ hold
> Error: 'NoneType' object is not callable
> 
> 0 position found.
> 2022 Oct 11, 10:41 (🦋) /portfolio/bro/degiro/ $
> ```
> 
> Could you look into this @montezdesousa?

@hjoaquim is fixing some stuff here https://github.com/OpenBB-finance/OpenBBTerminal/pull/2747, we can try to reproduce

**Comment by xapel** [comment]
I don't know how to test from main. Is there instructions for how to do this?

**Comment by hjoaquim** [comment]
**To update your main branch**:

1. `git remote --v`
image

2. `git fetch OpenBB-finance`

> Note that `OpenBB-finance` is my alias, you should look for yours with the described on (1)

image


3. Within your fork you can do: `git merge OpenBB-finance/main`

> Once again, `OpenBB-finance` is my alias!

image


**After**:

Just try the instructions you described above :blush:

**Comment by xapel** [comment]
I have the code checked out in a folder on my machine now. How do I proceed? Do I need to build it first? Or can I just run something from the terminal?

**Comment by hjoaquim** [comment]
@xapel in the meantime `degiro` seems to have the issues fixed. But if you have some improvements on it, feel free to add a Pull Request!

**Pull request merged**
