### PR TITLE
Bug/2583

### PR DESCRIPTION
**Pull request by catalintoma**
# Description

- [x] Refactored denomination usages by using a common helper
- [x] Fixed Yahoo Finance model not respecting 'thousands' denomination 
- [x] Fixed Yahoo Finance view not exporting raw data
- [x] #2583 

# How has this been tested?

- [x] Added YF model tests
- [x] Added tests for the denomination helper

# Checklist:

- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by catalintoma** [comment]
@DidierRLopes can you add the 'bug' label for this? If there is a way for me to set it on PR creation, please let me know to pay more attention.

I marked this as draft since I still want to improve the unit tests, but I am curious what you think about this approach. I've kind of wondered into to unknown with this with my limited Python skills, but felt there was room for refactoring all the places where we deal with converting denominations.

**Comment by colin99d** [comment]
Looks great so far! Nice work.

**Comment by DidierRLopes** [comment]
This is looking very nice @catalintoma ! Keep up the good work! 🤝

**Comment by catalintoma** [comment]
I've requested a review, I haven't seen anything else to fix.
Main refactoring's are around:

- Using helper for denomination transforms
- Fix YF model not returning raw data (numbers) and also not using correct 'thousands' denomination
- Fix YF view not exporting raw data

**Comment by colin99d** [comment]
Perfect! Will do later today.

**Review by colin99d — APPROVED** [review]
Great work man! Thanks for this pr.

**Pull request merged**
