### PR TITLE
Auto Generate API Documentation

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Automatically created documentation. #2352 needs to be merged before this PR is merged.

Things to think about:
- [ ] Should this auto-delete old-docs every time run?

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by minhhoang1023** [comment]
@colin99d Was trying out with pandas doc yesterday and as a reflection, there are a few things I want to change with the current doc format.

1. Adding the entire path with default values: This makes it easy for people to copy and paste to their notebook or applications
2. Add the kwargs `view=True` for the View documentation


So the updated one would look something like this.

# common.behavioural_analysis.sentiment_stats

To use a view, make sure to add `view=True` as the last parameter

## Using Model
### *common.behavioural_analysis.sentiment_stats(ticker: str) -> Dict*

Get sentiment stats [Source: finnhub]

    Parameters
    ----------
    ticker : str
        Ticker to get sentiment stats

    Returns
    -------
    Dict
        Get sentiment stats

## Using View
### *common.behavioural_analysis.sentiment_stats(ticker: str, export: str = '', view=True)*


    Sentiment stats which displays buzz, news score, articles last week, articles weekly average,
    bullish vs bearish percentages, sector average bullish percentage, and sector average news score

    Parameters
    ----------
    ticker : str
        Ticker to get sentiment stats
    export : str
        Format to export data

**Comment by colin99d** [comment]
@minhhoang1023 got your changes in, I really like this new format. Feel free to let me know if you want any other changes.

**Comment by JerBouma** [comment]
Does this feature a proper introduction page like https://openbb-finance.github.io/OpenBBTerminal/. If not, this has to be included. @minhhoang1023 @colin99d

**Comment by minhhoang1023** [comment]
@colin99d This looks great Colin! 🚀 Once the API PR is merged into main, let's merge this bad boy too.

For this introduction page, @JerBouma and I discussed we can make it a different PR. We still need to add in `pip install` documentation, and it's not ready yet. On the other hand, the new API is ready and needs its own documentation

**Comment by jose-donato** [comment]
Nice one colin

**Pull request merged**
