### PR TITLE
Released this code

### PR DESCRIPTION
**Pull request by montezdesousa**
* Released this code (4.0.0b1) with 2 differences: bumps pytest-recorder to ^0.2.4 in openbb and openbb-provider toml and rerecords yfinance tests

### CODE REVIEW

**Comment by the-praxs** [comment]
@montezdesousa what's pending to merge this branch?

**Comment by montezdesousa** [comment]
> @montezdesousa what's pending to merge this branch?

Tests running

**Comment by the-praxs** [comment]
> > @montezdesousa what's pending to merge this branch?
> 
> Tests running

Failed. I see its urllib. Do we have a fix?

**Comment by montezdesousa** [comment]
> > > @montezdesousa what's pending to merge this branch?
> > 
> > 
> > Tests running
> 
> Failed. I see its urllib. Do we have a fix?



> > > @montezdesousa what's pending to merge this branch?
> > 
> > 
> > Tests running
> 
> Failed. I see its urllib. Do we have a fix?

Need to publish new version of pytest-recorder, locally it works fine

**Comment by the-praxs** [comment]
@montezdesousa LGTM

**Review by the-praxs — APPROVED** [review]

**Pull request merged**
