### PR TITLE
Add stocksera source to `stocks/dps/ctb`

### LINKED ISSUE #1300: [IMPROVE] Integrate stocksera API into stocks/insider/finviz_model.py
I have been scraping Finviz regularly and saving the insider trading records in my own database. The stocksera API gives you access to the historical insider trading data. Both of them will return a panda dataframe.

```
import stocksera

stock = stocksera.Stock()

# Get last n records of insider trading from Finviz
insider_trading_df = stock.insider_trading(limit=2000)

# Get analysis of last 1 month insider trading summary from Finviz
latest_insider_trading_summary_df = stock.latest_insider_trading_summary()
```

Not sure how useful will it be, but here is the documentation to the api I have currently. https://github.com/guanquann/Stocksera-API

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Fixes #1300 

This PR finished #2377, which was closed because of the large amount of merge conflicts. This version "works", but I get the exact same chart for every graph. I need to determine whether this is because of the data received by Stocksera, or whether it is some bad code on our end.

It looks like this is an issue with the data source (the values are the same for AAPL and AMZN):
Screen Shot 2022-10-18 at 10 38 30 AM

It looks like these are the default values. Some tickers (like GME) give actual values. This data quality seems pretty low and I do not suggest using stocksera as a data source. Waiting on agreement from someone else to close this pr and #1300.

# How has this been tested?
Both the keys command and ctb command need to be tested. They keys command needs to be tested in the terminal and the api, while the new source for ctb only needs to be tested in the terminal because there is not a way to access it from the sdk (per conversation with @hjoaquim). If we want to find a different way to implement this just let me know and I can do it.
- [x] Make sure affected commands still run in terminal
    - `python terminal.py "keys/stocksera [APIKEY]`
    - `python terminal.py "stocks/load gme/dps/ctb --source stocksera"`
- [x] Ensure the api still works
    - `openbb.stocks.dps.ctb()`
    - `openbb.keys.get_keys_info()`
- [x] Check any related reports
    - Cannot check right now due to unrelated outstanding bugs that are fixed in: #2878, but commands changes are not in any reports.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by colin99d** [comment]
I am closing this due to data reliability concerns, per @DidierRLopes

**Comment by guanquann** [comment]
Hi. This is not a problem with the data source. The maximum shares available to borrow is 10M. Any number more than 10M will be truncated to 10M

**Comment by colin99d** [comment]
If we are confident on the quality of the data source then I just need to do some QA on this PR and then it should be good to merge.

**Review by Chavithra — APPROVED** [review]
Looks ok to me.

**Comment by jmaslek** [comment]
Integration tests and unit tests :D

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
