### PR TITLE
Fix load a benchmark that isn't in the list of limited choices + yf.Ticker().info bugs

### LINKED ISSUE #4054: [Bug] Portfolio/Bench - Can't load a benchmark that isn't in the list of limited choices
```
2023 Jan 26, 17:29 (🦋) /portfolio/ $ bench xiu.to

usage: bench -b BENCHMARK [-s] [-h]
bench: error: argument -b/--benchmark: invalid choice: 'xiu.to' (choose from 'SPY', 'IVV', 'VTI', 'VOO', 'QQQ', 'VTV', 'VEA', 'IEFA', 'AGG', 'BND', 'VWO', 'VUG', 'IEMG', 'IJR', 'GLD', 'IWF', 'IJH', 'VIG', 'IWM', 'IWD', 'VO', 'EFA', 'VXUS', 'VGT', 'VYM', 'BNDX', 'VNQ', 'VB', 'XLK', 'ITOT', 'VCIT', 'VCSH', 'XLE', 'XLV', 'BSV', 'XLF', 'SCHD', 'RSP', 'LQD', 'IVW', 'VEU', 'TIP', 'IAU', 'SCHX', 'IXUS', 'IWR', 'IWB', 'DIA', 'EEM', 'USMV', 'SCHF', 'IVE', 'MUB', 'VV', 'VBR', 'ESGU', 'VT', 'DGRO', 'SHY', 'DVY', 'QUAL', 'SCHB', 'MBB', 'SDY', 'IGSB', 'VTIP', 'JPST', 'TLT', 'ACWI', 'MDY', 'IUSB', 'SHV', 'VGK', 'XLY', 'BIL', 'GOVT', 'VHT', 'VOE', 'XLP', 'SCHP', 'IEF', 'PFF', 'XLU', 'VTEB', 'EFV', 'SCHG', 'EMB', 'DFAC', 'SCHA', 'GDX', 'VMBS', 'TQQQ', 'VGSH', 'HYG', 'XLI', 'IWS', 'VXF', 'SPLG', 'SPYV', 'IWN')
```
This function did not behave this way in the past. Some choices were given, but one was also free to step outside of the choices and benchmark to anything. There are thousands of ETFs, just in the US, why are the choices limited to these specifically?

### LINKED ISSUE #4135: [Bug] Portfolio/MaxDD - Error: 'Namespace' object has no attribute 'sheet_name'
Loading any portfolio and then using the `maxdd` function results in an error. 

```
2023 Feb 05, 14:06 (🦋) /portfolio/ $ maxdd

Error: 'Namespace' object has no attribute 'sheet_name'
```

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

* Fixes #4054 
* Fixes #4135 
* Other issue fixed: `alloc` was not recalculating after changing the benchmark. Now if benchmark is changed, recalculation is forced, otherwise we display what was saved before (bit faster getting results if you did not change benchmark and just want to re-run alloc command)

`portfolio`
`load --example`
`bench --benchmark TSLA`
`bench --benchmark QQQ`
`bench --benchmark FAKE_BENCH`
or
`python terminal.py -t portfolio/test_portfolio.openbb -v --subproc 0`

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deeleeramone** [comment]
Looks like there's a new complication in town, but I don't think this is related to this PR, I will make a new issue for it. 

```
2023 Feb 05, 13:32 (🦋) /portfolio/ $ maxdd

Error: 'Namespace' object has no attribute 'sheet_name'
```

**Comment by deeleeramone** [comment]
This one is another yf.Ticker().info artifact:


```
2023 Feb 05, 13:55 (🦋) /portfolio/po/ $ blacklitterman

Optimization can take time. Please be patient...

Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
No marketCap was found on list of tickers provided 

Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 0 is different from 14)

Error: not enough values to unpack (expected 3, got 0)

Error: not enough values to unpack (expected 2, got 0)
```

**Comment by montezdesousa** [comment]
> Sorry for hijacking your PR a little bit but I fixed:
> 
> * The `maxdd` issue @deeleeramone referenced.
> * Fixed the same issue for `mret`
> * Some commands used sheet_name wrong meaning it wouldn't let you export to a specific sheet name (but the command itself would work fine). Fixed that too.
> 
> Then I discovered the useless graph that `mret` gave you giving no insights whatsoever. So I redid that and made it so that it produces the table below. This should be much more insightful. The graph is still available as it is relevant for shorter periods than all and I've made it so that it exports the multi index nicely.
> 
> image
> 
> ```
> (🦋) /portfolio/ $ mret
> 
>                                                  Total Monthly returns [%]
> ┏━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┓
> ┃ Year ┃ Instruments ┃ Jan    ┃ Feb    ┃ Mar    ┃ Apr   ┃ May    ┃ Jun   ┃ Jul   ┃ Aug   ┃ Sep   ┃ Oct    ┃ Nov   ┃ Dec    ┃
> ┡━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━┩
> │ 2010 │ Portfolio   │ 0.00   │ 0.00   │ 0.00   │ 0.00  │ 0.00   │ 0.00  │ 15.03 │ -6.73 │ 9.36  │ 6.11   │ -0.92 │ 15.35  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 0.00   │ 0.00   │ 0.00   │ 0.00  │ -7.97  │ -4.26 │ 6.85  │ -4.50 │ 9.28  │ 3.74   │ 0.57  │ 6.66   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 0.00   │ 0.00   │ 0.00   │ 0.00  │ 7.97   │ 4.26  │ 8.18  │ -2.23 │ 0.08  │ 2.37   │ -1.48 │ 8.69   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2011 │ Portfolio   │ 4.55   │ -5.97  │ -1.46  │ 10.10 │ -1.78  │ -5.78 │ -2.38 │ -2.80 │ -0.06 │ 9.04   │ 32.75 │ -42.00 │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 1.57   │ 2.84   │ 0.15   │ 2.65  │ -2.14  │ -2.62 │ -1.33 │ -5.92 │ -4.56 │ 13.65  │ -4.34 │ 1.54   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 2.98   │ -8.80  │ -1.61  │ 7.44  │ 0.36   │ -3.16 │ -1.05 │ 3.11  │ 4.49  │ -4.61  │ 37.09 │ -43.55 │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2012 │ Portfolio   │ 14.37  │ -60.20 │ 7.74   │ 4.90  │ -9.09  │ -4.07 │ 4.61  │ 2.70  │ 5.01  │ -11.00 │ 1.76  │ -0.40  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 4.68   │ 4.75   │ 2.79   │ -0.30 │ -5.80  │ 1.53  │ 1.90  │ 2.02  │ 3.01  │ -1.82  │ 0.54  │ -0.79  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 9.69   │ -64.95 │ 4.95   │ 5.19  │ -3.29  │ -5.60 │ 2.72  │ 0.68  │ 2.00  │ -9.18  │ 1.22  │ 0.39   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2013 │ Portfolio   │ 0.54   │ -2.10  │ -1.59  │ -0.55 │ 8.83   │ -0.30 │ -1.71 │ -0.87 │ 5.88  │ -1.85  │ 3.52  │ -8.21  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 5.38   │ 1.48   │ 3.48   │ 1.68  │ 3.85   │ -0.93 │ 5.09  │ -2.69 │ 3.72  │ 4.93   │ 3.03  │ 2.11   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ -4.84  │ -3.57  │ -5.07  │ -2.23 │ 4.98   │ 0.63  │ -6.81 │ 1.82  │ 2.16  │ -6.78  │ 0.49  │ -10.32 │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2014 │ Portfolio   │ -2.66  │ -11.16 │ 5.60   │ -2.55 │ 5.65   │ -0.37 │ 4.31  │ 2.38  │ 21.15 │ 5.39   │ 5.22  │ -0.80  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ -2.96  │ 4.29   │ 0.01   │ 0.40  │ 2.16   │ 2.12  │ 0.64  │ 3.65  │ -1.12 │ 1.20   │ 2.97  │ 0.75   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 0.30   │ -15.45 │ 5.59   │ -2.95 │ 3.49   │ -2.49 │ 3.67  │ -1.27 │ 22.27 │ 4.19   │ 2.25  │ -1.55  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2015 │ Portfolio   │ 0.94   │ 4.62   │ 3.08   │ 0.23  │ 6.44   │ -5.10 │ 0.06  │ -6.61 │ -7.27 │ 9.57   │ 0.90  │ 0.78   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ -1.73  │ 5.98   │ -0.70  │ 2.01  │ 1.92   │ -2.24 │ 2.41  │ -5.33 │ -4.34 │ 8.98   │ 0.78  │ -0.74  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 2.67   │ -1.36  │ 3.78   │ -1.78 │ 4.52   │ -2.87 │ -2.35 │ -1.28 │ -2.93 │ 0.60   │ 0.11  │ 1.52   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2016 │ Portfolio   │ -6.35  │ 0.42   │ 9.83   │ 0.61  │ 3.21   │ 0.10  │ 7.01  │ -0.19 │ 1.54  │ -4.27  │ 2.74  │ 3.88   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ -7.24  │ 0.71   │ 6.99   │ 0.94  │ 1.90   │ -1.00 │ 3.48  │ 0.41  │ -0.74 │ -1.74  │ 3.93  │ 2.40   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 0.89   │ -0.29  │ 2.84   │ -0.33 │ 1.32   │ 1.10  │ 3.53  │ -0.59 │ 2.29  │ -2.54  │ -1.20 │ 1.48   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2017 │ Portfolio   │ 3.72   │ 4.03   │ 3.11   │ 4.55  │ 3.31   │ 1.14  │ 5.02  │ 1.39  │ -4.37 │ 3.35   │ 1.23  │ 4.33   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 1.80   │ 4.21   │ 0.36   │ 1.21  │ 1.44   │ 0.45  │ 2.11  │ -0.31 │ 1.66  │ 2.20   │ 2.16  │ 1.60   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 1.93   │ -0.18  │ 2.75   │ 3.34  │ 1.88   │ 0.69  │ 2.91  │ 1.70  │ -6.03 │ 1.15   │ -0.93 │ 2.73   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2018 │ Portfolio   │ 11.43  │ -2.74  │ -2.38  │ 0.02  │ 5.93   │ -0.59 │ -0.65 │ 0.76  │ -3.09 │ -12.64 │ -1.19 │ -8.36  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 5.58   │ -2.65  │ -3.97  │ 1.30  │ 3.06   │ 0.43  │ 3.20  │ 3.19  │ 0.58  │ -7.89  │ 1.24  │ -9.60  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 5.84   │ -0.09  │ 1.59   │ -1.27 │ 2.87   │ -1.02 │ -3.84 │ -2.43 │ -3.67 │ -4.75  │ -2.43 │ 1.24   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2019 │ Portfolio   │ 10.00  │ 2.75   │ 1.69   │ 7.14  │ -7.61  │ 8.55  │ 4.83  │ -0.30 │ 3.86  │ 1.28   │ 5.49  │ 4.48   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 7.07   │ 3.43   │ 1.17   │ 4.03  │ -5.10  │ 6.41  │ 2.63  │ -1.63 │ 1.48  │ 2.48   │ 4.01  │ 2.66   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 2.94   │ -0.68  │ 0.51   │ 3.11  │ -2.51  │ 2.14  │ 2.20  │ 1.33  │ 2.39  │ -1.20  │ 1.49  │ 1.82   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2020 │ Portfolio   │ 1.80   │ -4.47  │ -11.10 │ 21.51 │ 6.56   │ 2.19  │ 6.45  │ 4.52  │ -1.41 │ 3.47   │ 9.58  │ 4.05   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 1.81   │ -7.53  │ -11.16 │ 13.76 │ 4.30   │ 0.49  │ 5.06  │ 7.37  │ -4.47 │ -1.47  │ 11.37 │ 3.18   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ -0.01  │ 3.06   │ 0.06   │ 7.75  │ 2.26   │ 1.70  │ 1.39  │ -2.84 │ 3.06  │ 4.93   │ -1.79 │ 0.87   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2021 │ Portfolio   │ 11.25  │ -1.10  │ 3.26   │ 6.19  │ -19.41 │ 4.50  │ 5.72  │ 3.42  │ -7.78 │ 7.51   │ 0.30  │ 3.52   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 1.00   │ 3.31   │ 4.12   │ 5.99  │ 0.48   │ 2.16  │ 2.94  │ 3.13  │ -3.48 │ 6.80   │ 1.16  │ 4.89   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 10.25  │ -4.41  │ -0.86  │ 0.20  │ -19.89 │ 2.34  │ 2.78  │ 0.29  │ -4.30 │ 0.71   │ -0.87 │ -1.37  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2022 │ Portfolio   │ -15.46 │ 22.01  │ 4.73   │ -9.10 │ 2.31   │ -9.32 │ 10.79 │ -9.57 │ -9.48 │ 11.78  │ 12.62 │ -5.39  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ -6.95  │ -2.70  │ 5.38   │ -5.28 │ 0.79   │ -7.49 │ 7.64  │ -3.34 │ -7.82 │ 8.91   │ 2.34  │ -5.51  │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ -8.51  │ 24.71  │ -0.65  │ -3.82 │ 1.52   │ -1.82 │ 3.15  │ -6.22 │ -1.66 │ 2.86   │ 10.28 │ 0.13   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │ 2023 │ Portfolio   │ 11.44  │ 3.37   │ 0.00   │ 0.00  │ 0.00   │ 0.00  │ 0.00  │ 0.00  │ 0.00  │ 0.00   │ 0.00  │ 0.00   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Benchmark   │ 4.75   │ 2.53   │ 0.00   │ 0.00  │ 0.00   │ 0.00  │ 0.00  │ 0.00  │ 0.00  │ 0.00   │ 0.00  │ 0.00   │
> ├──────┼─────────────┼────────┼────────┼────────┼───────┼────────┼───────┼───────┼───────┼───────┼────────┼───────┼────────┤
> │      │ Alpha       │ 6.69   │ 0.83   │ 0.00   │ 0.00  │ 0.00   │ 0.00  │ 0.00  │ 0.00  │ 0.00  │ 0.00   │ 0.00  │ 0.00   │
> └──────┴─────────────┴────────┴────────┴────────┴───────┴────────┴───────┴───────┴───────┴───────┴────────┴───────┴────────┘
> ```

nw, table gives more info indeed

**Comment by montezdesousa** [comment]
> This one is another yf.Ticker().info artifact:
> 
> ```
> 2023 Feb 05, 13:55 (🦋) /portfolio/po/ $ blacklitterman
> 
> Optimization can take time. Please be patient...
> 
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> Market cap removed from info (key='marketCap'). Use Ticker.fast_info instead
> No marketCap was found on list of tickers provided 
> 
> Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 0 is different from 14)
> 
> Error: not enough values to unpack (expected 3, got 0)
> 
> Error: not enough values to unpack (expected 2, got 0)
> ```

I'll take this in a different issue

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
