### PR TITLE
Mstarpy funds

### PR DESCRIPTION
**Pull request by Mael-J**
# Description

In the funds command, I added new command for fund analysis using the library mstarpy. Funds data come from MorningStar.com.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Hey @Mael-J ,

Sorry for the delay to review on our side. We are currently doing a feature freeze for a very big release that will occur next week! Once that is out of the way, we will test this PR and give feedback.

Thanks for contributing 🙏🏽

**Comment by deeleeramone** [comment]
Is there a way to return this data from an endpoint/JSON request instead of BeautifulSoup?

**Comment by Mael-J** [comment]
> Is there a way to return this data from an endpoint/JSON request instead of BeautifulSoup?

**Comment by Mael-J** [comment]
> Is there a way to return this data from an endpoint/JSON request instead of BeautifulSoup?

What data you speak about ? thank you

**Comment by deeleeramone** [comment]
> 

What I mean is the way in which Mstarpy gets the data is by scraping using BeautifulSoup. This makes it difficult to maintain and more easily broken by the source.

**Comment by Mael-J** [comment]
> > 
> 
> What I mean is the way in which Mstarpy gets the data is by scraping using BeautifulSoup. This makes it difficult to maintain and more easily broken by the source.

Yes, it is true that some functions get data using BeautifulSoup. There are on purpose not used in openBB terminal because of their weakness.

**Comment by jmaslek** [comment]
Hey @Mael-J.

Apologies again for the delay.  I am going to dig in.  One thing is that the funds menu is currently disabled (removed) in terminal_controller.py.  

Can you re-add it so that I can test out the terminal functionalities.  Editing this menu will require a little work in terms of getting the deprecated dependencies out, but I am happy to help.

Also feel free to let us know if there are any issues with resolving the merge conflicts.

**Pull request closed without merging**
