### PR TITLE
Fix portfolio and benchmark length matching

### LINKED ISSUE #4201: [Bug] Portfolio/Bench - Error "[Timestamp('2023-01-16 00:00:00')] not in index"
To recreate, 

`/portfolio/load --example/bench QQC.TO`

```
2023 Feb 10, 00:41 (🦋) /portfolio/ $ bench QQC.TO

Error: "[Timestamp('2021-05-31 00:00:00'), Timestamp('2021-07-05 00:00:00'), Timestamp('2021-11-25 00:00:00'), Timestamp('2021-12-24 00:00:00'), Timestamp('2022-01-17 00:00:00'), Timestamp('2022-05-30 00:00:00'), Timestamp('2022-06-20 00:00:00'), Timestamp('2022-07-04 00:00:00'), Timestamp('2022-11-24 00:00:00'), Timestamp('2023-01-16 00:00:00')] not in index"
```

QQC is the Canadian version of QQQ. The American listing for the same ticker - without a suffix - QQC is, Simplify Nasdaq 100 PLUS Convexity ETF. They are not equivalents, nor interchangeable.

### PR DESCRIPTION
**Pull request by northern-64bit**
# Description

Closes #4201 by fixing the length matching performed in the "bench" command.

# How has this been tested?

Running the command and making sure the results stay the same
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by montezdesousa — COMMENTED** [review]
IIUC we are assuming that if DataFrames share the same length the dates match, this might not be always the case, right? 

Or even if they have different length is it guaranteed that the smallest is a subset of the largest?

I tried this example and the resulting DataFrames don't share the same length
```python
from openbb_terminal.portfolio.portfolio_helper import make_equal_length
import pandas as pd
df0 = pd.DataFrame({'returns': [0.4, 0.6, 0.8]}, index=[1, 3, 4])
df1 = pd.DataFrame({'returns': [0.3, 0.5]}, index=[2, 3])
df0_new, df1_new = make_equal_length(df0, df1)
df0_new, df1_new
```

If the case above is an issue we might use pandas inner merge and then provide each DataFram individually.

**Comment by jmaslek** [comment]
> IIUC we are assuming that if DataFrames share the same length the dates match, this might not be always the case, right?
> 
> Or even if they have different length is it guaranteed that the smallest is a subset of the largest?
> 
> I tried this example and the resulting DataFrames don't share the same length
> 
> ```python
> from openbb_terminal.portfolio.portfolio_helper import make_equal_length
> import pandas as pd
> df0 = pd.DataFrame({'returns': [0.4, 0.6, 0.8]}, index=[1, 3, 4])
> df1 = pd.DataFrame({'returns': [0.3, 0.5]}, index=[2, 3])
> df0_new, df1_new = make_equal_length(df0, df1)
> df0_new, df1_new
> ```
> 
> If the case above is an issue we might use pandas inner merge and then provide each DataFrame individually.

So I think the tricky part is holidays on one exchange.  I am not sure what the correct way to report that would be.  My gut says to do an outer join and then just backfill (and just assume that a couple days of 0 returns doesnt mess with statistics or correlations)

**Comment by montezdesousa** [comment]
> > IIUC we are assuming that if DataFrames share the same length the dates match, this might not be always the case, right?
> > Or even if they have different length is it guaranteed that the smallest is a subset of the largest?
> > I tried this example and the resulting DataFrames don't share the same length
> > ```python
> > from openbb_terminal.portfolio.portfolio_helper import make_equal_length
> > import pandas as pd
> > df0 = pd.DataFrame({'returns': [0.4, 0.6, 0.8]}, index=[1, 3, 4])
> > df1 = pd.DataFrame({'returns': [0.3, 0.5]}, index=[2, 3])
> > df0_new, df1_new = make_equal_length(df0, df1)
> > df0_new, df1_new
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If the case above is an issue we might use pandas inner merge and then provide each DataFrame individually.
> 
> So I think the tricky part is holidays on one exchange. I am not sure what the correct way to report that would be. My gut says to do an outer join and then just backfill (and just assume that a couple days of 0 returns doesnt mess with statistics or correlations)

sounds good

**Comment by northern-64bit** [comment]
> > > IIUC we are assuming that if DataFrames share the same length the dates match, this might not be always the case, right?
> > > Or even if they have different length is it guaranteed that the smallest is a subset of the largest?
> > > I tried this example and the resulting DataFrames don't share the same length
> > > ```python
> > > from openbb_terminal.portfolio.portfolio_helper import make_equal_length
> > > import pandas as pd
> > > df0 = pd.DataFrame({'returns': [0.4, 0.6, 0.8]}, index=[1, 3, 4])
> > > df1 = pd.DataFrame({'returns': [0.3, 0.5]}, index=[2, 3])
> > > df0_new, df1_new = make_equal_length(df0, df1)
> > > df0_new, df1_new
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If the case above is an issue we might use pandas inner merge and then provide each DataFrame individually.
> > 
> > 
> > So I think the tricky part is holidays on one exchange. I am not sure what the correct way to report that would be. My gut says to do an outer join and then just backfill (and just assume that a couple days of 0 returns doesnt mess with statistics or correlations)
> 
> sounds good

It has now been fixed by applying outer join and just replacing all NaNs with zeros.

**Comment by jmaslek** [comment]
Loading the example portfolio is now invalid:

```
2023 Feb 19, 20:09 (🦋) /portfolio/ $ load --example

Loading an example, please type `about` to learn how to create your own Portfolio Excel sheet.

         Loading benchmark:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 2/4 [00:00<00:00, 10.45it/s]Error: 'Series' object has no attribute 'columns'

                                                                                                                                                                                                        
Portfolio: OpenBB Example Portfolio
Risk Free Rate: 0.00%
Benchmark: SPDR S&P 500 ETF Trust (SPY)
```

**Comment by northern-64bit** [comment]
> Loading the example portfolio is now invalid:
> 
> ```
> 2023 Feb 19, 20:09 (🦋) /portfolio/ $ load --example
> 
> Loading an example, please type `about` to learn how to create your own Portfolio Excel sheet.
> 
>          Loading benchmark:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 2/4 [00:00<00:00, 10.45it/s]Error: 'Series' object has no attribute 'columns'
> 
>                                                                                                                                                                                                         
> Portfolio: OpenBB Example Portfolio
> Risk Free Rate: 0.00%
> Benchmark: SPDR S&P 500 ETF Trust (SPY)
> ```

Fixed :)

**Review by montezdesousa — COMMENTED** [review]
There are some commands breaking for some reason, like  `summary`, some on `metrics`, `yret`.

Run `python terminal.py -t 33 -v` to check. `alloc` is broken, but apparently it's on `develop` branch already

Getting this: `Error: unsupported format string passed to Series.__format__`

**Comment by northern-64bit** [comment]
Hello @montezdesousa! Can you please review the PR so that we can merge it. Thanks!

**Review by montezdesousa — APPROVED** [review]
Sorry must have missed this one, tks for reminding

**Pull request merged**
