### PR TITLE
Here we merge all API Refactor related branches

### PR DESCRIPTION
**Pull request by Chavithra**
# Description

Here are the menus we are merging :
- [x] stocks (Diogo / Henrique / Colin) - reviewed by Minh & merged & needs to check again
- [x] crypto (Colin) reviewed by Minh & merged
- [x] economy (Diogo) being reviewed by Minh
- [x] portfolio (James / Diogo)
- [x] forex (Colin) reviewed by Minh & needs to check again
- [x] etf (Colin) needs to review
- [x] econometrics (Colin) needs to review
- [x] funds (Colin) needs to review
- [ ] alt (Colin)

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by colin99d** [comment]
Big note: Do NOT do ANYTHING with pred menu stuff. This is remvoed by #1933 @Chavithra @minhhoang1023 @simmonsj330 @montezdesousa

**Comment by minhhoang1023** [comment]
@colin99d You're super quick yo!  🚀 

I'm testing it using all the API endpoints. Some of these functions might be in some types of `helper`. Comments are below:
 
- We don't yet have a default value for the `load` function in forex. Docstring is missing on the description, and available options for `resolution` and `intervals`

image

**Comment by Chavithra** [comment]
To check before merging:
- `ascending` -> `ascend`
- descending` -> `descend`

**Comment by minhhoang1023** [comment]
> To check before merging:
> 
> * `ascending` -> `ascend`
> * `descending` -> `descend`

Also sortby

**Comment by simmonsj330** [comment]
@minhhoang1023 just made a push for portfolio stuff, rest of portfolio will be 100% done by today

**Comment by Chavithra** [comment]
Todo for next PR:
- Few : `ascending` => `ascend`
- Few : `sort_by` => `sortby`

**Review by minhhoang1023 — APPROVED** [review]

**Pull request merged**
