### PR TITLE
Fix `--std` argument in bbands command

### PR DESCRIPTION
**Pull request by northern-64bit**
# Description

Closing #4863.

Makes the `--std` parameter actually influence the output and  fixes the handling of float inputs.

# How has this been tested?

Running the command with float inputs and assuring that the result varies.

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by deeleeramone — CHANGES_REQUESTED** [review]
While the parameter accepts the float value, the legend does not reflect that choice between 1 and 1.5

Screenshot 2023-04-23 at 7 17 05 PM

**Comment by deeleeramone** [comment]
Now it's awkwardly on top.  Isn't it strange how each trace isn't defined on a proper legend that you can toggle on/off?

Screenshot 2023-04-30 at 7 44 58 PM

Screenshot 2023-04-30 at 7 48 44 PM

**Comment by northern-64bit** [comment]
> Now it's awkwardly on top. Isn't it strange how each trace isn't defined on a proper legend that you can toggle on/off?

I created an issue (#4932) regarding the overlap, which already has a pr linked to it now. Shall we merge this and then adjust possibly adjust it and add a legend for each trace after #4941? The pr fixes the `--std` argument and the missing legend for each trace is an overarching thing for the whole TA menu, so it should be its own issue.

**Comment by deeleeramone** [comment]
> I created an issue (https://github.com/OpenBB-finance/OpenBBTerminal/issues/4932) regarding the overlap, which already has a pr linked to it now. Shall we merge this and then adjust possibly adjust it and add a legend for each trace after https://github.com/OpenBB-finance/OpenBBTerminal/pull/4941?

Excellent!

**Review by deeleeramone — APPROVED** [review]
Screenshot 2023-05-01 at 5 50 25 PM

**Pull request merged**
