### PR TITLE
Removed warning when importing API

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Right now the API prints a warning on import. This warning is no longer necessary, so I removed the print statement.

# How has this been tested?
- [x] Make sure affected commands still run in terminal
    - There was no specific command to test, so I ran `python terminal.py` to confirm that the terminal still works. I did not test more than this because I am confident that removing a print statement will not have effects on other places in the terminal.
- [x] Ensure the api still works
   - I opened up a jupyter notebook and ran `from openbb_terminal.api import openbb` to confirm no error message was shown. I then ran commands from the stocks and forecast menu to ensure that there were no unforeseen side effects. Because of the very remote chance that deleting a print statement would change more code, I stopped after this limited testing.
- [x] Check any related reports
    - Ran all reports (except portfolio) and confirmed that they ran error free and the output seemed reasonable.
    - I did find an issue with equity, but it seemed unrelated to my PR. I reported the bug: #2833.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by minhhoang1023** [comment]
As discussed earlier with @colin99d , I'll approve this later this sprint. Right now it doesn’t hurt us to have it, and can be relevant for old users to have the pointer towards new documentation.

As long as we have this removed by the launch, this should be fine.

**Comment by deeleeramone** [comment]
How about a warning for when the filename of `api.py` changes and breaks everyone's scripts/notebooks.

**Comment by minhhoang1023** [comment]
@deeleeramone We will have a warning every time there's a breaking change.

**Review by piiq — APPROVED** [review]
Finally we're getting rid of this warning!

**Review by minhhoang1023 — APPROVED** [review]

**Pull request merged**
