### PR TITLE
Added export to stocks/qa/beta

### LINKED ISSUE #2491: [Bug] Stocks/QA/beta: --export does not export
Recreate with:
```
/stocks
load SPY
qa
beta -r AAPL --export csv
```

### PR DESCRIPTION
**Pull request by hjoaquim**
- Fixes #2491 

Since **beta** and **alpha** are constants, I ended up doing this:

image

Is it correct/ the common practice?

### CODE REVIEW

**Comment by deeleeramone** [comment]
I'm not sure what the convention for this raw data would be; I was simply reporting that the export functionality didn't work. But, now that you have my attention, can this chart show the relationship to alpha over time?

Beta {ticker} as a +/- % value, relative to Alpha {SPY or user choice}?

**Comment by hjoaquim** [comment]
@deeleeramone I would suggest for us to close the bug and open a new issue labeled "enhancement". Do you agree?

**Review by jose-donato — APPROVED** [review]

**Comment by jose-donato** [comment]
@colin99d pingu

**Comment by hjoaquim** [comment]
Following @jose-donato suggestion:
image

**Pull request merged**
