### PR TITLE
Improve SIA experience as based on feedback

### LINKED ISSUE #2201: [IMPROVE] Instead of exiting the terminal with CTRL + C, let it intercept the activated command
**What's the feature that should be improved?**
When running commands that take a reasonable time to complete, it can sometimes be undesired to continue. This can be the case for certain Machine Learnings models or when needing to collect a lot of data. E.g. within the `sia` menu if you don't specify `industry` and `sector` it could be that you end up waiting a long time for something you might not even want.

See the following:
image

There is also absolutely no reason that a method to close the entire terminal is by using CTRL + C. Why can't this be for interrupting commands instead?

**Describe how you would like the feature improved**
When using CTRL + C, it should activate a different command than interrupting the entire terminal.

image

### PR DESCRIPTION
**Pull request by DidierRLopes**
* Fixes #2201

### CODE REVIEW

**Comment by DidierRLopes** [comment]
@Chavithra can you help me with the tests here?

**Comment by JerBouma** [comment]
Could you add in somewhere (e.g. within the progress bar description) that the user can cancel the process with `CTRL + C`? I am pretty sure this is not common knowledge (since it also means copy).

**Comment by piiq** [comment]
> Could you add in somewhere (e.g. within the progress bar description) that the user can cancel the process with `CTRL + C`? I am pretty sure this is not common knowledge (since it also means copy).

Won't that kill the terminal process @JerBouma

**Comment by JerBouma** [comment]
> > Could you add in somewhere (e.g. within the progress bar description) that the user can cancel the process with `CTRL + C`? I am pretty sure this is not common knowledge (since it also means copy).
> 
> Won't that kill the terminal process @JerBouma

The whole point of this PR is to make an exception on that right?

**Comment by piiq** [comment]
IIUC no, it's to disable default Sector/Industry

**Comment by JerBouma** [comment]
@DidierRLopes literary links to my issue right? https://github.com/OpenBB-finance/OpenBBTerminal/issues/2201

And we got this:
```
        if ns_parser:
            try:
                (
                    self.stocks_data,
                    self.tickers,
                ) = financedatabase_view.display_bars_financials(
                    self.metric_yf_keys[ns_parser.metric][0],
                    self.metric_yf_keys[ns_parser.metric][1],
                    self.country,
                    self.sector,
                    self.industry,
                    self.mktcap,
                    self.exclude_exchanges,
                    ns_parser.limit,
                    ns_parser.export,
                    ns_parser.raw,
                    self.stocks_data,
                )
            except KeyboardInterrupt:
                pass
```

**Comment by piiq** [comment]
my brain is very smooth after this weekend

**Comment by JerBouma** [comment]
@DidierRLopes Can you include a message either within the TQDM or somewhere else that it is clear that `CTRL + C` cancels the process? This is not common knowledge.

**Review by JerBouma — CHANGES_REQUESTED** [review]
@DidierRLopes Can you include a message either within the TQDM or somewhere else that it is clear that `CTRL + C` cancels the process? This is not common knowledge.

**Comment by DidierRLopes** [comment]
> @DidierRLopes Can you include a message either within the TQDM or somewhere else that it is clear that `CTRL + C` cancels the process? This is not common knowledge.

I had done that, must have forgotten to push the changes 🤦🏽‍♂️ on it

**Review by JerBouma — APPROVED** [review]

**Pull request merged**
