### PR TITLE
Add didiers to_records method

### PR DESCRIPTION
**Pull request by jmaslek**
Allows you to do 

- obbject.to_dict(orient = " ") just has to be valid arg
- obbject.to_records() -> gives the json type stuff

Remove polars so that can be an extension

### CODE REVIEW

**Comment by DidierRLopes** [comment]
image

**Review by DidierRLopes — APPROVED** [review]

**Review by IgorWounds — CHANGES_REQUESTED** [review]
This looks good!

To not introduce redundancy. Shall we just have the to_dict() method with a literal of these:

['dict', 'list', 'series', 'split', 'tight', 'records', 'index']

This way, we can set the records to be the default orientation and people can easily change to other orientations based on their needs. This will make the to_records() method not needed.

**Comment by jmaslek** [comment]
> This looks good!
> 
> To not introduce redundancy, shall we just have the to_dict() method with a literal of these:
> 
> ['dict', 'list', 'series', 'split', 'tight', 'records', 'index']
> 
> This way, we can set the records to be the default orientation and people can easily change to other orientations based on their needs. This will make the to_records() method not needed.

Was just following this: https://github.com/OpenBB-finance/OpenBBTerminal/pull/5557#issuecomment-1763055940

I like the to_dict returning an actual dictionary, that we can index.  I can add the literals, but would rather just have the to_records option.

**Comment by IgorWounds** [comment]
> Was just following this: [#5557 (comment)](https://github.com/OpenBB-finance/OpenBBTerminal/pull/5557#issuecomment-1763055940)
> 
> I like the to_dict returning an actual dictionary, that we can index. I can add the literals, but would rather just have the to_records option.

Got it. I think that you can just change the default to be the "list" option which is essentially what the pure to_dict() is doing right now. If you really want to split off the to_records, to_X, ...; we could do it with shortcuts the same way we did with to_df(). 

Personally, I wouldn't say I like having too many helper functions that can easily be united and many Python users use Pandas which will make it easy to understand that they can change the to_dict() output in the same way they would do with Pandas.

**Comment by jjfantini** [comment]
I have been loving the `to_polars()` method. I had a custom method `to_polars()` with v3. I think if anything def make it an extension...users are slowly converting to Polars, I think its best to prepare for that future 😄

**Comment by jmaslek** [comment]
> > Was just following this: [#5557 (comment)](https://github.com/OpenBB-finance/OpenBBTerminal/pull/5557#issuecomment-1763055940)
> > I like the to_dict returning an actual dictionary, that we can index. I can add the literals, but would rather just have the to_records option.
> 
> Got it. I think that you can just change the default to be the "list" option which is essentially what the pure to_dict() is doing right now. If you really want to split off the to_records, to_X, ...; we could do it with shortcuts the same way we did with to_df().
> 
> Personally, I wouldn't say I like having too many helper functions that can easily be united and many Python users use Pandas which will make it easy to understand that they can change the to_dict() output in the same way they would do with Pandas.

Adjuisted this to reflect this.  @DidierRLopes you good?

I also brought back polars, since why not

**Review by IgorWounds — APPROVED** [review]

**Review by DidierRLopes — APPROVED** [review]
🚢it

**Comment by jjfantini** [comment]
v happy you decided to keep `polars` :) @jmaslek

**Pull request merged**
