### PR TITLE
feat(docs): add math katex support

### PR DESCRIPTION
**Pull request by Disorrder**
Now we can add equations

image

### CODE REVIEW

**Review by jose-donato — APPROVED** [review]
LGTM

**Comment by jose-donato** [comment]
@jmaslek try it

**Comment by Disorrder** [comment]
Just made stylesheet self-hosted, instead of relying on external CDN

**Comment by jmaslek** [comment]
noice.  

Screenshot 2023-05-04 at 11 14 36 AM

**Pull request merged**
