### PR TITLE
Deeleeramone indices

### PR DESCRIPTION
**Pull request by deeleeramone**
This adds autocomplete support for an additional 90 global indices by updating the file:

/openbb_terminal/economy/yfinance_model.py

This has been tested locally, all tickers support complete history. 

```
2022 Apr 11, 03:04 (🦋) / $ economy/index -si
2022 Apr 11, 03:04 (🦋) /economy/ $ index -si
                                     Major Indices                                     
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Argument          ┃ Name                                            ┃ Ticker        ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ sp500             │ S&P 500 Index                                   │ ^GSPC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ speup             │ S&P Europe 350 Index                            │ ^SPEUP        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp400             │ S&P 400 Mid Cap Index                           │ ^SP400        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp600             │ S&P 600 Small Cap Index                         │ ^SP600        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ny                │ NYSE US 100 Index                               │ ^NY           │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nyse              │ NYSE Composite Index                            │ ^NYA          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ amex              │ NYSE-AMEX Composite Index                       │ ^XAX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nasdaq            │ Nasdaq Composite Index                          │ ^IXIC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russell1000       │ Russell 1000 Index                              │ ^RUI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russell2000       │ Russell 2000 Index                              │ ^RUT          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russell3000       │ Russell 3000 Index                              │ ^RUA          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russellvalue      │ Russell 2000 Value Index                        │ ^RUJ          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russellgrowth     │ Russell 2000 Growth Index                       │ ^RUO          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dja               │ Dow Jones Composite Average Index               │ ^DJA          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dji               │ Dow Jones Industrial Average Index              │ ^DJI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ tsx               │ TSX Composite Index                             │ ^GSPTSE       │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftse100           │ FTSE Global 100 Index                           │ ^FTSE         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftse250           │ FTSE Global 250 Index                           │ ^FTMC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftse350           │ FTSE Global 350 Index                           │ ^FTLC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftai              │ FTSE AIM All-Share Global Index                 │ ^FTAI         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ fteu1             │ FTSE Eurotop 100 Index                          │ ^FTEU1        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ftas              │ UK FTSE All-Share Index                         │ ^FTAS         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ spuk              │ S&P United Kingdom (PDS)                        │ ^SPUK         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ uk100             │ CBOE UK 100 Index                               │ ^BUK100P      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ switzerland       │ Zurich Stock Exchange ESTX 50 PR.EU             │ ^STOXX50E     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ germany           │ DAX Performance Index                           │ ^GDAXI        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ paris             │ CAC Paris 40 Index                              │ ^FCHI         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ brussels          │ BEL 20 Brussels Exchange Index                  │ ^BFX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ bombay            │ S&P Bombay Stock Exchange SENSEX                │ ^BSESN        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ tel-aviv          │ Tel-Aviv 125 Index                              │ ^TA125.TA     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ russia            │ MOEX Russia Index                               │ IMOEX.ME      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ asx200            │ S&P/ASX 200 Index                               │ ^AXJO         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ australia         │ Australia All Ordinary Shares Index             │ ^AORD         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nz50              │ S&P New Zealand 50 Index                        │ ^nz50         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ kosbi             │ KOSPI Compsite Index                            │ ^KS11         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nikkei            │ Nikkei 255 Index                                │ ^N225         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ shanghai          │ Shanghai Composite Index                        │ 000001.SS     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ shenzhen          │ Shenzhen Component Index                        │ 399001.SZ     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ taiwan            │ TSEC Weighted Index                             │ ^TWII         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ hang-seng         │ Hang Seng Index                                 │ ^HSI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ jakarta           │ Jakarta Composite Index                         │ ^JKSE         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ malaysia          │ FTSE Bursa Malaysia KLCI                        │ ^KLSE         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ singapore         │ STI Index - Singapore SGD                       │ ^STI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ mexico            │ IPC Mexico Index                                │ ^MXX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ brazil            │ IBOVESPA Sao Paulo Brazil Index                 │ ^BVSP         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ vix               │ CBOE Volatility Index                           │ ^VIX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ vin               │ CBOE Near-Term VIX Index                        │ ^VIN          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ vvix              │ CBOE VIX Volatility Index                       │ ^VVIX         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ shortvol          │ CBOE Short VIX Futures Index                    │ ^SHORTVOL     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ vxn               │ CBOE NASDAQ 100 Volatility Index                │ ^VXN          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ gvz               │ CBOE Gold Volatility Index                      │ ^GVZ          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ovx               │ CBOE Crude Oil Volatility Index                 │ ^OVX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dx-y              │ US Dollar Index                                 │ DX-Y.NYB      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ tnx               │ CBOE Interest Rate 10 Year T-Note               │ ^TNX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ tyx               │ CBOE 30 year Treasury Yields                    │ ^TYX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ irx               │ CBOE 13 Week Treasury Bill                      │ ^IRX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp500tr           │ S&P 500 Total Return USD                        │ ^SP500TR      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xsp               │ S&P 500 Mini SPX Options Index                  │ ^XSP          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-materials      │ S&P 500 Materials Sector Index                  │ ^SP500-15     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-industrials    │ S&P 500 Industrials Sector Index                │ ^SP500-20     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-discretionary  │ S&P 500 Consumer Discretionary Index            │ ^SP500-25     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-staples        │ S&P 500 Consumer Staples Sector Index           │ ^SP500-30     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-health         │ S&P 500 Health Care Sector Index                │ ^SP500-35     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-financials     │ S&P 500 Financials Sector Index                 │ ^SP500-40     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-it             │ S&P 500 IT Sector Index                         │ ^SP500-45     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-communications │ S&P 500 Communications Sector Index             │ ^SP500-50     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-utilities      │ S&P 500 Utilities Sector Index                  │ ^SP500-55     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-real_estate    │ S&P 500 Real Estate Sector Index                │ ^SP500-60     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-airlines       │ S&P 500 Airlines Industry Index                 │ ^SP500-203020 │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sp-tech_hardware  │ S&P 500 Technology Hardware Industry            │ ^SP500-452020 │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ djt               │ Dow Jones Transportation Average Index          │ ^DJT          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ dju               │ Dow Jones Utility Average Index                 │ ^DJU          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ixch              │ NASDAQ Health Care Index                        │ ^IXCH         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ixtc              │ NASDAQ Telecommunications Index                 │ ^IXTC         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ inds              │ NASDAQ Industrial Index                         │ ^INDS         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ixco              │ NASDAQ Computer Index                           │ ^INCO         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ bank              │ NASDAQ Bank Index                               │ ^BANK         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ tran              │ NASDAQ Transportation Index                     │ ^TRAN         │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ice-auto          │ ICE FactSet Global NextGen Auto Index           │ ^ICEFSNA      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ice-comm          │ ICE FactSet Global NextGen Communications Index │ ^ICEFSNC      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nyl               │ NYSE World Leaders Index                        │ ^NYL          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nyi               │ NYSE International 100 Index                    │ ^NYI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ nyy               │ NYSE TMT Index                                  │ ^NYY          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xmi               │ NYSE ARCA Major Market Index                    │ ^XMI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xoi               │ NYSE ARCA Oil and Gas Index                     │ ^XOI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ ixb               │ NYSE Materials Select Sector Index              │ ^IXB          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ pse               │ NYSE ARCA Tech 100 Index                        │ ^PSE          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xci               │ NYSE ARCA Computer Tech Index                   │ ^XCI          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xal               │ NYSE ARCA Airline Index                         │ ^XAL          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xtc               │ NYSE ARCA North American Telecom Industry Index │ ^XTC          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ bxm               │ CBOE Buy-Write Monthly Index                    │ ^BXM          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ sox               │ PHLX Semiconductor Index                        │ ^SOX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ xau               │ PHLX Gold/Silver Index                          │ ^XAU          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ hgx               │ PHLX Housing Sector Index                       │ ^HGX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ osx               │ PHLX Oil Services Sector Index                  │ ^OSX          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ uty               │ PHLX Utility Sector Index                       │ ^UTY          │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ w5000             │ Wilshire 5000                                   │ ^W5000        │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ w5000flt          │ Wilshire 5000 Float Adjusted Index              │ ^W5000FLT     │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ wgreit            │ Wilshire Global REIT Index                      │ ^WGREIT       │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ wgresi            │ Wilshire Global Real Estate Sector Index        │ ^WGRESI       │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ wilreit           │ Wilshire US REIT Index                          │ ^WILREIT      │
├───────────────────┼─────────────────────────────────────────────────┼───────────────┤
│ wilresi           │ Wilshire US Real Estate Security Index          │ ^WILRESI      │
└───────────────────┴─────────────────────────────────────────────────┴───────────────┘
```

### CODE REVIEW

**Comment by JerBouma** [comment]
Looks good, thanks for this. This is a much more complete overview, when Linting is corrected I am ready to approve.

**Comment by JerBouma** [comment]
Perhaps one suggestion after all. Could you add in a search parameter so I could optionally say `index -si volatility` to look just for those indices that have this query inside their name or ticker. I can imagine some people might just be looking for a specific index, e.g. "russel" and can quickly find it with a search parameter than the terminal overflowing with options.

**Comment by JerBouma** [comment]
It's true autocomplete does a great job here except when you would like to plot multiple indices alongside each other. The table becomes far too large when you call the `-si` command here. That's is why I would suggest something like: `-si all` if you want the complete table whereas `-si` returns my initial list. Then also the option to do `-si SEARCH_TERM` to search the all list.

**Comment by deeleeramone** [comment]
Updated with these changes

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
