### PR TITLE
Enhance economy menu with custom math functions

### PR DESCRIPTION
**Pull request by jmaslek**
Based off of #2549.

One thing we don't support is the ability to do some simple operations on certain columns.  This is a basic idea to do so.

The workflow would be something along the lines of (this loads in the 5y and 2y treasury yields and then creates a new column that is the difference [yes i know this series exists, but for illustrations this works] ).  Note this uses pandas.DataFrame.eval() so anything available there is fair game (i.e log functions, not just addition/subtraction)

```
economy
fred dgs2 dgs5
eval two_minus_five = dgs2-dgs5
plot two_minus_five
```

Voila.  

A couple notes: would need to add some potential support for multiple series.  Currently just overwriting DATASETS["custom"] -- should be EZ. 

The slash issue will likely confuse users (but can be avoided by doing `series**-1`).

Obviously will have some issues if users load in datasets with different time indexes.  

Curious on your thoughts @deeleeramone @DidierRLopes @JerBouma

### CODE REVIEW

**Comment by DidierRLopes** [comment]
This is a great idea! 👍🏽

**Comment by JerBouma** [comment]
Think this is great, could even calculate the duration with this. Could this be integrated in more areas? E.g. it also makes sense for Forecasting and Econometrics. Like for Statistics you sometimes take the log to normalize the series.

**Comment by jmaslek** [comment]
> Think this is great, could even calculate the duration with this. Could this be integrated in more areas? E.g. it also makes sense for Forecasting and Econometrics. Like for Statistics you sometimes take the log to normalize the series.

Should be straightforward as long as there are data frames we can use the evaluation method on.

**Comment by deeleeramone** [comment]
It would be really useful to have a `--title` flag on the custom plot functions. A chart with no title is just "incorrect", and it would be impossible to know the user's intention for generating a title automatically.

**Comment by deeleeramone** [comment]
As a user, I want to be able to *not* use, rely on, Sheets/Excel in order to accomplish arithmetic functions for OpenBB Terminal data. 

Screen Shot 2022-09-19 at 7 35 32 PM

**Comment by DidierRLopes** [comment]
Why does the sum doesn't work?
Screenshot 2022-10-08 at 22 11 01

**Comment by DidierRLopes** [comment]
@piiq is there a way to allow the user to do something like `eval newel = dgs2 / dgs5`.

Can you look into this?

**Comment by colin99d** [comment]
Screen Shot 2022-10-09 at 9 12 27 AM
@jmaslek this command just needs a better help message so users know how to use it.

**Comment by jmaslek** [comment]
> Why does the sum doesn't work? Screenshot 2022-10-08 at 22 11 01

Think I fixed this?   Issue was doing concat with axis=0 not axis=1.

Also note I coded this so that if a column exists, I appended a _duplicate to distinguish.

**Comment by jmaslek** [comment]
> Screen Shot 2022-10-09 at 9 12 27 AM
> 
> @jmaslek this command just needs a better help message so users know how to use it.

Okay added error messages for invalid syntax and also if the user tries to use a column that does not exist.  Can add more edge cases.

**Review by colin99d — APPROVED** [review]

**Pull request merged**
