### PR TITLE
Fix dashboards

### LINKED ISSUE #3453: [Bug] Dashboards/Stocks - Gets stuck on Executing 3 of 5
image

### LINKED ISSUE #3459: [Bug] Dashboards/Correlation - Gets stuck at 2 of 4
Screenshot 2022-11-17 at 7 33 30 PM

### LINKED ISSUE #3461: [Bug] Dashboards/Futures - Gets stuck at 4 of 6
Screenshot 2022-11-17 at 8 02 22 PM

### LINKED ISSUE #3463: [Bug] Dashboards/vsurf - get stuck at 2 of 4
Screenshot 2022-11-17 at 8 04 10 PM

### PR DESCRIPTION
**Pull request by hjoaquim**
In this PR:
 - Fix #3463
 - Fix #3461
 - Fix #3459
 - Fix #3453

Fixes the dashboards that were getting stuck by updating `voila`, `ipywidgets` and `jupyterlab-widgets`.

References:
 - https://github.com/voila-dashboards/voila/issues/1188
 - https://github.com/jupyterlab/jupyterlab/issues/12977
 - https://github.com/jupyter-widgets/ipywidgets/issues/3558

### CODE REVIEW

**Comment by hjoaquim** [comment]
@piiq @Chavithra what kind of dd should one do for this kind of change?

**Comment by colin99d** [comment]
@hjoaquim they were all getting stuck for me. So I can test it.

**Comment by colin99d** [comment]
@hjoaquim how long was vsurf taking for you? Im on like 10 minutes and its still loading.

**Comment by hjoaquim** [comment]
@colin99d pretty much instantly:

image

Have you created a new conda environment along with checking out this code and then `poetry install`?

**Comment by colin99d** [comment]
Yeah I definitely remembered to do that... Lemme go... update my mac settings real quick

**Comment by colin99d** [comment]
I updated all my settings and it still takes forever. I was not able to get through the load.

**Comment by colin99d** [comment]
Let me try other ones, I know vsurf can have problems because it makes a lot of requests.

**Comment by hjoaquim** [comment]
Good to know that it's working for ubuntu and Mac!

**Comment by hjoaquim** [comment]
I believe CI tests failing related with `riskfolio` will be fixed with #3582

**Comment by jmaslek** [comment]
Looks like the failing ci was not addressed there :/

**Comment by hjoaquim** [comment]
@jmaslek shouldn't this: https://github.com/OpenBB-finance/OpenBBTerminal/pull/3582/files#diff-fb443e6d2bbb3d9522bda37bec25f3a0588fc4d5dd4a8b9deb996bce2f7b6e4d
disable the particular test that's failing?

**Comment by jmaslek** [comment]
> @jmaslek shouldn't this: https://github.com/OpenBB-finance/OpenBBTerminal/pull/3582/files#diff-fb443e6d2bbb3d9522bda37bec25f3a0588fc4d5dd4a8b9deb996bce2f7b6e4d disable the particular test that's failing?

I think this requires a @pytest.mark.optimization decorator on the tests to skip?  @Chavithra ?

**Comment by jmaslek** [comment]
> > @jmaslek shouldn't this: https://github.com/OpenBB-finance/OpenBBTerminal/pull/3582/files#diff-fb443e6d2bbb3d9522bda37bec25f3a0588fc4d5dd4a8b9deb996bce2f7b6e4d disable the particular test that's failing?
> 
> I think this requires a @pytest.mark.optimization decorator on the tests to skip? @Chavithra ?

Or running pytest with the --optimization flag, which is not the case?  Investigating

**Comment by jmaslek** [comment]
So the tests are just using: `pytest tests/ --autodoc`

What I am confused on is why this is not failing everywhere and just here.  Possibly based on the poetry.lock changes?

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
