### PR TITLE
Fix: Show relevant news for stocks in OpenBB terminal This update res…

### PR DESCRIPTION
**Pull request by Chaitanyjanmale2**
…olves an issue where the OpenBB terminal displayed irrelevant news when users requested information about specific stocks Issue Number-#6066 .(Added efficent way to query for news which will return more accurate and relavent news related to stock market)

# Pull Request the OpenBBTerminal

## Description

- added the change to query the stock related news which are accurate and relevant to stock news.
- #6066 .
- attached in document.
- saw a problem so tried to fix it.

## How has this been tested?

- I have attached the Analysis document please check.
[6066.docx](https://github.com/OpenBB-finance/OpenBBTerminal/files/15030988/6066.docx)

- [x] Ensure the affected commands still execute in the OpenBB Terminal.
- [x] Ensure the Platform (previously named SDK) is working as intended.
- [x] Check any related reports.

## Checklist

- [x] I ensure I have self-reviewed my code.
- [x] I have commented/documented my code, particularly in hard-to-understand sections.
- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

### CODE REVIEW

**Review by WynandVStaden — COMMENTED** [review]
Nice job. I liked how you documented the changes so well in 6066.docx. I am not repository owner. Only owner can approve for integration. After integration then I will mark issue as closed or owner will.

**Comment by montezdesousa** [comment]
Hi @Chaitanyjanmale2, thanks for the contribution.

We are not maintaining that code anymore, it will be remove shortly. We are working on a similar CLI built on top of OpenBB Platform, see https://github.com/OpenBB-finance/OpenBBTerminal/pull/5302.

You can know more about the decision here https://openbb.co/blog/sunsetting-openbb-terminal-why-how-and-what-now

**Comment by Chaitanyjanmale2** [comment]
Hi @montezdesousa ,Okay.

well ,how will i know that the issue im working on is correct one i mean its worth spending my time
Please let me know

**Comment by montezdesousa** [comment]
> Hi @montezdesousa ,Okay.
> 
> well ,how will i know that the issue im working on is correct one i mean its worth spending my time Please let me know

Any issue reported related to `openbb_platform` code will be valid. We're almost launching the CLI (which replaces the original OpenBBTerminal), after that some GitHub issue clean-up needs to be done and CLI related issues will also be valid.

**Pull request closed without merging**
