### PR TITLE
[Feature] Limit number of countries in TE request

### PR DESCRIPTION
**Pull request by hjoaquim**
1. **Why**? (1-3 sentences or a bullet point list):

    - Allowing more than N countries in a TE request would break with a http code of 400 - this PR enhances the UX.

2. **What**? (1-3 sentences or a bullet point list):

    - Added a validation for the number of countries in the fetcher.

3. **Impact** (1-2 sentences or a bullet point list):

    - Low - small improvement on UX.

4. **Testing Done**:

    - Experiment with any amount of countries from `openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/utils/countries.py`:
```python
from openbb import obb
countries = [...]
obb.economy.calendar(provider="tradingeconomics", country=countries).to_df()
```

5. **Reviewer Notes** (optional):

    - It looks like it depends on the countries we're sending. Sometimes it fails for 28, other times 31/32. I wasn't able to get more than 32 with any combination of countries. Also, couldn't find any information related with this limit on TE API docs. cc @andrewkenreich

### CODE REVIEW

**Comment by deeleeramone** [comment]
> 1. **Why**? (1-3 sentences or a bullet point list):
>        
>        * Allowing more than N countries in a TE request would break with a http code of 400 - this PR enhances the UX.
> 
>     2. **What**? (1-3 sentences or a bullet point list):
>        
>        * Added a validation for the number of countries in the fetcher.
> 
>     3. **Impact** (1-2 sentences or a bullet point list):
>        
>        * Low - small improvement on UX.
> 
>     4. **Testing Done**:
>        
>        * Experiment with any amount of countries from `openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/utils/countries.py`:
> 
> 
> ```python
> from openbb import obb
> countries = [...]
> obb.economy.calendar(provider="tradingeconomics", country=countries).to_df()
> ```
> 
>     5. **Reviewer Notes** (optional):
>        
>        * It looks like it depends on the countries we're sending. Sometimes it fails for 28, other times 31/32. I wasn't able to get more than 32 with any combination of countries. Also, couldn't find any information related with this limit on TE API docs. cc @andrewkenreich

Is there a reason why "All" is not used instead of trying to get a huge list? It would be pretty simple to filter post-request, and storing that data in cache would dramatically reduce the number of API calls.

**Review by IgorWounds — APPROVED** [review]

**Comment by IgorWounds** [comment]
@deeleeramone

**Comment by deeleeramone** [comment]
> Is `all` even an option? Couldn't find that on TE API docs. I like the idea, if possible.
> 
> Although, we can still set a limit for number of countries in one request, if TE has one (as it look it does), using the validator.

All is what you get when you only enter a start/end date.  A different way of going about restricting the length of the URL would be by the character count instead of the number of countries. 

2000 characters is a general "safe" limit for URL length, although this can vary by platform.

**Comment by hjoaquim** [comment]
> > Is `all` even an option? Couldn't find that on TE API docs. I like the idea, if possible.
> > Although, we can still set a limit for number of countries in one request, if TE has one (as it look it does), using the validator.
> 
> All is what you get when you only enter a start/end date. A different way of going about restricting the length of the URL would be by the character count instead of the number of countries.
> 
> 2000 characters is a general "safe" limit for URL length, although this can vary by platform.

That seems to be the case - let's do that instead.

**Pull request closed without merging**
