### PR TITLE
1st integration with TimeGPT-1 (Beta), from Nixtla

### PR DESCRIPTION
**Pull request by DidierRLopes**
# Description

- Summary of the change / bug fix.

Integrate the new TimeGPT-1 (Beta) model from Nixtla.

- Screenshot of the feature or the bug before/after fix, if applicable.

image

- Relevant motivation and context.

TimeGPT-1 (Beta) is a new model that is early alpha from Nixtla. It was trained on the largest collection of data in history – over 100 billion rows of financial, weather, energy, and web data – and democratizes the power of time-series analysis.

- [ ] List any dependencies that are required for this change.

nixtlats

# How has this been tested?

* Please describe the tests that you ran to verify your changes.

Tested multiple commands with different time series.
- [ ] Need to try more different time series, to check all edge cases are handled
- [ ] Need to test providing more than one time series

* Provide instructions so we can reproduce.

- [x] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
- nixtlats not added to reqs
- api-key guide not updated in website/

**Comment by jmaslek** [comment]
So I loaded in an example stock load, (K0 ticker), which is saved to k0

Running the following:
```
2023 Aug 09, 15:42 (🐛) /forecast/ $ timegpt -d k0 --targetcol close --freq D --timecol date --ci 60,80

There was an error connecting to the API. Please try again later.

Error: list indices must be integers or slices, not str
```

In debug mode, it says a 500 error code from nixtla?


If I dont specify the --ci flag, teh default values give errors on is_integer:

```
2023 Aug 09, 15:43 (🐛) /forecast/ $ timegpt -d k0 --targetcol close --freq D --timecol date

Error: 'int' object has no attribute 'is_integer'
```

Could also use a better help message on --targetcol and --timecol, as not specifying them just defauklts to twice printed error:

```
2023 Aug 09, 15:44 (🐛) /forecast/ $ timegpt -d k0 --targetcol close --freq D

Error: 'ds'

Error: 'ds'
```

**Comment by DidierRLopes** [comment]
Nice, thanks for feedback! @jmaslek 

The API is in constant development by Azul (@FedericoGarza ) from Nixtla's team - were you using latest version? 

When I see these "There was an error connecting to the API. Please try again later." it's usually on their side, and so it's important to know what args we are sending so they can replicate.

**Comment by DidierRLopes** [comment]
Screenshot 2023-08-09 at 3 21 25 PM

@jmaslek seems you were running an old version, had no problems with ko.

**Comment by DidierRLopes** [comment]
Fixed the other 2 issues you found:

Screenshot 2023-08-09 at 3 59 37 PM

Screenshot 2023-08-09 at 4 04 33 PM

**Comment by jmaslek** [comment]
Running into something weird.  Loading in /fixedincome/fed --start 2020-01-01 -p weekly --export fedfunds.csv

Specifying the freq actually causes it to fail?

```
2023 Aug 23, 10:44 (🐛) /forecast/ $ timegpt -d fedfunds --timecol date --targetcol ff


2023 Aug 23, 10:44 (🐛) /forecast/ $ timegpt -d fedfunds --timecol date --targetcol ff --freq W

Error: status_code: 400, body: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Bad Request</pre>
</body>
</html>


Error: not enough values to unpack (expected 2, got 0)

```

**Comment by DidierRLopes** [comment]
> 

Got into the same issue. Just asked Nixtla team about it (CC @FedericoGarza ), but I think they are passing that freq to pandas.

image

**Comment by FedericoGarza** [comment]
hi @DidierRLopes and @jmaslek! Thanks for letting us know about this issue. We've released a new version of `nixtlats`, so `nixtlats>=0.1.11` should work. We have the following CI/CD test, but let me know if updating the library does not work on your end. Thank you! :heart:


image

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
