### PR TITLE
Update stocks_helper.py

### PR DESCRIPTION
**Pull request by pauljsymonds**
When a stock is returned:

Market: CLOSEDSENIOR PLC 10p

Fixed to show:

Market: CLOSED
Company: SENIOR PLC 10p

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
Why does this bug occur and what does that company mean exactly?

**Comment by pauljsymonds** [comment]
> Why does this bug occur and what does that company mean exactly?

This is just ticker info returned from yfinance and displayed when stock is loaded.

The formatting was incorrect and in some instances it displayed extra info.

I think it still requires some work but the initial bugs identified are fixed.

**Comment by JerBouma** [comment]
Alright, makes sense to do it this way then.

**Comment by pauljsymonds** [comment]
RE the Pylint error, I am 99% sure I tested this with both lower and uppercase in the terminal and I got an issue hence the change to the logic:

************* Module openbb_terminal.stocks.stocks_helper
[13](https://github.com/OpenBB-finance/OpenBBTerminal/runs/7147740560?check_suite_focus=true#step:15:14)
openbb_terminal/stocks/stocks_helper.py 1006: R1727 Boolean condition ''.US' or '.us' in ticker' will always evaluate to ''.US'' (condition-evals-to-constant)
[14](https://github.com/OpenBB-finance/OpenBBTerminal/runs/7147740560?check_suite_focus=true#step:15:15)

I also tried a .upper() but this function did not like a str.

**Review by colin99d — APPROVED** [review]
Looks great! Will merge once tests pass. Thanks for this!!

**Pull request merged**
