### PR TITLE
[Docs] Refactor Docs Pages For Diataxis

### PR DESCRIPTION
**Pull request by deeleeramone**
1. **Why**? (1-3 sentences or a bullet point list):

    - The Documentation was harder to navigate for people that were not used to the style of learning it was facilitating. We observed that the Diataxis framework had solutions for 4 major archetypes of learning styles which we refactored our documentation to.
    
2. **What**? (1-3 sentences or a bullet point list):

    - Changes the order and structure of the documentation to follow an OpenBB-adapted Diataxis framework.
    - Adds a few new pages.

3. **Impact** (1-2 sentences or a bullet point list):

    - Once merged, this will change the documentation flow and the look and feel of it.

4. **Testing Done**:

    - Made sure it works and that links aren't broken.
    - Still requires testing from users.
    
5. **Reviewer Notes** (optional):

    - Please try approaching this with fresh eyes and following parts of it.

### CODE REVIEW

**Comment by jmaslek** [comment]
When I first land on the platform page, the navbar is kind of vague:

Screenshot 2024-05-02 at 11 57 33 AM

i,e what is the dfifference between a How-To Guide and a Tutorial?  Same with Explanation.  I dont understand what Explanation means vs introduction or Technical Descriptions or FAQS.

**Comment by jmaslek** [comment]
Im also confused on some overlap.  For example there is extensions/data extensions and extsnions/toolkit , but then there is also explanation/toolkit vs provider

**Comment by jmaslek** [comment]
I think the things not clicking for me is

 - There is no quick getting started

 - There is no quick development guide

If I look at pandas, numpy, pytorch, scikit-learn, react, etc they all have a quick start/getting started and a development page, whereas with this I dont see exactly where we want people to be going first.

**Comment by deeleeramone** [comment]
This section has nothing to do with development, it belongs with either Installation or Getting Started.

Screenshot 2024-05-21 at 9 51 11 AM

**Comment by deeleeramone** [comment]
I'm confused by this, how is Publishing to PyPI related to the User experience? This is clearly a developer guide.

Screenshot 2024-05-21 at 9 56 38 AM

**Comment by deeleeramone** [comment]
Somewhere, not sure where exactly it fits, we need a page for the 'defaults' within `user_settings.json`.

**Comment by deeleeramone** [comment]
There are a couple of pages with explanations of, and examples demonstrating how to use, the charting extension, but are missing in this PR.

**Comment by jmaslek** [comment]
I think these should probably move under developer guide?

Screenshot 2024-05-21 at 2 27 37 PM

**Comment by jmaslek** [comment]
Same with the bottom ones here.  

Notsure if we want to maybe make a "how-to/quiickstart" type folder under developer guide for being super clear that these are where you can find how to quickly add to platform?

Screenshot 2024-05-21 at 2 29 12 PM

**Comment by jmaslek** [comment]
Also the Commitment of Traders probably up to getting started with theother usage examples?

**Review by jmaslek — APPROVED** [review]
Screenshot 2024-05-21 at 3 03 08 PM

**Review by IgorWounds — APPROVED** [review]

**Pull request merged**
