### PR TITLE
historical data for cost to borrow using stocksera api #1300

### PR DESCRIPTION
**Pull request by guanquann**
# Description

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [x] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Hey @guanquann,

Thanks for this! Could you add your key to our `keys_controller` menu so that we can set it directly from the terminal without need to play with files outside that?

Screenshot 2022-08-27 at 15 26 55

In addition, is there any reason why stocksera is set as default? Usually I set as default a data source that doesn't need an API key, UNLESS the quality of the data is better or so. What's the reasoning here?

**Comment by guanquann** [comment]
> Hey @guanquann,
> 
> Thanks for this! Could you add your key to our `keys_controller` menu so that we can set it directly from the terminal without need to play with files outside that?
> 
> Screenshot 2022-08-27 at 15 26 55
> 
> In addition, is there any reason why stocksera is set as default? Usually I set as default a data source that doesn't need an API key, UNLESS the quality of the data is better or so. What's the reasoning here?

Oops I didn't know the convention for default data source. Just feel that historical cost to borrow of a specific stock is better than the current cost of borrow of all stocks

**Comment by colin99d** [comment]
@DidierRLopes what are we planning on doing with this PR?

**Comment by DidierRLopes** [comment]
> @DidierRLopes what are we planning on doing with this PR?

What's the time expected to fix the issues and merge it?

**Comment by colin99d** [comment]
Not sure but I can take lead in it. I am going to start a new PR because this has so many conflicts.

**Pull request closed without merging**
