### PR TITLE
Hotfix/bug #3837

### LINKED ISSUE #3837: [Bug] Crypto/Disc/NFT - `--sort` argument fails when column name has a space in it.
```
/crypto/disc/nft
```
Screenshot 2022-12-27 at 10 00 24 AM

```
(🦋) /crypto/disc/ $ nft --sort Volume [$]

usage: nft [-l LIMIT] [-s SORTBY [SORTBY ...]] [-h] [--export EXPORT]
nft: error: argument -s/--sort: invalid choice: 'Volume' (choose from 'Name', 'Protocols', 'Floor Price [$]', 'Avg Price [$]', 'Market Cap [$]', 'Volume [$]')

(🦋) /crypto/disc/ $
```

### LINKED ISSUE #4106: [Bug] Crypto/disc/nft - dappradar api exception: Access denied - big wall of red text
Big wall of red text, and looks like an issue with cloudflare.

```
2023 Feb 01, 13:48 (🦋) /crypto/disc/ $ nft

dappradar api exception: <!DOCTYPE html>
<html lang="en-US">
   <head>
      <title>Access denied</title>
      <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
      <meta name="robots" content="noindex, nofollow" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <link rel="stylesheet" href="/cdn-cgi/styles/errors.css" media="screen" />
      <script>
(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:5}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
</script>

      <script>
      (function(){function d(c){var b=document.getElementById("copy-label"),a=document.getElementById("cf-details-wrapper-expandable");c.target.checked?a.classList.add("expanded"):(a.classList.remove("expanded"),b.innerText="Click to copy")}if(document.addEventListener){var e=function(){var c=document.getElementById("copy-label");var b=document.getElementById("error-details").textContent;if(navigator.clipboard)navigator.clipboard.writeText(b);else{var a=document.createElement("textarea");a.value=b;a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}c.innerText="Copied text to clipboard"};document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("error-details-checkbox"),b=document.getElementById("click-to-copy-btn");document.getElementById("copy-label").classList.remove("hidden");c.addEventListener("change",d);b.addEventListener("click",e)})}})();
      </script>
      <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
   </head>
   <body>
   <div class="cf-main-wrapper" role="main">
      <div class="cf-header cf-section">
         <div class="cf-error-title">
            <h1>Access denied</h1>
            <span class="cf-code-label">Error code <span>1020</span></span>
         </div>
         <div class="cf-error-description">
            <p>You do not have access to nft-sales-service.dappradar.com.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
         </div>
      </div>
   </div>

   <div class="cf-details-wrapper">
      <div class="cf-section" role="region">
         <div class="cf-expandable" id="cf-details-wrapper-expandable">
            <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
               <p class="cf-dropdown-title">Error details</p>
               <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
               class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
            </label>

            <input id="error-details-checkbox" class="hidden" type="checkbox">

            <div class="cf-expandable-error-info hidden">
               <p class="cf-error-copy-description">Provide the site owner this information.</p>
               <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
<div class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting nft-sales-service.dappradar.com/v2/collection/day?limit=20&amp;page=1&amp;currency=USD&amp;sort=marketCapInFiat&amp;order=desc.</p>

<p>Error code: 1020</p>
<p>Ray ID: 792cdc67aa0cc664</p>
<p>Country: CA</p>
<p>Data center: sea06</p>
<p>IP: 2604:3d08:8e7c:ba00:3194:dbd2:2d83:8121</p>
<p>Timestamp: 2023-02-01 18:48:22 UTC</p>
</div>
                  <p class="cf-copy-label hidden" id="copy-label">Click to copy</p>
               </button>
            </div>
         </div>
      </div>

      <div class="clearfix cf-footer cf-section" role="contentinfo">
      <div class="cf-column">
           <div class="feedback-hidden py-8 text-center" id="error-feedback">
    <div id="error-feedback-survey" class="footer-line-wrapper">
        Was this page helpful?
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
    </div>
    <div class="feedback-success feedback-hidden" id="error-feedback-success">
        Thank you for your feedback!
    </div>
</div>

      </div>
         <div class="cf-column cf-footer-line-wrapper text-center">
            <p>
               Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=1020_error" target="_blank">Cloudflare <img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link"></a>
            </p>
         </div>
      </div>
   </div>
<script>(function(){var js = "window['__CF$cv$params']={r:'792cdc67aa0cc664',m:'2svdAiQndlwGCg1VzCKTXEamgGDRNFicvmMliWkc82I-1675277302-0-AfPg921NxUBovSMbQCJNjW2D4ak8+1C4JzNd5lvqIEEZ7WePBX0sZn78jV5IlXzVl2vgruaRc82gOtgfdO8gyIgvqQ1v/AhcZ4QezJxDMjGRH31dOTzRb5WK5/DNSyCVNfOkOst8j+mYa4ErBYx0cU9RIulKZmXISy0j4wQ0cI9WH9izshI9oIMeQ4Udr77XTmTHH39ImEcd7OkebT5H7OU=',s:[0x23ec1caf79,0x0d24de811e],u:'/cdn-cgi/challenge-platform/h/b'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/b/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"792cdc67aa0cc664","token":"63428c9194c94d3abc7fb049876380f6","version":"2022.11.3","si":100}' crossorigin="anonymous"></script>
</body>
</html>

Failed to fetch data from DappRadar
```

### PR DESCRIPTION
**Pull request by brendef**
# Description

Fixing the bug referenced at #3837 - adding a space in the sort options causes the application to produce an error. I replaced the spaces with underscores.

Before fix
beforeFix#3837

After fix
afterFix#3837

I fixed this as I like this project and would love to be more involved. 

# How has this been tested?

- [x] Iterm2 on MacOS 

To reproduce this error, reference a column name with a space when sorting on any command in the crypto/disc/ category

# Checklist:

- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).

# Others
- [x] I have performed a self-review of my own code.

Fix #4106
Fix #3837

### CODE REVIEW

**Comment by jmaslek** [comment]
When I run this I get some errors:
```
2023 Jan 19, 14:43 (🦋) /crypto/disc/ $ nft --sort floor_price_[$]

dappradar api exception: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /v2/collection/day</pre>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"78c20f9999aa81fd","token":"63428c9194c94d3abc7fb049876380f6","version":"2022.11.3","si":100}' crossorigin="anonymous"></script>
</body>
</html>

Error: local variable 'df' referenced before assignment

Error: 'list' object has no attribute 'empty'
```

**Comment by brendef** [comment]
> When I run this I get some errors:
> 
> ```
> 2023 Jan 19, 14:43 (🦋) /crypto/disc/ $ nft --sort floor_price_[$]
> 
> dappradar api exception: <!DOCTYPE html>
> <html lang="en">
> <head>
> <meta charset="utf-8">
> <title>Error</title>
> </head>
> <body>
> <pre>Cannot GET /v2/collection/day</pre>
> <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"78c20f9999aa81fd","token":"63428c9194c94d3abc7fb049876380f6","version":"2022.11.3","si":100}' crossorigin="anonymous"></script>
> </body>
> </html>
> 
> Error: local variable 'df' referenced before assignment
> 
> Error: 'list' object has no attribute 'empty'
> ```

Thanks James, I'll get on fixing this immediately

**Comment by deeleeramone** [comment]
What's the status on this, @brendef? Have you applied this to the rest of the functions in the menu?



```
2023 Feb 18, 19:36 (🦋) /crypto/disc/ $ gainers --sort Volume [$]

usage: gainers [-i {14d,1h,1y,200d,24h,30d,7d}] [-l LIMIT] [-s SORTBY [SORTBY ...]] [-h] [--export EXPORT] [--sheet-name SHEET_NAME [SHEET_NAME ...]]
gainers: error: argument -s/--sort: invalid choice: 'Volume' (choose from 'Symbol', 'Name', 'Price [$]', 'Market Cap', 'Market Cap Rank', 'Volume [$]')
```

**Comment by hjoaquim** [comment]
Is it just me or someone else with this weird behavior:

image

When I go to the `crypto/disc` menu, I can't get any responses nor print help the menu

**Comment by hjoaquim** [comment]
Is it just me or someone else with this weird behavior:

image

When I go to the `crypto/disc` menu, I can't get any responses nor print help the menu

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
