### PR TITLE
Add ETF support for portfolio allocation command

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

This PR adds ETF support to the `alloc` command in the `portfolio` menu. This means that users that do not provide any country, sector or region for their ETF trades will still be able to see their allocations.

The method is similar on what was used to fetch company data for stocks. In this case the allocation_model module will automatically search for the ETF sector/country/region weights and assign the proportional value to the portfolio allocations.

Additional changes:
* Added ISINs as primary identifier for ETF/STOCKS data
* Fix print_rich_table bug on decimal places for np.float64 format
* Refactor assets allocation logic
* Pre-load SPY as a default benchmark so that user is not blocked to use commands after loading, it still can be changed with `bench`. It's similar to what was done with risk free rate.
* Fix bug when two trades of same stock occur in the same day
* Reformat `show` output and allow export
* Fix bug when alloc category empty
* Fix bug when optional fields empty

Example:

Portfolio X holdings, %:
ETF ABC:      1000$, 50%
STOCK XYZ: 1000$, 50%

Suppose ETF ABC has 50% stocks in US and 50% in Brazil, so it will contribute 500$ to the US allocation and 500$ to Brazil.
Suppose STOCK XYZ is from US.

Final country allocs, %:
US: 1500$, 75%
Brazil: 500$, 25%

- [x] Summary of the change / bug fix.
- [x] Relevant motivation and context. 

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
I can not test this because it requires me to set 2FA (which I haven't enabled). Furthermore, the process of getting this code is far too difficult for the user (see: https://github.com/Chavithra/degiro-connector#36-how-to-find-your--totp_secret_key-)

@Chavithra is there a proper solution for setting the DEGIRO key without needing 2FA? It currently crashes if I try to do exactly that.

image

**Comment by Chavithra** [comment]
Hi @JerBouma,

are you suggesting letting the user manually adding 2FA password each time they use the Terminal ?

Thanks

**Comment by JerBouma** [comment]
That sounds good. You gotta try and make it accessible for people that just know how to navigate the terminal. We can not ask them to edit some file or extract some code from an URL. Therefore the ideal solution here would be:

1. Let them set-up their DEGIRO account directly from `keys` (without the option provide 2FA here)
2. When they wish to log-in into the DEGIRO menu we have inside the `portfolio` menu, if they have 2FA enabled they input the 2FA key in here. Otherwise, simply running `login` should suffice.
3. They can now use the DEGIRO functionalities.

**Comment by JerBouma** [comment]
The current issue with the implementation is that it doesn't recognize that I bought ETFs on a different exchange. For example the ETF `VUSA` is this product on Yahoo Finance: https://finance.yahoo.com/quote/VUSA.AS/ and the U.S. equivalent is `VOO`. To make this work, the tickers need to be converted into ISIN properly.

```
2022 Aug 03, 05:52 (🦋) /portfolio/ $ load 20220803_105213_paexport_degiro.csv
 Preprocessing orderbook: ..........
    Loading company data: ......
      Loading price data: 
4 Failed downloads:
- IWDA: No data found, symbol may be delisted
- VUSA: No data found for this date range, symbol may be delisted
- VWRL: No data found for this date range, symbol may be delisted
- ESP0: No data found, symbol may be delisted
.Error: Index contains duplicate entries, cannot reshape


     Calculating returns: Error: 'Quantity'

Error: 'End Value'


Portfolio: 20220803_105213_paexport_degiro.csv
Risk Free Rate: 0
```

**Comment by montezdesousa** [comment]
> The current issue with the implementation is that it doesn't recognize that I bought ETFs on a different exchange. For example the ETF `VUSA` is this product on Yahoo Finance: https://finance.yahoo.com/quote/VUSA.AS/ and the U.S. equivalent is `VOO`. To make this work, the tickers need to be converted into ISIN properly.
> 
> ```
> 2022 Aug 03, 05:52 (🦋) /portfolio/ $ load 20220803_105213_paexport_degiro.csv
>  Preprocessing orderbook: ..........
>     Loading company data: ......
>       Loading price data: 
> 4 Failed downloads:
> - IWDA: No data found, symbol may be delisted
> - VUSA: No data found for this date range, symbol may be delisted
> - VWRL: No data found for this date range, symbol may be delisted
> - ESP0: No data found, symbol may be delisted
> .Error: Index contains duplicate entries, cannot reshape
> 
> 
>      Calculating returns: Error: 'Quantity'
> 
> Error: 'End Value'
> 
> 
> Portfolio: 20220803_105213_paexport_degiro.csv
> Risk Free Rate: 0
> ```

Yes, thanks for testing this, I'll try to fix that

**Comment by DidierRLopes** [comment]
@montezdesousa @JerBouma let's try to merge these PRs. As we refactor code, it will be harder to come back to these files to get them merged.

**Comment by montezdesousa** [comment]
> @montezdesousa @JerBouma let's try to merge these PRs. As we refactor code, it will be harder to come back to these files to get them merged.

I'll try this sprint

**Comment by JerBouma** [comment]
How far is this one coming along? @montezdesousa

**Comment by montezdesousa** [comment]
> How far is this one coming along? @montezdesousa 

Been afk this last 7 days. So sprint starting tomorrow for me, will try to deliver anyways @JerBouma

**Comment by JerBouma** [comment]
There are still some things off. As you can see the return calculation we do is not the same as on DEGIRO. It is fine that it differs a little but this is too much. Furthermore, it is impossible that the benchmark has such poor return given that my current portfolio consists primarily of S&P500 and World (thus the benchmark is closely related). Could you look into this? @montezdesousa 

image

**Review by JerBouma — APPROVED** [review]

**Pull request merged**
