### PR TITLE
NFTs - added floor price and collections commands

### PR DESCRIPTION
**Pull request by jose-donato**
# Description

Will be updated, missing tests and docs

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by jmaslek — CHANGES_REQUESTED** [review]
`ctrl A` 
`delete`

**Comment by minhhoang1023** [comment]
Would be nice to have a plot of price floor for the top collections for comparison purposes
image

image

**Comment by jose-donato** [comment]
> Would be nice to have a plot of price floor for the top collections for comparison purposes image
> 
> image

that involves making one request for each collection but it's a nice suggestion

will make add a flag like --fp on collections command that will do what you suggested :)

**Comment by minhhoang1023** [comment]
Can we use another color here? Yellow and orange on the same screen are not the best color combination. Or we can put them into a separate axis. 

image

image

**Comment by minhhoang1023** [comment]
Nice work! And go back to your pool - it's your vacay!

**Comment by jose-donato** [comment]
> Would be nice to have a plot of price floor for the top collections for comparison purposes image
> 
> image

image

**Comment by jose-donato** [comment]
@Chavithra please assist a test noob :( added the mock for the api call in init

**Comment by minhhoang1023** [comment]
This is a good one

image

**Comment by minhhoang1023** [comment]
can we add a legend here?
image

Other than that, lgtm!

**Comment by jose-donato** [comment]
> can we add a legend here? image
> 
> Other than that, lgtm!

image

since it's different axis i'm not sure if there is a better way of doing it

**Review by minhhoang1023 — APPROVED** [review]

**Pull request merged**
