### PR TITLE
SDK : faster and simpler architecture

### PR DESCRIPTION
**Pull request by Chavithra**
# Description

Currently the SDK contains different features:
- shortcuts
- selection between model and view : according to the chart=True/False parameter
- documentation of the module
- documentation of the functions
- logging

All these parts are entangled, which makes it hard to check/change one specific part.

**GOAL**
This PR is meant to make code more team work friendly.

**SIDE EFFECT**
The loading time of the SDK is reduced.

### CODE REVIEW

**Comment by piiq** [comment]
Is this mergeable?

P.S. How do we import the sdk after this change?

**Comment by hjoaquim** [comment]
> 

It would be like this:

```python
from openbb_terminal.core.library.sdk import openbb
```

**Comment by jmaslek** [comment]
Why are we making this much harder to import for an end user?  From openbb.sdk is fine, but now needing openbb.core.library.sdk is not.

**Comment by Chavithra** [comment]
> Why are we making this much harder to import for an end user? From openbb.sdk is fine, but now needing openbb.core.library.sdk is not.

Yes this was just for the drafting time.

Changed it to `openbb.sdk`

**Review by hjoaquim — APPROVED** [review]
Looks good to me!

**Comment by hjoaquim** [comment]
@montezdesousa @jmaslek this is ready imo, but since I was also pushing some commits, would be cool if one of you took a look at this! Tks!

**Comment by hjoaquim** [comment]
Also, @jmaslek we're keeping the `from openbb_terminal.sdk import openbb` so there are no changes from the user's perspective!

**Pull request merged**
