### PR TITLE
fixing equity report issue

### PR DESCRIPTION
**Pull request by andrewkenreich**
# Description

This fixes the equity reports - a SDK command was deleted and new one wasn't being used

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by deeleeramone — CHANGES_REQUESTED** [review]
The data request here is going to be problematic, and will always return nothing. Should be, `company_name`, right?

```
tables = openbb.etf.news(info["Short name"][0], 5) if "Short name" in info else symbol
```

**Comment by deeleeramone** [comment]
Data is failing to return from `openbb.stocks.fa.analyst`.

Screenshot 2023-04-27 at 1 58 13 PM

Screenshot 2023-04-27 at 2 04 10 PM

**Comment by deeleeramone** [comment]
Should probably avoid using sources that require an API key so that a demonstration notebook will work straight-out-of-the-box.  We get weird results for similar companies to `MSFT`. `RHT` is an OTC penny stock, Reliq Health Technologies, from Canada.  Not very much is similar between the two here.

Screenshot 2023-04-27 at 2 09 06 PM

**Comment by deeleeramone** [comment]
Not getting any insider data from one place, but it does exist when `openbb.stocks.ins.stats()` is used.

Screenshot 2023-04-27 at 2 19 14 PM

**Comment by deeleeramone** [comment]
A font is being called here, and the vast majority of people will not have it installed.

Screenshot 2023-04-27 at 2 23 24 PM

**Comment by deeleeramone** [comment]
@andrewkenreich I tried patching some additional items, try it out and lemme know what breaks.

**Review by deeleeramone — APPROVED** [review]

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
