### PR TITLE
My second attempt at coverage

### PR DESCRIPTION
**Pull request by colin99d**
# Description

This is my second attempt at adding code coverage to Github Actions. This time I used a much simpler package. Before we merge I want to make sure this is the type of coverage we want. I see two different kinds:

Large Companies:
These projects offer much more features and insight, BUT are more complicated AND require a user to click off of Github

Small repos:
These projects typically offer a simple automated post into the discussion board. These do not have quit as much insight, but they give us a quick way to get good feedback.

The repo included is one from the second option.

# How has this been tested?

Output shows below.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by Chavithra** [comment]
Hi @colin99d, is this creating a new comment each time ?

**Comment by colin99d** [comment]
> 

1. Yes, this is not the desires behavior and I will work on this after I fix the no report being shown
2. Yes that is an issue, see more [here](https://github.com/MishaKav/pytest-coverage-comment/issues/64)

On the bright side, even when this fails it does not make tests fail. So it will not slow us down like CodeCov.

**Review by Chavithra — CHANGES_REQUESTED** [review]
Two issue left :
1. Multiple comment showing
2. Coverage report not showing

**Comment by Chavithra** [comment]
> > 
> 
> 1. Yes, this is not the desires behavior and I will work on this after I fix the no report being shown
> 2. Yes that is an issue, see more [here](https://github.com/MishaKav/pytest-coverage-comment/issues/64)
> 
> On the bright side, even when this fails it does not make tests fail. So it will not slow us down like CodeCov.

@colin99d This PR seems to be an alternative.

Using xml instead of txt report.

**Comment by colin99d** [comment]
> 
> @colin99d This PR seems to be an alternative.
> 
> Using xml instead of txt report.

I do not believe they currently support XML. See this pr: https://github.com/MishaKav/pytest-coverage-comment/pull/59

**Comment by colin99d** [comment]
Looks like our first issue was fixed: https://github.com/MishaKav/pytest-coverage-comment/issues/64

**Comment by Chavithra** [comment]
> > @colin99d This PR seems to be an alternative.
> > Using xml instead of txt report.
> 
> I do not believe they currently support XML. See this pr: [MishaKav/pytest-coverage-comment#59](https://github.com/MishaKav/pytest-coverage-comment/pull/59)

Yeah was talking about this PR

Just forgot to put the PR link in my comment.

**Comment by colin99d** [comment]
> Two issue left :
> 
> 1. Multiple comment showing
> 2. Coverage report not showing

@Chavithra I spoke with the owner of the repo and we just need to change the coverage report to only run on pull_request. Once that is done we are good to go.

**Review by Chavithra — CHANGES_REQUESTED** [review]
Way better : now we have one single comment.

But the `Coverage Report` doesn't seem accurate to me.

**Comment by jmaslek** [comment]
is this alive?

**Comment by colin99d** [comment]
No. A lot of issues and too low priority to think about.

**Comment by DidierRLopes** [comment]
@colin99d will close this. You can always reopen this in the future 😄

**Pull request closed without merging**
