### PR TITLE
Update beta_model.py

### PR DESCRIPTION
**Pull request by AlexSchroer**
The script did not work and produced an error when loading the api in Jupyter Lab. line 11 and 12 edited and it works, hope it is correct.

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by colin99d** [comment]
Hey Alex, what version of python are you using? This looks like a typings issue which is weird because typically that will not interfere when actually running stuff.

**Comment by AlexSchroer** [comment]
Hi Colin, I use Python 3.8.13

**Comment by colin99d** [comment]
Screen Shot 2022-08-04 at 7 20 13 AM
It seems to be working fine for me and python 3.8 should not be causing issues. Do you mind sending me the code you ran?

**Comment by AlexSchroer** [comment]
it threw an error when trying to import the openbb_terminal library. I have updated everything yesterday and now it works. Sorry for causing work.

**Pull request closed without merging**
