### PR TITLE
Updates crypto load docs to match last load refactor

### PR DESCRIPTION
**Pull request by jose-donato**

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]
@deeleeramone created a ticket to add more granularity on the data. FYI 😋

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Why did you change the `closes[:-365]` to `closes[:365]`

**Comment by jose-donato** [comment]
> Why did you change the `closes[:-365]` to `closes[:365]`

i think there was an error. that column was displaying NaN. why would it be -365?

**Comment by DidierRLopes** [comment]
> > Why did you change the `closes[:-365]` to `closes[:365]`
> 
> i think there was an error. that column was displaying NaN. why would it be -365?

There's actually an issue, it should be `closes[-365:]` - this is so that we take the last 365 days from the data to calculate volatility

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
