### PR TITLE
Improves PO controller from UX perspective 

### PR DESCRIPTION
**Pull request by DidierRLopes**
This PR does the following:
* Improve UX of PO menu to be more intuitive 
* Commands unavailable when portfolio not loaded
* Fix reset to re-load portfolio and re-load params
* Remove add/rmv commands
* Allow -h in load and file cmd

### CODE REVIEW

**Comment by JerBouma** [comment]
@DidierRLopes If you haven't already, could you also look into this:

/portfolio/po/load & file do not show a help dialogue with -h flag
```
(🦋) /portfolio/po/ $ load -h
usage: load -f FILE [FILE ...] [-h]
load: error: the following arguments are required: -f/--file
```

**Comment by DidierRLopes** [comment]
> @DidierRLopes If you haven't already, could you also look into this:
> 
> /portfolio/po/load & file do not show a help dialogue with -h flag
> 
> ```
> (🦋) /portfolio/po/ $ load -h
> usage: load -f FILE [FILE ...] [-h]
> load: error: the following arguments are required: -f/--file
> ```

Yup, let me do that now :)

**Comment by DidierRLopes** [comment]
> > @DidierRLopes If you haven't already, could you also look into this:
> > /portfolio/po/load & file do not show a help dialogue with -h flag
> > ```
> > (🦋) /portfolio/po/ $ load -h
> > usage: load -f FILE [FILE ...] [-h]
> > load: error: the following arguments are required: -f/--file
> > ```
> 
> Yup, let me do that now :)

Should be done now @JerBouma

**Review by JerBouma — APPROVED** [review]
Looks good to me :)

**Pull request merged**
