### PR TITLE
Update installation docs for release

### PR DESCRIPTION
**Pull request by piiq**
- Point download links for environment and docker artifacts to main instead of a blob
- Clean-up debug echo in macos launcher script

### CODE REVIEW

**Comment by jmaslek** [comment]
I cant build locally:

```
Module build failed (from ./node_modules/@docusaurus/mdx-loader/lib/index.js):
SyntaxError: /Users/james/OpenBBTerminal/OpenBBTerminal/website/content/terminal/installation/macos.md: Expected corresponding JSX closing tag for <img>. (48:0)
```

**Comment by deeleeramone** [comment]
Also cannot build locally. 

Screenshot 2023-04-24 at 9 49 39 AM

**Comment by deeleeramone** [comment]
Do we update the download links now? Is there a way to make this more robust so that it doesn't need to be updated manually every release?

**Comment by piiq** [comment]
> Do we update the download links now?

No, James does this as a part of the release routine in the release branch



> Is there a way to make this more robust so that it doesn't need to be updated manually every release?

This question is outside of the scope of this PR

**Review by deeleeramone — APPROVED** [review]
Looks good.

**Pull request merged**
