### PR TITLE
[Feature] Add support for multiple tags in `historical_attributes` and `latest_attributes`

### PR DESCRIPTION
**Pull request by the-praxs**
# Why
Enhances the following endpoints to fetch data for multiple symbols and tags - 
* `equity/fundamental/historical_attributes`
* `equity/fundamental/latest_attributes`

This feature was requested by @minhhoang1023 and @andrewkenreich.

# What
* Added a field validator to add support for multiple symbols and tags in the standard models 
* Added new `symbol` and `tag` field in the standard models to identify the value in the `value` field
* Modified the `extract_data` function in the respective models to fetch data from multiple urls
* Added a new function `generate_url` within the `extract_data` function to generate urls for multiple symbols and tags
* Added a new `callback` function to fetch data from the Intrinio endpoints
* Added a check for response errors which sends an `OpenBBWarning` in the `callback` function
* Updated static files 

# Impact
* Minimal performance impact
* No breaking changes

# Tests
* Updates the params in the `latest_attributes` and `historical_attributes` fetcher tests for Intrinio
* Adds new params to the `latest_attributes` and `historical_attributes` commands in the `equity` menu integration tests

### CODE REVIEW

**Review by tehcoderer — APPROVED** [review]
LGTM 🚢 IT

**Review by IgorWounds — APPROVED** [review]

**Comment by deeleeramone** [comment]
I can create an error when the tag is not included in the data entitlements of the API key.

```
obb.equity.fundamental.latest_attributes("AAPL", tag="tipranks_news_bearish_1w")
```

```
OpenBBError: 2 validation errors for IntrinioLatestAttributesData
value.str
  Input should be a valid string [type=string_type, input_value={'error': 'Data access no....com with the details.'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
value.float
  Input should be a valid number [type=float_type, input_value={'error': 'Data access no....com with the details.'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/float_type
```

**Comment by deeleeramone** [comment]
We should be able to enter a proper List from the Python interface - like symbols.

```
obb.equity.fundamental.latest_attributes("AAPL", tag=["evtoebit","evtoocf"]).to_df()
```

```
ValidationError: 1 validation error for latest_attributes
tag
  Input should be a valid string [type=string_type, input_value=['evtoebit', 'evtoocf'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
```

**Comment by the-praxs** [comment]
> I can create an error when the tag is not included in the data entitlements of the API key.
> 
> ```
> obb.equity.fundamental.latest_attributes("AAPL", tag="tipranks_news_bearish_1w")
> ```
> 
>  ```
> OpenBBError: 2 validation errors for IntrinioLatestAttributesData
> value.str
>   Input should be a valid string [type=string_type, input_value={'error': 'Data access no....com with the details.'}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.5/v/string_type
> value.float
>   Input should be a valid number [type=float_type, input_value={'error': 'Data access no....com with the details.'}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.5/v/float_type
> ```
> 
> Similarly, when a tag is not valid a validation error occurs. The bad tag should be communicated in the warnings so that the valid items can still be returned. If all tags are bad, then raise EmptyDataError.

I added the `OpenBBWarning` that gets reflected in the `warnings` attribute of the `OBBject`. This allows us to retrieve data for other valid tags, if any, passed to the command.


> We should be able to enter a proper List from the Python interface - like symbols.
> 
> ```
> obb.equity.fundamental.latest_attributes("AAPL", tag=["evtoebit","evtoocf"]).to_df()
> ```
> 
>  ```
> ValidationError: 1 validation error for latest_attributes
> tag
>   Input should be a valid string [type=string_type, input_value=['evtoebit', 'evtoocf'], input_type=list]
>     For further information visit https://errors.pydantic.dev/2.5/v/string_type
> ```

Thank you for helping me with this one. I also added the functionality to pass multiple symbols also.

**Pull request merged**
