### PR TITLE
Update USD Liquidity Example Notebook for V4

### PR DESCRIPTION
**Pull request by deeleeramone**
This PR updates the example notebook of the USD Liquidity Index for use with OpenBB Platform V4.  It also adds a `.tsx` file with and `webp` preview images.  The images cannot be added directly to the `MD` files like we do in the documentation.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
I updated @jmaslek as a reviewer 🤝

**Comment by deeleeramone** [comment]
@jose-donato, will this TSX file and webp images be compatible with Hub if they are kept and maintained here?

**Comment by jose-donato** [comment]
> @jose-donato, will this TSX file and webp images be compatible with Hub if they are kept and maintained here?

i would make it a json so it's easier to fetch from the hub

**Comment by deeleeramone** [comment]
> i would make it a json so it's easier to fetch from the hub and also we would need to have the full path for the image to fetch it easily from the hub

More better now?

**Pull request merged**
