### PR TITLE
Fix 3184

### LINKED ISSUE #3184: [Bug] `crypto/dd/ex --descend` does not work
**Describe the bug**
1. `--descend` is not working
Screen Shot 2022-10-30 at 1 56 43 PM

**To Reproduce**
`crypto/dd/ex --descend`

### PR DESCRIPTION
**Pull request by jose-donato**
# Description

fix #3184

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
This is flipped.  By default its descending.  Flag should be --ascend

Screen Shot 2022-11-01 at 5 11 49 PM

**Comment by jose-donato** [comment]
> This is flipped. By default its descending. Flag should be --ascend
> 
> Screen Shot 2022-11-01 at 5 11 49 PM

yea i talked about this with andrew. it happens in lot of places and does not make sense at all

**Comment by jmaslek** [comment]
> yea i talked about this with andrew. it happens in lot of places and does not make sense at all

#3254 lol

**Comment by jose-donato** [comment]
> > yea i talked about this with andrew. it happens in lot of places and does not make sense at all
> 
> #3254 lol

cool

**Comment by jmaslek** [comment]
> cool, should i wait for that or convert this to ascend?

Lets change to ascend just to not be completely messed up.  My proposal would just need a giant find replace all.

**Comment by jose-donato** [comment]
Fixed

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
