### PR TITLE
Add Raspberry PI installation

### PR DESCRIPTION
**Pull request by Zedris**
I added a Raspbian (Raspberry Pi) installation section for the readme.
this entire installation took had me nuking my installation about 10-15 times to figure it out so it worked:P
Thanks for all the help Dangle!!

# Description

- [x] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [X] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by colin99d** [comment]
I love this PR! Great work! Unfortunately, I do not have a Raspberry Pi so I cannot test. @DidierRLopes do we have someone with one? Also, this is just icing on top, but we could have a command that automatically activates the environment and opens the terminal. I wrote a command that automatically adds such a command to your `.bashrc` so that it will work every time. Here is the command: `echo "function gst { conda activate gst && python terminal.py }" >> ~/.bashrc`.

**Comment by DidierRLopes** [comment]
> I love this PR! Great work! Unfortunately, I do not have a Raspberry Pi so I cannot test. @DidierRLopes do we have someone with one? Also, this is just icing on top, but we could have a command that automatically activates the environment and opens the terminal. I wrote a command that automatically adds such a command to your `.bashrc` so that it will work every time. Here is the command: `echo "function gst { conda activate gst && python terminal.py }" >> ~/.bashrc`.


Thanks for this @Zedris , this is amazing!

@colin99d since this is a living document and it's an installation of Raspberry PI, my first thinking is to go ahead and merge this 😄 If someone else tries the instruction and reports a bug they can let us know and we can improve the documentation based on that.

Thoughts?

**Comment by Zedris** [comment]
thanks guys i hope I wrote it up correctly I tried to copy the format already present in the readme. yea im a total noob so it took me way longer than i care to admit and alot of troubleshooting help from danglewood on disc to get gst up and running and then jupyter for a sort of headless run. ( i did make it harder for my self trying to run the pi on an ipad) but still graphs wont work unless i run a desktop environment and vnc into it or run the raspberry pi fully. if there was a way to get the graphs to run within the ssh terminal somehow it could be a fully remote gst terminal completely headless on an ipad or screen with just a tiny rpi :D

**Comment by colin99d** [comment]
> Thanks for this @Zedris , this is amazing!
> 
> @colin99d since this is a living document and it's an installation of Raspberry PI, my first thinking is to go ahead and merge this 😄 If someone else tries the instruction and reports a bug they can let us know and we can improve the documentation based on that.
> 
> Thoughts?

Sounds good to me!

**Review by colin99d — APPROVED** [review]

**Comment by DidierRLopes** [comment]
@Zedris my frieeeeend! Can you solve the markdown issues so we can merge these instructions? 🙌

**Pull request merged**
