### PR TITLE
Make default routines available & download personal routines on login

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

* Fixed `exe` command not allowing routines with spaces in file name
* Downloads and overwrites default routines from https://tffo1zc1.directus.app/items/Routines on login
* Downloads and overwrites personal routines on login (limited to 100 routines), this runs silently in a separate daemon thread to avoid stalling the user on login if download takes more than expected
* Deletes `account_model.py` and moves functions to `routines_handler.py`
* Adds "Version" and "Last update" columns to `account/list` command

image

Screenshot 2023-04-12 at 15 59 12

### CODE REVIEW

**Comment by JerBouma** [comment]
Something is off, it doesn't recognize my FRED key.

```

(🦋) / $ exe --file The Influence of the Central Bank.openbb



(🦋) /fixedincome/ $ ecb --export CentralBanks.xlsx --sheet-name ECB Rates

API_FRED_KEY not defined. Set the API key under keys menu.

(🦋) /fixedincome/ $ fed --export CentralBanks.xlsx --sheet-name FED Rates

API_FRED_KEY not defined. Set the API key under keys menu.

(🦋) /fixedincome/ $ projection --export CentralBanks.xlsx --sheet-name FED Projections

API_FRED_KEY not defined. Set the API key under keys menu.




(🦋) /economy/ $ ccpi --countries european_union_27 --start 2000-01-01 --export CentralBanks.xlsx --sheet-name CPI EU

Saved file: /Users/jeroenbouma/OpenBBUserData/exports/CentralBanks.xlsx

(🦋) /economy/ $ cpi --start 2000-01-01 --export CentralBanks.xlsx --sheet-name CPI US

API_FRED_KEY not defined. Set the API key under keys menu.

(🦋) /fixedincome/ $ treasury --long united_states,euro_area --export CentralBanks.xlsx --sheet-name Government Yields

Saved file: /Users/jeroenbouma/OpenBBUserData/exports/CentralBanks.xlsx
```

**Comment by montezdesousa** [comment]
> Something is off, it doesn't recognize my FRED key.
> 
> ```
> 
> (🦋) / $ exe --file The Influence of the Central Bank.openbb
> 
> 
> 
> (🦋) /fixedincome/ $ ecb --export CentralBanks.xlsx --sheet-name ECB Rates
> 
> API_FRED_KEY not defined. Set the API key under keys menu.
> 
> (🦋) /fixedincome/ $ fed --export CentralBanks.xlsx --sheet-name FED Rates
> 
> API_FRED_KEY not defined. Set the API key under keys menu.
> 
> (🦋) /fixedincome/ $ projection --export CentralBanks.xlsx --sheet-name FED Projections
> 
> API_FRED_KEY not defined. Set the API key under keys menu.
> 
> 
> 
> 
> (🦋) /economy/ $ ccpi --countries european_union_27 --start 2000-01-01 --export CentralBanks.xlsx --sheet-name CPI EU
> 
> Saved file: /Users/jeroenbouma/OpenBBUserData/exports/CentralBanks.xlsx
> 
> (🦋) /economy/ $ cpi --start 2000-01-01 --export CentralBanks.xlsx --sheet-name CPI US
> 
> API_FRED_KEY not defined. Set the API key under keys menu.
> 
> (🦋) /fixedincome/ $ treasury --long united_states,euro_area --export CentralBanks.xlsx --sheet-name Government Yields
> 
> Saved file: /Users/jeroenbouma/OpenBBUserData/exports/CentralBanks.xlsx
> ```

Does it work if you run those commands manually? Is the key defined in the keys menu?

**Comment by JerBouma** [comment]
Ahh this is on my end, it's because if you log-in I "lose" all API keys. Need to import env.

**Comment by jmaslek** [comment]
Works on my end.  Gonna merge this for release 

Screenshot 2023-04-13 at 8 41 14 AM

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
