### PR TITLE
Docker: update installation instruction

### PR DESCRIPTION
**Pull request by Chavithra**
# Description

Updating the installation instructions for Docker.

@Lukazcreations : can you validate the macOS instructions?
@hjoaquim : can you validate the instructions for Linux distributions?

Thanks

### CODE REVIEW

**Comment by hjoaquim** [comment]
@Chavithra 
When using `docker compose run openbb` 
I got `PermissionError: [Errno 13] Permission denied: '/home/python/OpenBBUserData/logs/808cdb43-7316-49e4-86d1-6d13ccc763f8/gst_docker_1670233023'` --> should be hjoaquim instead of python

Then I tried `docker run --rm -it \
  -v ~/.openbb_terminal/:/home/python/.openbb_terminal \
  -v ~/OpenBBUserData:/home/python/OpenBBUserData \
  ghcr.io/openbb-finance/openbbterminal/openbb:latest`
and got `Unable to find image`. Changing the `openbb:latest` to `openbb:2.0.0` I also got the error above.

**Comment by Lukazcreations** [comment]
@Chavithra 
After I ran this command `docker compose run -e DISPLAY=$IP:0 openbb`

`Traceback (most recent call last):
  File "/home/python/terminal.py", line 2, in <module>
    from openbb_terminal import terminal_controller
  File "/home/python/openbb_terminal/terminal_controller.py", line 27, in <module>
    from openbb_terminal.terminal_helper import is_packaged_application
  File "/home/python/openbb_terminal/terminal_helper.py", line 22, in <module>
    from openbb_terminal import thought_of_the_day as thought
  File "/home/python/openbb_terminal/thought_of_the_day.py", line 11, in <module>
    from openbb_terminal.helper_funcs import get_user_agent
  File "/home/python/openbb_terminal/helper_funcs.py", line 55, in <module>
    matplotlib.use(cfgPlot.BACKEND)
  File "/home/python/.cache/pypoetry/virtualenvs/openbb-K8M3siuK-py3.10/lib/python3.10/site-packages/matplotlib/__init__.py", line 1146, in use
    plt.switch_backend(name)
  File "/home/python/.cache/pypoetry/virtualenvs/openbb-K8M3siuK-py3.10/lib/python3.10/site-packages/matplotlib/pyplot.py", line 282, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "/home/python/.cache/pypoetry/virtualenvs/openbb-K8M3siuK-py3.10/lib/python3.10/site-packages/matplotlib/pyplot.py", line 283, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/python/.cache/pypoetry/virtualenvs/openbb-K8M3siuK-py3.10/lib/python3.10/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/home/python/.cache/pypoetry/virtualenvs/openbb-K8M3siuK-py3.10/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "/home/python/.cache/pypoetry/virtualenvs/openbb-K8M3siuK-py3.10/lib/python3.10/site-packages/matplotlib/backends/qt_compat.py", line 142, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding`

**Review by hjoaquim — APPROVED** [review]
Looks good to me - we'll address linux charts later.

**Review by Lukazcreations — APPROVED** [review]
Finally got it working on M1 Mac. The error I was getting was due to an edit on the .env file.

**Pull request merged**
