### PR TITLE
Removes command govp from crypto/defi

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description
Removes command govp from crypto/defi. As explained in #1936 the command was not working already because data was unavailable.

image

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?
pytest tests/openbb_terminal/cryptocurrency/defi/test_defi_controller.py --record-mode=rewrite

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by Chavithra — APPROVED** [review]
It seems ok to me.

**Comment by DidierRLopes** [comment]
@montezdesousa let's use a better naming for titles. When we scroll through closed PRs having "fix 9999" is not helpful. 

Also, if you mention the ticker on the PR that you are fixing with some keywords, e.g. "this pr **fixes #xxxx**" then once this gets merged that issue gets closed automatically 😄

**Comment by montezdesousa** [comment]
> @montezdesousa let's use a better naming for titles. When we scroll through closed PRs having "fix 9999" is not helpful. 
> 
> Also, if you mention the ticker on the PR that you are fixing with some keywords, e.g. "this pr **fixes #xxxx**" then once this gets merged that issue gets closed automatically 😄 

Ok sry about that, got it

**Comment by DidierRLopes** [comment]
> > @montezdesousa let's use a better naming for titles. When we scroll through closed PRs having "fix 9999" is not helpful.
> > Also, if you mention the ticker on the PR that you are fixing with some keywords, e.g. "this pr **fixes #xxxx**" then once this gets merged that issue gets closed automatically 😄
> 
> Ok sry about that, got it

No need to say sorry!! I did it too back in the day, and then had issues making sense of the titles 😄

PS: for the name of the branch it actually makes sense to have the issue number since it's a one-off thing that you will have locally, and we delete the branch after merging anyway.

**Comment by montezdesousa** [comment]
> > > @montezdesousa let's use a better naming for titles. When we scroll through closed PRs having "fix 9999" is not helpful.
> > > Also, if you mention the ticker on the PR that you are fixing with some keywords, e.g. "this pr **fixes #xxxx**" then once this gets merged that issue gets closed automatically 😄
> > 
> > 
> > Ok sry about that, got it
> 
> No need to say sorry!! I did it too back in the day, and then had issues making sense of the titles 😄
> 
> PS: for the name of the branch it actually makes sense to have the issue number since it's a one-off thing that you will have locally, and we delete the branch after merging anyway.

Yes, makes sense! Rookie mistakes 😄

**Pull request merged**
