### PR TITLE
Bump python version

### LINKED ISSUE #1960: [Bug]
**Describe the bug**
Open BB terminal fails to start on Apple M1.

**To Reproduce**
Followed the steps at:
https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#installing-the-terminal

**Command Line logs**
python terminal.py
Intel MKL FATAL ERROR: This system does not meet the minimum requirements for use of the Intel(R) Math Kernel Library.
The processor must support the Intel(R) Supplemental Streaming SIMD Extensions 3 (Intel(R) SSSE3) instructions.
The processor must support the Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) instructions.
The processor must support the Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

**Desktop (please complete the following information):**

- OS: Mac Monterey
- Python version 3.8.3

**Additional context**
Add any other information that you think could be useful for us.

### PR DESCRIPTION
**Pull request by piiq**
# Description

This PR upgrades the default python version to 3.9 in the dependencies and the documentation. This introduces the following features and fixes:

- Native support of Apple Silicon
- Resolves #1960
- Bumps version of tensorflow to 3.9 to resolve dependabot alerts
- Bumps the default python version for github actions

To test this PR recreate your conda environment following the updated documentation:

On **M1** macs: 

```bash
conda env remove -n gst
conda env create -n gst --file build/conda/conda-3-9-env.yaml
conda activate gst
poetry install
conda install -c apple tensorflow-deps
poetry install -E prediction-m1-mac
```

On all other platforms:

```bash
conda env remove -n gst
conda env create -n gst --file build/conda/conda-3-9-env.yaml
conda activate gst
poetry install
poetry install -E prediction
```

and run integrated tests for the terminal:

```bash
python terminal.py scripts/*.openbb -t
```

### CODE REVIEW

**Comment by piiq** [comment]
the integrated tests produced the following errors:

```
GamestonkTerminal/scripts/test_econometrics_panel.openbb: 'NoneType' object has no attribute 'name'
GamestonkTerminal/scripts/test_econometrics_ts.openbb: 'NoneType' object has no attribute 'name'
GamestonkTerminal/scripts/test_crypto_dd.openbb: 429 Client Error: Too Many Requests for url: https://api.coingecko.com/api/v3/coins/list
GamestonkTerminal/scripts/test_crypto_ov.openbb: 'Highest'
GamestonkTerminal/scripts/test_economy.openbb: cannot do slice indexing on DatetimeIndex with these indexers  of type str
GamestonkTerminal/scripts/test_stocks_options.openbb: Expiration `2022-07-08` cannot be found. Available expiration are: [2022-07-15, 2022-09-16, 2023-01-20, 2023-03-17, 2023-06-16, 2023-09-15, 2024-01-19]
```

**Comment by piiq** [comment]
@JerBouma @Chavithra can you look if this works on windows? The test commands are in the PR description

**Review by simmonsj330 — APPROVED** [review]
Looks good to me!

**Review by simmonsj330 — COMMENTED** [review]
Would changing the version number need to be done every version increase?

**Comment by piiq** [comment]
> Would changing the old version fallback tag to be done every version increase?

Yes

**Pull request merged**
