### PR TITLE
Test coverage of providers and params on integration tests

### PR DESCRIPTION
**Pull request by IgorWounds**
QA the QA

### CODE REVIEW

**Comment by hjoaquim** [comment]
Missing:
- test api int tests (should be the same logic)
- test python + api int tests for data processing commands (http=post)

**Comment by IgorWounds** [comment]
Missing:
  - update the nox file to run unit tests
  - make sure the unit tests for the QA pass

**Comment by the-praxs** [comment]
Validation Error and Module Not Found Error (tests.app). What could be causing this 🤔

**Comment by hjoaquim** [comment]
@piiq in this PR I've removed an `__init__.py` which apparently was causing naming issues among the tests. Can this cause any problems on CI or VSCode test explorer?

cc: @IgorWounds

**Pull request merged**
