### PR TITLE
Dependancy updates: Darts  --> `0.23.0` & thepassiveinvestor --> `1.0.11`

### PR DESCRIPTION
**Pull request by martinb-bb**

### CODE REVIEW

**Comment by jmaslek** [comment]
okay I dont see finviz on here :P

**Comment by jmaslek** [comment]
do you also need to update the check on import?

**Comment by martinb-bb** [comment]
> do you also need to update the check on import?

all done :)

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
Able to accss menu after running poetry install / poerty install -E prediction

**Pull request merged**
