### PR TITLE
Working through crypto fixes

### PR DESCRIPTION
**Pull request by colin99d**
# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by minhhoang1023 — COMMENTED** [review]
Nice work! 

A couple of comments:

- `api.crypto.load` should have the `symbol` param instead of `symbol_search`

image
- `api.crypto.candles`: The scientific notation should be replaced by [ KMBTP] magnitude. You can use the `lambda_long_number_format_y_axis` helper function
image
- `api.crypto.find`: we still have `coin` as a param, it should be `search_term`. As we allow them to specific whether it's a symbol, coin name or id.
image

- `api.crypto.defi.aterra` & `api.crypto.defi.ayr`: I got this error when using the endpoint. The API got deprecated?
image

- `api.crypto.defi.validators`: We would need the `sortby` key columns in docstring. Normally they can get it from the table, but in this case column names were already re-formatted.
image

- `api.crypto.disc.cggainers` & `api.crypto.disc.cglosers` throw an error
image

- `api.crypto.dd.nonzero`  & `api.crypto.dd.active` & `api.crypto.dd.change` & `api.crypto.dd.eb` & `api.crypto.dd.btcrb` & rest of commands in dd menu: `since` and `until` should be replaced by `start_date` and `end_date`
- `api.crypto.dd.book` & (api.crypto.dd.balance): `from_symbol` & `to_symbol` order is switched. Should be the other way around
image

- `api.crypto.dd.ps` & `api.crypto.dd.mkt`: we should use `from_symbol` and `to_symbol` like how you did above
- `api.crypto.dd.gh`: should have `start_date` and `end_date`
- `api.crypto.dd.news`: `top` should be `limit`

**Review by minhhoang1023 — CHANGES_REQUESTED** [review]
Left my comments in the above

**Comment by colin99d** [comment]
@minhhoang1023 it looks like the api.crypto.defi.aterra & api.crypto.defi.ayr commands may be out of commission. What should we do here?

**Comment by minhhoang1023** [comment]
> @minhhoang1023 it looks like the api.crypto.defi.aterra & api.crypto.defi.ayr commands may be out of commission. What should we do here?

Let's depreciate them 🔪

**Comment by minhhoang1023** [comment]
Adding one more comment:
- `api.crypto.dd.mcapdom` & `api.crypto.dd.mt` should have `start_date` and `end_date`

**Pull request merged**
