### PR TITLE
Fixed incorrect data display using `stocks/fa/est` command

### LINKED ISSUE #4938: [Bug] `fa/est -t AAPL -e quarterearnings` - data is not returning properly.
Recreate with: `fa/est -t AAPL -e quarterearnings`

Unknown rows in position 2 & 5.  Unknown column at the index position.

Screenshot 2023-04-30 at 3 17 08 PM

### PR DESCRIPTION
**Pull request by the-praxs**
Fixes #4938.

`get_estimates` has been revamped from the ground up to provide correct data for displaying on the terminal.

### CODE REVIEW

**Comment by the-praxs** [comment]
@jmaslek Is the test failing due to some expected values in `test_estimates.txt`?

**Comment by jmaslek** [comment]
> @jmaslek Is the test failing due to some expected values in `test_estimates.txt`?

Yup!  Since you changed the output slightly, the test needs to be re-recorded to capture what is expected.  You should be able to do so with:

(do for both _model and _view)

```pytest tests/openbb_terminal/stocks/fundamental_analysis/test_business_insider_model.py --rewrite-expected```

**Comment by the-praxs** [comment]
> > @jmaslek Is the test failing due to some expected values in `test_estimates.txt`?
> 
> Yup! Since you changed the output slightly, the test needs to be re-recorded to capture what is expected. You should be able to do so with:
> 
> (do for both _model and _view)
> 
> `pytest tests/openbb_terminal/stocks/fundamental_analysis/test_business_insider_model.py --rewrite-expected`

I get the following error when I run this command - `Exit: Uninstall brotli and brotlipy before running tests`

How to solve this issue?

**Comment by jmaslek** [comment]
> > > @jmaslek Is the test failing due to some expected values in `test_estimates.txt`?
> > 
> > 
> > Yup! Since you changed the output slightly, the test needs to be re-recorded to capture what is expected. You should be able to do so with:
> > (do for both _model and _view)
> > `pytest tests/openbb_terminal/stocks/fundamental_analysis/test_business_insider_model.py --rewrite-expected`
> 
> I get the following error when I run this command - `Exit: Uninstall brotli and brotlipy before running tests`
> 
> How to solve this issue?

`pip uninstall Brotli -y`

**Comment by jmaslek** [comment]
> > > > > @jmaslek Is the test failing due to some expected values in `test_estimates.txt`?
> > > > 
> > > > 
> > > > Yup! Since you changed the output slightly, the test needs to be re-recorded to capture what is expected. You should be able to do so with:
> > > > (do for both _model and _view)
> > > > `pytest tests/openbb_terminal/stocks/fundamental_analysis/test_business_insider_model.py --rewrite-expected`
> > > 
> > > 
> > > I get the following error when I run this command - `Exit: Uninstall brotli and brotlipy before running tests`
> > > How to solve this issue?
> > 
> > 
> > `pip uninstall Brotli -y`
> 
> This worked, thanks for the help!
> 
> I have a question - what is the purpose of `brotli` and `brotlipy` package in OpenBB?

So Brotli is a compression algorithm (I believe its googles).  IN our early days, we had issues with using pytest when the brotli compression was used.  So it was not in the dependency tree.  It was recently brought in with the video transcription, so in order to avoid issues with tests, we have a check to uninstall it

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
