### PR TITLE
Powerful stock search

### PR DESCRIPTION
**Pull request by DidierRLopes**
Follow this thread for context https://twitter.com/didier_lopes/status/1510356061055856643

### CODE REVIEW

**Comment by colin99d** [comment]
Imagine customer service so good you message someone on twitter and the feature is live 3 hours later.

**Comment by DidierRLopes** [comment]
@colin99d you made it here:
https://twitter.com/hashtag/lifeatopenbb?src=hashtag_click

**Comment by DidierRLopes** [comment]
@Chavithra I need you!!

What does this mean?

```
            if called_args or called_kwargs:
>               mock.assert_called_once_with(*called_args, **called_kwargs)
E               AssertionError: Expected 'mock' to be called once. Called 0 times.
```

**Comment by Chavithra** [comment]
Modifications :
- Renamed `amount` => `limit`, inside :
  - `tests\openbb_terminal\stocks\test_stocks_helper.py`
- Remove parameter like `"--country=''"`, apparently the single quote are not understood by `ArgumentParser.parse_known_args`

**Comment by DidierRLopes** [comment]
Thank you @Chavithra ❤️

**Review by jmaslek — APPROVED** [review]

**Comment by joshuabuildsthings** [comment]
@DidierRLopes & @Chavithra - Thanks for this; it's going to be an amazing upgrade!

**Pull request merged**
