### PR TITLE
Add X11 support for docker to display charts

### PR DESCRIPTION
**Pull request by carsanbu**
# Add X11 support for docker to display charts

After running the docker image in my Debian Linux distribution I realized it was not possible to display charts so I added support mounting a volume in the X11 socket and fixing the DISPLAY variable in environment.

I tested this with Debian Linux but I can't test with Windows or macOS and I don't know if displaying charts is already supported in these OS, I don't want to break anything so, can anyone test this?

How I tested:

```bash
docker compose run openbb
stocks/candle -t LIN
```
The chart is now displayed:
image

### CODE REVIEW

**Comment by piiq** [comment]
Hey @carsanbu, thanks for investing time into better support for linux 👏💪❤️ 

Sorry, this is most likely not work on windows because a lack of `/tmp`. 

Regarding fixing the DISPLAY variable. If it's not set on the host system what would be the behaviour? Do you think we can improve the docs and explain how to override the default settings and mount additional files into the container rather than change the compose file?

**Comment by carsanbu** [comment]
Hi @piiq,
I understand, I think it's possible to create an [extension](https://docs.docker.com/compose/extends/) of the actual compose file and only use it in case you want to use X11. I think it would be the best solution.
I'm going to try this and maybe I can update with a new solution.

**Comment by piiq** [comment]
That would be great! Post here if you need any help

**Comment by jiiiijiij** [comment]
I think there should be a seperate docker-compose.yaml for linux. Thank your for the help. Now my million dollar dream can come true, lol

**Comment by carsanbu** [comment]
Updated with the backwards compatible solution, Now in an extension file. It is possible to run in any X11 system using this command:
`docker compose -f build/docker/docker-compose.yaml -f build/docker/docker-compose.x11.yaml run openbb`

I would like to document this option somewhere but I don´t see the correct place.

**Comment by hjoaquim** [comment]
> I would like to document this option somewhere but I don´t see the correct place.

@carsanbu `website/content/terminal/installation/docker.md` under `<TabItem value="Linux" label="Linux">` might be the place!

**Comment by hjoaquim** [comment]
This fixes the issues I was experiencing with charts and tables on Ubuntu.
Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3647

**Comment by piiq** [comment]
great job @carsanbu 
thanks a lot!
waiting for the docs and let's merge it 🚀

**Review by piiq — APPROVED** [review]

**Pull request merged**
