### PR TITLE
Uppercase excel reference

### PR DESCRIPTION
**Pull request by montezdesousa**
# Pull Request OpenBB

## The OpenBBTerminal

<details>
<summary> Pull Request for the OpenBBTerminal</summary>

### Description

- [ ] Summary of the change/ bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

### How has this been tested?

- Please describe the tests that you ran to verify your changes.
- Please provide instructions so we can reproduce.
- Please also list any relevant details for your test configuration.

- [ ] Ensure the affected commands still execute in the OpenBB Terminal.
- [ ] Ensure the Platform (previously named SDK) is working as intended.
- [ ] Check any related reports.

### Checklist

- [ ] I ensure I have self-reviewed my code.
- [ ] I have commented/documented my code, particularly in hard-to-understand sections.
- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

</details>

## The OpenBB Platform

<details>
<summary> Pull Request for the OpenBB Platform</summary>

### Description

- [ ] Summary of the change/ bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

### How has this been tested?

- Please describe the tests that you ran to verify your changes.
- Please provide instructions so we can reproduce.
- Please also list any relevant details for your test configuration.

- [ ] Ensure all unit and integration tests pass.
- If you modified/added command(s):
  - [ ] Ensure the command(s) execute with the expected output.
    - [ ] API.
    - [ ] Python Interface.
  - [ ] If applicable, please add new tests for the command (see [CONTRIBUTING.md](/openbb_platform/CONTRIBUTING.md) to leverage semi-automated testing).
- If a new provider was introduced or a new fetcher was added to an existing provider:
  - [ ] Ensure the existing tests pass.
  - [ ] Ensure the new provider and/or fetcher is stable and usable.
  - [ ] If applicable, please add new tests for the provider and/or fetcher (see [CONTRIBUTING.md](/openbb_platform/CONTRIBUTING.md) to leverage semi-automated testing).
- If a new provider or extension was added:
  - [ ] Update the list of [Extensions](/openbb_platform/EXTENSIONS.md).
  - [ ] Update the list of [Providers](/openbb_platform/PROVIDERS.md).
  - [ ] If it's a community extension or provider, update the [integration tests GitHub Action workflow](/.github/workflows/platform-api-integration-test.yml).

### Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] I ensure that I am following the [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
  - [ ] (If applicable) I have updated tests following [these guidelines](/openbb_platform/CONTRIBUTING.md#qa-your-extension).

</details>

### CODE REVIEW

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
No need to commit the reference as it gets auto-generated anyway.

If anything we probably should remove that folder and add it to .gitignore

**Comment by DidierRLopes** [comment]
@montezdesousa when I'm on a reference page on the Pro, e.g.:
Screenshot 2024-01-16 at 3 13 34 PM

the page title is:
Screenshot 2024-01-16 at 3 13 54 PM

---

this is achieved through this code at the header
```
import HeadTitle from '@site/src/components/General/HeadTitle.tsx';

<HeadTitle title="Analyst Estimates - Analyst Estimates - Equity | OpenBB Terminal Pro Docs" />
```

can you add this to the generate markdown so that the head title represents the excel function, e.g.

```
OBB.ECONOMY.CPI | Openbb Add-in for Excel
```

**Comment by piiq** [comment]
> If anything we probably should remove that folder and add it to .gitignore

I think this is a very good idea

**Comment by montezdesousa** [comment]
@DidierRLopes @piiq I found it useful to help reviewer by displaying changes on PRs and tracking changes when building locally. Otherwise you need to pull and rebuild everything locally to review a PR.

**Comment by DidierRLopes** [comment]
@montezdesousa I have removed the reference folder and added it to gitignore. I will go ahead and approve this PR - feel free to merge it!

The reasoning for removing the reference folder:
- The sense you are getting of helpfulness is actually a "fake feeling" because:
1. All those files are automatically generated so it's actually misleading to look into them in a PR since you can't just edit one markdown file - but will end up having to edit the python generator instead. And it's much easy to just review that code.
2. There's no reason why the changes built locally by the person committing the PR are linked with the latest `generate markdown file` . E.g. I can generate markdown file and then edit that same file, and you will think that the markdown you are seeing is what the user will see, but it is not.

- The PR is extremely big for no reason
- We will need to keep building locally and pushing that to reflect what users are seeing, so it's better to have nothing so there isn't any confusion
- It's in general a good practice to checkout a branch and actually run the code instead of just scrolling through the code

PS: I will do the same for the other references (including adding to the .gitignore) but will do so in another PR, so we can ship this tomorrow.

**Review by DidierRLopes — APPROVED** [review]

**Comment by montezdesousa** [comment]
> @montezdesousa I have removed the reference folder and added it to gitignore. I will go ahead and approve this PR - feel free to merge it!
> 
> The reasoning for removing the reference folder:
> 
> * The sense you are getting of helpfulness is actually a "fake feeling" because:
> 
> 1. All those files are automatically generated so it's actually misleading to look into them in a PR since you can't just edit one markdown file - but will end up having to edit the python generator instead. And it's much easy to just review that code.
> 2. There's no reason why the changes built locally by the person committing the PR are linked with the latest `generate markdown file` . E.g. I can generate markdown file and then edit that same file, and you will think that the markdown you are seeing is what the user will see, but it is not.
> 
> * The PR is extremely big for no reason
> * We will need to keep building locally and pushing that to reflect what users are seeing, so it's better to have nothing so there isn't any confusion
> * It's in general a good practice to checkout a branch and actually run the code instead of just scrolling through the code
> 
> PS: I will do the same for the other references (including adding to the .gitignore) but will do so in another PR, so we can ship this tomorrow.

Alright, let's move on and merge!

For discussion sake I see a few downsides in auto generating the reference in the GitHub action, namely that we can deploy blindly i.e. without seeing the impact of the changes made on the generator. If the PR is big it's because there are real changes in the content that need to be highlighted since they might be unintended. 

What do we gain by auto generating? Reference always in sync with generator. I'd prefer to have the files out of sync with the generator but working than having it always in sync but with unseen changes that might be a bug.

Risk-benefit wise I don't think it's worth it.

**Comment by DidierRLopes** [comment]
> > @montezdesousa I have removed the reference folder and added it to gitignore. I will go ahead and approve this PR - feel free to merge it!
> > The reasoning for removing the reference folder:
> > 
> > * The sense you are getting of helpfulness is actually a "fake feeling" because:
> > 
> > 
> > 1. All those files are automatically generated so it's actually misleading to look into them in a PR since you can't just edit one markdown file - but will end up having to edit the python generator instead. And it's much easy to just review that code.
> > 2. There's no reason why the changes built locally by the person committing the PR are linked with the latest `generate markdown file` . E.g. I can generate markdown file and then edit that same file, and you will think that the markdown you are seeing is what the user will see, but it is not.
> > 
> > 
> > * The PR is extremely big for no reason
> > * We will need to keep building locally and pushing that to reflect what users are seeing, so it's better to have nothing so there isn't any confusion
> > * It's in general a good practice to checkout a branch and actually run the code instead of just scrolling through the code
> > 
> > PS: I will do the same for the other references (including adding to the .gitignore) but will do so in another PR, so we can ship this tomorrow.
> 
> Alright, let's move on and merge!
> 
> For discussion sake I see a few downsides in auto generating the reference in the GitHub action, namely that we can deploy blindly i.e. without seeing the impact of the changes made on the generator. If the PR is big it's because there are real changes in the content that need to be highlighted since they might be unintended.
> 
> What do we gain by auto generating? Reference always in sync with generator. I'd prefer to have the files out of sync with the generator but working than having it always in sync but with unseen changes that might be a bug. Plus the fact we generate more stuff on the fly (sdkv3, platform, etc.) implies that a single PR to update Excel might actually introduce unforeseen changes in other pages.
> 
> Risk-benefit wise I don't think it's worth it.

That's not true @montezdesousa 

The deploying blindly never happens because if someone reviews code they will review the code from the generator, which is what matters. Whenever I review docs PRs, I **ALWAYS** checkout the branch and run it locally to see what it looks like bc of this exact reason.

Also, if someone makes changes in a generator outside Excel, you will be able to catch that when reviewing the PR.

Also 2, I can create a PR that changes the generator and I don't build locally and then you have the false sense that I didn't touch anything on the docs, and I did. 

A good analogy for me is doing that is the equivalent of someone having to do a PR with code changes + a binary of the terminal running, every time - but for our documentation. But there's no reason why that binary needs to be the one that gets compiled from the code you are pushing, so it doesn't really make sense doing so. And what you end up doing is checkout the code and run it locally to test the feature - which is similar to what should happen with the auto-generate.

The markdown files are an artifact and not the full story.

**Comment by montezdesousa** [comment]
> > > @montezdesousa I have removed the reference folder and added it to gitignore. I will go ahead and approve this PR - feel free to merge it!
> > > The reasoning for removing the reference folder:
> > > 
> > > * The sense you are getting of helpfulness is actually a "fake feeling" because:
> > > 
> > > 
> > > 1. All those files are automatically generated so it's actually misleading to look into them in a PR since you can't just edit one markdown file - but will end up having to edit the python generator instead. And it's much easy to just review that code.
> > > 2. There's no reason why the changes built locally by the person committing the PR are linked with the latest `generate markdown file` . E.g. I can generate markdown file and then edit that same file, and you will think that the markdown you are seeing is what the user will see, but it is not.
> > > 
> > > 
> > > * The PR is extremely big for no reason
> > > * We will need to keep building locally and pushing that to reflect what users are seeing, so it's better to have nothing so there isn't any confusion
> > > * It's in general a good practice to checkout a branch and actually run the code instead of just scrolling through the code
> > > 
> > > PS: I will do the same for the other references (including adding to the .gitignore) but will do so in another PR, so we can ship this tomorrow.
> > 
> > 
> > Alright, let's move on and merge!
> > For discussion sake I see a few downsides in auto generating the reference in the GitHub action, namely that we can deploy blindly i.e. without seeing the impact of the changes made on the generator. If the PR is big it's because there are real changes in the content that need to be highlighted since they might be unintended.
> > What do we gain by auto generating? Reference always in sync with generator. I'd prefer to have the files out of sync with the generator but working than having it always in sync but with unseen changes that might be a bug. Plus the fact we generate more stuff on the fly (sdkv3, platform, etc.) implies that a single PR to update Excel might actually introduce unforeseen changes in other pages.
> > Risk-benefit wise I don't think it's worth it.
> 
> That's not true @montezdesousa
> 
> The deploying blindly never happens because if someone reviews code they will review the code from the generator, which is what matters. Whenever I review docs PRs, I **ALWAYS** checkout the branch and run it locally to see what it looks like bc of this exact reason.
> 
> Also, if someone makes changes in a generator outside Excel, you will be able to catch that when reviewing the PR.
> 
> Also 2, I can create a PR that changes the generator and I don't build locally and then you have the false sense that I didn't touch anything on the docs, and I did.
> 
> A good analogy for me is doing that is the equivalent of someone having to do a PR with code changes + a binary of the terminal running, every time - but for our documentation. But there's no reason why that binary needs to be the one that gets compiled from the code you are pushing, so it doesn't really make sense doing so. And what you end up doing is checkout the code and run it locally to test the feature - which is similar to what should happen with the auto-generate.
> 
> The markdown files are an artifact and not the full story.

I'm not saying blind deploy will happen, but since there's nothing preventing it I'm concerned with that case. If you are assuming PR is always properly reviewed current setup is good.

**Comment by DidierRLopes** [comment]
> > > > @montezdesousa I have removed the reference folder and added it to gitignore. I will go ahead and approve this PR - feel free to merge it!
> > > > The reasoning for removing the reference folder:
> > > > 
> > > > * The sense you are getting of helpfulness is actually a "fake feeling" because:
> > > > 
> > > > 
> > > > 1. All those files are automatically generated so it's actually misleading to look into them in a PR since you can't just edit one markdown file - but will end up having to edit the python generator instead. And it's much easy to just review that code.
> > > > 2. There's no reason why the changes built locally by the person committing the PR are linked with the latest `generate markdown file` . E.g. I can generate markdown file and then edit that same file, and you will think that the markdown you are seeing is what the user will see, but it is not.
> > > > 
> > > > 
> > > > * The PR is extremely big for no reason
> > > > * We will need to keep building locally and pushing that to reflect what users are seeing, so it's better to have nothing so there isn't any confusion
> > > > * It's in general a good practice to checkout a branch and actually run the code instead of just scrolling through the code
> > > > 
> > > > PS: I will do the same for the other references (including adding to the .gitignore) but will do so in another PR, so we can ship this tomorrow.
> > > 
> > > 
> > > Alright, let's move on and merge!
> > > For discussion sake I see a few downsides in auto generating the reference in the GitHub action, namely that we can deploy blindly i.e. without seeing the impact of the changes made on the generator. If the PR is big it's because there are real changes in the content that need to be highlighted since they might be unintended.
> > > What do we gain by auto generating? Reference always in sync with generator. I'd prefer to have the files out of sync with the generator but working than having it always in sync but with unseen changes that might be a bug. Plus the fact we generate more stuff on the fly (sdkv3, platform, etc.) implies that a single PR to update Excel might actually introduce unforeseen changes in other pages.
> > > Risk-benefit wise I don't think it's worth it.
> > 
> > 
> > That's not true @montezdesousa
> > The deploying blindly never happens because if someone reviews code they will review the code from the generator, which is what matters. Whenever I review docs PRs, I **ALWAYS** checkout the branch and run it locally to see what it looks like bc of this exact reason.
> > Also, if someone makes changes in a generator outside Excel, you will be able to catch that when reviewing the PR.
> > Also 2, I can create a PR that changes the generator and I don't build locally and then you have the false sense that I didn't touch anything on the docs, and I did.
> > A good analogy for me is doing that is the equivalent of someone having to do a PR with code changes + a binary of the terminal running, every time - but for our documentation. But there's no reason why that binary needs to be the one that gets compiled from the code you are pushing, so it doesn't really make sense doing so. And what you end up doing is checkout the code and run it locally to test the feature - which is similar to what should happen with the auto-generate.
> > The markdown files are an artifact and not the full story.
> 
> I'm not saying blind deploy will happen, but since there's nothing preventing it I'm concerned with that case. If you are assuming PR is always properly reviewed current setup is good.

It should! If not we need to improve there, at the root 😄

**Comment by piiq** [comment]
just to address some of @montezdesousa's concerns with some observations.
statistically (in the past) we've experienced ppl editing the reference files and ending up surprized their updated are not reflected on the docs website more times than we had blind pushes that broke the docs (don't remember those actually). this observation leads me to assume that the presence of the reference files in the repo did produce a false sense of them being the source of truth. moving forward properly communicating that the reference docs are auto generated and the generators should be checked IMO is a better way.

**Pull request merged**
