### PR TITLE
Added fix

### PR DESCRIPTION
**Pull request by the-praxs**
# Description

- [x] Fixed the extra string quotes in default options for the `reports` menu commands 
- [x] #4715 
- [x] #4717 
- [x] Make the `reports` menu work normally
- [x] No dependency change required

# How has this been tested?
The `symbol` variable under `# Parameters` cell can be checked in the generated notebook.

- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by the-praxs** [comment]
Can anybody review this?

**Comment by hjoaquim** [comment]
The above comment, also applies to #4710

**Review by hjoaquim — CHANGES_REQUESTED** [review]
Hello @the-praxs , once again, thanks for this contribution!

Maybe here we can go for something a little simpler to avoid getting into several if-else statements (if our parameter base eventually grows!).

What about adding `parameters_dict[key] = value.replace('"', "")` on the line 185?

I guess this would achieve the same and account for future addition of parameters.

Wdyt?

**Comment by the-praxs** [comment]
@hjoaquim a very fine suggestion indeed. I modified the code and it works well. 

Can you tell me the purpose of the lines 187-188?
```python
if "report_name" in parameters_dict:
        parameters_dict.pop("report_name")
```

**Comment by hjoaquim** [comment]
> @hjoaquim a very fine suggestion indeed. I modified the code and it works well.
> 
> Can you tell me the purpose of the lines 187-188?
> 
> ```python
> if "report_name" in parameters_dict:
>     parameters_dict.pop("report_name")
> ```

In my view, that function is used to extract report parameters to display on the menu, and we don't actually want the report name to be a parameter that the user can access!

**Review by hjoaquim — APPROVED** [review]
Thank you for iterating with me on this one @the-praxs and welcome to the contributors team! 
Looking forward to having you on the community :rocket:

**Pull request merged**
