### PR TITLE
FEAT: EPS and Revenue Estimations from Seeking Alpha

### PR DESCRIPTION
**Pull request by kajdo**
# Description

- [x] Summary of the change / bug fix.
Feature 'Earnings Estimates EPS and Revenue':
Enables to request estimated EPS and Revenue by Analysts (incl. number of analysts)

- [x] Link # issue, if applicable.
N/A

- [x] Screenshot of the feature or the bug before/after fix, if applicable.
image

- [x] Relevant motivation and context.
The main motivation is to provide analyst estimations for a quick check and a possibility to use the data for fair-value calculations.

- [x] List any dependencies that are required for this change.
no new dependencies

# How has this been tested?
mostly manually
* Please describe the tests that you ran to verify your changes.
tested manually
- stocks/fa/revfc (with loaded stock) and
- stocks/fa/epsfc (with loaded stock)
compared data with https://seekingalpha.com/symbol/{{TICKER}}/earnings/estimates

* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [?] Ensure the SDK still works
SDK changed a couple of days ago -- pls update the documentation, so I can ensure the new features are working in the SDK as well
- [x] Check any related reports
N/A

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
description of new features + example provided
- [?] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
tests are not working for the moment - would appreciate any support
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
done - but SDK changed a couple of days ago and the documentation is outdated
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deeleeramone** [comment]
@colin99d, this user needs a little help with `pytest`. I pinged you in the Discord conversation.

**Comment by kajdo** [comment]
Thx to the help in discord, I added the unit tests for model, view and controller

**Comment by jmaslek** [comment]
Hey this is an awesome addition!

I was able to break it when the ticker is not found.  I loaded in IONQ and ran the following:
```
2022 Nov 15, 08:23 (🦋) /stocks/fa/ $ epsfc

Error: '606807'

Error: 'list' object has no attribute 'empty'
```
There should be some checking if the response is good.

**Comment by kajdo** [comment]
will check and make it more robust ... also found that i didn't include the part of the checklist in the contribution guide and that the General Linting is failing because of that .... sry - but will update with a fix if ticker isn't found + the fix for the linter check during the next days

**Comment by kajdo** [comment]
@jmaslek seeking alpha doesn't provide data - so I will at least do a check and handle the error better, to prevent a unhandled errormsg

image

**Comment by piiq** [comment]
@kajdo for missing data handling - have a look at how this is implemented in other parts of the terminal.
The convention we follow in case no data is available is for the model to return an empty DF and on the view side if the df.empty condition is met - the terminal prints a message saying that there was no data found.

Here's a screenshot of an example from the docs
image


Text if you need some help, it would be great to merge this PR

**Comment by kajdo** [comment]
@piiq - thx for the tip - very helpful!!! I incorporated a more robust way incl. the handled "no data found" msg

@jmaslek - unfortunately still no data for ionq on sa - but at least no hickup in OpenBBTerminal anymore ;)

**Comment by DidierRLopes** [comment]
Hey @kajdo ,

Sorry for the delay on our side. We are currently doing a feature freeze for a very big release that will occur next week! Once that is out of the way, we will test this PR and give feedback.

Thanks for contributing! 🙏🏽

**Comment by kajdo** [comment]
thx for the update. if i have to adapt sth, just let me know

**Comment by jmaslek** [comment]
Hey!

Sorry this has taken me this long.  I will try to do better moving forward.

I resolved the conflicts locally, but I was unable to push to your branch to get up to date, so the first thing will just be to resolve the merge conflicts (we changed the way we do the default choices, so accepting the incoming should work).

Thanks for making the fix to handle not found data!

I have one styling request and then I am happy to merge this.  The long decimals are tricky to read, namely:
```
                                  AAPL Revenue History and Estimations                                  
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃ fiscalyear ┃ consensus_mean ┃ change % ┃ analysts ┃ actual         ┃ consensus_low  ┃ consensus_high ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩
│ 2022       │ 392778994500.0 │ 7.37     │ 41.0     │ 394328000000.0 │ 389326000000.0 │ 396977000000.0 │
├────────────┼────────────────┼──────────┼──────────┼────────────────┼────────────────┼────────────────┤
│ 2023       │ 407185671270.0 │ 3.26     │ 35.0     │ 0              │ 383263714310.0 │ 429122000000.0 │
├────────────┼────────────────┼──────────┼──────────┼────────────────┼────────────────┼────────────────┤
```

So if we could put that into the k/M/B notation, I think that would look great :)
 
We have a helper function: lambda_long_number_format that will do this, so you can just apply to the table!

Sorry again for the delay!

**Comment by kajdo** [comment]
sorry - had to finalize end-of-year work ... now I have more time to finalize the PR

@jmaslek - could you retry to push your changes to resolve the conflicts to the fork - it should be open now

I will implement the k/M/B notation ... if i don't find out how to do - i will ping the friendly folks on discord :)

**Comment by jmaslek** [comment]
Still not letting me:
```
 ! [remote rejected]       HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/kajdo/openbbterminal'
```

**Comment by jmaslek** [comment]
@kajdo I opened a PR into your main branch.  Feel free to merge that which will update here.

**Comment by kajdo** [comment]
@jmaslek d*mn ... must have misconfigured something - github told me back then it's clever to do so and i did ... now I can't remember :D :D :D 

did the numebr format change and will have a look if i can manage to do the merge

**Comment by kajdo** [comment]
@jmaslek alright ... merged, changed my repo setting so that shouldn't happen again and did the change to have nice number formats on eps and revenue forecast

not sure if i have to do something else - the SDK endpoints are missing, but there was a change somewhen and the documentation didn't reflect it so I don't know how to do it .... if you have any feedback - happy to incorporate it

**Comment by jmaslek** [comment]
Thanks @kajdo. The only immediate thing I see is that the files inside website can be deleted -- we now autogenerate the docs on merge.  I will take another look tonight/tomorrow.

The functions in sdk can be added following the trail_map convention (in miscellaneous/library ) -- happy to help out with this further if needed!

**Comment by kajdo** [comment]
thx! will have another look tomorrow ... think i will manage the sdk thingy ... but not sure if i understand how i can test it while implementing a new sdk-endpoint .... will drop a question in discord about that somewhen in the next days - think the feature itself works fine as long as seekingalpha isn't changing to much

**Comment by jmaslek** [comment]
Perfect!

Screenshot 2022-12-09 at 1 41 39 PM


If you want me to handle the sdk additions, let me know, I can approve and merge this and then add them in my current PR.  

IF you want to add them, I will hold off on approving.

**Comment by kajdo** [comment]
if you could add them - that would be great ... will check the diff to figure out how to do it later (might have some other interesting figures for fundamental data)

**Review by jmaslek — APPROVED** [review]

**Comment by kajdo** [comment]
fixed linting and unit test error ... i think i saw another error in the unit test runs in the prev. Anaconda Python Test run, but it wasn't related to my change

**Pull request merged**
