### PR TITLE
Improve speed of get repo stars by implementing async requests

### PR DESCRIPTION
**Pull request by alexferrari88**
# Description

In issue #1694, it is suggested to implement the async/await pattern to implement non blocking requests when fetching data from GitHub. With this PR, I suggest my solution.

# How has this been tested?

`$> alternative/oss`
`$ alternative/oss> sh -r OpenBB-finance/OpenBBTerminal`

# Checklist:

- [X] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [X] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [X] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [X] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [X] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by alexferrari88** [comment]
Unfortunately I couldn't run the automated tests because, whenever I run `pytest tests/` I get this error: 
`Exit: Uninstall brotli and brotlipy before running tests`

Also, testing asyncio functions requires the package pytest-asyncio. I am familiar with `pip freeze > requirements.txt` but since this project is using conda and poetry, how can I go about it?

**Comment by jose-donato** [comment]
nice work!

To solve that issue you need to run this command:
`pip unistall brotlipy`

**Comment by alexferrari88** [comment]
> nice work!
> 
> To solve that issue you need to run this command: `pip unistall brotlipy`

Thank you, that worked! Any idea on how I can include pytest-asyncio in the requirements?

**Comment by alexferrari88** [comment]
@jose-donato I have added pytest-asyncio manually to requests.txt therefore now the tests are running. Only problem is that I think VCR is making them fail. On my laptop (where I have re-created the cassette for alternative/oss) all tests are passing fine...

**Comment by Chavithra** [comment]
Hello friends,

**SPEED IMPROVEMENT**

Right now I don't see any parallelization of IO (HTTP requests) in this code.

So my guess is that won't change performances compare to previous version.

Is there something I am missing ?

**SPEED TEST**
A speed test could help lift doubt.

**Comment by alexferrari88** [comment]
> Hello friends,
> 
> **TESTS** @alexferrari88 if you are talking about why this is currently failing on Ubuntu CI : I think it's just because of dependencies.
> 
> You can do like this to add a dependency :
> 
> ```shell
> poetry add pytest-asyncio
> poetry export -f requirements.txt  -o requirements.txt --without-hashes --dev
> poetry export -f requirements.txt  -o requirements-full.txt --extras prediction --without-hashes --dev
> poetry export -f requirements.txt  -o bots/requirements.txt --extras bots --without-hashes --dev
> ```
> 
> More information here : https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests#311-how-to-handle-dev-dependencies-

thank you for such a helpful comment @Chavithra! All the tests are passing now!

**Comment by DidierRLopes** [comment]
@jose-donato you happy with this? 😄

**Comment by DidierRLopes** [comment]
The chart is currently not popping for me.

If I had the `plt.pause(0.1)` before it shows but then I can't close the window because it freezes execution. 

See https://stackoverflow.com/questions/44163601/asyncio-matplotlib-show-still-freezes-program.

Not sure what to do in this situation. @piiq ?

**Comment by alexferrari88** [comment]
> The chart is currently not popping for me.
> 
> If I had the `plt.pause(0.1)` before it shows but then I can't close the window because it freezes execution.
> 
> See https://stackoverflow.com/questions/44163601/asyncio-matplotlib-show-still-freezes-program.
> 
> Not sure what to do in this situation. @piiq ?

I didn't experience the problem while debugging (I guess because it is normally "paused" as you go instruction by instruction. 

With `plt.pause(0.1)` it freezes for me as well, but not for `plt.pause(0.5)`. I have updated the PR, can you please check if it is working for you?

**Comment by DidierRLopes** [comment]
> > The chart is currently not popping for me.
> > If I had the `plt.pause(0.1)` before it shows but then I can't close the window because it freezes execution.
> > See https://stackoverflow.com/questions/44163601/asyncio-matplotlib-show-still-freezes-program.
> > Not sure what to do in this situation. @piiq ?
> 
> I didn't experience the problem while debugging (I guess because it is normally "paused" as you go instruction by instruction.
> 
> With `plt.pause(0.1)` it freezes for me as well, but not for `plt.pause(0.5)`. I have updated the PR, can you please check if it is working for you?

It completely breaks terminal for me, with both `USE_ION` True or False 😞

**Comment by alexferrari88** [comment]
> > > The chart is currently not popping for me.
> > > If I had the `plt.pause(0.1)` before it shows but then I can't close the window because it freezes execution.
> > > See https://stackoverflow.com/questions/44163601/asyncio-matplotlib-show-still-freezes-program.
> > > Not sure what to do in this situation. @piiq ?
> > 
> > 
> > I didn't experience the problem while debugging (I guess because it is normally "paused" as you go instruction by instruction.
> > With `plt.pause(0.1)` it freezes for me as well, but not for `plt.pause(0.5)`. I have updated the PR, can you please check if it is working for you?
> 
> It completely breaks terminal for me, with both `USE_ION` True or False 😞

oh, so strange! Will keep investigating...

**Comment by piiq** [comment]
I'm not sure async python would work with the event loop we have. The terminal is single threaded. IIUC it's either do all terminal in async python or none of it. We had the same problems with the first bot experiments. 
Is there any other way to make speedup this command @alexferrari88 ?

**Comment by alexferrari88** [comment]
> I'm not sure async python would work with the event loop we have. The terminal is single threaded. IIUC it's either do all terminal in async python or none of it. We had the same problems with the first bot experiments. Is there any other way to make speedup this command @alexferrari88 ?

Well, technically, any python program (unless you use some tricks I'm not even remotely expert it) is single threaded, due to the GIL. What async does is making possible to run routines concurrently meaning that the execution can be switched between different coroutines whenever there is some waiting needed (e.g. when sending a request).

My current understanding of matplotlib is that it blocks the thread during the show method and this wrecks the async implementation. Strangely I cannot find much by googling. What I'm thinking right now is finding a way to start the plot drawing only once the asyncloop exits. I need to find out how though...

**Comment by alexferrari88** [comment]
> > > The chart is currently not popping for me.
> > > If I had the `plt.pause(0.1)` before it shows but then I can't close the window because it freezes execution.
> > > See https://stackoverflow.com/questions/44163601/asyncio-matplotlib-show-still-freezes-program.
> > > Not sure what to do in this situation. @piiq ?
> > 
> > 
> > I didn't experience the problem while debugging (I guess because it is normally "paused" as you go instruction by instruction.
> > With `plt.pause(0.1)` it freezes for me as well, but not for `plt.pause(0.5)`. I have updated the PR, can you please check if it is working for you?
> 
> It completely breaks terminal for me, with both `USE_ION` True or False 😞

To understand better what is going on, what OS are you using?
I'm running this on Windows 11 within WSL2 and for me it runs without problems. I want to understand why for some people it completely breaks the terminal...

**Comment by DidierRLopes** [comment]
> > It completely breaks terminal for me, with both `USE_ION` True or False 😞
> 
> To understand better what is going on, what OS are you using, @DidierRLopes ? I'm running this on Windows 11 within WSL2 and for me it runs without problems. I want to understand why for some people it completely breaks the terminal...

Am using a Mac!

**Comment by DidierRLopes** [comment]
Am going to close this PR since we haven't found a solution that doesn't block terminal execution. 😞

**Pull request closed without merging**
