### PR TITLE
Add columns to `stocks/search`

### LINKED ISSUE #5505: [IMPROVE] Return `/stocks/search` with the unique identifier codes in Terminal.
These columns do exist, so should be a relatively quick win.

```python
import financedatabase as fd
fd.Equities().data.columns
```

```
Index(['name', 'summary', 'currency', 'sector', 'industry_group', 'industry',
       'exchange', 'market', 'country', 'state', 'city', 'zipcode', 'website',
       'market_cap', 'isin', 'cusip', 'figi', 'composite_figi',
       'shareclass_figi'],
      dtype='object')
```

### PR DESCRIPTION
**Pull request by AdwaitSalankar**
Fixes #5505

---

Added the following new columns to `stocks/search`
```
isin, cusip, figi, composite_figi, shareclass_figi
```

Screenshot of the feature
Before:

Imgur

After:

Imgur

# Description

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by AdwaitSalankar** [comment]
@deeleeramone Can you please review this?

**Review by deeleeramone — CHANGES_REQUESTED** [review]
Thanks for jumping in! This is exactly what we need.  Because we have modified the expected output, we need to recapture the test cassettes.  You can do this from the command line, from the root folder of the project:

```
pytest tests/openbb_terminal/stocks/test_stocks_helper.py --record-mode once --rewrite-expected
```

You may need to uninstall Brotli before running pytest:

```
pip uninstall brotli -y
```

This should result in 3 files being modified:

- `test_search.yaml`
- `test_search[False].txt`
- `test_search[True].txt`

**Comment by AdwaitSalankar** [comment]
Hi @deeleeramone!
I ran this command:
```
pytest tests/openbb_terminal/stocks/test_stocks_helper.py --record-mode once --rewrite-expected
```
but I got this error:
```
FAILED tests/openbb_terminal/stocks/test_stocks_helper.py::test_search[True] - KeyError: "['isin', 'cusip', 'figi', 'composite_figi', 'shareclass_figi'] not in index"  
FAILED tests/openbb_terminal/stocks/test_stocks_helper.py::test_search[False] - KeyError: "['isin', 'cusip', 'figi', 'composite_figi', 'shareclass_figi'] not in index" 
```
I printed `data.columns` just before line 201 in `stocks_helper.py` and I saw:
```
Index(['name', 'summary', 'currency', 'sector', 'industry_group', 'industry',
       'exchange', 'market', 'country', 'state', 'city', 'zipcode', 'website',
       'market_cap'],
      dtype='object')
```

I don't get why fewer columns appear here while all the columns were present when the application was running.
Can you please help me with this?

**Comment by deeleeramone** [comment]
> I don't get why fewer columns appear here while all the columns were present when the application was running. Can you please help me with this?

I got you, mate!  It appears that there is a decorator calling a default test cassette which doesn't get overwritten like other functions do.  The solutions are not obvious, so I'll do the quick and dirty.  For future reference, they are:

- Delete the .yaml file in the cassettes folder: `tests/openbb_terminal/stocks/cassettes/test_stocks_helper/test_search.yaml`, and then run the command again.
- Edit the `test_stocks_helper.py` file by removing the decorator referencing the cassette in question, then run the command again.

Thanks for the PR!

**Review by deeleeramone — APPROVED** [review]

**Pull request merged**
