### PR TITLE
Sync with hub on reset + routines fixes

### PR DESCRIPTION
**Pull request by montezdesousa**
* Syncs terminal with hub when `reset`
* Silences routines download
* Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4841
* Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4846
* Avoids downloading routines and updating backend sources when loading sdk
* Fixes `Warning: Input is not a terminal (fd=0).` running reports on installer and integration tests
* Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4800 by rolling over and removing log files before setting up new ones

Installers:
* Windows: https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/4766026824
* Mac: https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/4766041924

@hjoaquim can you confirm this doesn't break anything on the logs? Its basically reverting to where we were before https://github.com/OpenBB-finance/OpenBBTerminal/pull/4813, but keeping the session if remember is 'n'

### CODE REVIEW

**Comment by hjoaquim** [comment]
@montezdesousa reset causes the same issue as described here: https://github.com/OpenBB-finance/OpenBBTerminal/issues/4800

**Comment by hjoaquim** [comment]
@montezdesousa is this a build based on this branch: https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/4760367861 ?

**Comment by montezdesousa** [comment]
> @montezdesousa is this a build based on this branch: https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/4760367861 ?

Yes

**Review by jmaslek — APPROVED** [review]

**Review by hjoaquim — APPROVED** [review]
All mentioned issues are fixed when testing on the Windows intaller.

**Pull request merged**
