### PR TITLE
Added fix

### LINKED ISSUE #4707: [Bug] `crypto/find --help` - find: error: the following arguments are required: -c/--coin
The help dialogue is printed when `-h` is employed, but not when `--help` is used.

Related to #4620 because it is the same issue.

Screenshot 2023-04-06 at 7 24 03 PM

### PR DESCRIPTION
**Pull request by the-praxs**
Fixed #4707 

- [x] "--help" argument giving error when used with `load`, `find`, `price` commands.
- [x] #4707 

# How has this been tested?
Tested by executing the terminal application in Python
and running the commands with the arguments.

- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deeleeramone** [comment]
@jmaslek, is it best to remove the line entirely, instead of simply commenting it out?  This does indeed resolve the issue.

**Comment by the-praxs** [comment]
> @jmaslek, is it best to remove the line entirely, instead of simply commenting it out? This does indeed resolve the issue.

I did want to remove the lines because they serve no purpose there, functionality or debugging-wise. There's no need to use the required parameter because `-h` and `--help` does not preclude any other arguments.

If you want I can resubmit the PR with these lines removed.

**Comment by the-praxs** [comment]
@hjoaquim made the same changes and submitted for review.

**Review by hjoaquim — APPROVED** [review]
Well done :rocket:

**Pull request merged**
