### PR TITLE
hotfix/print_rich_table_limit

### PR DESCRIPTION
**Pull request by Ltwo3five**
# Description

### Summary of the change / bug fix.

> Limit was not being applied to the interactive table. I added the logic that was already present in print console table to print interactive table

### Link # issue, if applicable.
[   #5050](https://github.com/OpenBB-finance/OpenBBTerminal/issues/5050)

> rich_table

# How has this been tested?

### * Please describe the tests that you ran to verify your changes.

> End to End Test

### * Provide instructions so we can reproduce.
/stocks/load aapl/fa/earnings --source YahooFinance --limit 5
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports
# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
Hey!  Thanks for the PR.  

With the interactive tables, we don't need the limit.  To address that specific issue, the better solution would be to remove the limit argument from the command.

**Comment by deeleeramone** [comment]
> With the interactive tables, we don't need the limit. To address that specific issue, the better solution would be to remove the limit argument from the command.

This makes me think, it's probably not a bug in this instance because it still works when the `interactive` flag is off.  This behaviour is also not consistent across functions.  Some will respect the `limit` argument when `interactive`, while others do not.  For example, `/arkord --limit 5`, works as both `interactive` and non.

**Comment by LOne2three** [comment]
> Hey! Thanks for the PR.
> 
> With the interactive tables, we don't need the limit. To address that specific issue, the better solution would be to remove the limit argument from the command.

I have added logic to call_earnings to disable the limit argument when interactive is enabled because as far as I understand the limit argument should still be present when interactive is disabled. And according  @deeleeramone the limit command is inconsistent across functions, I have checked call_arkord in disc controller and the reason this is so is because the dataframe has the limit applied before being used as an argument in print_rich_table whereas for call_earnings the dataframe has the limit applied within print_rich_function.

**Comment by deeleeramone** [comment]
FYI, PRs must be merged to the `/develop` branch.  They cannot be merged to `/main`.

**Pull request closed without merging**
