### PR TITLE
Small pr touching minimal files

### PR DESCRIPTION
**Pull request by jmaslek**

### CODE REVIEW

**Comment by deeleeramone** [comment]
There's a bunch of corrections made to the V3 stuff that is just going to 404,  should those ones be redirected to the archived repo?

**Comment by jmaslek** [comment]
> There's a bunch of corrections made to the V3 stuff that is just going to 404, should those ones be redirected to the archived repo?

good time to remove the legacy docs?

**Comment by hjoaquim** [comment]
This might need some more `Find replace all` due to the latest release.

**Comment by deeleeramone** [comment]
Was the full intention of this PR realized when the docs were moved to the new repo?

**Comment by jmaslek** [comment]
> Was the full intention of this PR realized when the docs were moved to the new repo?

No clue.  In theory, the only links should have been in the website folder. Probably best to close this and coordinate everyone to get this done.

**Pull request closed without merging**
