### PR TITLE
[FEAT] Additional metrics for evaluating forecasting (RMSE+ MSE)

### PR DESCRIPTION
**Pull request by martinb-bb**
Adding in `RMSE` and `MSE` metrics for accuracy calculations when performing backtesting on models.

[Twitter](https://twitter.com/adam_cjohnson/status/1623154046331924480?s=46&t=Mrg0MsCFae0uDE2RCvW7kA)
image

In terminal: 
image
image

SDK:
image

### CODE REVIEW

**Comment by martinb-bb** [comment]
@DidierRLopes ☝️

**Comment by jmaslek** [comment]
Any reason we can't add the others from darts.metrics?

**Comment by jmaslek** [comment]
Thats fair.  Only reason I ask is because I was going to try using the sdk for a kaggle comp that used SMAPE as the scoring metric, but I noticed it wasn't an option, so I didnt use it.  Having as many is both helpful and overkill.

**Comment by martinb-bb** [comment]
Added smape for you :) 
image

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
