### PR TITLE
DO NOT MERGE YET: Add Conda build file for Python 310

### PR DESCRIPTION
**Pull request by deeleeramone**
This PR addresses issues with Conda and Poetry playing nicely together. Notably, this resolves Poetry's failure to install:`qdldl==0.15.post3`

So far, this has been tested to work with:

- Mac M1 with OS Ventura 13.1 and ARM version of Miniconda.
- Windows 11 Pro and Miniconda.

To install with this build file:

```
conda update -n base -c conda-forge conda
conda env create -n obb-test --file build/conda/conda-3-10-env-full.yaml
conda activate obb-test
poetry install -E all
```

I deleted all caches from pypoetry, pip, and Conda prior to building the new environment. 

This also resolves the issue described here: https://github.com/OpenBB-finance/OpenBBTerminal/issues/4117#issuecomment-1414320477 - Jupyter kernel fails because of NSEvent

### CODE REVIEW

**Comment by deeleeramone** [comment]
Also tested successfully with Linux Ubuntu.

**Comment by jmaslek** [comment]
@piiq are you approving this?

**Comment by martinb-bb** [comment]
Breaks for me :(

**Comment by deeleeramone** [comment]
@martin-bb where does it break, is it `prophet`?

**Comment by martinb-bb** [comment]
For me it's lightgbm

**Comment by deeleeramone** [comment]
> For me it's lightgbm

If you version bump lightgbm to 3.3.5, does it help?

**Comment by martinb-bb** [comment]
No I tried. Same issue.

**Comment by deeleeramone** [comment]
> No I tried. Same issue.

Same deal if you use, `pip install -r requirements-full.txt`?

**Comment by piiq** [comment]
addressed in #4508

**Pull request closed without merging**
