### PR TITLE
Fixes ecocal command

### LINKED ISSUE #2248: [Bug] /economy/ecocal --category flag is broken. Argparse is not joining words.
Screen Shot 2022-08-04 at 10 51 27 AM

argparse is not joining words, and see categories as only the first word, resulting in an `invalid choice`

```
2022 Aug 04, 13:48 /economy/ $ ecocal --categories economic activity -i medium
usage: ecocal [-c COUNTRY [COUNTRY ...]] [-i {high,medium,low,all}]
              [-cat {employment,credit,balance,economic activity,central banks,bonds,inflation,confidence index} [{employment,credit,balance,economic activity,central banks,bonds,inflation,confidence index} ...]]
              [-s START_DATE] [-e END_DATE] [-h] [--export EXPORT] [--raw] [-l LIMIT]
ecocal: error: argument -cat/--categories: invalid choice: 'economic' (choose from 'employment', 'credit', 'balance', 'economic activity', 'central banks', 'bonds', 'inflation', 'confidence index')

2022 Aug 04, 13:48 /economy/ $ ecocal --categories economic activity
usage: ecocal [-c COUNTRY [COUNTRY ...]] [-i {high,medium,low,all}]
              [-cat {employment,credit,balance,economic activity,central banks,bonds,inflation,confidence index} [{employment,credit,balance,economic activity,central banks,bonds,inflation,confidence index} ...]]
              [-s START_DATE] [-e END_DATE] [-h] [--export EXPORT] [--raw] [-l LIMIT]
ecocal: error: argument -cat/--categories: invalid choice: 'economic' (choose from 'employment', 'credit', 'balance', 'economic activity', 'central banks', 'bonds', 'inflation', 'confidence index')
```

@DidierRLopes has also mentioned elsewhere that functions with flags containing more than one letter should only use double-dashes because a single dash with more than one character can create errors. A solution would be to rename the flag as `--cat` and remove `--categories and -c`

### PR DESCRIPTION
**Pull request by DidierRLopes**
Fixes #2248 

Screenshot 2022-08-07 at 23 08 16

### CODE REVIEW

**Comment by jmaslek** [comment]
Can we rename the function from ecocal->econcal?

**Comment by montezdesousa** [comment]
> Can we rename the function from ecocal->econcal?

I don't love `ecocal`, but couldn't come up with better name at the time. I'm ok with `econcal`, but what do you think of something smaller like `events` or `agenda`?

**Comment by montezdesousa** [comment]
> > Can we rename the function from ecocal->econcal?
> 
> I don't love `ecocal`, but couldn't come up with better name at the time. I'm ok with `econcal`, but what do you think of something smaller/cleaner like `events` or `agenda`?

**Comment by montezdesousa** [comment]
Changes looks good to me, it actually fixes a still to be found issue with filtering by categories with spaces. Apparently investpy uses _ in those cases.

not good: `investpy.news.economic_calendar(time_filter = "time_only", categories=["economic activity"])`
good: `investpy.news.economic_calendar(time_filter = "time_only", categories=["economic_activity"])`

**Review by montezdesousa — APPROVED** [review]

**Comment by DidierRLopes** [comment]
I added the "_" to not have the issue with 2 words but after I replace the underscore by a space. Unfortunately, we can't use `choices=` when `nargs="+"` which is annoying :/

@montezdesousa if we merge this can you then change the function name from `ecocal` to`events` ?

**Comment by montezdesousa** [comment]
> I added the "_" to not have the issue with 2 words but after I replace the underscore by a space. Unfortunately, we can't use `choices=` when `nargs="+"` which is annoying :/
Seen, didn't test it. So we can just remove that replace and should work

> 
> @montezdesousa if we merge this can you then change the function name from `ecocal` to`events` ?
yes

**Pull request merged**
