### PR TITLE
Changing packaging version

### PR DESCRIPTION
**Pull request by hjoaquim**
This PR patch the deprectation of `LegacyVersion` under `packaging` - also discussed here: https://github.com/pypa/packaging/issues/631

- Removes `LegacyVersion`
- Specifies that `packaging=">=22.0"`

Steps taken: 

```bash
poetry add packaging=">=22.0"
poetry export -f requirements.txt  -o requirements.txt --without-hashes --dev
poetry export -f requirements.txt  -o requirements-full.txt --extras prediction --extras optimization --without-hashes --dev
```

Fix:
- #3750

### CODE REVIEW

**Comment by jmaslek** [comment]
I think the better solution will be to change:
```
current_version: Union[version.LegacyVersion, version.Version]
```
to 
```
current_version: version.Version
```

And then add packaging^22.

Thoughts?

**Comment by hjoaquim** [comment]
Does the Tests / General Linting create a fresh environment each time? The error does not make sense since `version.parse()` returns only `Version` with packaging 22

**Comment by jmaslek** [comment]
> Does the Tests / General Linting create a fresh environment each time? The error does not make sense since `version.parse()` returns only `Version` with packaging 22

It uses the actions/cache@v3 to restore dependencies.  I am not sure how to change those, so you may need to just add `packaging==22` to the yml

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
> > Does the Tests / General Linting create a fresh environment each time? The error does not make sense since `version.parse()` returns only `Version` with packaging 22
> 
> It creates a fresh env when the dep tree is re-solved

The tests create a new env, but the linting uses the cache from gh actions.  That has not been updated in 9 months.  

I used this doc to open a new PR that will edit the cache when the poetry lock changes: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by hjoaquim** [comment]
@jmaslek @piiq thanks for the clarification!

**Pull request merged**
