### PR TITLE
Feature/ecb-balance-of-payments: Adds Balance of Payments to Economy Router and Data From ECB

### PR DESCRIPTION
**Pull request by deeleeramone**
This PR adds Balance of Payments reports to the Economy router, with data coming from the ECB.  This integrates series covered by the dashboard here: [https://data.ecb.europa.eu/publications/balance-payments-and-other-external-statistics/3032569](https://data.ecb.europa.eu/publications/balance-payments-and-other-external-statistics/3032569)

There is data going back to 2013, and is mostly quarterly in granularity with "main" and "summary" also having monthly.

Adding other Central Banks/Governments as providers to this endpoint would help create a global view of trade balances and the flow of capital between regions.

The default state is `report_type = 'main'` and `frequency = 'monthly'`

```
obb.economy.balance_of_payments()
```

Screenshot 2023-11-12 at 2 13 32 PM

All parameters are Literals. Valid report_types are:

```
[
    "main",
    "summary",
    "services",
    "investment_income",
    "direct_investment",
    "portfolio_investment",
    "other_investment",
]
```

Valid countries are:

```
[
    "brazil",
    "canada",
    "china",
    "eu_ex_euro_area",
    "eu_institutions",
    "india",
    "japan",
    "russia",
    "switzerland",
    "united_kingdom",
    "united_states",
    "total"
]
```

Screenshot 2023-11-12 at 2 10 58 PM

The data models are large, but the returned data will never contain all fields.  The verbosity ensures that the order of fields is maintained across all `report_types`, and accommodates the subtle differences.

See [Wikipedia](https://en.wikipedia.org/wiki/Balance_of_payments) or [Investopedia](https://www.investopedia.com/terms/b/bop.asp#toc-what-is-the-balance-of-payments-bop)

### CODE REVIEW

**Comment by the-praxs** [comment]
@deeleeramone before reviewing, a heads up that the base will change to `develop` as the merge is underway!

**Comment by the-praxs** [comment]
@deeleeramone can you update the branch to `develop` and resolve any conflicts that may occur?

**Comment by deeleeramone** [comment]
> @deeleeramone can you update the branch to `develop` and resolve any conflicts that may occur?

It's gonna be best to close this an open a clean PR.

**Comment by deeleeramone** [comment]
Replaced by #5726

**Pull request closed without merging**
