### PR TITLE
Feature/futures curve history

### PR DESCRIPTION
**Pull request by skhan59bbk**
This feature adds the ability for a user to view a futures curve as at a previous date, helping to analyse how the curve has evolved over time (flattened/steepened/etc). 

This functionality is available in Bloomberg's equivalent `GC<GO>` function.

A new `--as-of` option has been added to the `futures/curve` function, where the user can enter their desired historical reference date.

image

`curve -t ES --as-of 2022-12-07`

If there is data for the date in question, the chart will plot both the latest curve and the chosen historical curve (with appropriate legend to distinguish between the two). 

image

The `--raw` option will also display the prices for both dates: 

image

_NB: also fine in "interactive" mode - I'm just screenshotting the simplified table._

If the user selects an invalid `--as-of` date (e.g. a weekend or a date prior to the contract existing), the function will revert to just showing the live curve but print an appropriate message nonetheless:

image

Finally, `--as-of` is optional, so running the curve command as before still works as it did.  

-------------------------------------------------------------------------------------------
# Checklist:

- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
This looks awesome!  Will try to get to tomorrow!

Can I be picky and suggest that instead of "--as-of", we do "-d", "--date", which aligns with how we get the treasury curves :)

**Comment by skhan59bbk** [comment]
Sure thing! Hopefully find time to change it tomorrow.

**Comment by skhan59bbk** [comment]
Changed to `-d` and `--date` as requested. 

image

**Comment by jmaslek** [comment]
> Changed to `-d` and `--date` as requested.
> 
> image

Thanks!  I added a small patch for the xaxis formatting (doing something like CL was giving a weird grid).

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
