### PR TITLE
Able to change the data range in some stock controllers

### PR DESCRIPTION
**Pull request by pftp-jz**
# Description

new feature

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context. 
- [x] List any dependencies that are required for this change.

Adding a way to change the range of the data being used without fetching it again, and reverse the change to the original range.

For stocks_controller, dps_controller, ba_controller,  dd_controller, fa_controller, gov_controller, pred_controller, qa_controller, ta_controller

For stocks_controller changes in range affect all controllers below it 

For dps_controller, ba_controller,  dd_controller, fa_controller, gov_controller, pred_controller, qa_controller, ta_controller - data ranges revert for stocks_controller current range once you exit the controller

Useful to perform analysis with different range in data and see the variation of the analysis

One example is : This way you can load data for training in ml them simple loadrange -e -30, and spare the last 30 days for testing your model with the most recent data.

# How has this been tested?

passed all pytest tests
Tested new functionality in terminal

still needs to be develop tests using it, but it's a simple function, it only slices a df into a new df and revert the change.

Weirdly one test is failing, from a function i didn't modify
-> comparison_analysis -> test_finviz_compare_view.py -> test_screener

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by pftp-jz** [comment]
loadfulldata will very likely be merged into loadrange, with a argument like, loadrange -r --reset,

**Comment by DidierRLopes** [comment]
Hey @pftp-jz 

Thanks for this!

Instead of adding 2 new commands, why not have:
```
loadrange =  load TICKER --rangestart -30 --rangeend -10
```
and
```
loadfulldata =  load TICKER -a
```

That makes it easier since we are talking about the same function, and just a different way to have access to its data

**Review by DidierRLopes — CHANGES_REQUESTED** [review]
Comment above

**Comment by pftp-jz** [comment]
After making it, i realised it was kinda dumb to make an entire function for loadfulldata

I talked about it in discord about merging  into loadrange, and also add more functionality to it later.
I was afraid of crowding Load since it already has 11 arguments.

New functionalities like adding Len, split by % of data, split by specific date (see effect of news), split by specific quarter (companies reports)  & etc...

**Comment by DidierRLopes** [comment]
> After making it, i realised it was kinda dumb to make an entire function for loadfulldata, loadfulldata could simple be -rd --reloaddata
> 
> I talked about it in discord about merging into loadrange, and also add more functionality to it later. I was afraid of crowding Load since it already has 11 arguments.
> 
> New functionalities like adding Len, split by % of data, split by specific date (see effect of news), split by specific quarter (companies reports) & etc...
> 
> So what should i do, merge both to load anyway, or keep loadrange, to add more functionality to it later?
> 
> @DidierRLopes

Good points.

Let's get some more feedback here: @jmaslek @JerBouma @minhhoang1023 @piiq

**Comment by piiq** [comment]
My only comment on this particular implementation is that -s (--start) and -e (--end) are used as date (datetime) arguments everywhere in the terminal and to me it seems that it's better to keep it this way. 

On the conceptual side top of my head (I'm just juggling ideas here, not sure) I would store the a `self.range` instead of the second dataframe and use the range to slice the `self.stock`. That always gives me all the data in the controller and a way to select a subset for analysis.

In addition since the slash issue will be resolved by this https://github.com/OpenBB-finance/OpenBBTerminal/pull/2064 PR it will open opportunities to use own data loaded from anywhere on the computer and IMO that gives a lot more control over what data I do the analysis on.

@pftp-jz can you post an end-to-end command sequence that utilizes these new functions (like an .openbb routine file)? Maybe I'm missing something and your example will help understand more of the context?

**Comment by pftp-jz** [comment]
@piiq nice catch, to be consistent would be better to have -s -e reserved for the datetime arguments

It probably would be better to store only the range than a copy of the subset of a dataframe, But, all functions already used self.stock as a base, this way you can simple change the range and execute all the functions as usual, if you want to store range and use a subset, you will have to either add argument to all functions using the different data to use the subset or the full data + the logic in each of them. any addition/modification to different types of arguments could result in the same work being done for extra functionality. 
if you refer to it only as range and not a copty like df2 = df1[-30:], any changes to in /stocks/ going to another stocks/ta/ will throw a error, self.stock need to be an df not slice of one

i also posted a PR https://github.com/OpenBB-finance/OpenBBTerminal/pull/2068 for that problem with the slashs + other problems too, the regex i used match for any argument using / in paths not only load we probably could mix our solutions to get something better, like --export function for instance. -> there is also other solutions here like queue commands from any path, like /home/stocks/load AMZN/fa
But this way you don't have to reload data from source every time, polygon/ other sources have some limits  to the amount of API calls you can make, and there is no reason to make 4 calls to get data you already have

There is lots of examples, like i mentioned you can spare a part of your to train using regression and use the last N rows as a test dataset for the result. its mostly useful for PRED, QA and TA, you can go back and forth from past "events" (news quarters & etc...) . We can make weekly / month analysis of the data, last 22 days analysis & etc...

**Comment by piiq** [comment]
@pftp-jz all these very good points

@JerBouma will you have time to look at this PR and chip in? The use case is:
- To have a subset(s) of loaded data available to pass into individual commands without the need to reload the data from the source every time. Do you see any solution usage-wise?
Let's brainstorm this together

**Comment by JerBouma** [comment]
This is an interesting idea but I wonder, why is it such a problem that you need to fetch the data again? It doesn't take a tremendous amount of time and even though you need to call the API again, how often do you really change this range? I get the ML example so in that case include this option within the `load` command? I find having two additional commands just for a, to me, quite specific use-case not the ideal solution.

Furthermore, I don't really like the way the amount of days is modelled. The market is not open 24/7 so the user could assume he is looking at the last month when he inputs `-30` days while he is actually (most likely) looking at the last 1.5 months. Or do you properly model for this?

**Comment by DidierRLopes** [comment]
I am closing this one as the use-case may be too specific. We may look into this in the future, and we can then re-open this PR. Thanks!

**Pull request closed without merging**
