### PR TITLE
Redirect users to correct installation tab based on OS

### PR DESCRIPTION
**Pull request by jose-donato**

### CODE REVIEW

**Comment by andrewkenreich** [comment]
Need a catch all here for random user agent types -

image

This is shown if it isnt found

**Review by andrewkenreich — CHANGES_REQUESTED** [review]
Other should show Windows

**Comment by jose-donato** [comment]
@andrewkenreich should be good now. nice catch

**Comment by andrewkenreich** [comment]
looks good to me - @jmaslek you want to review as well?

**Review by andrewkenreich — APPROVED** [review]

**Pull request merged**
