### PR TITLE
Add record session into routine capabiltiies

### PR DESCRIPTION
**Pull request by DidierRLopes**
https://user-images.githubusercontent.com/25267873/193699845-a8225906-67ed-4391-b90f-8996333f5a84.mp4

### CODE REVIEW

**Comment by colin99d** [comment]
It would mean a lot to me if the command was q and you could name the macro with one letter.

**Comment by colin99d** [comment]
https://www.redhat.com/sysadmin/use-vim-macros#:~:text=To%20record%20a%20macro%20and,again%20to%20stop%20the%20recording.

**Comment by DidierRLopes** [comment]
> It would mean a lot to me if the command was q and you could name the macro with one letter.

"q" is already used for quit unfortunately.

I can have just the command `record` to start and stop. What do you think?

For the macro being a single letter, we prob need a mapping from routine to macro. I can work on that in the future.

**Comment by colin99d** [comment]
> > It would mean a lot to me if the command was q and you could name the macro with one letter.
> 
> "q" is already used for quit unfortunately.
> 
> I can have just the command `record` to start and stop. What do you think?
> 
> For the macro being a single letter, we prob need a mapping from routine to macro. I can work on that in the future.

Im sorry it was just a vim joke

**Comment by colin99d** [comment]
@DidierRLopes. Maybe this is out of scope for this pr but when running the `exe` command should we remove the .openbb and just show `test` instead of `test.openbb`?

**Review by colin99d — APPROVED** [review]
I bullied it, and it survived. Nice work!

**Comment by DidierRLopes** [comment]
> @DidierRLopes. Maybe this is out of scope for this pr but when running the `exe` command should we remove the .openbb and just show `test` instead of `test.openbb`?

Probably I would leave the .openbb so that the user knows that the file needs to have that extension

**Pull request merged**
