### PR TITLE
[Feature] - Add derivates historical chart

### PR DESCRIPTION
**Pull request by IgorWounds**
1. **Why**? (1-3 sentences or a bullet point list):

    - The goal is to extend the charting coverage of the OpenBB Platform.

2. **What**? (1-3 sentences or a bullet point list):

    - Maps the `price_historical` charting function to the futures derivatives price data.

3. **Impact** (1-2 sentences or a bullet point list):

    - Now users can utilize the charting capabilities for this endpoint.
    
4. **Testing Done**:

    - Ensured that the chart is spawned and working.

### CODE REVIEW

**Review by deeleeramone — COMMENTED** [review]
I think this is in the same category of issue as the Technical router integration tests. Perhaps satisfying issues in one place opened a new one elsewhere?

Screenshot 2024-06-19 at 2 29 04 PM

**Comment by deeleeramone** [comment]
@hjoaquim, something weird is happening here, `chart=True` works in the Fast API  but not in the Python interface. However, the same chart, ultimately `equity.price.historical`, works in the Python interface.

Screenshot 2024-06-20 at 12 48 20 PM

```
INFO:     127.0.0.1:55594 - "GET /api/v1/derivatives/futures/historical?chart=true&provider=yfinance&symbol=ES&interval=1d HTTP/1.1" 200 OK
```

```console
In [2]: data = obb.derivatives.futures.historical("ES", chart=True)

In [3]: data
Out[3]: 
OBBject

id: 0667486f-2c9e-700d-8000-6d8b77eeb5d9
results: [{'date': datetime.datetime(2000, 9, 18, 0, 0), 'open': 1485.25, 'high': 1...
provider: yfinance
warnings: [{'category': 'OpenBBWarning', 'message': "Parameter 'chart' not found."}...
chart: None
extra: {'metadata': {'arguments': {'provider_choices': {'provider': 'yfinance'}, 's...
```

**Comment by deeleeramone** [comment]
Not sure what happened here, but I had uninstalled both `derivatives` and `openbb-charting` then reinstalled. A second uninstall/install of `openbb-charting` seems to have resolved the difference and now `chart=True` is working.

Now I got a weird glitch:


https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/5aca17bb-1b55-49d0-a7c6-3f49f1f417ba


This is a separate issue than the PR, the implementation of the execution seems fine.

**Comment by hjoaquim** [comment]
> Now I got a weird glitch:
> Screen.Recording.2024-06-20.at.1.43.55.PM.mov
> 
> This is a separate issue than the PR, the implementation of the execution seems fine.

That's new 😲

**Comment by deeleeramone** [comment]
> > Now I got a weird glitch:
> > Screen.Recording.2024-06-20.at.1.43.55.PM.mov
> > This is a separate issue than the PR, the implementation of the execution seems fine.
> 
> That's new 😲

Probably related to some kind of broken syntax in the `frontend-components` compilation, and it could also be an interaction between that compiled code and the Platform code. It is *very* difficult to resolve issues related to that because they are not dynamically integrated with the code, but rather frozen forever.

**Comment by IgorWounds** [comment]
@deeleeramone @hjoaquim are there updates regarding the charting? How should I proceed?

**Review by hjoaquim — APPROVED** [review]
Let's fix the tests and this is good to go; the fact that the charting is now modular makes this look so good and clean!

**Pull request merged**
