### PR TITLE
[Feature] Update chart creation so it doesn't break the command execution

### PR DESCRIPTION
**Pull request by hjoaquim**
1. **Why**? (1-3 sentences or a bullet point list):

    - Creating a chart shouldn't break the whole creation of the `OBBject` (unless in debug mode).

2. **What**? (1-3 sentences or a bullet point list):

    - Encapsulate in a try/except block.

3. **Impact** (1-2 sentences or a bullet point list):

    - NA / minor UX.

4. **Testing Done**:

    - Run any chart - manually insert an exception for testing purposes.

### CODE REVIEW

**Comment by deeleeramone** [comment]
LGTM, on a side-note, which function was failing when `chart=True` and under what conditions? It would be good to know this so it can be looked into.

**Comment by hjoaquim** [comment]
> LGTM, on a side-note, which function was failing when `chart=True` and under what conditions? It would be good to know this so it can be looked into.

Actually, any! This come up on a random experiment and just thought it would be a good idea to not break everything just bc the chart couldn't be computed!

**Comment by deeleeramone** [comment]
> Actually, any! This come up on a random experiment and just thought it would be a good idea to not break everything just bc the chart couldn't be computed!


WDYM, any? I understand what this is doing, but am looking for a repeatable scenario where `chart=True` fails.

**Review by deeleeramone — APPROVED** [review]

**Comment by hjoaquim** [comment]
> > Actually, any! This come up on a random experiment and just thought it would be a good idea to not break everything just bc the chart couldn't be computed!
> 
> WDYM, any? I understand what this is doing, but am looking for a repeatable scenario where `chart=True` fails.

It does not fail in any function afaik; I forced an exception to check something, not sure about the context anymore tho

**Pull request merged**
