### PR TITLE
[Release] 4.2.0

### PR DESCRIPTION
**Pull request by hjoaquim**
^

### CODE REVIEW

**Review by montezdesousa — APPROVED** [review]

**Comment by deeleeramone** [comment]
Are we bumping version numbers and `.lock` files here or does that happen somewhere else?

**Comment by montezdesousa** [comment]
We bump here during the release

**Comment by deeleeramone** [comment]
> We bump here during the release

Just to clarify, is this an automatic process now? Last release the lock files and versions were all updated as a commit to the release branch.

**Comment by hjoaquim** [comment]
we need to bump `openbb` on the cli

**Review by piiq — APPROVED** [review]

**Pull request merged**
