### PR TITLE
replace ln and ld by search

### LINKED ISSUE #2542: [IMPROVE] ETF replacing ld and ln by search
We should just have a `search` command instead of `ld` and `ln`.

The search should have `-n/--name` and `--d/--desc` arguments.

### PR DESCRIPTION
**Pull request by DidierRLopes**
* This fixes #2542 2542

### CODE REVIEW

**Comment by DidierRLopes** [comment]
@Chavithra need a hand with the tests here pleaaseeee

**Comment by Chavithra** [comment]
The following code only work if you have space separated option/value, like `search --name oil --source FinanceDatabase`:
```python
            required="-h" not in other_args
            and "-n" not in other_args
            and "--name" not in other_args,
```

If you are using option/value like this ` search --name=oil --source=FinanceDatabase` it will cease to work as expected.

**Comment by DidierRLopes** [comment]
> Hi Didier,
> 
> The following code only work if you have space separated option/value, like `search --name oil --source FinanceDatabase`:
> 
> ```python
>             required="-h" not in other_args
>             and "-n" not in other_args
>             and "--name" not in other_args,
> ```
> 
> If you are using option/value like this ` search --name=oil --source=FinanceDatabase` it will cease to work as expected.

Ohhh.. but that's how it was before. How was it working? 🤔

**Comment by Chavithra** [comment]
Like if you have `"--name=oil  --source=FinanceDatabase", then:

```python
 other_args = [
    "--name=oil",
    "--source=FinanceDatabse",
]
```

So the `"--name" in other_args` statement won't work.

**Review by Chavithra — APPROVED** [review]
The `etf/search` command works on my side.

**Comment by DidierRLopes** [comment]
> Like if you have `"--name=oil --source=FinanceDatabase", then:
> 
> ```python
>  other_args = [
>     "--name=oil",
>     "--source=FinanceDatabse",
> ]
> ```
> 
> So the `"--name" in other_args` statement won't work.

I see now. That's smart. Nice catch, wouldn't have catch it that easily. Thanks @Chavithra

**Pull request merged**
