### PR TITLE
fresh reports fix

### PR DESCRIPTION
**Pull request by soggyomelette**
# Description

Fresh PR for reports installer fix as previous didn't merge correctly

### CODE REVIEW

**Comment by piiq** [comment]
on my machine when I run the report all the charts pop up on screen and. stay there

**Review by piiq — APPROVED** [review]

**Comment by soggyomelette** [comment]
Charts in terminal don't show up after a report is run - not able to identify the issue so far

**Comment by soggyomelette** [comment]
At the moment, the issue is with the bt module switching to a non-interactive plotting backend but attempts to switch back don't seem to work. So, as a temporary fix, the bt module is not available to use from the api but whenever a fix is identified, it will be modified in a future PR

**Review by Chavithra — APPROVED** [review]
Looks good to me.

**Pull request merged**
