### PR TITLE
Order Documentation Navigation Sidebar Alphabetically

### PR DESCRIPTION
**Pull request by wonhyeongseo**
# Description

- [x] Summary of the change / bug fix.
  Alphabetically order main.yml using python yaml package.
```python3
# https://gist.github.com/wonhyeongseo/059da4759ed91f10ce6cff8e53934e46
# pip install pyyaml
import yaml

# raw file: https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/website/data/menu/main.yml
with open('main.yml', 'rt', encoding='utf8') as f:
  content = yaml.safe_load(f.read())
  content = content['main'][0]

def sort_nested(l: list):
  result = []
  for d in sorted(l, key=lambda d: d['name'].lower()):
    if d.get('sub'):
      d['sub'] = sort_nested(d['sub'])
    result.append(d)
  return result

with open('new.yml', 'wt', encoding='utf8') as f:
  yaml.safe_dump(sort_nested(content['sub']))

# some manual work was needed to copy the
# remainder of main.yml to new.yml and format the document.
```

- [x] Link # issue, if applicable.
   fix https://github.com/OpenBB-finance/OpenBBTerminal/issues/2685
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
   image
   image
- [x] Relevant motivation and context.
   Second PR for Hacktoberfest
- [x] List any dependencies that are required for this change.
  None

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the api still works
- [x] Check any related reports

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by DidierRLopes — COMMENTED** [review]
Hey @wonhyeongseo, this is amazing! Thanks for contributing!

It seems the number of lines do not match, and I would have expected that they should be the same since we are just ordering.

Am I missing something?

**Comment by wonhyeongseo** [comment]
Hello @DidierRLopes, happy to help 😄 
The line difference is because there were comments and some empty lines that couldn't be parsed by pyyaml. If you want, I can recover those manually.
Thanks again for your feedback. Hope you have a wonderful day!

**Comment by jose-donato** [comment]
Hey @wonhyeongseo thanks for this amazing and detailed contribution 🔥 

Two important things: 
1. we cannot change stuff below the comment because below that the content is generated automatically for the OpenBB SDK
2. can we add somewhere the script so we can use it later when/if it gets messy again? maybe we can open a new issue for enhancement and integrate this into a github action, or pre-commit :)

**Comment by wonhyeongseo** [comment]
Hello @DidierRLopes, here are the details for the differences:
```
cryptocurrency 6
  overview 2        ref: "/terminal/crypto/ov/fun"
  due diligence 4   ref: "/terminal/crypto/dd/desc", "/terminal/crypto/dd/funot"
stocks 2 (comments) ref: /terminal/portfolio/pa/group
empty-line 1
```
Except for the removal of an empty line between forecast and stocks, I can confirm that there are no differences in the code now. Thank you so much for catching this!

Hello @jose-donato, I saw the comment on L1672 (now L1671) and made sure to not edit the lines below. Github Actions is a great idea and I'm willing to explore it, but I am unsure why pyyaml missed out 6 lines from the file. May I please try this in a separate issue? Thank you for your review 😄

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
