### PR TITLE
Fixing default view and ascending order in cglosers and cggainers

### LINKED ISSUE #1905: [Bug] crypto/disc/cglosers - sorting by market cap is not on by default, as described by the help dialogue.
crypto/disc/cglosers: 

  - sorting by market cap is not on by default, as described by the help dialogue.
  - applying the filter to sort by market cap puts the highest rank at the bottom, which is unconventional presentation.
  
Screen Shot 2022-06-05 at 1 57 37 PM

### PR DESCRIPTION
**Pull request by simmonsj330**
# Description
Fixes #1905 
Made default cglosers sort by Market Cap [$] and switched ordering of sorting from descending to ascending.
Screen Shot 2022-06-09 at 5 30 37 PM
Screen Shot 2022-06-09 at 5 30 49 PM

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context. 

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by jmaslek** [comment]
hmmm.  The market cap still sorts in reverse order
```
2022 Jun 10, 09:15 (🦋) /crypto/disc/ $ cggainers -s Market Cap [$]

┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Symbol ┃ Name              ┃ Price [$] ┃ Market Cap [$] ┃ Market Cap Rank ┃ Volume [$] ┃ Change 1h [%] ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dai    │ Dai               │ 1.00      │ 6.6B           │ 15              │ 204.6M     │ -0.08         │
├────────┼───────────────────┼───────────┼────────────────┼─────────────────┼────────────┼───────────────┤
```
Also having to have the user type out `Market Cap [$]` is tedious, and should be able to sort by `Market Cap` (then we can add in the ($) after the fact.

You are also getting a warning which can be directly applied to pycoingecko_model (`df = pd.concat([df, pd.DataFrame(data)])` instead of using append)

**Comment by DidierRLopes** [comment]
After doing James requests, for the test to pass you need to do:
`pytest tests/openbb_terminal/cryptocurrency/discovery/test_pycoingecko_view.py --record-mode=rewrite`

**Comment by simmonsj330** [comment]
@jmaslek Sorting is in ascending order where the lowest market cap would put it at the highest market cap rank. For example bitcoin is the 1 market cap rank and appears at the top when sorting by rank but appears at the bottom when sorting by market cap itself

**Comment by jmaslek** [comment]
> @jmaslek Sorting is in ascending order where the lowest market cap would put it at the highest market cap rank. For example bitcoin is the 1 market cap rank and appears at the top when sorting by rank but appears at the bottom when sorting by market cap itself

I see.  One could technically sort on the negative rank, but I think the user should understand why the sorting is in reverse order for the rank.  So just add the test and you are good to go!

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
