### PR TITLE
Add 3 Token Terminal commands

### PR DESCRIPTION
**Pull request by DidierRLopes**
* Adds `crypto/ov/fun`

Screenshot 2022-08-29 at 00 07 31

* Adds `crypto/dd/funot`
* Adds `crypto/dd/desc`

Screenshot 2022-08-29 at 00 08 53

### CODE REVIEW

**Comment by jose-donato** [comment]
image

looks like we need to uppercase the symbol before passing to the api?

**Comment by jose-donato** [comment]
image

should we use one as default in the case users dont pass any?

**Comment by jose-donato** [comment]
image

we should probably divide by 1_000_000 to make that 1e6 disappear from top left

**Comment by jose-donato** [comment]
image

@DidierRLopes im still getting this

**Comment by DidierRLopes** [comment]
> image
> 
> @DidierRLopes im still getting this,, am i doing something wrong?

Did you do `poetry install` ? It works for me

Screenshot 2022-09-02 at 15 42 22

**Comment by jose-donato** [comment]
image

**Comment by jose-donato** [comment]
image

**Review by jose-donato — APPROVED** [review]
thanks,, looking solid 🍌

**Pull request merged**
