### PR TITLE
[Bug] Broken ETF functionalities

### PR DESCRIPTION
**Pull request by soggyomelette**
# Description

Tries to solve #1972 by changing the code in stockanalysis_model.py to ensure it extracts the data from stockanalysis.com correctly

Also modifies the code in etf_controller.py to handle comparison between ETFs when spaces are used instead of commas (the parser isn't able to interpret arguments with spaces correctly)

Before:
image

After:
image

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
Thank you!

Can you fix the tests as well please? @Chavithra can help you here if needed

**Comment by JerBouma** [comment]
Fixed it for you, @soggyomelette

**Comment by soggyomelette** [comment]
> Fixed it for you, @soggyomelette 

Thanks a lot! @Chavithra showed me how to do it but am travelling atm so hadn't done it yet

**Comment by JerBouma** [comment]
> > Fixed it for you, @soggyomelette
> 
> Thanks a lot! @Chavithra showed me how to do it but am travelling atm so hadn't done it yet

No problem! Feel free to merge :)

**Comment by DidierRLopes** [comment]
Nice one @soggyomelette 🚀

**Pull request merged**
