### PR TITLE
Adds a test for binance key as asked for in #2006

### PR DESCRIPTION
**Pull request by soggyomelette**
# Description
Adds a test for the binance key in the keys menu as there initially wasn't one present 

Before:
image

After with incorrect key:
image

After with correct key:
image

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes: Ran with incorrect keys and with my own keys to reproduce above results 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by soggyomelette** [comment]
I also see that there are a few other keys that don't have tests written for them, is that something I could add to a TODO list?

**Comment by DidierRLopes** [comment]
> I also see that there are a few other keys that don't have tests written for them, is that something I could add to a TODO list?

Hi @soggyomelette , yes please!

**Review by DidierRLopes — APPROVED** [review]

**Comment by DidierRLopes** [comment]
You just need to run `black file_changed_path` and then we can merge this 😄

**Comment by soggyomelette** [comment]
> > I also see that there are a few other keys that don't have tests written for them, is that something I could add to a TODO list?
> 
> Hi @soggyomelette , yes please!

Great, I'll start working on it!

**Comment by DidierRLopes** [comment]
Thank you @soggyomelette ❤️

**Pull request merged**
