### PR TITLE
Audit SDK and View/Model functions

### PR DESCRIPTION
**Pull request by colin99d**
# Description

A tool the automatically compares the SDK and view/model functions. This allows users to see if either one has duplicate functions, and then see how they map to each other.

To run use `python sdk_audit.py`

# How has this been tested?

Ran the functionality

Also ran `openbb.crypto.dd.balance("BTC")` to test that my change did not break the command.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).
- [x] Add whether it is a model or a view

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by Chavithra — CHANGES_REQUESTED** [review]
Hi @colin99d,

So document can be generated but I see duplicate lines and functions without docstring.

Example:
```
covid_model.get_global_cases
covid_model.get_case_slopes
```

**Comment by colin99d** [comment]
> Hi @colin99d,
> 
> So document can be generated but I see duplicate lines and functions without docstring.
> 
> Example:
> 
> ```
> covid_model.get_global_cases
> covid_model.get_case_slopes
> ```

Hey Chavi,

I just generated a new csv. Both of the functions you listed are only included once, and both have docstrings. Did you change anything before running?

**Comment by colin99d** [comment]
> Hi @colin99d,
> 
> So document can be generated but I see duplicate lines and functions without docstring.
> 
> Example:
> 
> ```
> covid_model.get_global_cases
> covid_model.get_case_slopes
> ```

Hey Chavi,

I just generated a new csv. Both of the functions you listed are only included once, and both have docstrings. Did you change anything before running?

**Comment by colin99d** [comment]
> Hi @colin99d,
> 
> So document can be generated but I see duplicate lines and functions without docstring.
> 
> Example:
> 
> ```
> covid_model.get_global_cases
> covid_model.get_case_slopes
> ```

Hey Chavi,

I just generated a new csv. Both of the functions you listed are only included once, and both have docstrings. Did you change anything before running?

**Comment by colin99d** [comment]
Ok, I did find some errors:

- Removing "py" everywhere in module string and not just on ending (I made the code smarter and this bug if fixed)
- SDK calls functions that are inside a `_helpers.py` file. This breaks the MVC format, and my script cannot find them. This should be fixed by moving the function into a view or model.
- Linking the SDK to a place where the function is imported, instead of where it is defined. `openbb_terminal.cryptocurrency.due_diligence.binance_view.get_balance` is defined in the model, but we import it from the view. 
Below are images of the remaining blank docstrings:
Screenshot 2022-11-14 at 8 48 58 AM

**Review by Chavithra — APPROVED** [review]
Looks ok to me.
Although this version not compatible with Windows.

Edit: it should have Windows support now.

**Pull request merged**
