### PR TITLE
Add new functionality to measure country performance

### PR DESCRIPTION
**Pull request by JerBouma**
# Description
This adds new functionality to measure country performance, this includes:

- economy/_country_: Country Performance
- economy/gdp: Show annual nominal Gross Domestic Product (GDP)
- economy/qgdp: Show quarterly real Gross Domestic Product (GDP)
- economy/fgdp: Show forecasts of nominal and real Gross Domestic Product (GDP)
- economy/debt: Show government debt-to-GDP ratio
- economy/cpi: obtain the (harmonized) Consumer Price Index (CPI)
- economy/ccpi: obtain components of the CPI including Food, Energy and Total
- economy/balance: Show Government defict or surplus in capital income and expenditures
- economy/revenue: Show Government revenue based on tax income
- economy/spending: Show Government spending as indicator of size of government
- economy/trust: Show Government trust based on surveys regarding confidence in the government  

This makes it possible to look into cases like https://en.wikipedia.org/wiki/Greek_government-debt_crisis and https://economictimes.indiatimes.com/news/international/business/japans-debt-mountain-how-is-it-sustainable/articleshow/76298563.cms?from=mdr.

image

A good example is to look into the high Debt-to-GDP ratio that Greece has compared to the average OECD countries hinting at the large pressure of foreign debt.

image

I can also show how little my country cared about military compared to the United States 😛 

image

# How has this been tested?

Made new tests for `oecd_model.py` and also added them to the `test_economy_controller.py`.

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ x ] Make sure affected commands still run in terminal
- [ x ] Ensure the SDK still works
- [ x ] Check any related reports. **Economy report not affected.**

# Checklist:

- [ x ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ x ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ x ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ x ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ x ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
i broke it:

```
2023 Mar 17, 14:08 (🦋) /economy/ $ gdp -c united_states,china

Error: 'china'

Error: 'list' object has no attribute 'columns'
```

didnt realize that wasnt a choice, but found an edge case :P

**Comment by jmaslek** [comment]
```
│     gdp                Show annual nominal Gross Domestic Product (GDP)                               [OECD]    │
│     qgdp               Show quarterly real Gross Domestic Product (GDP)      
```

this should be one function with a -q flag like in stocks/fa

**Comment by jmaslek** [comment]
Screenshot 2023-03-17 at 2 15 12 PM

This seems kind of confusing.  If its forecasting, we should probably indicate with some shading somewhere?  Or is it the historical forecast?

**Comment by jmaslek** [comment]
debt default timestampe not in correct form:
```
  -s START_DATE, --start START_DATE
                        Start date of data, in YYYY-MM-DD format (default: 1993-03-17 14:16:41.123661)
  -e END_DATE, --end END_DATE
```

**Comment by jmaslek** [comment]
cpi seems misleading since you give the numbers in terms of YoY, but the chart is titled as CPI:

Screenshot 2023-03-17 at 2 19 11 PM

**Comment by jmaslek** [comment]
ccpi takes forever, anything we can add a timer for?

**Comment by deeleeramone** [comment]
It would be ideal to have the functionality available to other time-series data in the economy menu. 

Screenshot 2023-03-17 at 1 57 26 PM

**Comment by JerBouma** [comment]
> ```
> │     gdp                Show annual nominal Gross Domestic Product (GDP)                               [OECD]    │
> │     qgdp               Show quarterly real Gross Domestic Product (GDP)      
> ```
> 
> this should be one function with a -q flag like in stocks/fa

Issue is that a good bunch of countries don't have quarterly so then you need some smart functionality too.

**Comment by JerBouma** [comment]
> ccpi takes forever, anything we can add a timer for?

Most likely the date range is too big, will look into it.

**Comment by JerBouma** [comment]
> cpi seems misleading since you give the numbers in terms of YoY, but the chart is titled as CPI:
> 
> Screenshot 2023-03-17 at 2 19 11 PM
> 

CPI is actually by default known as YoY so this is normal actually. Just Google CPI and look at the charts.

**Comment by JerBouma** [comment]
> Screenshot 2023-03-17 at 2 15 12 PM
> 
> This seems kind of confusing. If its forecasting, we should probably indicate with some shading somewhere? Or is it the historical forecast?

Fixed, it also doesn't plot this box if you change the date to be before a future date.

image

**Comment by JerBouma** [comment]
@jmaslek 

Fixed everything you mentioned:

- Instead of mention annual and quarterly gdp, I mention nominal and real GDP. Since they have different country lists, my suggestion is to keep them seperate. Also becomes they are two quite different things.
- Fixed all date formats.
- Reduced CCPI range, it was set to 30 years with monthly data which meant long loading. This is now 5 years with monthly data.
- I didn't change CPI since YoY is actually how CPI is represented. When people say the "CPI is 10%" they mean "10% compared to previous year". The term Consumer Price **Index** just doesn't refer to an index with a specific base .
- Fixed forecasting GDP to present the actual forecast.
- If you now enter a country that has no idea (as not in the list) the _model will tell you.

**Comment by JerBouma** [comment]
I don't know why it does this, made a new env too. Can you fix tests for me? Just needs a rewrite @jmaslek 

```
INTERNALERROR>   File "/Users/jeroenbouma/miniconda3/envs/obb2/lib/python3.10/site-packages/pluggy/_result.py", line 9, in _raise_wrapfail
INTERNALERROR>     raise RuntimeError(
INTERNALERROR> RuntimeError: wrap_controller at 'pytest_runtest_makereport' /Users/jeroenbouma/miniconda3/envs/obb2/lib/python3.10/site-packages/dash/testing/plugin.py:106 did not yield

=============================================================================== no tests ran in 0.05s ===============================================================================
(obb2) jeroenbouma@Jeroens-MacBook-Pro OpenBBTerminal % 
```

**Comment by jmaslek** [comment]
`rgdp -u IDX -c united_states`
Screenshot 2023-03-20 at 8 50 25 AM


Also for the gdp numbers, lets default to dollars instead of percent change to match what one would find with a google search or a fred search:
Screenshot 2023-03-20 at 8 52 12 AM

**Comment by jmaslek** [comment]
None of these functionalities have been added to the economy integration test scripts (under miscellaneous)

**Comment by jmaslek** [comment]
Under `fgdp`, you have:
```
  -u {Q,A}, --units {Q,A}
                        Use either Q (quarterly) or A (annually) for units (default: Q)
```

Lets use the same standard we use in `/fa/` and just make this a -q flag.

**Comment by JerBouma** [comment]
> `rgdp -u IDX -c united_states` Screenshot 2023-03-20 at 8 50 25 AM
> 
> Also for the gdp numbers, lets default to dollars instead of percent change to match what one would find with a google search or a fred search: Screenshot 2023-03-20 at 8 52 12 AM

Fixed this and Real GDP of OECD doesn't have absolute numbers unfortunately. Can add in FRED as additional source but in the end, this does allow for proper comparison between countries and if you want `macro` gives RGDP absolute numbers (just a bit limited). I am bit conflicted if it's worth the time now to build that in properly, I don't need it for my case.

Also fixed quarterly flag for fgdp and added commands to integration tests. Also, are integration tests still used? The file contained a lot of old functionality which is why I didn't update it at first.

**Comment by jmaslek** [comment]
Looks like the sdk trail map is missing too.  Looks like you edited economy_sdk_model.py, but if you look at the top:
```
# ######### THIS FILE IS AUTO GENERATED - ANY CHANGES WILL BE VOID ######### #
```

That file gets generated from the trail map.

**Comment by jmaslek** [comment]
> > Looks like the sdk trail map is missing too. Looks like you edited economy_sdk_model.py, but if you look at the top:
> > ```
> > # ######### THIS FILE IS AUTO GENERATED - ANY CHANGES WILL BE VOID ######### #
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That file gets generated from the trail map.
> 
> So do I still need to update the csv? I thought that wasnt te way to go anymore.

yup:
https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/CONTRIBUTING.md#add-sdk-endpoint

**Comment by JerBouma** [comment]
> > > Looks like the sdk trail map is missing too. Looks like you edited economy_sdk_model.py, but if you look at the top:
> > > ```
> > > # ######### THIS FILE IS AUTO GENERATED - ANY CHANGES WILL BE VOID ######### #
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That file gets generated from the trail map.
> > 
> > 
> > So do I still need to update the csv? I thought that wasnt te way to go anymore.
> 
> yup: https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/CONTRIBUTING.md#add-sdk-endpoint

Fixed, actually ran into unrelated issues when running that script so fixed that too. Apparently not everyone runs that script on every change ;)

**Review by jmaslek — CHANGES_REQUESTED** [review]
anything on the website need to be changed?

**Review by jmaslek — APPROVED** [review]
noice

**Pull request merged**
