### PR TITLE
Replaces '/' with ';' for running multiple commands

### LINKED ISSUE #1620: [Bug] slash issue
**Describe the bug**
A "bad" load from the econometrics menu will crash the terminal. "Bad" loads have included so far: not giving an alias along with the filename, and setting the filename directly without using the auto-complete feature (which is dope, ty.) 

**To Reproduce**
from the terminal, enter the econometrics menu and try to explicitly load a filepath (i used one i just stored from FRED data) - `load -f /home/<user>/code/OpenBBTerminal/exports/icsa-test.csv` with or without an `alias` it fails, `load: error: argument -f/--file: expected at least one argument` which it not accurate, as it was given an argument. 

**Screenshots**
Screen Shot 2022-04-03 at 12 06 07 AM

**Desktop (please complete the following information):**

- OS:  (Host) Mac OS X 12.2.1 running Parallels running (Guest) Ubuntu 20.04.2 ARM64
- Python version = 3.8.13

**Additional context**
Should be easy to reproduce, hmu in Discord otherwise, happy to help troubleshoot.

### PR DESCRIPTION
**Pull request by bolshoytoster**
This is probably not complete (documentation hasn't been updated), and it breaks things like `../dd` but it's better than not being able to input paths. Fixes #1620. 

- [x] parents_classes
- [x] scripts folders
- [x] routines folders
- [x] call_exe and call_sh funds that have the hacky version to parse the "/" - there's prob 1 more functionality like this

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
I can run all `*.openbb` files excluding `openbb_terminal/timezone.openbb`
* Provide instructions so we can reproduce. 
Run `exe ./routines/example.openbb`
* Please also list any relevant details for your test configuration.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by colin99d** [comment]
Great work! I will review this tomorrow.

**Review by colin99d — APPROVED** [review]
Code looks great to me! I tried everything and it worked great. Thanks for the PR @bolshoytoster. @DidierRLopes anything else before we merge?

**Comment by DidierRLopes** [comment]
@colin99d there seems to be some sort of conflict. Once that is resolved and
- [] - the slash change doesn't break analytics
- [] - the integration tests run smoothly

I am an happy person 😄

**Comment by bolshoytoster** [comment]
I’ve resolved the conflict, but I just need to finish (re)implementing slash for navigating.

It can be used only for the first token in a command, i.e. `../foo bar`, it would be nice to get the suggestions to work with this as well, but that’s probably for a different PR.

**Comment by DidierRLopes** [comment]
> I’ve resolved the conflict, but I just need to finish (re)implementing slash for navigating.
> 
> It can be used only for the first token in a command, i.e. `../foo bar`, it would be nice to get the suggestions to work with this as well, but that’s probably for a different PR.
> 
> edit: it looks in working order
> 
> On an unrelated note, even with `--depth=1`, `git clone`ing this repo takes ages for me because it is >200Mb in size, most of that coming from `tests/bots/stocks/dark_pool_shorts/cassettes/test_ftd`.
> 
> There is >100mb in that directory due to entire zip files embedded in yaml files. If I understand the tests correctly, they're downloading a file from a url then checking the response is expected. I think we could massively reduce the size of this repo by comparing against a hash instead of the full response, but I'm not too sure if it's possible.
> 
> There's also a gif - `images/usage.gif` - taking 68Mb, using a different format like mp4 would decrease this.

Thanks for this! We are still discussing internally the move forward on this, but will let you know this week more 😄 

@Chavithra is there anything we can do to speed up `git clone` ?

**Comment by Chavithra** [comment]
> > I’ve resolved the conflict, but I just need to finish (re)implementing slash for navigating.
> > It can be used only for the first token in a command, i.e. `../foo bar`, it would be nice to get the suggestions to work with this as well, but that’s probably for a different PR.
> > edit: it looks in working order
> > On an unrelated note, even with `--depth=1`, `git clone`ing this repo takes ages for me because it is >200Mb in size, most of that coming from `tests/bots/stocks/dark_pool_shorts/cassettes/test_ftd`.
> > There is >100mb in that directory due to entire zip files embedded in yaml files. If I understand the tests correctly, they're downloading a file from a url then checking the response is expected. I think we could massively reduce the size of this repo by comparing against a hash instead of the full response, but I'm not too sure if it's possible.
> > There's also a gif - `images/usage.gif` - taking 68Mb, using a different format like mp4 would decrease this.
> 
> Thanks for this! We are still discussing internally the move forward on this, but will let you know this week more 😄
> 
> @Chavithra is there anything we can do to speed up `git clone` ?

Hello there,

that’s not how vcr library works : we can’t replace with a hash.

We can clean probably the history though.

**Comment by DidierRLopes** [comment]
@Chavithra you are going to work on this for this sprint. Are you gonna start from this PR or should we close this?

**Comment by DidierRLopes** [comment]
Thanks for this @bolshoytoster.

I will close this ticket, we finally have made a decision regarding this and it is addressed in #2064

**Pull request closed without merging**
