### PR TITLE
Fixed iteritems deprecated message #2807

### LINKED ISSUE #2807: [Bug] FutureWarning Iteritems deprecated
**Describe the bug**
There is a panda dataframe warning message on terminal when run dcf command.

**To Reproduce**
1 - Go to stocks menu
2 - Load some stock
3 - Go to fa menu
4 - run dcf command

**Screenshots**
openbbterminal

**Desktop:**
- OS: Ubuntu 20.04
- Python 3.8.10

### PR DESCRIPTION
**Pull request by bohruz**
# Description

In pandas dataframe the method **.iteritems** wil be deprecated, and this MR changes the method to **.items** to remove the warning message in terminal. 
Issue openned [here](https://github.com/OpenBB-finance/OpenBBTerminal/issues/2807)

Fixes #2807 

### Before: 
openbbterminal

### Now:
image

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Thank you for this @bohruz 🙏🏽 We will review once tests pass!

**Review by colin99d — APPROVED** [review]

**Comment by colin99d** [comment]
Great fix @bohruz

**Comment by bohruz** [comment]
> Great fix @bohruz

Thank you!
I already solved the problem with lint

**Comment by bohruz** [comment]
> Contributor

Thank you @colin99d!

**Pull request merged**
