### PR TITLE
refactoring load, changed chart to candle

### PR DESCRIPTION
**Pull request by jose-donato**
**DRAFT: WILL BE UPDATED SOON**

* load simplified
* changed command `chart` to `candle` to match stocks

image

### CODE REVIEW

**Comment by minhhoang1023** [comment]
Nice work! 🚀 This is a much-needed one.

Some comments:

1. We should remove the auto-completion with source
image

**Comment by jose-donato** [comment]
Nice :) will go through your comments today

**Comment by minhhoang1023** [comment]
@jose-donato Let me know when it's ready and I'll review it. Let's get this bad boy out!

Now the load is not working at all..

image

**Comment by minhhoang1023** [comment]
When I loaded ADA in upper case, it said coin is not found. But in lower case that'd work

image

**Comment by minhhoang1023** [comment]
When the starting date is specified, an error was thrown

image

**Comment by jose-donato** [comment]
thanks for the help @Chavithra

**Comment by minhhoang1023** [comment]
When I use the load multiple times, coingecko would limit # of API calls. We should have an error message telling them that they should try again in a bit. Other than that, work perfectly! ✨ 


image

**Review by minhhoang1023 — APPROVED** [review]

**Pull request merged**
