### PR TITLE
New Open Source menu

### PR DESCRIPTION
**Pull request by jose-donato**
# Description

This PR adds a new menu to alternative context. This new menu aims to cover open source data and uses Github api as source.
It contains three different commands:
- `rs`: displays a certain repository summary
image

- `sh`: displays star history of a certain repository overtime 
image

- `tr`: displays top repos sorted by stars or forks and can be filtered by categories (e.g., finance)
image

Three features to start but github api is nice and has lot of data. This menu will help users analyse different repos and other open source data.

# How has this been tested?

Tested controller and view/model.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by piiq — CHANGES_REQUESTED** [review]
We need proper api key handling here
image

**Comment by jose-donato** [comment]
> We need proper api key handling here image

thanks. will take a look

**Comment by jose-donato** [comment]
@piiq should be good now

**Comment by piiq** [comment]
@jose-donato not so fast
image
lol

**Comment by jose-donato** [comment]
> @jose-donato can you add an .openbb script for integration tests?
> 
> in addition to this I would like to propose renaming the `os` command to `oss` or `gh` or `github` because `os` is a built in python package and we might have some confusion when using the functionality of the menu from python or jupyter

renamed to `oss`!

the third time is the charm (hopefully)

**Comment by jose-donato** [comment]
@DidierRLopes @Chavithra it only happened after pulling branches from main, do you know what is wrong here?

**Comment by piiq** [comment]
@jose-donato just tested it. works great, although it took VERY long to generate redis' star history
image

possible to add github to the keys menu?

**Comment by jose-donato** [comment]
> @jose-donato just tested it. works great, although it took VERY long to generate redis' star history image
> 
> possible to add github to the keys menu?

yes it takes a lot of time. not sure we can optimize it though. only if we do the requests in parallel! i researched a little bit and it looks like we can only get the star history this way.

yea i forgot about that! will add

**Review by piiq — APPROVED** [review]
This is good for me
@Chavithra can you have a look if logging is implemented correctly here?

**Comment by Chavithra** [comment]
I think we need to filter the user agent.

**Review by Chavithra — APPROVED** [review]
Looks good to me !

**Pull request merged**
