### PR TITLE
Friday night bugs

### LINKED ISSUE #2511: [Bug] Stocks/FA - Cash, Income, Balance - Limit flag doesn't work.
The limit flags do not work for these functions. 

Screen Shot 2022-09-07 at 8 04 14 AM

When `--source Polygon` only one frame of data is returned. The numbers are also returned as $M/B instead of whole numbers like the others. Whole numbers are better for data processes than abbreviations, this should be converted to full values.

Screen Shot 2022-09-07 at 8 05 58 AM

Screen Shot 2022-09-07 at 8 08 33 AM

### LINKED ISSUE #2516: [Bug] Crypto/OV/CR: when `--type borrow`, Error: "['blockfi', 'swissborg'] not in index"
from v1.8_rc:

Screen Shot 2022-09-07 at 10 54 46 PM

### LINKED ISSUE #2531: [Bug] stocks/fa/earnings
For stock "AMT" I get this error:
Screenshot 2022-09-13 at 11 51 38

### LINKED ISSUE #2532: [Bug] stocks/fa/shrs should only have 1 table output
Screenshot 2022-09-13 at 11 53 24

We should use a variable to select the table we are interested to see

### LINKED ISSUE #2537: [Bug] stocks/gov/contracts empty for AMT still shows plot
Screenshot 2022-09-13 at 12 35 34

### LINKED ISSUE #2538: [Bug] stocks/dd/est to just output 1 table
Have a flag to select the table to be shown

### LINKED ISSUE #2547: [Bug] Cosmetic only - stocks/gov/lasttrades - "Last government trading trading".
Screen Shot 2022-09-14 at 9 34 44 PM

### LINKED ISSUE #2548: [Bug] Stocks/gov/topbuys - when "--govtype" == "house", returns error.
This is likely because this category is redundant. For all intents and purposes, there are only two buckets for the US Federal office: congress and senate.

Screen Shot 2022-09-14 at 9 45 06 PM

### PR DESCRIPTION
**Pull request by jmaslek**
I see > 100 issues and take offense with that.  Also my wife isnt home

fix #2548 
fix #2547 
fix #2531 
fix #2537
fix #2516   oh lord im doing crypto now  
fix #2511 
fix #2538  more of an enhancement, but oh well
fix #2532  also an enhancement

### CODE REVIEW

**Comment by DidierRLopes** [comment]
Stealing my weekend fun like this 👀

**Comment by DidierRLopes** [comment]
You may want to add a "fix #TICKET" so that they get closed automatically after this gets merged

**Review by DidierRLopes — APPROVED** [review]

**Comment by jmaslek** [comment]
> You may want to add a "fix #TICKET" so that they get closed automatically after this gets merged

OMG

I have been so confused on how to get them linked.

**Comment by jmaslek** [comment]
> Stealing my weekend fun like this 👀 

This is what happens when you sleep.

**Pull request merged**
