### PR TITLE
Fix wrongly formatted values on `stocks/fa/cash`

### LINKED ISSUE #4203: [Bug] Stocks/FA/Cash - Value for CIK number and Calendar Year is X.XXX M/K
Screenshot 2023-02-09 at 10 52 29 PM

Calendar year is converted where is shouldn't be.

Screenshot 2023-02-09 at 10 54 32 PM

### PR DESCRIPTION
**Pull request by hjoaquim**
# Description

- [x] Summary of the change / bug fix.
1. Enhance the `lambda_long_number_format` by adding to more check to `str` types:
   a. starts with "0" -> if yes, most likely is some kind of ID
   b. is a valid date (Y-M-D)
2. Convert str dates to actual datetime objects on `fmp_model.clean_metrics_df`

- [x] Link # issue, if applicable.
Fix #4203

- [x] Screenshot of the feature or the bug before/after fix, if applicable.
After fix:
image

- [x] Relevant motivation and context.
:bug: :skull: 

- [x] List any dependencies that are required for this change.
NA

# How has this been tested?

`stocks/load aapl/fa/income`
`stocks/load aapl/fa/cash`
`stocks/load aapl/fa/balance`

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
Does this also need to be applied to some of the other commands (i.e balance/income)

**Comment by hjoaquim** [comment]
@jmaslek already being applied as the 3 of them use `fmp_model.clean_metrics_df`

**Comment by jmaslek** [comment]
> @jmaslek already being applied as the 3 of them use `fmp_model.clean_metrics_df`

nice.  sorry was being proactive and havent looked yet

**Review by jmaslek — APPROVED** [review]
Works on my end!

**Comment by hjoaquim** [comment]
@jmaslek thanks for fixing the tests and reviewing!

**Pull request merged**
