### PR TITLE
Regression Models Explainability (XAI) using SHAP

### PR DESCRIPTION
**Pull request by martinb-bb**
# Description

We are now able to provide explainability to `Regression` and `Linear Regression` models. 

It uses **SHAP** values to provide “explanations” of each input features. The input features are the different past lags (of the target and/or past covariates), as well as potential future lags of future covariates used as inputs by the forecasting model to produce its forecasts. Furthermore, in the case of multivariate series, the features contain each dimension of each of the (lagged) series.

Therefore, for users, both `regr` and `linregr` will train and then automatically provide explainability of **feature value** to the next day's forecast value.

To run:

`regr AAPL`
or 
`linregr AAPL --all-past-covariates`

image
image
 

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the api still works
- [x] Check any related reports

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
That text color needs to be adjusted

**Comment by jmaslek** [comment]
Are these values stored as a df somewhere that we can have a --raw flag for printing table as well as the plot?

**Comment by jmaslek** [comment]
> > That text color needs to be adjusted
> 
> Fixed. See new image in PR description.

so much better

**Comment by martinb-bb** [comment]
> Are these values stored as a df somewhere that we can have a --raw flag for printing table as well as the plot?

Will provide more information if I can shortly.

**Comment by colin99d** [comment]
> > Are these values stored as a df somewhere that we can have a --raw flag for printing table as well as the plot?
> 
> Will provide more information if I can shortly.

shap_explain = ShapExplainer(model)
shap_explain.summary_plot(horizons=1)

Should we just return shap_explain?

**Comment by martinb-bb** [comment]
`Regr` and `Linregr` now have a new argparse that will allow users to print out the raw explainability dataframe

`--explainability-df   Prints out a raw dataframe showing explainability results. (default: False)` 

```
2022 Oct 13, 08:57 (🦋) /forecast/ $ regr  20221012_134433_AAPL --explainability-df
Predicting Regression for 5 days
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 115/115 [00:00<00:00, 137.09it/s]
Regression model obtains MAPE: 3.75% 



   Actual price: 138.98    
┏━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Datetime   ┃ Prediction ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 2022-10-12 │ 139.17     │
├────────────┼────────────┤
│ 2022-10-13 │ 138.74     │
├────────────┼────────────┤
│ 2022-10-14 │ 138.58     │
├────────────┼────────────┤
│ 2022-10-17 │ 138.21     │
├────────────┼────────────┤
│ 2022-10-18 │ 138.13     │
└────────────┴────────────┘
Explainability DataFrame
component   close_target_lag-14  close_target_lag-13  close_target_lag-12  close_target_lag-11  close_target_lag-10  ...  close_target_lag-5  close_target_lag-4  close_target_lag-3  close_target_lag-2  close_target_lag-1
date                                                                                                                 ...                                                                                                    
2019-10-28            -0.441323             2.189853             0.866423            -5.543255             7.231418  ...            1.179480           -4.927667           -0.681262           -0.296650          -61.627247
2019-10-29            -0.436999             2.164734             0.846325            -5.550523             7.246673  ...            1.181950           -4.867683           -0.680222           -0.293241          -61.037983
2019-10-30            -0.431968             2.114494             0.847441            -5.562280             7.273024  ...            1.167492           -4.860231           -0.672423           -0.290435          -62.412132
2019-10-31            -0.421905             2.117286             0.849248            -5.582587             7.247783  ...            1.165696           -4.804346           -0.666002           -0.296979          -62.419296
2019-11-01            -0.422464             2.121800             0.852368            -5.563135             7.216440  ...            1.152226           -4.758334           -0.680976           -0.297013          -61.107170
...                         ...                  ...                  ...                  ...                  ...  ...                 ...                 ...                 ...                 ...                 ...
2022-10-05             0.191823            -0.894855            -0.407228             2.823210            -3.281263  ...           -0.431748            1.219016            0.123618            0.073972           18.965855
2022-10-06             0.180840            -1.018976            -0.439017             2.551305            -3.172533  ...           -0.299563            0.900095            0.167811            0.090559           19.252125
2022-10-07             0.205700            -1.098439            -0.397244             2.467510            -2.916240  ...           -0.222695            1.216781            0.205765            0.091922           18.326481
2022-10-10             0.221616            -0.994021            -0.384371             2.269992            -2.953964  ...           -0.299025            1.488759            0.208884            0.087514           13.230668
2022-10-11             0.200702            -0.961841            -0.354026             2.299065            -3.063802  ...           -0.364579            1.511112            0.198798            0.063247           13.545579

[772 rows x 14 columns]
```

Not sure how useful that is but its possible now.

**Comment by jmaslek** [comment]
> @jmaslek @colin99d `Regr` and `Linregr` now have a new argparse that will allow users to print out the raw explainability dataframe
> 
> `--explainability-raw Prints out a raw dataframe showing explainability results. (default: False)`
> 
> ```
> 2022 Oct 13, 08:57 (🦋) /forecast/ $ regr  20221012_134433_AAPL --explainability-raw
> Predicting Regression for 5 days
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 115/115 [00:00<00:00, 137.09it/s]
> Regression model obtains MAPE: 3.75% 
> 
> 
> 
>    Actual price: 138.98    
> ┏━━━━━━━━━━━━┳━━━━━━━━━━━━┓
> ┃ Datetime   ┃ Prediction ┃
> ┡━━━━━━━━━━━━╇━━━━━━━━━━━━┩
> │ 2022-10-12 │ 139.17     │
> ├────────────┼────────────┤
> │ 2022-10-13 │ 138.74     │
> ├────────────┼────────────┤
> │ 2022-10-14 │ 138.58     │
> ├────────────┼────────────┤
> │ 2022-10-17 │ 138.21     │
> ├────────────┼────────────┤
> │ 2022-10-18 │ 138.13     │
> └────────────┴────────────┘
> Explainability DataFrame
> component   close_target_lag-14  close_target_lag-13  close_target_lag-12  close_target_lag-11  close_target_lag-10  ...  close_target_lag-5  close_target_lag-4  close_target_lag-3  close_target_lag-2  close_target_lag-1
> date                                                                                                                 ...                                                                                                    
> 2019-10-28            -0.441323             2.189853             0.866423            -5.543255             7.231418  ...            1.179480           -4.927667           -0.681262           -0.296650          -61.627247
> 2019-10-29            -0.436999             2.164734             0.846325            -5.550523             7.246673  ...            1.181950           -4.867683           -0.680222           -0.293241          -61.037983
> 2019-10-30            -0.431968             2.114494             0.847441            -5.562280             7.273024  ...            1.167492           -4.860231           -0.672423           -0.290435          -62.412132
> 2019-10-31            -0.421905             2.117286             0.849248            -5.582587             7.247783  ...            1.165696           -4.804346           -0.666002           -0.296979          -62.419296
> 2019-11-01            -0.422464             2.121800             0.852368            -5.563135             7.216440  ...            1.152226           -4.758334           -0.680976           -0.297013          -61.107170
> ...                         ...                  ...                  ...                  ...                  ...  ...                 ...                 ...                 ...                 ...                 ...
> 2022-10-05             0.191823            -0.894855            -0.407228             2.823210            -3.281263  ...           -0.431748            1.219016            0.123618            0.073972           18.965855
> 2022-10-06             0.180840            -1.018976            -0.439017             2.551305            -3.172533  ...           -0.299563            0.900095            0.167811            0.090559           19.252125
> 2022-10-07             0.205700            -1.098439            -0.397244             2.467510            -2.916240  ...           -0.222695            1.216781            0.205765            0.091922           18.326481
> 2022-10-10             0.221616            -0.994021            -0.384371             2.269992            -2.953964  ...           -0.299025            1.488759            0.208884            0.087514           13.230668
> 2022-10-11             0.200702            -0.961841            -0.354026             2.299065            -3.063802  ...           -0.364579            1.511112            0.198798            0.063247           13.545579
> 
> [772 rows x 14 columns]
> ```
> 
> Not sure how useful that is but its possible now.

thats alot of text on screen.  Maybe we dont do that and just offer a special export for that,

**Comment by martinb-bb** [comment]
@jmaslek How do you want to export? to a csv?

**Comment by jmaslek** [comment]
> @jmaslek will a csv suffice?

yeah.  or xlsx/whatever we already do through export

**Comment by martinb-bb** [comment]
@jmaslek It will now auto export to csv when user wants to see raw. Only csv since there are so many datapoints. 
image

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
