### PR TITLE
#2684 [CT] Improve stocks/sia error handling, abstract duplicate code

### LINKED ISSUE #2684: [Bug] /Stocks/SIA - load function doesn't work. Error: 'NoneType' object is not subscriptable
Recreate by entering the menu with no stock loaded, then load a ticker from any source. 

Screen Shot 2022-09-30 at 8 16 50 PM

### PR DESCRIPTION
**Pull request by catalintoma**
# Description

- [x] Improve error message when YF doesn't return needed data, abstract duplicate code
- [x] Fixes #2684 

# How has this been tested?

- [x] Extended unit tests

# Checklist:

- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by colin99d** [comment]
Nice work!! Also thanks for adding tests as well!

**Review by colin99d — APPROVED** [review]

**Comment by colin99d** [comment]
Once tests and linters are good I can merge. Let me know if you need any help.

**Comment by catalintoma** [comment]
> 

I noticed this step failed quit fast
Tests / Base Tests - Ubuntu-latest - Python 3.9 (pull_request) 

Also wanted to ask if there is any way the linter (other tooling?) detect duplicate code? I think on this controller there were around 40 lines of code duplicated!

If it's not something extremely hard, I would raise an improvement issue for this, I noticed this "code smell" in many places

**Comment by colin99d** [comment]
Hmm weird. It looks like Github actions is failing. I will try to run again later.

**Comment by colin99d** [comment]
Also, I believe pylint can be configured to check for code duplication. But when I last used it, we got way too many false positives.

**Comment by catalintoma** [comment]
@colin99d can you kick the CI again? Seems like one still failed

**Comment by colin99d** [comment]
https://github.com/actions/checkout/issues/944

Something in our CI is broken, but its not our fault. I am downgrading the version we use and then tests should run.

**Pull request merged**
