### PR TITLE
Stock menu refactoring for easier API usage

### PR DESCRIPTION
**Pull request by northern-64bit**
# Description

This pr refactors the stocks menu for easier use of the api and is a part of the general API upgrade in combination of #2097 (and more future prs).

# How has this been tested?

Will be tested soon

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by minhhoang1023** [comment]
I'm reviewing it. will leave some comments.

Noticed that there are some commands in the stocks menu that's not yet refactored yet, such as `candle` or `display_news`

**Comment by minhhoang1023** [comment]
- `bullbear`, `get_dd` command still have the `ticker` argument name.

image

image

**Comment by northern-64bit** [comment]
> * `bullbear`, `get_dd`, `headlines` command still have the `ticker` argument name.

Will do, missed these since they were in the common file directory and not in the stocks directory

**Comment by minhhoang1023** [comment]
@northern-64bit Excellent work! This is a beast of a PR 🚀 ✨ 

Some commands are missing default arguments, and some have not yet been refactored. I'm leaving it below.

- `api.stocks.ba.mentions`, `api.stocks.ba.sentiment`, `api.stocks.ba.watchlist`, `api.stocks.ba.trend` missing default value arguments
image

image

image

- `api.stocks.candle` and `api.stocks.display_news` are not yet refactored. Can you have a look?

**Comment by JerBouma** [comment]
@montezdesousa Can you take this one over and merge it in? Discussed with @Chavithra and @minhhoang1023.

**Pull request merged**
