### PR TITLE
Improve economy menu

### PR DESCRIPTION
**Pull request by DidierRLopes**
I have refactored a bit economy menu, waiting for feedback.

### CODE REVIEW

**Comment by JerBouma** [comment]
Was already wondering when you would do this, will have a look tomorrow :)

**Comment by DidierRLopes** [comment]
> Was already wondering when you would do this, will have a look tomorrow :)

Had a lot to catchup this week, but managed to have some time for this today! 😄 It wasn't as big of a change as I thought it would be as well tbf!

**Comment by DidierRLopes** [comment]
Also, nvm the tests, I'll fix them after we agree on some layout for the menu :)

**Comment by JerBouma** [comment]
Think you want this on the same line (and a maximum amount of options to prevent overflowing):
```
│ Stored datasets:                                                                                                                                                                     │
│   macro    : United_States_CPI                                                                                                                                                       │
│   macro    : United_States_GDP                                                                                                                                                       │
│   macro    : United_States_RGDP                                                                                                                                                      │
│                                     
```
What if I want to plot GDP and S&P 500 together in an instant, can we give the ability to allow for that without needing to call both `macro` and `index` first? That was my initial idea with `--store` (and helps within a .openbb script). I get that `--store` is undesired though.

**Idea**: you can also plot data directly from the `plot` command if you correctly enter the stored dataset names. E.g. let's say I want to see the CPI of United States and the index of S&P 500. I know that `macro`'s database name is `United_States_CPI` and I know that the index name is `sp500` so I input this into `plot` and it automatically recognises where it needs to get the data from. Bit advanced, but we can expand on that in the guide so it makes sense to all and in due time allow for auto-filing.

**Comment by DidierRLopes** [comment]
> Think you want this on the same line (and a maximum amount of options to prevent overflowing):
> 
> ```
> │ Stored datasets:                                                                                                                                                                     │
> │   macro    : United_States_CPI                                                                                                                                                       │
> │   macro    : United_States_GDP                                                                                                                                                       │
> │   macro    : United_States_RGDP                                                                                                                                                      │
> │                                     
> ```
> 
> What if I want to plot GDP and S&P 500 together in an instant, can we give the ability to allow for that without needing to call both `macro` and `index` first? That was my initial idea with `--store` (and helps within a .openbb script). I get that `--store` is undesired though.
> 
> **Idea**: you can also plot data directly from the `plot` command if you correctly enter the stored dataset names. E.g. let's say I want to see the CPI of United States and the index of S&P 500. I know that `macro`'s database name is `United_States_CPI` and I know that the index name is `sp500` so I input this into `plot` and it automatically recognises where it needs to get the data from. Bit advanced, but we can expand on that in the guide so it makes sense to all and in due time allow for auto-filing.

I was thinking that that is fine, what you are doing is just adding more data to the ram so you have a faster access to it.

I don't understand what you meant around the plotting question!

**Comment by JerBouma** [comment]
What I am looking for is the ability to plot data without needing to plot it first with the other functions, e.g. `macro`, `fred`, `index`. Right now, I first need to use those commands (and get two separate plots) before I can combine a graph with`macro` and `fred` data. That is kinda annoying.

Ideally, you want to plot both without needing to run the commands separately first. E.g. I say `plot --y1 United_States_CPI --y2 sp500` and it figures out the data comes from `macro` and `index`.

**Comment by DidierRLopes** [comment]
> What I am looking for is the ability to plot data without needing to plot it first with the other functions, e.g. `macro`, `fred`, `index`. Right now, I first need to use those commands (and get two separate plots) before I can combine a graph with`macro` and `fred` data. That is kinda annoying.
> 
> Ideally, you want to plot both without needing to run the commands separately first. E.g. I say `plot --y1 United_States_CPI --y2 sp500` and it figures out the data comes from `macro` and `index`.

But that is a different feature than what we have right now?

**Comment by JerBouma** [comment]
Think it might be good as it is right now and we can create a PR later with more features? Then we can also start writing Guides on the menu.

**Comment by JerBouma** [comment]
Oui oui!

**Comment by DidierRLopes** [comment]
Stamp? 😄 

Do we want to create tickets for the tasks to improve this?

**Review by JerBouma — APPROVED** [review]

**Pull request merged**
