### PR TITLE
Adding to v4

### PR DESCRIPTION
**Pull request by jmaslek**
Cleaning up whatever I run into.  

added futures extension with yf

### CODE REVIEW

**Review by IgorWounds — APPROVED** [review]
Looks great!

**Comment by deeleeramone** [comment]
How do I load a specific contract, i.e., not the continuous front month?

**Comment by jmaslek** [comment]
> How do I load a specific contract, i.e., not the continuous front month?

Same exact way you would in the current terminal

**Comment by jmaslek** [comment]
@IgorWounds don't merge yet. Going to add the other commands from the current terminal while I'm at it

**Comment by deeleeramone** [comment]
> Same exact way you would in the current terminal

Am I missing something here?  `=F` on every symbol breaks that possibility.

Screenshot 2023-08-13 at 6 50 27 PM

**Comment by jmaslek** [comment]
Exactly. Same functionality as the current terminal.

**Comment by deeleeramone** [comment]
> Exactly. Same functionality as the current terminal.

So not the same?

Screenshot 2023-08-13 at 7 36 18 PM

Screenshot 2023-08-13 at 7 37 03 PM

**Comment by jmaslek** [comment]
Fuck me. I can't read

**Comment by deeleeramone** [comment]
While we're circling this wagon,  I propose, `--expiry`, become, `--expiration`, to be consistent with the options naming.

**Comment by jmaslek** [comment]
@deeleeramone 
```
>>> sdk.futures.load("GC", expiration="2024-04")
OBBject

id: 064da66e-f2ef-76f8-8000-781e63a2a17c
results: [{'date': datetime.datetime(2023, 8, 7, 0, 0), 'open': 2017.5, 'high': 2019.300048828125, 'low': 2006.199951171875, 'close': 2009.9000244140625, 'volume': 309.0}, {'date': datetime.datetime(2023, 8, 8, 0, 0), 'open': 2010.800048828125, 'high': 2010.800048828125, 'low': 1996.5, 'close': 1999.699951171875, 'volume': 384.0}, {'date': datetime.datetime(2023, 8, 9, 0, 0), 'open': 2003.9000244140625, 'high': 2004.4000244140625, 'low': 1987.5, 'close': 1990.0999755859375, 'volume': 496.0}, {'date': datetime.datetime(2023, 8, 10, 0, 0), 'open': 1988.300048828125, 'high': 2002.699951171875, 'low': 1985.0, 'close': 1988.199951171875, 'volume': 742.0}, {'date': datetime.datetime(2023, 8, 11, 0, 0), 'open': 1986.9000244140625, 'high': 1991.5, 'low': 1984.0, 'close': 1985.800048828125, 'volume': 742.0}]
```

**Pull request merged**
