### PR TITLE
News from feedparser + Binance API key check fix

### PR DESCRIPTION
**Pull request by DidierRLopes**
image

Missing documentation, let me know if you like it! 👍🏽

### CODE REVIEW

**Comment by jmaslek** [comment]
`load aapl/news`

```
> Wed, 27 Jul 2022 20:31:00 GMT - Apple Inc. stock rises Wednesday, still underperforms market - MarketWatch
https://www.marketwatch.com/story/apple-inc-stock-rises-wednesday-still-underperforms-market-01658953916-a3a605a9db79

> Thu, 28 Jul 2022 13:57:27 GMT - Apple Stock Surge Raises Stakes as Earnings Loom - Bloomberg
https://www.bloomberg.com/news/articles/2022-07-28/apple-stock-surge-raises-stakes-as-earnings-loom-tech-watch

> Thu, 28 Jul 2022 14:12:00 GMT - Apple's privacy changes, TikTok competition inescapable for Meta, for now - Reuters
https://www.reuters.com/technology/apples-privacy-changes-tiktok-competition-inescapable-meta-now-2022-07-28/

> Thu, 28 Jul 2022 01:37:33 GMT - Apple Q3 FY2022 Earnings Report Preview: What to Look For - Investopedia
https://www.investopedia.com/apple-q3-fy2022-earnings-report-preview-6281130

> Mon, 25 Jul 2022 22:08:04 GMT - Steve Jobs' original Apple 1 computer prototype up for auction - Fox Business
https://www.foxbusiness.com/lifestyle/steve-jobs-original-apple-1-computer-prototype-auction
```

Not in order of date?

**Comment by jmaslek** [comment]
news -h not updated :P

```
usage: news [--article ARTICLE [ARTICLE ...]] [-h] [--export EXPORT] [-l LIMIT] [--source {feedparser,newsapi}]

Prints latest news about company, including date, title and web link. [News API]

options:
  --article ARTICLE [ARTICLE ...]
                        stocks/NEWS_data
  -h, --help            show this help message
  --export EXPORT       Export raw data into csv, json, xlsx
  -l LIMIT, --limit LIMIT
                        Number of entries to show in data.
  --source {feedparser,newsapi}
                        Data source to select from

For more information and examples, use 'about news' to access the related guide.
`

**Comment by DidierRLopes** [comment]
> `load aapl/news`
> 
> ```
> > Wed, 27 Jul 2022 20:31:00 GMT - Apple Inc. stock rises Wednesday, still underperforms market - MarketWatch
> https://www.marketwatch.com/story/apple-inc-stock-rises-wednesday-still-underperforms-market-01658953916-a3a605a9db79
> 
> > Thu, 28 Jul 2022 13:57:27 GMT - Apple Stock Surge Raises Stakes as Earnings Loom - Bloomberg
> https://www.bloomberg.com/news/articles/2022-07-28/apple-stock-surge-raises-stakes-as-earnings-loom-tech-watch
> 
> > Thu, 28 Jul 2022 14:12:00 GMT - Apple's privacy changes, TikTok competition inescapable for Meta, for now - Reuters
> https://www.reuters.com/technology/apples-privacy-changes-tiktok-competition-inescapable-meta-now-2022-07-28/
> 
> > Thu, 28 Jul 2022 01:37:33 GMT - Apple Q3 FY2022 Earnings Report Preview: What to Look For - Investopedia
> https://www.investopedia.com/apple-q3-fy2022-earnings-report-preview-6281130
> 
> > Mon, 25 Jul 2022 22:08:04 GMT - Steve Jobs' original Apple 1 computer prototype up for auction - Fox Business
> https://www.foxbusiness.com/lifestyle/steve-jobs-original-apple-1-computer-prototype-auction
> ```
> 
> Not in order of date?

It doesn't has order of data, but we are only grabbing data from past 24 hours. So thought it wouldn't matter much. Thoughts?

**Comment by DidierRLopes** [comment]
@jmaslek wth is going on here?

**Comment by jmaslek** [comment]
> It doesn't has order of data, but we are only grabbing data from past 24 hours. So thought it wouldn't matter much. Thoughts?

That screenshot has articles from 3 different days so kinda confusing.  Sorting would be ideal to get newer first, but if its not possible atm, or you don't have time, is fine for now.

**Comment by jmaslek** [comment]
> @jmaslek wth is going on here?

you fucked it up 😅

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
