### PR TITLE
Docs   part 2

### PR DESCRIPTION
**Pull request by andrewkenreich**
Final Docs fixin

### CODE REVIEW

**Comment by andrewkenreich** [comment]
fixes stocks.* issues on disc - fa, ba and a few others
Fixes some PO stuff

**Comment by JerBouma** [comment]
Fixed docker link, fixed some broken links.

**Comment by andrewkenreich** [comment]
We need to update all installation files with the proper links

**Review by Chavithra — APPROVED** [review]
Looks ok to me.

**Pull request merged**
