### PR TITLE
removing explicit `statsforecast` version from conda and fixing numpy

### PR DESCRIPTION
**Pull request by martinb-bb**
# Description

No need to set it. Darts now checks for the latest (1.2.0)

### CODE REVIEW

**Comment by martinb-bb** [comment]
@simmonsj330 We can use this PR to test upgrading numpy with installer as well.

**Comment by martinb-bb** [comment]
to test new env:

```
conda env create -n pr_test --file build/conda/conda-3-9-env-full.yaml
conda activate pr_test
poetry install -E prediction
```

**Comment by simmonsj330** [comment]
@martinb-bb it do be werking 
Screen Shot 2022-11-03 at 4 38 07 PM

**Review by simmonsj330 — APPROVED** [review]

**Comment by simmonsj330** [comment]
After updating numpy, the installer seems to be working
Screen Shot 2022-11-03 at 5 50 41 PM

**Comment by martinb-bb** [comment]
@simmonsj330 Conda now working nicely. :) Please let me know if you are ready to merge!

**Comment by martinb-bb** [comment]
@simmonsj330  Shall we update the requirements too?

**Pull request merged**
