### PR TITLE
Seprate Intrinio financials data tags into a different command

### PR DESCRIPTION
**Pull request by the-praxs**
# Changelog

- [x] Removes calculated data from provider models.
- [x] Removes the `symbol` and `cik` fields in the provider models.
- [x] Adds `ebit` field in income statement standard model.
- [x] Adds `ebit`, `ebitda` and `ebitda_margin` fields in the `equity/fundamentals/income`
- [x] Sets `symbol`, and `cik` as `Optional` fields in the financial statements standard models.
- [x] Sets `period` as a required field in the financial statements standard models.
- [x] Corrects field names in `equity/fundamentals/balance`.
- [x] Adds `search_financial_attributes` command under `equity.fundamentals` to search for the data tags.
- [x] Adds `financial_attributes` command under `equity.fundamentals` to fetch values for the data tags.
- [x] Adds tests for the new commands.
- [x] Cleans `descriptions.py`.
- [x] Add `"provider": "fmp"` to `equity.fundamental.multiples` test functions.

### CODE REVIEW

**Comment by deeleeramone** [comment]
The commas, slashes, other characters, and trailing white space in the fields may have unintended consequences:

from: `obb.equity.fundamental.income("AAPL", provider="intrinio")`

```
'total other income / (expense), net'
'weighted average basic & diluted shares outstanding'
'total pre-tax income '
```

**Comment by the-praxs** [comment]
> The commas, slashes, other characters, and trailing white space in the fields may have unintended consequences:
> 
> from: `obb.equity.fundamental.income("AAPL", provider="intrinio")`
> 
> ```
> 'total other income / (expense), net'
> 'weighted average basic & diluted shares outstanding'
> 'total pre-tax income '
> ```
> 
> The calculations data should be split between other functions, `ratios`, `growth`, and maybe `metrics`. I know they are all packed into the same response, so if they must go to only one endpoint `metrics` might make the most sense.

I can fix the trailing white space but the other characters are part of the field name as returned by Intrinio. Do let me know if you have any solution for it.

Calculations data is merely to get values of the data tags that Minh wants. There's another function being added to allow searching for data tags and get its value, exclusive to Intrinio.

**Review by IgorWounds — APPROVED** [review]

**Review by jmaslek — CHANGES_REQUESTED** [review]
I get errors it seems when something is not able to get a result?

i.e
`obb.equity.fundamental.financial_attributes("AAPL", tag="roa", start_date="2001-01-01")`

**Comment by the-praxs** [comment]
> I get errors it seems when something is not able to get a result?
> 
> i.e `obb.equity.fundamental.financial_attributes("AAPL", tag="roa", start_date="2001-01-01")`

Fixed!

**Comment by jmaslek** [comment]
>  Adds ebit, ebitda and ebitda_margin fields in the equity/fundamentals/income

Screenshot 2023-11-14 at 4 51 39 PM

**Review by jmaslek — APPROVED** [review]

**Comment by the-praxs** [comment]
> > Adds ebit, ebitda and ebitda_margin fields in the equity/fundamentals/income
> 
> Screenshot 2023-11-14 at 4 51 39 PM

`provider="intrinio"`

**Pull request merged**
