### PR TITLE
chore: fix interval bug in the pynb

### PR DESCRIPTION
**Pull request by jzhao62**
# Pull Request Template for OpenBB Developers

fixing week interval in the copper-gold ratio demo

### CODE REVIEW

**Comment by deeleeramone** [comment]
Hi! Thanks for the contribution, we appreciate that. In order to merge to the repo, the branch naming conventions are required. Please rename your branch, as `bugfix/fix-demo-bugs`, to allow for this.

Thanks!

**Comment by piiq** [comment]
@luqmanbello how hard would it be to disable branch naming rules for PRs coming from forks?

@jzhao62 can you please sign the CLA? Use the links from the comment of the CLA bot. It's just 3 clicks. We'll handle the merge after that

> [CLA assistant check](https://cla-assistant.io/OpenBB-finance/OpenBBTerminal?pullRequest=6435) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/OpenBB-finance/OpenBBTerminal?pullRequest=6435) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ deeleeramone❌ jzhao62You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenBB-finance/OpenBBTerminal?pullRequest=6435) it.

**Comment by luqmanbello** [comment]
> @luqmanbello how hard would it be to disable branch naming rules for PRs coming from forks?
> 
@piiq I would look into it.

**Comment by hjoaquim** [comment]
@luqmanbello did you find a way to allow or bypass external contributor's PRs?

**Comment by luqmanbello** [comment]
> @luqmanbello did you find a way to allow or bypass external contributor's PRs?

You can merge this PR even if that test fails. it is not one of the requirements.

**Comment by hjoaquim** [comment]
thank you @jzhao62! I hope this was the first of many!

**Comment by hjoaquim** [comment]
Pushed a small fix for correct date time conversion here: https://github.com/OpenBB-finance/OpenBBTerminal/pull/6435/commits/6cdf910a5e024b60b9f01c19bbf02975e634229e
cc @deeleeramone @jzhao62

**Review by hjoaquim — APPROVED** [review]

**Pull request merged**
