### PR TITLE
Big Fix: 2815. Updated if condition that was raising exception

### PR DESCRIPTION
**Pull request by 0xDareDevil**
# Description

- Fixes [Crypto: find -h - Error: 'NoneType' object has no attribute 'coin'](https://github.com/OpenBB-finance/OpenBBTerminal/issues/2815#top)

# How has this been tested?

- Tested manually with different scenarios.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by colin99d** [comment]
Thank you so much for this!! Let me review it!

**Comment by colin99d** [comment]
Screen Shot 2022-10-13 at 3 48 52 PM
I am still getting this bug.

**Comment by colin99d** [comment]
Screen Shot 2022-10-13 at 3 49 20 PM
Here is the full stack trace

**Comment by 0xDareDevil** [comment]
let me check

**Review by DidierRLopes — APPROVED** [review]

**Comment by 0xDareDevil** [comment]
@colin99d Updated the code to fix the error

**Comment by 0xDareDevil** [comment]
> Screen Shot 2022-10-13 at 3 48 52 PM
> 
> I am still getting this bug.

Fixed this

**Review by colin99d — APPROVED** [review]
Looks good to me!

**Comment by 0xDareDevil** [comment]
> Looks good to me!

@colin99d Uh oh.. I think the formatting wasn't needed, as the `coin` variable is required in other `else if` conditions.. check here in image below on line 908, 918 and 934 where `coin` is needed and will raise error as it isn't defined if we use formatting..

image

**Comment by colin99d** [comment]
Thats my bad, good catch!

**Pull request merged**
