### PR TITLE
Fixes some James bugs

### LINKED ISSUE #2952: [Bug]stocks/gov/contracts shows warning
with aapl loaded:

```
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────── OpenBB Terminal v1.9.1 (https://openbb.co) ─╯
2022 Oct 20, 19:09 (🦋) /stocks/gov/ $ contracts
/Users/james/OpenBBTerminal/OpenBBTerminal/openbb_terminal/stocks/government/quiverquant_view.py:426: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_contracts.groupby("Date").sum().div(1000).plot(kind="bar", rot=0, ax=ax)
```

### LINKED ISSUE #2959: [Bug] stocks/dd/suppliers no data returned
title.  For reference, load aapl and see no suppliers, but they are listed here : https://csimarket.com/stocks/competition2.php?supply&code=AAPL

(cough downside of scraping cough)

### LINKED ISSUE #2960: [Bug] stocks/bt/rsi warning
as per usual, aapl loaded
```
2022 Oct 20, 20:15 (🦋) /stocks/bt/ $ rsi
/Users/james/miniconda3/envs/obb/lib/python3.9/site-packages/future/utils/__init__.py:312: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  return func(**kwargs)
/Users/james/miniconda3/envs/obb/lib/python3.9/site-packages/future/utils/__init__.py:312: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  return func(**kwargs)
```

### LINKED ISSUE #2965: [Bug] stocks/ta/vwap bad argument
load ionq -i 1
```
2022 Oct 20, 20:31 (🦋) /stocks/ta/ $ vwap
Error: view_vwap() got an unexpected keyword argument 's_interval'
```

### LINKED ISSUE #2967: [Bug] stocks/qa/beta off with intraday data
from stocks/qa:
```
load aapl -i 1
pick returns
beta

Loading Daily SPY stock with starting period 2019-10-17 for analysis.
Error: Inputs must not be empty.
```

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Fixes #2952 
Fixes #2965 
Fixes #2960
Fixes #2967 
Fixes #2959 

This PR fixes a several bugs, and also increases the overall quality of the codebase. Some of the quality improvements include making `supplier` and `customer` output much better, moving some `qa_controller` code into a model, and allowing the `qa/beta` command to work with intervals besides 1440.

# How has this been tested?

- [x] Make sure affected commands still run in terminal
    - `python terminal.py stocks/load aapl/gov/contracts` 
    - `python terminal.py "stocks/load ionq -i 1/ta/vwap" --debug`
    - `python terminal.py stocks/load aapl/bt/rsi`
    - `python terminal.py "stocks/load aapl -i 1/qa/pick returns/beta" --debug`
    - `python terminal.py "stocks/load aapl/qa/pick returns/beta" --debug`
    - `python terminal.py "stocks/load aapl -w/qa/pick returns/beta" --debug`
    - `python terminal.py stocks/load aapl/dd/supplier`
    - `python terminal.py stocks/load aapl/dd/customer`
- [x] Ensure the SDK still works
    - Did not test `bt` because it is not on the SDK
    - Did not test `beta` because it is not on the SDK
    - `openbb.stocks.dd.supplier("TSLA")` 
    - `openbb.stocks.dd.supplier("TSLA", chart=True)` 
    - `openbb.stocks.dd.customer("TSLA")`
    - `openbb.stocks.dd.customer("TSLA", chart=True)` 
    - `openbb.stocks.gov.contracts("AAPL")`
- [x] Check any related reports
    - `python terminal.py reports/equity gme` failed for me, I believe #2878 fixes this, but this issue also appears on the main branch so I am confident that this PR does not create it.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
gov:
```
2022 Oct 21, 08:11 (🦋) /stocks/gov/ $ contracts

2022 Oct 21, 08:11 (🦋) /stocks/gov/ $
```

**Comment by jmaslek** [comment]
vwap
Screen Shot 2022-10-21 at 8 13 27 AM

**Comment by jmaslek** [comment]
rsi:
```
2022 Oct 21, 08:14 (🦋) /stocks/bt/ $ rsi

2022 Oct 21, 08:14 (🦋) /stocks/bt/ $
```

**Comment by jmaslek** [comment]
1 minute beta
Screen Shot 2022-10-21 at 8 15 50 AM

**Comment by jmaslek** [comment]
Suppliers:
```
2022 Oct 21, 08:16 (🦋) /stocks/dd/ $ supplier
List of suppliers: Company Name, Revenue, Net Income, Net Margin, Cash Flow


                                              Suppliers for AAPL                                              
┏━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃      ┃ Company Name                                       ┃ Revenue  ┃ Net Income ┃ Net Margin ┃ Cash Flow ┃
┡━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ AAPL │ Apple Inc.                                         │ 82959.00 │ 19442.00   │ 23.44 %    │ -319.00   │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
│ SONY │ Sony Group Corporation                             │ 72597.32 │ 6500.61    │ 8.95 %     │ 2460.41   │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
│ PKX  │ Posco Holdings Inc                                 │ 70688.56 │ 6673.66    │ 9.44 %     │ 0.00      │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
│ TSM  │ Taiwan Semiconductor Manufacturing Company Limited │ 57224.80 │ 21372.80   │ 37.35 %    │ 23798.50  │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
│ LPL  │ Lg Display Co Ltd                                  │ 27786.58 │ 1240.20    │ 4.46 %     │ 3922.83   │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
│ DOW  │ Dow Inc.                                           │ 15664.00 │ 1681.00    │ 10.73 %    │ -738.00   │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
│ INTC │ Intel Corporation                                  │ 15321.00 │ -454.00    │ -          │ -1825.00  │
├──────┼────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼───────────┤
```

**Comment by colin99d** [comment]
> 1 minute beta Screen Shot 2022-10-21 at 8 15 50 AM

Is there an issue here?

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
