### PR TITLE
hotfix / improve autoscaling/dynamic loading, fix forex candle charts, equity reports

### LINKED ISSUE #5151: [Bug] Large Decimal values display with commas in tables.
This screenshot is from `/crypto/load btc/forecast/tcn`, but have also seen this from Crypto menu commands.

Screenshot 2023-06-19 at 9 39 36 AM

### LINKED ISSUE #5171: [Bug] `forex/candle`: Chart messes up after warning dialogue for too much data pops up.
`/forex/load JPYUSD --interval 1min --start 2023-06-21`

Any source will do it.

Screenshot 2023-06-22 at 11 34 54 AM

Screenshot 2023-06-22 at 11 29 53 AM

### LINKED ISSUE #5179: `forex/candle` - Data and the timestamps are wrong.
There's several problems here that all compound to make this data unusable, regardless of any source.

- The three methods of exporting (load --export, export from chart, export from raw data table) all export different things.
- The chart doesn't display the data properly and chops off the head of the dataframe.
- The chart only displays an x-axis between 9:30 and 4:00 when it is 24-hour data.
- The TZ info is "localized" (maybe?) on the chart but the raw data remains in UTC, so what time is it really and why is 03:47 the first row of exported data when exporting the file from the chart directly? 

Correct:
```
load USDJPY --interval 1min --start 2023-06-23 --source Polygon --export csv
```

Screenshot 2023-06-23 at 1 31 15 PM

Screenshot 2023-06-23 at 1 26 09 PM

But when you do `candle --raw` and export the file from the table, the timestamp is scrubbed from the index and renders the export useless:

Incorrect:

```
load USDJPY --interval 1min --start 2023-06-23 --source Polygon/candle --raw
```

The first row from the table is also missing from the exported file.

Screenshot 2023-06-23 at 1 34 31 PM

The chart only goes between 9:30 AM and 4PM (FX markets operate 24/7 x 5 days a week, so this makes absolutely no sense), and then exporting the raw data from the chart makes things worse by chopping off the head of the dataframe.

Screenshot 2023-06-23 at 1 37 18 PM

It might be displaying "09:30", but is that UTC time?

Screenshot 2023-06-23 at 1 58 54 PM

The first entry of the exported file (from the chart button) is at 03:47 instead of 00:00.

Screenshot 2023-06-23 at 1 46 02 PM

### LINKED ISSUE #5182: [Bug] `crypto/load eth/qa/quantile/load btc/quantile`: Title and labels change, but data does not.
Recreate with:

```
crypto/load eth/qa/quantile/load btc/quantile
```

Screenshot 2023-06-25 at 8 23 15 AM

### LINKED ISSUE #5187: [Bug] `/stocks/candle --raw` - Filtering by date breaks the table
```
load IBM --start 1990-01-01
candle --raw
```

https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/608f9b16-800a-4ede-94b2-122ac10c508e

### PR DESCRIPTION
**Pull request by tehcoderer**
closes #5187 closes #5179 closes #5171 closes #5151 close #5182

### CODE REVIEW

**Comment by deeleeramone** [comment]
Pretty good edge case here, `load usdjpy --start 2023-06-23 --interval 5min --source Polygon`

Screenshot 2023-06-26 172043

**Comment by deeleeramone** [comment]
AlphaVantage:

image

**Comment by deeleeramone** [comment]
Great solution on cutting the gaps.

Screenshot 2023-06-28 at 12 32 15 PM

`/stocks/candle` localizes Forex data properly, but `/forex/candle` is in UTC.  Can the Forex menu work like the Stocks can?

Screenshot 2023-06-28 at 12 33 58 PM

**Comment by tehcoderer** [comment]
> Great solution on cutting the gaps.
> 
> Screenshot 2023-06-28 at 12 32 15 PM
> 
> `/stocks/candle` localizes Forex data properly, but `/forex/candle` is in UTC. Can the Forex menu work like the Stocks can?
> 
> Screenshot 2023-06-28 at 12 33 58 PM

doneeee

**Comment by deeleeramone** [comment]
it's been localized, but now the new data for today has stopped collecting. 

Screenshot 2023-06-28 at 6 58 18 PM

**Comment by deeleeramone** [comment]
Screenshot 2023-06-28 at 7 06 23 PM

**Comment by tehcoderer** [comment]
> Screenshot 2023-06-28 at 7 06 23 PM

???
image

**Comment by tehcoderer** [comment]
@deeleeramone figured it out, added a +1 day to end date since some sources use UTC date for query

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
