### PR TITLE
Creates examples folder for SDK Notebook examples

### PR DESCRIPTION
**Pull request by deeleeramone**
This commit creates a folder (examples) and README.md file for SDK examples as Jupyter Notebooks.  Notebook files to come in the next commit.

### CODE REVIEW

**Comment by deeleeramone** [comment]
Feedback, suggestions, requests, all welcome!

**Comment by DidierRLopes** [comment]
Nice work! Some comments:
* The loading notebook should show relying on multiple different data sources to show that as a user you can select your preferred data source easily.
* Styling - I would try to have the `fig.show()` on the same cell as the code, so that there's no spacing between them
* I would display less raw data and more images as that's more powerful visually. Perhaps instead of just displaying raw data you could also display histogram
* File names without space is better, it works better when using the auto-completer in a shell.
* The README can also have a brief TOC of what each notebook shows
* We can perhaps have a notebook that uses streamlit to show that users can create more powerful dashboards.

Apart form that this is looking great 👍🏽

**Comment by deeleeramone** [comment]
>     * The loading notebook should show relying on multiple different data sources to show that as a user you can select your preferred data source easily.

So this is probably a bug, but the SDK does not seem to follow the preferred data source that is defined by the user, and it's not an option under the Hub SDK page.

**Comment by jmaslek** [comment]
> > ```
> > * The loading notebook should show relying on multiple different data sources to show that as a user you can select your preferred data source easily.
> > ```
> 
> So this is probably not a bug, but the SDK does not seem to follow the preferred data source that is defined by the user, and it's not an option under the Hub SDK page.
> 
> Screenshot 2023-05-23 at 2 02 53 PM
> 
> I'll find a more diverse way of showing this that will bring in some more visual content at the same time.

Think the idea was to include some of the `source = 'ABC'` options

**Review by jmaslek — COMMENTED** [review]
in the volatility nb, you are killing me not plotting the different results :laugh:

**Comment by deeleeramone** [comment]
@DidierRLopes, I think I covered everything on your list, except for the Streamlit one.  I'll build something for that one over tonight and tomorrow.  @jmaslek, updated the realized vol, and others, with charts instead of too many tables.  Ready for another look over.

**Comment by DidierRLopes** [comment]
@deeleeramone this is a very nice improvement. Good work.

I will likely find a place for the Hub to showcase these 4 notebooks as examples :)

**Comment by jmaslek** [comment]
On the gold/copper nb, maybe change the load to be
```
openbb.futures.historical("GC", start_date="2000-01-01", end_date="2023-05-20")
```

to show there is more than stocks.load

**Comment by jmaslek** [comment]
Lets avoid bringing in the forecast module

Screenshot 2023-05-25 at 11 45 04 AM

**Comment by jmaslek** [comment]
hmm.  Github web doesnt show the charts:

Screenshot 2023-05-25 at 11 47 42 AM

**Comment by deeleeramone** [comment]
> Look at how it presents in my nb

You mean your code linters?

This is how it presents in Jupyter: 

Screenshot 2023-05-25 at 9 13 28 AM

**Comment by deeleeramone** [comment]
> On the gold/copper nb, maybe change the load to be
> 
> ```
> openbb.futures.historical("GC", start_date="2000-01-01", end_date="2023-05-20")
> ```
> 
> to show there is more than stocks.load

`openbb.futures.historical` does not include today, and it's not as friendly because the `end_date` is a required field. 

Screenshot 2023-05-25 at 9 26 56 AM

**Comment by deeleeramone** [comment]
> right in the ipynb with all the bells and whistles installed in vscode Screenshot 2023-05-25 at 12 18 19 PM

You have not selected a kernel for the notebook or ran any of the cells.  :P

**Comment by deeleeramone** [comment]
> Lets avoid bringing in the forecast module

Is there another SDK one-liner function that performs this task outside of the `forecast.plot()`? 

`qa.line()` does not have multiple inputs, the Econometrics and Economy `plot` commands from the Terminal do not have any direct entry points exposed to the SDK.

**Comment by jmaslek** [comment]
> > Lets avoid bringing in the forecast module
> 
> Is there another SDK one-liner function that performs this task outside of the `forecast.plot()`?
> 
> `qa.line()` does not have multiple inputs, the Econometrics and Economy `plot` commands from the Terminal do not have any direct entry points exposed to the SDK.

Just calling plotly directly

**Comment by jmaslek** [comment]
> > right in the ipynb with all the bells and whistles installed in vscode Screenshot 2023-05-25 at 12 18 19 PM
> 
> You have not selected a kernel for the notebook or ran any of the cells. :P

but the figure above shows completely

**Comment by deeleeramone** [comment]
>  Just calling plotly directly

The example before that does this, and I am illustrating that there is another method that is less code for building a new figure object from scratch.

`data.plot()` does this:

Screenshot 2023-05-25 at 10 18 17 AM

which I don't like.

**Comment by deeleeramone** [comment]
> > > right in the ipynb with all the bells and whistles installed in vscode Screenshot 2023-05-25 at 12 18 19 PM
> > 
> > 
> > You have not selected a kernel for the notebook or ran any of the cells. :P
> 
> but the figure above shows completely

It's rendered in the notebook already.  If you try to use any of the dataframes, they will return as not defined.

**Comment by the-praxs** [comment]
This looks fantastic @deeleeramone! I am awaiting your commit for streamlit, I want to understand and learn how you are working on it!

**Comment by deeleeramone** [comment]
> This looks fantastic @deeleeramone! I am awaiting your commit for streamlit, I want to understand and learn how you are working on it!

Turns out Streamlit needs to be served over its own localhost port, so there isn't much point of a Notebook example.  The examples that are accessible through the Terminal `/dashboards` is a good reference point to get started for now.

**Comment by DidierRLopes** [comment]
@jmaslek can we merge this soon? 

Want to add the page on the Hub, but want the links to point to our main repo instead of @deeleeramone branch

**Comment by jmaslek** [comment]
> @jmaslek can we merge this soon? 
> 
> 
> 
> Want to add the page on the Hub, but want the links to point to our main repo instead of @deeleeramone branch

Yeah. Ship it. My comments were just suggestions anyways

**Comment by DidierRLopes** [comment]
> > @jmaslek can we merge this soon?
> > Want to add the page on the Hub, but want the links to point to our main repo instead of @deeleeramone branch
> 
> Yeah. Ship it. My comments were just suggestions anyways

u are a suggestion.

We can iterate on feedback from here!

**Review by DidierRLopes — APPROVED** [review]

**Pull request merged**
