### PR TITLE
Poetry : remove optional dependencies + set papermill 2.4.0

### PR DESCRIPTION
**Pull request by Chavithra**
# Description

Here we update the content of these files:
- `pyproject.toml`
- `poetry.lock`

Change version:
```toml
papermill = "^2.4.0"
```

Removing the following optional element from `pyproject.toml`
```toml
[tool.poetry.dependencies]
kaleido = {version = "^0.2.1", optional = true}
```

### CODE REVIEW

**Comment by colin99d** [comment]
@martinb-bb don't we still need torch?

**Comment by martinb-bb** [comment]
Yes we need torch.

**Comment by Chavithra** [comment]
@martinb-bb @colin99d it's from optional not from the extras.

**Comment by colin99d** [comment]
> @martinb-bb @colin99d it's from optional not from the extras.
> 
> We still have `torch` here:
> 
> ```toml
> [tool.poetry.extras]
> prediction = ["torch"]
> ```

Yes, but if torch is just there then it doesnt know what version to grab.

**Comment by martinb-bb** [comment]
If you want to make changes to poetry, please check if making a new environment works and installer builds before removing. We cannot afford more issues for building forecasting. ☺️

**Comment by simmonsj330** [comment]
Also, pyinstaller **needs** to remain as is in `pyproject.toml` and as 4.10 or else the build system will not work.

**Comment by piiq** [comment]
@Chavithra, closing this one without merge to create a new one that solely changes papermill and removes kaleido?

**Review by colin99d — APPROVED** [review]

**Comment by martinb-bb** [comment]
Let me check forecast menu functionality with new env before we merge this please.

**Review by piiq — CHANGES_REQUESTED** [review]
don't forget to re-generate the requirements.txt files

**Pull request merged**
