### PR TITLE
Large Language Model - Text to command

### PR DESCRIPTION
**Pull request by minhhoang1023**
LlamaIndex is a “data framework” to help you build LLM applications. This library provides an advanced retrieval/query interface over your data: Feed in any LLM input prompt, get back retrieved context and knowledge-augmented output. 

In this case, we embed an entire database of help commands from the terminal. These help commands have all sub parameters, a short summary and also example usage.

When we provide a natural language question to `askobb`, we use `gpt-3.5-turbo` or `gpt-4` to query this data to provide us an answer in the form of a terminal command. 

`askobb -q what is the last price of the apple stock -m gpt-4` 
`Suggested command: stocks/quote -t AAPL`

Repo now works with latest `llama-index`
`pip install llama-index`

Important notes:
- This requires you to have a OpenAI API Key
- You can use either `gpt-3.5-turbo` as default, or switch to using `gpt-4` with the `-m` flag if your API key has access.

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by lewistham9x** [comment]
How do you generate the .txt files used in gpt_index? Is there code to generate it for other menus?

**Comment by minhhoang1023** [comment]
@lewistham9x Yes, I used the code to generate help text from arg parse. The menu I was adding them manually but we're creating a code to auto-generate this. Will share with you real soon 🚀

**Comment by minhhoang1023** [comment]
@lewistham9x In the meantime, I added the `generate_data.py` code. You can run this to generate the help text for other menus.

Simply run it as `python openbb_terminal/miscellaneous/gpt_index/generate_data.py`

**Comment by martinb-bb** [comment]
image
Weird logging issue. Cannot figure out why Forex is printing. Will remove this comment when fixed.

**Comment by martinb-bb** [comment]
image
 Working from ROOT of terminal with all 747 commands using `gpt-3.5-turbo`

**Comment by martinb-bb** [comment]
TODO: 

1. Poetry install package
2. refactor llama index library for latest ver

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
