### PR TITLE
Improved SEO of OpenBB Docs

### PR DESCRIPTION
**Pull request by jerryduluk**
Going through all Docs pages and optimizing SEO description and keywords, as well as other small typos and grammar.

### CODE REVIEW

**Comment by DidierRLopes** [comment]
This is what I get from opening FAQ of Installation and Updates from BOTH OpenBB SDK and OpenBB Terminal. Which makes it indistinguishable.

@jose-donato can we automate adding a SDK / Terminal / Bot tag? E.g. "Installation and Updates - Terminal | OpenBB Docs.

Or do we need to do it manually?

Screenshot 2023-04-22 at 6 09 50 PM

**Comment by jose-donato** [comment]
> This is what I get from opening FAQ of Installation and Updates from BOTH OpenBB SDK and OpenBB Terminal. Which makes it indistinguishable.
> 
> @jose-donato can we automate adding a SDK / Terminal / Bot tag? E.g. "Installation and Updates - Terminal | OpenBB Docs.
> 
> Or do we need to do it manually?
> 
> Screenshot 2023-04-22 at 6 09 50 PM

i tried playing with it and couldnt find a way to auto do this, i think it needs to be manually

**Comment by jose-donato** [comment]
image

i can fix this tmrw

**Comment by DidierRLopes** [comment]
> > This is what I get from opening FAQ of Installation and Updates from BOTH OpenBB SDK and OpenBB Terminal. Which makes it indistinguishable.
> > @jose-donato can we automate adding a SDK / Terminal / Bot tag? E.g. "Installation and Updates - Terminal | OpenBB Docs.
> > Or do we need to do it manually?
> > Screenshot 2023-04-22 at 6 09 50 PM
> 
> i tried playing with it and couldnt find a way to auto do this, i think it needs to be manually

@jerryduluk can you fix that tomorrow morning?

**Comment by jose-donato** [comment]
so we had a problem here:
- if we added the title on the markdown like this
```
---
title: Installation and Updates - Terminal
sidebar_position: 1
....
```

both the sidebar and the first paragraph would also have these values like in the image below

image


**solution**: 

created a small component that receives the title we want to put for SEO:

```
---
title: Installation and Updates
sidebar_position: 1
description: TBD
---

import HeadTitle from '@site/src/components/General/HeadTitle.tsx';

<HeadTitle title="Installation and Updates - Terminal" />
```

This way it will only affect the page SEO (page title) and not mess with the sidebar as we can see in the image below

image


@jerryduluk we just need to add this on the markdowns we want this to happen. check the file `content/terminal/faqs/installation_updates.md` for an example

```
import HeadTitle from '@site/src/components/General/HeadTitle.tsx';

<HeadTitle title="Installation and Updates - Terminal" />
```

**Pull request merged**
