### PR TITLE
Added econometrics

### PR DESCRIPTION
**Pull request by colin99d**
# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
@colin99d Quick question, I recall that the design I had in mind for the `econometrics` menu didn't work well with the API _at all_. Was this corrected?

**Comment by colin99d** [comment]
@JerBouma I did not look into that. Only looked into standardizing for what Minh wanted.

**Comment by JerBouma** [comment]
That's fine, already had the discussion with Minh that we do Econometrics at a later stage.

**Comment by colin99d** [comment]
Update: I made those changes.

**Comment by JerBouma** [comment]
So its ready?

**Comment by JerBouma** [comment]
I can't seem to load an examples dataset:
image

**Comment by colin99d** [comment]
Screen Shot 2022-08-12 at 9 04 37 AM
Too EZ

**Comment by JerBouma** [comment]
This is done then right? Feel free to merge.

**Pull request merged**
