### PR TITLE
Hotfix/fix yfinance sdk4

### PR DESCRIPTION
**Pull request by deeleeramone**
Fixes additional regressions.

Before:

Screenshot 2023-09-20 at 8 34 14 AM

After:

Screenshot 2023-09-20 at 8 35 58 AM

### CODE REVIEW

**Comment by IgorWounds** [comment]
Hi,

This introduced errors. Does it work as intended through the Swagger?

`FAILED openbb_sdk/providers/cboe/tests/test_cboe_fetchers.py::test_cboe_major_indices_historical_fetcher - pydantic.error_wrappers.ValidationError: 1 validation error for CboeMajorIndicesHistoricalData
Date
  invalid datetime format (type=value_error.datetime)`

**Comment by deeleeramone** [comment]
> Hi,
> 
> This introduced errors. Does it work as intended through the Swagger?
> 
> `FAILED openbb_sdk/providers/cboe/tests/test_cboe_fetchers.py::test_cboe_major_indices_historical_fetcher - pydantic.error_wrappers.ValidationError: 1 validation error for CboeMajorIndicesHistoricalData Date invalid datetime format (type=value_error.datetime)`

This branch was created directly from `feature/openbb-sdk-v4` and doesn't have anything to do with CBOE. Nonetheless, I have fixed the regression that was introduced by changes I didn't make.

Screenshot 2023-09-20 at 4 06 15 PM

**Comment by the-praxs** [comment]
@deeleeramone I have created a PR that forks from this branch and tackles this issue for all historical models. Please review this and let me know your opinions.

https://github.com/OpenBB-finance/OpenBBTerminal/pull/5464

**Review by the-praxs — APPROVED** [review]
🚀

**Pull request merged**
