### PR TITLE
Adds ross index

### PR DESCRIPTION
**Pull request by jose-donato**
# Description

Adds new command to `oss` menu.
`rossidx` shows the fastest-growing open-source startups from [Runa Capital source](https://runacap.com/ross-index/)
image
image

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by jmaslek** [comment]
For the table, since the GitHub gets chopped off very quickly, does it look good if you try using text wrap to that column?

**Comment by piiq** [comment]
Would hbars be better here for readability of the labels?

**Comment by jose-donato** [comment]
Will try those two things

**Comment by jmaslek** [comment]
> > my initial suggestion was to have the charting with the following convention
> > ```
> > rossidx --chart -ct stars
> > rossidx --chart -ct forks
> > rossidx --chart -ct growth
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but i like what you've done more 💪
> 
> nice! the only problem with that is that there is forks annual growth and stars annual growth, even though runacap just shows the stars (+ stars annual growth) on the chart on their website :)

also the argparse names should stick to one letter for one `-` (@DidierRLopes yelled at me before as  this is the unix convention)

**Comment by jose-donato** [comment]
> > > my initial suggestion was to have the charting with the following convention
> > > ```
> > > rossidx --chart -ct stars
> > > rossidx --chart -ct forks
> > > rossidx --chart -ct growth
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > but i like what you've done more 💪
> > 
> > 
> > nice! the only problem with that is that there is forks annual growth and stars annual growth, even though runacap just shows the stars (+ stars annual growth) on the chart on their website :)
> 
> also the argparse names should stick to one letter for one `-` (@DidierRLopes yelled at me before as this is the unix convention)

yup that's true, will change

**Pull request merged**
