### PR TITLE
Feature: Ultima Insights NewsMonitor Integration

### PR DESCRIPTION
**Pull request by AdiSai**
# Description

- [x] Summary of the change / bug fix.
Integrating Ultima Insights News Monitor for the news and cnews commands
- [x] Link # issue, if applicable.
N/A
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
Screenshot 2023-03-30 at 3 18 18 PM
- [x] Relevant motivation and context.
Ultima Insights' News Monitor is a platform that harnesses the power of GPT + LLMs to help deliver better, more relevant news to investors. We help find the news & tell you why it's important before it's on the front page of Bloomberg.
- [x] List any dependencies that are required for this change.
an Ultima Insights API key, available from https://www.ultimainsights.ai/

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
There should be some kind of print message when there is no ticker available:
```
2023 Mar 31, 14:15 (🦋) /stocks/ $ news -t ionq --source UltimaInsights


2023 Mar 31, 14:15 (🦋) /stocks/ $
```

**Comment by jmaslek** [comment]
The instructions for setting up an API key need to be added to the following file:
```
/website/content/terminal/usage/guides/api-keys.md
```

I will look at the sdk generation now.

**Comment by AdiSai** [comment]
> The instructions for setting up an API key need to be added to the following file:
> 
> ```
> /website/content/terminal/usage/guides/api-keys.md
> ```
> 
> I will look at the sdk generation now.

Added the API key instructions to the guide as well.

**Comment by jmaslek** [comment]
Hmm I am now getting an error:
```
2023 Mar 31, 16:20 (🦋) /stocks/ $ news -t aapl


Uncategorized Breaking News (Bloomberg, Reuters, WSJ, CNBC):
> 2023-03-31 20:02:00+00:00 - GM plans to phase out Apple CarPlay in EVs, with Google's help - Reuters.com
https://news.google.com/rss/articles/CBMiZWh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvZ20tcGxhbnMtcGhhc2Utb3V0LWFwcGxlLWNhcnBsYXktZXZzLXdpdGgtZ29vZ2xlcy1oZWxwLTIwMjMtMDMtMzEv0gEA?oc=5

> 2023-03-31 18:50:00+00:00 - Apple wins appeal against UK's decision to investigate its mobile ... - Reuters
https://news.google.com/rss/articles/CBMidGh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvYXBwbGUtd2lucy1hcHBlYWwtYWdhaW5zdC11a3MtZGVjaXNpb24taW52ZXN0aWdhdGUtaXRzLW1vYmlsZS1icm93c2VyLTIwMjMtMDMtMzEv0gEA?oc=5

------------------------
Error: 'relevancyScore'
```

**Comment by AdiSai** [comment]
> news -t aapl

Fixed that issue, sorry about that

**Comment by AdiSai** [comment]
> Hmm I am now getting an error:
> 
> ```
> 2023 Mar 31, 16:20 (🦋) /stocks/ $ news -t aapl
> 
> 
> Uncategorized Breaking News (Bloomberg, Reuters, WSJ, CNBC):
> > 2023-03-31 20:02:00+00:00 - GM plans to phase out Apple CarPlay in EVs, with Google's help - Reuters.com
> https://news.google.com/rss/articles/CBMiZWh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvZ20tcGxhbnMtcGhhc2Utb3V0LWFwcGxlLWNhcnBsYXktZXZzLXdpdGgtZ29vZ2xlcy1oZWxwLTIwMjMtMDMtMzEv0gEA?oc=5
> 
> > 2023-03-31 18:50:00+00:00 - Apple wins appeal against UK's decision to investigate its mobile ... - Reuters
> https://news.google.com/rss/articles/CBMidGh0dHBzOi8vd3d3LnJldXRlcnMuY29tL3RlY2hub2xvZ3kvYXBwbGUtd2lucy1hcHBlYWwtYWdhaW5zdC11a3MtZGVjaXNpb24taW52ZXN0aWdhdGUtaXRzLW1vYmlsZS1icm93c2VyLTIwMjMtMDMtMzEv0gEA?oc=5
> 
> ------------------------
> Error: 'relevancyScore'
> ```

Fixed the issue, sorry about that

**Review by jmaslek — COMMENTED** [review]
On our call, you had said there was a way to sort by newest articles?  I am not seeing that, as the -o flag does nothing and its still just relevancy score?

**Pull request closed without merging**
