### PR TITLE
Out of the box crypto report

### LINKED ISSUE #3783: [Bug] Crypto Report with BTC
/reports/crypto btc
```
An error was encountered in cell [13], check the notebook:
```

The code block is 
```
try:
    historical_data = get_historical_data(ticker, dates)
except Exception as e:
    raise KeyboardInterrupt
```

Error:
```
Pair BTC/USDT not found in binance
```

### PR DESCRIPTION
**Pull request by hjoaquim**
Fixes problems associated with the lack of API keys. 
Template reports should work out of the box for every environment/install method.

Fix #3783

### CODE REVIEW

**Comment by jmaslek** [comment]
Testing out, I get an error in cell 8 which is 
```
news = openbb.crypto.dd.news(symbol=ticker).head(10)

if (isinstance(news,pd.DataFrame) and not news.empty) and news:
    news = news.set_index("published_at")
    news.sort_index()
    news["link"] = news["link"].apply(lambda x: f'<a href="{x}">{x}</a>')
    news
else:
    news = pd.DataFrame()
```

error:
```
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by jmaslek** [comment]
After fixing the news thing, I still get the same error in get_historical_data:

```
try:
    historical_data = get_historical_data(ticker, dates)
except Exception as e:
    raise KeyboardInterrupt
```

Its a KeyError here:
```
KeyError: 'Close'

The above exception was the direct cause of the following exception:
```

**Comment by jmaslek** [comment]
Actually the issue in the load is that the default values, CCXT and binance, do not have BTC/USDT or BTC/USD

**Comment by hjoaquim** [comment]
That makes sense, I was wondering why I didn't have that error

**Comment by hjoaquim** [comment]
@jmaslek changed the `load` source to use YahooFinance

**Comment by jmaslek** [comment]
@hjoaquim Nice.  Now me being in the us is breaking at In[26]:

```
# last trades
trades = openbb.crypto.dd.trades(symbol=ticker, exchange_id="binance", to_symbol="USDT")
if (isinstance(trades,pd.DataFrame) and not trades.empty) or (not isinstance(trades,pd.DataFrame) and trades):
    trades = trades.set_index("Date")
    trades
else:
    trades = pd.DataFrame()
```

**Comment by hjoaquim** [comment]
@jmaslek quick solution would be to change country :laughing: 
Pushed another change trying to remove binance everywhere

**Review by jmaslek — APPROVED** [review]
works now in the US!

**Pull request merged**
