### PR TITLE
Add fixed income menu

### PR DESCRIPTION
**Pull request by northern-64bit**
# Description

Adding a fixed income menu to the terminal.

Will cover the following:

- Reference rates (ESTER, SOFR, SONIA, Ameribor)
- Central Bank Rates (FED and ECB with projections)
- Government Bond Rates (3 month and 10 year rates for any country, including yield curves for US and Euro)
- Corporate Bond Rates (ICE BoFa, Moody’s, Spot Rates and Commercial Paper)

Credit Ratings for now not available (because paid). We'll be able to calculate the spreads with the ICE BoFa benchmarks.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by JerBouma** [comment]
I'm going ham on this PR right now. Will make a bunch of adjustments.

**Comment by JerBouma** [comment]
I've made some significant changes already. The main point here is that a lot of the functionality is actually the same interest rate but split out in commands. I've made it so they are now all in the same one.

```
(🦋) /fixedincome/ $ effr -h

usage: effr [-p {monthly,daily,weekly,daily_excl_weekend,annual,biweekly,volume}] [-s START_DATE] [-e END_DATE] [-o] [-q] [-t] [-h] [--export EXPORT]
            [--sheet-name SHEET_NAME [SHEET_NAME ...]] [--raw]

Get Effective Federal Funds Rate data. A bank rate is the interest rate a nation's central bank charges to its domestic banks to borrow money. The rates central banks charge are set
to stabilize the economy. In the United States, the Federal Reserve System's Board of Governors set the bank rate, also known as the discount rate.

optional arguments:
  -p {monthly,daily,weekly,daily_excl_weekend,annual,biweekly,volume}, --parameter {monthly,daily,weekly,daily_excl_weekend,annual,biweekly,volume}
                        Specific Effective Federal Funds Rate data to retrieve (default: monthly)
  -s START_DATE, --start START_DATE
                        Starting date (YYYY-MM-DD) of data (default: 1900-01-01)
  -e END_DATE, --end END_DATE
                        Ending date (YYYY-MM-DD) of data (default: None)
  -o, --overnight       Gets the Overnight Bank Funding Rate (default: False)
  -q, --quantiles       Whether to show 1, 25, 75 and 99 percentiles (default: False)
  -t, --target          Whether to show the target range data (default: False)
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx and figure into png, jpg, pdf, svg (default: )
  --sheet-name SHEET_NAME [SHEET_NAME ...]
                        Name of excel sheet to save data to. Only valid for .xlsx files. (default: None)
  --raw                 Flag to display raw data (default: False)

For more information and examples, use 'about effr' to access the related guide.
```

And:

```
(🦋) /fixedincome/ $ projection -h

usage: projection [-l] [-h] [--export EXPORT] [--sheet-name SHEET_NAME [SHEET_NAME ...]] [--raw]

Get FOMC Summary of Economic Projections for the Fed Funds Rate.

optional arguments:
  -l, --long-run        Whether to show the long run projection (default: False)
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx and figure into png, jpg, pdf, svg (default: )
  --sheet-name SHEET_NAME [SHEET_NAME ...]
                        Name of excel sheet to save data to. Only valid for .xlsx files. (default: None)
  --raw                 Flag to display raw data (default: False)

For more information and examples, use 'about projection' to access the related guide.
```

Just an example, all comes from two commands:

image

**Comment by JerBouma** [comment]
I still need to go over all other commands **and** I still need to put everything into context. Why is this relevant to look at, does this allow for a detailed analysis of any kind? If not, what's missing? Etcetera.

**Comment by jmaslek** [comment]
@JerBouma are you going to change the guides/documentation to reflect the changes.

**Comment by JerBouma** [comment]
Yeah, I will do that too, makes sense since I am basically changing the whole thing.

**Comment by JerBouma** [comment]
Only thing left right now is `Corporate Bonds` section and a couple more spreads (to mimic Credit Ratings movements). Everything else is ready.

image

**Comment by JerBouma** [comment]
Just sharing since I am enjoying this piece of art 🤌 

image

Based on these Spot Rates and Par Yields I'll now be able to design the beauty below. Just missing forward rates..

image

**Comment by JerBouma** [comment]
@jmaslek I've updated the Fixed Income documentation and docstrings. Should now be clear. Also made sure that within the SDK you can view the options relatively easy. For example:

```
Help on get_fed in module openbb_terminal.fixedincome.fred_model object:

class get_fed(builtins.object)
 |  get_fed(parameter: str = 'monthly', start_date: Optional[str] = None, end_date: Optional[str] = None, overnight: bool = False, quantiles: bool = False, target: bool = False) -> pandas.core.frame.DataFrame
 |  
 |  Obtain data for Effective Federal Funds Rate.
 |  
 |  Parameters
 |  ----------
 |  parameter: str
 |      The parameter to get data for. Choose from:
 |          "monthly"
 |          "daily"
 |          "weekly"
 |          "daily_excl_weekend"
 |          "annual"
 |          "biweekly"
 |          "volume"
 |  start_date: Optional[str]
 |      Start date, formatted YYYY-MM-DD
 |  end_date: Optional[str]
 |      End date, formatted YYYY-MM-DD
 |  overnight: bool
 |      Whether you want to plot the Overnight Banking Federal Rate
 |  quantiles: bool
 |      Whether you want to see the 1, 25, 75 and 99 percentiles
 |  target: bool
 |      Whether you want to see the high and low target range
```

And `icebofa` and `icespread` can obtain the more elaborate explanations:

image

So.. **Ready for Review**!

**Review by jmaslek — APPROVED** [review]
legggoooooo

**Pull request merged**
