### PR TITLE
Added capitalization fixes for stock/search

### LINKED ISSUE #3197: [Bug] Stocks/search --country: autocomplete lists capitalized country names, but ArgParse wants to see lower case.
Using autocomplete to select the `--country` in `/stocks/search --country` will fail.

Screenshot 2022-10-30 at 12 40 45 PM

Also, `--exchange` accepts only capitalized country names.

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Fixes #3197 

This makes the capitilization for the country auto filler, and for the exchange argument match the new terminal standard. Also changed the name of `usa` to `united_states` in exchange, moved exchange from hyphens to underscores, and added generally formatting improvements to the output.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
    - `python terminal.py "stocks/search -c united_states"`
    - `python terminal.py "stocks/search -e usa"`
- [x] Ensure the SDK still works
    - `from openbb_terminal.sdk import openbb
    - `openbb.stocks.search(country="united_states", exchange_country="united_states")`
- [x] Check any related reports

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
While you are addressing this one, can you add a metavar to the arguments that give crazy long -h options:

```
2022 Oct 31, 11:59 (🦋) /stocks/ $ search -h

usage: search [-q QUERY [QUERY ...]]
              [-c {afghanistan,anguilla,argentina,australia,austria,azerbaijan,bahamas,bangladesh,barbados,belgium,belize,bermuda,botswana,brazil,british_virgin_islands,cambodia,canada,cayman_islands,chile,china,colombia,costa_rica,cyprus,czech_republic,denmark,dominican_republic,egypt,estonia,falkland_islands,finland,france,french_guiana,gabon,georgia,germany,ghana,gibraltar,greece,greenland,guernsey,hong_kong,hungary,iceland,india,indonesia,ireland,isle_of_man,israel,italy,ivory_coast,japan,jersey,jordan,kazakhstan,kyrgyzstan,latvia,liechtenstein,lithuania,luxembourg,macau,macedonia,malaysia,malta,mauritius,mexico,monaco,mongolia,montenegro,morocco,mozambique,myanmar,namibia,netherlands,netherlands_antilles,new_zealand,nigeria,norway,panama,papua_new_guinea,peru,philippines,poland,portugal,qatar,reunion,romania,russia,saudi_arabia,senegal,singapore,slovakia,slovenia,south_africa,south_korea,spain,suriname,sweden,switzerland,taiwan,tanzania,thailand,turkey,ukraine,united_arab_emirates,united_kingdom,united_states,uruguay,vietnam,zambia}]
              [-s SECTOR [SECTOR ...]] [-i INDUSTRY [INDUSTRY ...]]
              [-e {usa,argentina,austria,australia,belgium,brazil,canada,chile,china,czech-republic,denmark,egypt,estonia,europe,finland,france,germany,greece,hong-kong,hungary,iceland,india,indonesia,ireland,israel,italy,japan,latvia,lithuania,malaysia,mexico,netherlands,new-zealand,norway,portugal,qatar,russia,singapore,south-africa,south-korea,spain,saudi-arabia,sweden,switzerland,taiwan,thailand,turkey,united-kingdom,venezuela}]
              [-h] [--export EXPORT] [-l LIMIT]

Show companies matching the search query

optional arguments:
  -q QUERY [QUERY ...], --query QUERY [QUERY ...]
                        The search term used to find company tickers (default: )
  -c {afghanistan,anguilla,argentina,australia,austria,azerbaijan,bahamas,bangladesh,barbados,belgium,belize,bermuda,botswana,brazil,british_virgin_islands,cambodia,canada,cayman_islands,chile,china,colombia,costa_rica,cyprus,czech_republic,denmark,dominican_republic,egypt,estonia,falkland_islands,finland,france,french_guiana,gabon,georgia,germany,ghana,gibraltar,greece,greenland,guernsey,hong_kong,hungary,iceland,india,indonesia,ireland,isle_of_man,israel,italy,ivory_coast,japan,jersey,jordan,kazakhstan,kyrgyzstan,latvia,liechtenstein,lithuania,luxembourg,macau,macedonia,malaysia,malta,mauritius,mexico,monaco,mongolia,montenegro,morocco,mozambique,myanmar,namibia,netherlands,netherlands_antilles,new_zealand,nigeria,norway,panama,papua_new_guinea,peru,philippines,poland,portugal,qatar,reunion,romania,russia,saudi_arabia,senegal,singapore,slovakia,slovenia,south_africa,south_korea,spain,suriname,sweden,switzerland,taiwan,tanzania,thailand,turkey,ukraine,united_arab_emirates,united_kingdom,united_states,uruguay,vietnam,zambia}, --country {afghanistan,anguilla,argentina,australia,austria,azerbaijan,bahamas,bangladesh,barbados,belgium,belize,bermuda,botswana,brazil,british_virgin_islands,cambodia,canada,cayman_islands,chile,china,colombia,costa_rica,cyprus,czech_republic,denmark,dominican_republic,egypt,estonia,falkland_islands,finland,france,french_guiana,gabon,georgia,germany,ghana,gibraltar,greece,greenland,guernsey,hong_kong,hungary,iceland,india,indonesia,ireland,isle_of_man,israel,italy,ivory_coast,japan,jersey,jordan,kazakhstan,kyrgyzstan,latvia,liechtenstein,lithuania,luxembourg,macau,macedonia,malaysia,malta,mauritius,mexico,monaco,mongolia,montenegro,morocco,mozambique,myanmar,namibia,netherlands,netherlands_antilles,new_zealand,nigeria,norway,panama,papua_new_guinea,peru,philippines,poland,portugal,qatar,reunion,romania,russia,saudi_arabia,senegal,singapore,slovakia,slovenia,south_africa,south_korea,spain,suriname,sweden,switzerland,taiwan,tanzania,thailand,turkey,ukraine,united_arab_emirates,united_kingdom,united_states,uruguay,vietnam,zambia}
                        Search by country to find stocks matching the criteria (default: )
  -s SECTOR [SECTOR ...], --sector SECTOR [SECTOR ...]
                        Search by sector to find stocks matching the criteria (default: )
  -i INDUSTRY [INDUSTRY ...], --industry INDUSTRY [INDUSTRY ...]
                        Search by industry to find stocks matching the criteria (default: )
  -e {usa,argentina,austria,australia,belgium,brazil,canada,chile,china,czech-republic,denmark,egypt,estonia,europe,finland,france,germany,greece,hong-kong,hungary,iceland,india,indonesia,ireland,israel,italy,japan,latvia,lithuania,malaysia,mexico,netherlands,new-zealand,norway,portugal,qatar,russia,singapore,south-africa,south-korea,spain,saudi-arabia,sweden,switzerland,taiwan,thailand,turkey,united-kingdom,venezuela}, --exchange {usa,argentina,austria,australia,belgium,brazil,canada,chile,china,czech-republic,denmark,egypt,estonia,europe,finland,france,germany,greece,hong-kong,hungary,iceland,india,indonesia,ireland,israel,italy,japan,latvia,lithuania,malaysia,mexico,netherlands,new-zealand,norway,portugal,qatar,russia,singapore,south-africa,south-korea,spain,saudi-arabia,sweden,switzerland,taiwan,thailand,turkey,united-kingdom,venezuela}
                        Search by a specific exchange country to find stocks matching the criteria (default: )
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx (default: )
  -l LIMIT, --limit LIMIT
                        Number of entries to show in data. (default: 10)

For more information and examples, use 'about search' to access the related guide.
```

**Comment by colin99d** [comment]
> `search -e USA` no work
> 
> ```
> 
> 2022 Oct 31, 12:00 (🦋) /stocks/ $ search -e USA
> 
> usage: search [-q QUERY [QUERY ...]]
>               [-c {afghanistan,anguilla,argentina,australia,austria,azerbaijan,bahamas,bangladesh,barbados,belgium,belize,bermuda,botswana,brazil,british_virgin_islands,cambodia,canada,cayman_islands,chile,china,colombia,costa_rica,cyprus,czech_republic,denmark,dominican_republic,egypt,estonia,falkland_islands,finland,france,french_guiana,gabon,georgia,germany,ghana,gibraltar,greece,greenland,guernsey,hong_kong,hungary,iceland,india,indonesia,ireland,isle_of_man,israel,italy,ivory_coast,japan,jersey,jordan,kazakhstan,kyrgyzstan,latvia,liechtenstein,lithuania,luxembourg,macau,macedonia,malaysia,malta,mauritius,mexico,monaco,mongolia,montenegro,morocco,mozambique,myanmar,namibia,netherlands,netherlands_antilles,new_zealand,nigeria,norway,panama,papua_new_guinea,peru,philippines,poland,portugal,qatar,reunion,romania,russia,saudi_arabia,senegal,singapore,slovakia,slovenia,south_africa,south_korea,spain,suriname,sweden,switzerland,taiwan,tanzania,thailand,turkey,ukraine,united_arab_emirates,united_kingdom,united_states,uruguay,vietnam,zambia}]
>               [-s SECTOR [SECTOR ...]] [-i INDUSTRY [INDUSTRY ...]]
>               [-e {usa,argentina,austria,australia,belgium,brazil,canada,chile,china,czech-republic,denmark,egypt,estonia,europe,finland,france,germany,greece,hong-kong,hungary,iceland,india,indonesia,ireland,israel,italy,japan,latvia,lithuania,malaysia,mexico,netherlands,new-zealand,norway,portugal,qatar,russia,singapore,south-africa,south-korea,spain,saudi-arabia,sweden,switzerland,taiwan,thailand,turkey,united-kingdom,venezuela}]
>               [-h] [--export EXPORT] [-l LIMIT]
> search: error: argument -e/--exchange: invalid choice: 'USA' (choose from 'usa', 'argentina', 'austria', 'australia', 'belgium', 'brazil', 'canada', 'chile', 'china', 'czech-republic', 'denmark', 'egypt', 'estonia', 'europe', 'finland', 'france', 'germany', 'greece', 'hong-kong', 'hungary', 'iceland', 'india', 'indonesia', 'ireland', 'israel', 'italy', 'japan', 'latvia', 'lithuania', 'malaysia', 'mexico', 'netherlands', 'new-zealand', 'norway', 'portugal', 'qatar', 'russia', 'singapore', 'south-africa', 'south-korea', 'spain', 'saudi-arabia', 'sweden', 'switzerland', 'taiwan', 'thailand', 'turkey', 'united-kingdom', 'venezuela')
> ```

I believe the standard we chose globally is lower case.

**Comment by jmaslek** [comment]
> I believe the standard we chose globally is lower case.

It is.  But we should match any case

**Review by jmaslek — APPROVED** [review]
Is working for me.  Although now I have opeened anmother floodgate that the industries are not underscore dependent, but that is out of scope here,

**Pull request merged**
