### PR TITLE
[feature]: feature/overview-to-profile: Deprecate `equity.fundamental.overview()` and move to `equity.profile()`

### PR DESCRIPTION
**Pull request by deeleeramone**
This PR moves the function, `obb.equity.fundamental.overview()`, to `obb.equity.profile()`.

Why?

- More clarity and consistency.
- `overview()` is serviced only by the FMP provider, and the data returned belongs under `obb.equity.profile()`, along with the others.

Screenshot 2024-01-29 at 7 50 07 PM

What?

The existing endpoint has been deprecated. The new function supports multiple symbols.

Screenshot 2024-01-29 at 8 14 27 PM

Impact:

- Minimal.
- No breaking changes.
- Future warning.

Impact Score:

2

Tests:

- Additional unit test captured
- Added FMP to the integration tests of `equity.profile()`

### CODE REVIEW

**Review by IgorWounds — APPROVED** [review]

**Comment by IgorWounds** [comment]
@deeleeramone can we adjust the name of the PR according to the new Procedure and attach an impact score?

**Review by hjoaquim — CHANGES_REQUESTED** [review]
This can only be merged after #6005, otherwise will not work as intended (deprecation wise).

Also, (and I know I've advocated otherwise in the past) let's generate the static assets so that the publishing procedure it's easier when we get to that!

**Comment by hjoaquim** [comment]
> > Also, (and I know I've advocated otherwise in the past) let's generate the static assets so that the publishing procedure it's easier when we get to that!
> 
> I've been told previously not to generate static assets because of the requirements for specific Python versions and that they will be generated on release. Is this not the case?

In the last release there were a lot of changes in the static assets that no one was really sure if were accurate - we informally agreed that, most of the time, it makes sense to push the static assets in the PR that impacts them for better traceability!

**Review by hjoaquim — APPROVED** [review]
Jumped in to add some adjustments, but overall everything looks great!

**Pull request merged**
