### PR TITLE
Hotfix for SIA menu

### PR DESCRIPTION
**Pull request by jmaslek**
I am not proud, but I found a yf alternative that seems to be stable-ish.  This is like the cheap knock off brand of band aids that will work for a few minutes.  But it works.

Fixes: #4283

### CODE REVIEW

**Comment by JerBouma** [comment]
Give me a moment to look if I can fix `attrib` with FMP.

**Comment by JerBouma** [comment]
Fixed `attrib` and therefore also removed the message:
image

**Comment by JerBouma** [comment]
Does the menu actually work? I get no company data on any of the functionalities.

image

**Comment by jmaslek** [comment]
> Give me a moment to look if I can fix `attrib` with FMP.

is this a free endpoint or will it throw an error with free tier?

**Comment by JerBouma** [comment]
> > Give me a moment to look if I can fix `attrib` with FMP.
> 
> is this a free endpoint or will it throw an error with free tier?

Freeee

**Comment by JerBouma** [comment]
> > Does the menu actually work? I get no company data on any of the functionalities.
> > image
> 
> probably need to move away from stock analysis scraping.

Agreed, could replace with FMP here too. But the other one is actually Yahoo Finance. In any case, plotting over multiple years is the only one that is actually insightful so it can go as well.

**Comment by jmaslek** [comment]
> > > Does the menu actually work? I get no company data on any of the functionalities.
> > > image
> > 
> > 
> > probably need to move away from stock analysis scraping.
> 
> Agreed, could replace with FMP here too. But the other one is actually Yahoo Finance. In any case, plotting over multiple years is the only one that is actually insightful so it can go as well.

So thats out of the scope here, as this just addressd loading into the menu.  Plz approve

**Review by JerBouma — APPROVED** [review]
Yush

**Comment by jmaslek** [comment]
@JerBouma wanna open a new issue for the stuff you mentioned?

**Comment by JerBouma** [comment]
> @JerBouma wanna open a new issue for the stuff you mentioned?

Done https://github.com/OpenBB-finance/OpenBBTerminal/issues/4308

**Pull request merged**
