### PR TITLE
Risk metrics for qa and portfolio

### PR DESCRIPTION
**Pull request by northern-64bit**
# Description
Implementation of risk metrics. If I have missed some useful risk metric or have some errors in my calculations then message me please.

Done:
- Sortino ratio (qa)
- Sharpe ratio (qa)
- Omega ratio (qa)
- Adding metrics to portfolio context
- Documentation + Hugo Website
- Tests

To do:
- Nothing

# How has this been tested?

Testing the commands. The implementation of the mathematics needs to be checked by someone.

# Checklist:

- [x] Update [our Hugo documentation](https://gamestonkterminal.github.io/GamestonkTerminal/) following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by northern-64bit** [comment]
Please check the mathematics and the values in order to see if anything is wrongly calculated. Thanks!

**Comment by DidierRLopes** [comment]
@northern-64bit sorry for the delay on this!!! The announcement took all our energy 😰

BUUT we're baaackk!

@northern-64bit can you fix the issues, they are down to the renaming. Then @dcajasn can you review this PR? 😄

**Comment by northern-64bit** [comment]
No problem! The new website looks great! 

I think that I renamned it in order to fix the conflicts, but now it doesn't work at all. Any idea why or what I did wrong?

**Comment by northern-64bit** [comment]
> Hey! As soon as I launch the terminal I get this:
> 
> ```
> 2022 Apr 07, 11:19 (🦋) / $ portfolio
> Error: No module named 'gamestonk_terminal'
> ```
> 
> I also see there are >2300 files changed so some merge didn't go well. It may be easier to just copy paste the files you changed into a new branch off of the main one so you have all the renaming done

This should now be fixed in the new pr #1666

**Pull request closed without merging**
