### PR TITLE
Added plots for tickers

### LINKED ISSUE #1765: [Bug] Portfolio - Efficient Frontier has lost the Asset Labels
Screen Shot 2022-05-05 at 1 26 28 AM

what it used to look like:

### PR DESCRIPTION
**Pull request by colin99d**
# Description
Fixes #1765

- [x] Summary of the change / bug fix.
- [x] Link # issue, if applicable.
- [x] Screenshot of the feature or the bug before/after fix, if applicable.
- [x] Relevant motivation and context. 
- [x] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Review by jmaslek — CHANGES_REQUESTED** [review]
Using the covariance is only correct when the variance is the risk measure used.

This is using CVaR

Screen Shot 2022-05-19 at 8 15 57 PM

**Comment by colin99d** [comment]
> Using the covariance is only correct when the variance is the risk measure used.
> 
> This is using CVaR
> 
> Screen Shot 2022-05-19 at 8 15 57 PM

How would I get this for the individual tickers?

**Comment by jmaslek** [comment]
> How would I get this for the individual tickers?

You are going to need to figure out which variable is the correct one being plotted.  I believe it is the `risk` one, but not 100% confident.

**Comment by colin99d** [comment]
@jmaslek then how would I get something like the CVar for each ticker?

**Comment by colin99d** [comment]
@jmaslek @JerBouma I was able to figure out how this code worked better and to make an approach that should always work. However, my numbers are not turning out quite right and I am not sure why. Do you guys mind taking a look?

**Comment by jmaslek** [comment]
Looking now.

Do you mean to commit `openbb_terminal/jupyter/reports/stored/20220404_092139_crypto_market.html`

**Comment by jmaslek** [comment]
CVaR still wildly off lets see why

Screen Shot 2022-05-22 at 6 14 18 PM

**Comment by colin99d** [comment]
> Looking now.
> 
> Do you mean to commit `openbb_terminal/jupyter/reports/stored/20220404_092139_crypto_market.html`

No lol

**Comment by colin99d** [comment]
> CVaR still wildly off lets see why
> 
> Screen Shot 2022-05-22 at 6 14 18 PM

They are all off. Something is off. Im just not sure what. I tried copying what he did.

**Comment by jmaslek** [comment]
I gotchu.  You didn't annualize variance

**Comment by colin99d** [comment]
Aye!! Nice catch. Its working now.

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
