### PR TITLE
Minor fixes on login

### PR DESCRIPTION
**Pull request by hjoaquim**
Aims to fix:

- banner not showing if credentials expire  --> Fixed :heavy_check_mark: 
- `openbb --login` not working  --> Fixed :heavy_check_mark:

### CODE REVIEW

**Comment by Chavithra** [comment]
Let's leave the conditions like this for now.

**Comment by jmaslek** [comment]
> @Chavithra with the conditions as it's now on the `develop` branch, I can't launch the terminal without an account. Is that the default behavior?

This should not be the case.  There should be nothing about accounts on develop yet by default

**Comment by hjoaquim** [comment]
^I misunderstood the purpose of the condition and reverted to the original state

**Comment by hjoaquim** [comment]
> The dependency tree has been changed. Please update requirements.txt and requirements-full.txt

why?

**Review by montezdesousa — COMMENTED** [review]
`openbb --login` does not yield the prompt if there is no session save, it logs the user as guest. Is this the desired behavior?

**Comment by jmaslek** [comment]
> > The dependency tree has been changed. Please update requirements.txt and requirements-full.txt
> 
> why?

ignore.  bad bot

**Comment by montezdesousa** [comment]
> `openbb --login` does not yield the prompt if there is no session save, it logs the user as guest. Is this the desired behavior?

`poetry install` solved it

**Review by montezdesousa — APPROVED** [review]

**Pull request merged**
