### PR TITLE
New Feature Financial Analysis, checks Yahoo if no data at Alpha Advantage.

### PR DESCRIPTION
**Pull request by pauljsymonds**
# Description

- [ ] Summary of the change - Added a feature to go to Yahoo Finance for Cash flows, Income Statement and Balance Sheet when data not in Alpha Advantage, (Covers UK tickers)

- [ ] Relevant motivation and context. - Useful for those in UK looking at FTSE data.

- [ ] List any dependencies that are required for this change. - import ssl, numpy and from bs4 import BeautifulSoup

# How has this been tested?

Tested:

stocks
load SNR.L
fa
balance
cash
income

all returned data

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ *] I have performed a self-review of my own code.
- [ *] I have commented my code, particularly in hard-to-understand areas.
- [ ?] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ *] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by colin99d** [comment]
Awesome idea! I can review this tonight or tomorrow.

**Review by colin99d — CHANGES_REQUESTED** [review]
Nice pr! I really like adding in yahoo finance when alpha vantage fails. I noticed two issues:
- Date in the headers is formatted DD/MM/YYYY, but we stick to YYYY/MM/DD terminal-wide
- It looks that if while I am in the fa menu I load `SNR.L` and then load `GME` and then load `SNR.L` again none of the commands work anymore and they all produce errors

**Comment by colin99d** [comment]
Also, this is optional but some people may want to choose yahoo finance over alpha vantage when both are available. Adding a source option in the controller would be helpful for this. If you need any help here let me know.

**Comment by pauljsymonds** [comment]
I've made the changes you suggested to the dates and separated the source.

I've removed the code that calls Yahoo from the AV so no data is returned.

I have not successfully been able to get the --source flag working.

I noticed also when in the terminal and -s is passed it returns the sources (intellisense) yet -s is for dates.  Not sure where that is coming from.

**Review by colin99d — APPROVED** [review]
Looks good! Once tests pass lets merge.

**Pull request merged**
