### PR TITLE
Fix Various portfolio/po issues

### LINKED ISSUE #3135: [Bug] Portfolio optimization bugs
* `-f or --file` is not being added by default on `params` despite prompt
Screenshot 2022-10-27 at 19 15 19

* Saving parameters to file is broken
Screenshot 2022-10-27 at 19 16 55

* Unhandled optimisation error with 1d period
Screenshot 2022-10-27 at 22 42 09

* Help is unavailable after optimization
Screenshot 2022-10-27 at 22 47 36

* Error with `maxsharpe -tr`
Screenshot 2022-10-27 at 22 51 12

* In general a lot of the flags allowed by each command are not working if not default

* `plot` and `rpf` don't have autocompletion

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Fixes #3135

- Files can now be uploaded in params without the `-f` flag.
- Refactors the load and save files to use the new paths we created including the exports folder.
- Moves the sample files into the openbb_terminal/miscellaneous folder
- Adds error handling when a dataframe is empty
- Gave the autocompleter better handling for a none type
- Updated the `tr` parameter to be an int
- Add options for `plot` and `rpf`

**Note**: I am highly confident there are a lot more errors in this menu (it doesnt even follow MVC). And a lot of it is pretty hard to understand. However, this will take a lot of time so a decision like this goes to @Chavithra, @JerBouma, and @andrewkenreich.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
    - `python terminal.py portfolio/po/params/load OpenBB_Parameters_Template_v1.0.0.xlsx` (can load without -f)
    - `python terminal.py portfolio/po/params/load OpenBB_Parameters_Template_v1.0.0.xlsx/save colin.ini` (can save to new ath)
    - `python terminal.py "portfolio/po/load 50_30_10_10_Portfolio.xlsx/maxsharpe -p 1d" --debug`
        - I then confirmed that the file was saved to the correct location, and that the new file matches the old file 
    - `python terminal.py "portfolio/po/load 50_30_10_10_Portfolio.xlsx/maxsharpe"` then run `maxsharpe -h`
    - `python terminal.py "portfolio/po/load 50_30_10_10_Portfolio.xlsx/maxsharpe -tr 5"` (switched this argument to an integer)
    - Found another issue where using maxsharpe twice causes issues with prompt toolkit, code below shows a bug that is now fixed
    - `python terminal.py "portfolio/po/load 50_30_10_10_Portfolio.xlsx/maxsharpe -tr 5"` then `maxsharpe -tr 3` then `maxsharpe -tr 4`
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by JerBouma** [comment]
Much of the code is based on models from Riskfolio-lib. This is fine as we can expect the results to be accurate. However, the creator didn't follow our styling guide and wasn't the most experienced coder. So, **ideally** we would want to rewrite a lot of the code to improve it. I think this is relevant once we notice that there is a lot of interest from our target personas.

**Comment by jmaslek** [comment]
Idk if this is an issue, but if I am in `po` and I run an optimization, the autocomplete no longer works for load.

```
load OpenBB_Portfolio_Template_v1.0.0.xlsx
maxsharpe
load {no autocomplete here}
```

**Comment by colin99d** [comment]
This PR is a bandaid on a menu that needs a lot of refactoring. There are probably a lot of other bugs we do not know about as well, but until someone really takes the time to really fix it they will keep popping up.

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
So the bug you addressed was the -f which is fixed.

I tested all the edge cases I had with our previous auto complete issues, and it all worked.

**Pull request merged**
