### PR TITLE
Autogenerated screenshots and plotshots

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

This PR implements new general command that should allow users to autogenerate openbb frame images with plot.

`screenshot` with plot available
image

# How has this been tested?
`screenshot --terminal` or `screenshot` if no plot available
`screenshot` with plot available

### CODE REVIEW

**Review by DidierRLopes — COMMENTED** [review]
Don't forget to add `pyautogui` to dependencies!

I always get this with screenshot utilizing 
```
2022 Sep 17, 14:01 (🦋) /stocks/ $ screenshot
Cannot reach window.
```

What's thee difference between `screenshot` and `plotshot`? I would probably merge these into the same command (but not sure what is the difference between them)

**Comment by DidierRLopes** [comment]
Nvm, I didn't read the description @montezdesousa 🤣 

I would do the following:
Just have 1 `screenshot` command

If there is an image, screenshot the image. 
If there isn't, screenshot terminal as fallback.

Allow user to do `screenshot --terminal` to force screenshot terminal

**Comment by montezdesousa** [comment]
> Don't forget to add `pyautogui` to dependencies!
> 
> I always get this with screenshot utilizing
> 
> ```
> 2022 Sep 17, 14:01 (🦋) /stocks/ $ screenshot
> Cannot reach window.
> ```
> 
> What's thee difference between `screenshot` and `plotshot`? I would probably merge these into the same command (but not sure what is the difference between them)

Should be working regardless of where is run now

**Comment by montezdesousa** [comment]
> Nvm, I didn't read the description @montezdesousa 🤣
> 
> I would do the following: Just have 1 `screenshot` command
> 
> If there is an image, screenshot the image. If there isn't, screenshot terminal as fallback.
> 
> Allow user to do `screenshot --terminal` to force screenshot terminal

Yup, makes sense... Already there now. Also updated terminal frame like @jose-donato suggested

**Comment by DidierRLopes** [comment]
Can we add a `"\n"` once the user runs `screenshot`?

From
```
2022 Sep 18, 06:59 (🦋) /stocks/ $ screenshot
2022 Sep 18, 07:00 (🦋) /stocks/ $
```
to
```
2022 Sep 18, 06:59 (🦋) /stocks/ $ screenshot

2022 Sep 18, 07:00 (🦋) /stocks/ $
```

same here
```
2022 Sep 18, 07:00 (🦋) /stocks/ $ screenshot
Cannot reach window.
2022 Sep 18, 07:01 (🦋) /stocks/ $
```

I always get this "Cannot reach window". Do you know why?

**Comment by montezdesousa** [comment]
> Can we add a `"\n"` once the user runs `screenshot`?
> 
> From
> ```
> 2022 Sep 18, 06:59 (🦋) /stocks/ $ screenshot
> 2022 Sep 18, 07:00 (🦋) /stocks/ $
> ```
> to
> ```
> 2022 Sep 18, 06:59 (🦋) /stocks/ $ screenshot
> 
> 2022 Sep 18, 07:00 (🦋) /stocks/ $
> ```
> 
> same here
> ```
> 2022 Sep 18, 07:00 (🦋) /stocks/ $ screenshot
> Cannot reach window.
> 2022 Sep 18, 07:01 (🦋) /stocks/ $
> ```
> 
> I always get this "Cannot reach window". Do you know why?
> 

No, I'll do some testing on Mac, might be OS related.

Rn, I changed the code to just save the .PNG file because Pillow only creates a temporary file that I cannot save and share on Twitter. Will fix later this as well

**Comment by hjoaquim** [comment]
Hey @montezdesousa, tried it on Ubuntu and got this:

image

It doesn't allow me to launch the terminal :cry:

Let me know if I can help with this!!

**Comment by montezdesousa** [comment]
I'll take the help. Pyautogui used for terminal screenshot is not supported by Mac os or Linux.

So Theo suggestion was to remove pyautogui from dependencies and ship only the plot screenshot for now. Todo -> remove pyautogui from dependencies 

On the plot screenshot I have a small issue to solve when the pillow image is prompt on windows, the .PNG is corrupt for some reason, this does not happen on Mac. Todo -> fix the corrupt PNG on windows when plot screenshot

Finally, move the .PNG files on the images terminal folder.

We can chat about this!

**Review by minhhoang1023 — APPROVED** [review]

**Pull request merged**
