### PR TITLE
Updated portfolio/load --rfr options

### LINKED ISSUE #3068: [Bug] portfolio/load --rfr - too many 0s
**Describe the bug**
Small bug where risk free rate prompt has a lot of 0s.

**Screenshots**
Screenshot 2022-10-26 at 09 56 39

**Desktop (please complete the following information):**

- OS: MacOS Monterey
- Python version 3.9.13

**Additional context**
Add any other information that you think could be useful for us.

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Fixes #3068 
The --rfr option does not round the float values, leading to poor formatting of options.

# How has this been tested?

- [x] Make sure affected commands still run in terminal
    - type python terminal.py portfolio` then type `load --rfr` and look at how well-formatted the suggestions are.
- [x] Ensure the SDK still works (no need, this only affects a controller)
- [x] Check any related reports (no need, this only affects a controller)

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
Im confused why we have autocomplete here instead of just using a float type?

**Comment by JerBouma** [comment]
I believe the idea was so that you don't have to type 0.00001 to get 0.1%

**Comment by jmaslek** [comment]
> I believe the idea was so that you don't have to type 0.00001 to get 0.1%

how does an autocomplete of decimals change that you can just enter 0.1?

**Comment by colin99d** [comment]
Instructions unclear. How we doing this?

**Comment by jmaslek** [comment]
I would get rid of autocomplete of numbers that can take any value (just make sure that we say in the docs 0.1 = 0.1%)

**Comment by JerBouma** [comment]
Make sense, add this to the `openbb.co/docs` and to the `-h`.

**Comment by colin99d** [comment]
Ok, should I close this PR?

**Comment by montezdesousa** [comment]
> Ok, should I close this PR?

Yes good for me

**Pull request closed without merging**
