### PR TITLE
Update documentation with more detailed installation instructions, requirements and more

### PR DESCRIPTION
**Pull request by jose-donato**
Update:

- Scripts and Routines
- Basics guide
- Installation guides, a page per guide and much more detailed.
- Requirements, remove it and add it to installation docs.
- Import and export data
- Restructured both menus

### CODE REVIEW

**Comment by JerBouma** [comment]
Noice, I'll make some additional changes tomorrow then ready to merge.

**Comment by JerBouma** [comment]
This some questions unanswered before we proceed:

Screenshot 2023-03-03 at 10 55 56

**Comment by JerBouma** [comment]
Hijacking your PR a bit to get some more doc changes in.

**Comment by JerBouma** [comment]
@jose-donato Can you look into making it so clicking on "Installation" sends you to your OS? And can you see what the issue is with the MacOS buttons?

**Comment by JerBouma** [comment]
Restructuring done.

image

image

**Comment by JerBouma** [comment]
@jmaslek Just asking you to look at it because reviewpad is whining. These are just upgrades to the Docs.

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
> @jmaslek Just asking you to look at it because reviewpad is whining. These are just upgrades to the Docs. The auto-select installation page has been taken out (so Jose's video is irrelevant).

looks fine to me

**Pull request merged**
