### PR TITLE
Fixing smaller issues and moving a few things around

### LINKED ISSUE #4020: [Bug] Economy Menu - Plotting function not plotting two things
One works:

`/economy/index sp500`

Screenshot 2023-01-19 at 9 41 27 AM

`/economy/index hk_hsi`

Screenshot 2023-01-19 at 9 42 24 AM

Two together, no dice:

`/economy/index sp500,hk_hsi`

Screenshot 2023-01-19 at 9 43 27 AM

Plotting using the `plot` function also produces the wrong scale for the second y-axis:

`plot --y1 sp500 --y2 hk_hsi`

Screenshot 2023-01-19 at 9 45 17 AM

### LINKED ISSUE #4044: [Bug] stocks/fa/info - Error: Yahoo has again changed data format, yfinance now unsure which key(s) is for decryption
Recreate with:

`/stocks/load aapl/fa/info`

image

Related to this: https://github.com/ranaroussi/yfinance/issues/1329

### LINKED ISSUE #4082: [IMPROVE] Treasury rates from `economy/treasury` are wrongly exported to Excel
If you export to Excel the number is off (`/economy/treasury --export xlsx`). The data is meant to be depicted as a percentage in Excel while it should be Excel doing the formatting there. So instead of the value being 4.71 it should be 0.0471. For example, if I would calculate the Sharpe Ratio and use this number to deduct from a stock's annual return, I would get very odd results.

So pretty simple divided by 100 in the code before exporting for all series 😉 

image

### PR DESCRIPTION
**Pull request by JerBouma**
This changes the following things:
- Moved `arktrades` to `screener`. It has no business being in `stocks/fa`.
- Made fixes to the Equity report. This tended to refer to old data, now runs smoothly.
- Updated the docs to remove any mention of `dd` as this menu is integrated in `stocks/fa`
- Updated SDK paths where they were pointing to the wrong location.
- Moved the `filings` command back in but moved it to `stocks/disc` since it has no business being on the home page of `stocks` fixing #4162.
- I saw a small mistake with sheet_name again, saying `heet_name` in `call_shrs`. Fixed that too.
- Fixed treasury rates not displaying properly when exported. It was a simple `/ 100`. See this source: https://www.federalreserve.gov/releases/h15/ (same as EconDB which we get data from) for the 10 year and then try `economy/treasury --export xlsx`. Previously this gave you 353%, a bit high don't you think? Fixes #4082
- Indices couldn't be plotted due to missing `ignore_tz=True`. Now fixed which fixes #4020 and #4022.
- Adding fast_info to `overview --source YahooFinance` which fixes  #4044.

### CODE REVIEW

**Comment by jmaslek** [comment]
plz fix #4154 as well

**Comment by JerBouma** [comment]
?

image

**Comment by jmaslek** [comment]
> ?
> 
> image

You fixed it.  Magic.

**Comment by JerBouma** [comment]
Impressed by myself sometimes that running the command is enough

**Comment by jmaslek** [comment]
Note that on the reports, we run integration test on those, so if a key is not provided (which they aren't in the CI), they should not fail. Can you confirm this by changing your api key to something invalid or deleting from the env file?

**Comment by JerBouma** [comment]
@jmaslek I did it mom, deleted .env and this is the result.

image

**Review by jmaslek — APPROVED** [review]

**Comment by JerBouma** [comment]
🥳

**Pull request merged**
