### PR TITLE
Add mutual funds to sdk

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

```python3
from openbb_terminal.sdk import openbb
openbb.funds?
f = openbb.funds.load("Vanguard", "US")
openbb.funds.historical(f, "2019-01-01", "2020-01-01", "both")
openbb.funds.historical_chart(f, "2019-01-01", "2020-01-01")
openbb.funds.sector(f)
openbb.funds.sector_chart(f)
openbb.funds.holdings(f)
openbb.funds.carbon(f)
openbb.funds.exclusion(f)
```

* Closes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4473

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
So I am confused.  This may just be how the mstarpy library handles things, but if I look at the example: `f = openbb.funds.load("Vanguard", "US")`, vanguard has hundreds of funds, so what does this specify exactly?

I do see that if I use VFIAX (their admiral SP500 fund), it still works, so maybe we change the docstrings to that example?

**Comment by montezdesousa** [comment]
> VFIAX

It's the first result of search term by "Legal Name". To be specific you'd have to specify the exact legal name:
Screenshot 2023-03-29 at 10 25 45


I get an error with VFIAX, what term did you use?
Screenshot 2023-03-29 at 10 29 51

**Comment by jmaslek** [comment]
> > VFIAX
> 
> It's the first result of search term by "Legal Name". To be specific you'd have to specify the exact legal name: Screenshot 2023-03-29 at 10 25 45
> 
> I get an error with VFIAX, what term did you use? Screenshot 2023-03-29 at 10 29 51

I see.  I just used funds.load("VFIAX", "US").  I think this is moreso just confusion with how the mstarpy library handles the funds.

**Comment by montezdesousa** [comment]
> > > VFIAX
> > 
> > 
> > It's the first result of search term by "Legal Name". To be specific you'd have to specify the exact legal name: Screenshot 2023-03-29 at 10 25 45
> > I get an error with VFIAX, what term did you use? Screenshot 2023-03-29 at 10 29 51
> 
> I see. I just used funds.load("VFIAX", "US"). I think this is moreso just confusion with how the mstarpy library handles the funds.

I can change them to "American Vanguard Corp", works?

**Comment by deeleeramone** [comment]
Can we rename the `page_size` argument to be more consistent with the rest of the functions, to `limit`?

**Comment by deeleeramone** [comment]
VFIAX does not load with the SecID either. Might be specific to VFIAX or Vanguard US specific. Other funds load using the SecID value.

Screenshot 2023-03-29 at 9 26 52 AM

```
In [15]: f = openbb.funds.load('FOUSA00L8W')
0 funds found whith the term FOUSA00L8W
Error: 0 funds found with the term FOUSA00L8W


In [16]: f = openbb.funds.load('52.8.VFIAX')
0 funds found whith the term 52.8.VFIAX
Error: 0 funds found with the term 52.8.VFIAX


In [17]: f = openbb.funds.load('F0USA00FS1')
0 funds found whith the term F0USA00FS1
Error: 0 funds found with the term F0USA00FS1


In [18]: f = openbb.funds.load('VFIAX')
0 funds found whith the term VFIAX
Error: 0 funds found with the term VFIAX
```


Screenshot 2023-03-29 at 9 31 58 AM

**Comment by deeleeramone** [comment]
> This is an mstarpy thing. What our load function calls is mstarpy.Funds(term, country). While not desirable, the action 
would be to open an issue on their library

I find this confusing because the Terminal function for `load` finds and loads VFIAX without problems, while the SDK `load` does not enjoy this capability. 

Screenshot 2023-03-29 at 10 06 19 AM

**Comment by jmaslek** [comment]
> > This is an mstarpy thing. What our load function calls is mstarpy.Funds(term, country). While not desirable, the action
> > would be to open an issue on their library
> 
> I find this confusing because the Terminal function for `load` finds and loads VFIAX without problems, while the SDK `load` does not enjoy this capability.
> 
> Screenshot 2023-03-29 at 10 06 19 AM
> 
> _updating_... I see, the load argument needs to also have a valid entry for country.
> 
> Screenshot 2023-03-29 at 10 12 02 AM

Because the terminal has the country defaulted to the US (or united_states, noit sure which they use).  The load function requires the country.  patch would be to default the load to have country kwarg=US.  will do that

**Comment by montezdesousa** [comment]
> Can we rename the `page_size` argument to be more consistent with the rest of the functions, to `limit`?

y, good catch

**Comment by jmaslek** [comment]
here you go

Screenshot 2023-03-29 at 1 27 26 PM

**Comment by deeleeramone** [comment]
> the terminal has the country defaulted to the US (or united_states, noit sure which they use)

Looks like they use the 2-letter country code here.

```
In [9]: f?
Type:        Funds
String form: <mstarpy.funds.Funds object at 0x1075a3e80>
File:        ~/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/mstarpy/funds.py
Docstring:  
Main class to access data about funds
Args:
    term (str): text to find a funds can be a the name, part of a name or the isin of the funds
    country (str) : text for code ISO 3166-1 alpha-2 of country
    pageSize (int): number of funds to return
    itemRange (int) : index of funds to return (must be inferior to PageSize)

Examples:
    >>> Funds('0P0000712R', "ca", 9, 0)
    >>> Funds('bond', "uk", 25, 2)

Raises:
    TypeError: raised whenever the parameter type is not the type expected
    ValueError : raised whenever the parameter is not valid or no funds found
```

**Review by jmaslek — APPROVED** [review]

**Comment by msh855** [comment]
This module does not work. I am trying the example of the documentation and it fails. 

Any updates or what it fails ?

**Comment by deeleeramone** [comment]
What is the error message? It works as expected when I try it.

> from openbb_terminal.sdk import openbb
> f = openbb.funds.load("Vanguard", "US")
> openbb.funds.historical(f, "2020-01-01", "2020-12-31")

Screenshot 2023-09-30 at 12 27 20 PM

**Comment by msh855** [comment]
The error I get is this: 

`AttributeError: Module or method '' has no attribute 'funds'.`

**Comment by jmaslek** [comment]
What version are you running?  (openbb.__version__)

**Comment by msh855** [comment]
I have upgrade the library to the latest version, but I now get a different error: 
```

openbb.funds(f, "2020-01-01", "2020-12-31")
Traceback (most recent call last):
  File "/Users/safishajjouz/opt/anaconda3/envs/obb/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-25a2a7dfc0a8>", line 1, in <module>
    openbb.funds(f, "2020-01-01", "2020-12-31")
TypeError: 'FundsRoot' object is not callable
```

**Comment by msh855** [comment]
It worked. Sorry, forgot to upgrade the package. Rookie issues.

**Pull request merged**
