### PR TITLE
Adding new portfolio metrics

### PR DESCRIPTION
**Pull request by northern-64bit**
# Description

Added new portfolio metrics to the metric command. These metrics are: 
        "gaintopain",
        "trackerr",
        "information",
        "tail",
        "commonsense",
        "jensens",
        "calmar",
        "kelly",
        "payoff",
        "profitfactor"

To do:

- [ ] Add risk of ruin
- [ ] Fix jensen's alpha (it acts weirdly, please help)

If anyone knows how to fix the commit log please message me.

# How has this been tested?

I ran all of the new metrics commands in the terminal and they seemed to work. Could someone please validate that they are correctly calculated?

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [x] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
Hey @northern-64bit,

What I am really missing is a simple Excel or Google Spreadsheet (or other tool) that illustrates that the calculations are correct. E.g. we need to be able to check whether the calculation makes logical sense to us.

I think I could just let this PR go through but it would be very high-level look at whether the calculations match that of what I wrote down. You think you can find a way to see if your calculations are correct? E.g. create a very simple portfolio and show that it works.

**Comment by northern-64bit** [comment]
> You think you can find a way to see if your calculations are correct? E.g. create a very simple portfolio and show that it works.

Sure, I'll make a simple portfolio in order to make a manual check with google sheets and then share it with you.

**Review by JerBouma — APPROVED** [review]
Approving this for now but we should re-check the metrics after portfolio refractor.

**Comment by northern-64bit** [comment]
This is ready to be merged now after the tests have been fixed.

**Pull request merged**
