### PR TITLE
Vscode/Github Codespaces dev container

### PR DESCRIPTION
**Pull request by jj701**
# Description

- [x] Summary of the change / bug fix.
 
Having dev containers makes its easier, faster and secure to setup the dev environment for the repository.

The pull request consists of:

- .devcontainer folder with:
    - **devcontainer.json :** (minimal necessary vscode extensions and settings)
    - **docker-compose.yaml :** (could be modified to run necessary services as per need)
    - **Dockerfile:**(non root with dev tools)
- Changes to README
    - added the Open in Github Codespaces Badge
    - added the Open in dev container Badge
- [ ] Link # issue, if applicable.

- [x] Screenshot of the feature or the bug before/after fix, if applicable.

image

- [x] Relevant motivation and context.

- Easy to setup dev environment
- More Secure dev environment as docker is non root
- Fast to bring up dev environment

- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.

I tried running the dev container locally in local vscode.
I tried bringing up github codespace for the repo

Both seems to work.

* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by PsuedoJack — APPROVED** [review]

**Comment by DidierRLopes** [comment]
This is sick!!! CC @the-praxs

**Comment by jj701** [comment]
@the-praxs @DidierRLopes  Were you able to test.

**Comment by DidierRLopes** [comment]
> I'm getting some issues, but @jmaslek got it to work.
> 
> I'll sync with him this week 🤝

I'm getting this for the GitHub Codespace one on charts: 
```
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-9077ca9692afa3d9389c8990ee2c2084-18a1b9a702c9abcb-00"}
```

It happens every now and then, but cannot pin point the cause. Once it happens the charts never work after and I need to exit application and start again.

**Comment by the-praxs** [comment]
> @the-praxs @DidierRLopes  Were you able to test.

I am going to test it today.

**Comment by goxcc** [comment]
nice

**Comment by jj701** [comment]
> 

So the you are able to open the repository in codespaces. Start the terminal. When loading charts, the error occurs intermittently. is that right?

**Comment by DidierRLopes** [comment]
> > 
> 
> So you are able to open the repository in codespaces. Start the terminal. When loading charts, the error occurs intermittently. is that right?

That is correct. And when it happens I can't have the charts working again so need to exit terminal and launch again. I wasn't able to spot a pattern. @jmaslek didn't have any issues on the other hand though.

I believe @aia is going to have a look at this too.

**Comment by aia** [comment]
Nice work, @jj701!

I have a few suggestions to improve this pull request.

1. In the README.md the text "Dev Containers" on the VSCode button is confusing. The first button in your pull request opens OpenBBTerminal repo in the local VSCode. The text on the first button should reflect that.
2. The second button you added in the README.md has a different style and size. I would add styling to the second button to at least match the size of the first button.
3. Next to the first and second button in the README.md, I would add a link to a brief description of what Dev Containers are and what can people expect. I would add a separate document with a brief intro into Dev Containers and a Q&A. I run into 404 Not Found error that Didier had. I am positive the error is because of the remote VM low CPU/Memory. I think covering this error in the Q&A would help.
4. The "customizations" section of the devcontainer.json holds the VSCode configuration on the remote container. I think we can do a lot better configuring VSCode for Dev Containers. We can add more VSCode extensions (e.g. Markdown, Mypy, linters, spelling) and we can configure VSCode to have a ready linting and debugging configuration.

**Comment by jj701** [comment]
> Nice work, @jj701!
> 
> I have a few suggestions to improve this pull request.
> 
> 1. In the README.md the text "Dev Containers" on the VSCode button is confusing. The first button in your pull request opens OpenBBTerminal repo in the local VSCode. The text on the first button should reflect that.
> 2. The second button you added in the README.md has a different style and size. I would add styling to the second button to at least match the size of the first button.
> 3. Next to the first and second button in the README.md, I would add a link to a brief description of what Dev Containers are and what can people expect. I would add a separate document with a brief intro into Dev Containers and a Q&A. I run into 404 Not Found error that Didier had. I am positive the error is because of the remote VM low CPU/Memory. I think covering this error in the Q&A would help.
> 4. The "customizations" section of the devcontainer.json holds the VSCode configuration on the remote container. I think we can do a lot better configuring VSCode for Dev Containers. We can add more VSCode extensions (e.g. Markdown, Mypy, linters, spelling) and we can configure VSCode to have a ready linting and debugging configuration.

Hi, For 1 and 2: Those are standard badges: 
https://docs.github.com/en/enterprise-cloud@latest/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/facilitating-quick-creation-and-resumption-of-codespaces#creating-an-open-in-github-codespaces-badge

For 3, Yes, you could  move the badge to new line and add more description to tell what they do and also have learn more link to the official documentation on devcontainers and codespaces.

For 4: I had left this empty, as I had lot of extensions not sure what would be needed, so thought users can add what they like. But Yeah, a initially set of extensions would be good, along with some settings for debugging, linting etc. You could add those configurations and extensions you think are needed that you might already be having.

**Review by jmaslek — APPROVED** [review]

**Comment by the-praxs** [comment]
> > Nice work, @jj701!
> > I have a few suggestions to improve this pull request.
> > 
> > 1. In the README.md the text "Dev Containers" on the VSCode button is confusing. The first button in your pull request opens OpenBBTerminal repo in the local VSCode. The text on the first button should reflect that.
> > 2. The second button you added in the README.md has a different style and size. I would add styling to the second button to at least match the size of the first button.
> > 3. Next to the first and second button in the README.md, I would add a link to a brief description of what Dev Containers are and what can people expect. I would add a separate document with a brief intro into Dev Containers and a Q&A. I run into 404 Not Found error that Didier had. I am positive the error is because of the remote VM low CPU/Memory. I think covering this error in the Q&A would help.
> > 4. The "customizations" section of the devcontainer.json holds the VSCode configuration on the remote container. I think we can do a lot better configuring VSCode for Dev Containers. We can add more VSCode extensions (e.g. Markdown, Mypy, linters, spelling) and we can configure VSCode to have a ready linting and debugging configuration.
> 
> Hi, For 1 and 2: Those are standard badges: https://docs.github.com/en/enterprise-cloud@latest/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/facilitating-quick-creation-and-resumption-of-codespaces#creating-an-open-in-github-codespaces-badge
> 
> For 3, Yes, you could move the badge to a new line, add more description to tell what they do and also have learn more link to the official documentation on devcontainers and codespaces.
> 
> For 4: I had left this empty, as I had lot of extensions not sure what would be needed, so thought users can add what they like. But Yeah, a initially set of extensions would be good, along with some settings for debugging, linting etc. Could you add those configurations and extensions you think are needed that, you might already have.

For extensions, the standard packages that come with OpenBB will suffice, which includes linting, formatting etc. One should be able to install additional packages based on their needs.

**Pull request merged**
