### PR TITLE
Hotfix/4526

### LINKED ISSUE #4526: [Bug] `stocks/fa/sec` - Doesn't know how to handle BRK-A
I know the data exists because: https://www.nasdaq.com/market-activity/stocks/brk-a/sec-filings

```
2023 Mar 17, 23:33 (🦋) /stocks/ $ load brk-a

Loading Daily data for BRK-A with starting period 2020-03-12.

2023 Mar 17, 23:33 (🦋) /stocks/ $ fa

2023 Mar 17, 23:33 (🦋) /stocks/fa/ $ sec

Error: 'NoneType' object has no attribute 'set_index'

Error: 'list' object has no attribute 'columns'


2023 Mar 17, 23:33 (🦋) /stocks/fa/ $ load brk.a

1 Failed download:
- BRK.A: No timezone found, symbol may be delisted

2023 Mar 17, 23:33 (🦋) /stocks/fa/ $ load brk.a --source Polygon

Loading Daily data for BRK.A with starting period 2020-03-12.

2023 Mar 17, 23:33 (🦋) /stocks/fa/ $ sec

Error: 'NoneType' object has no attribute 'set_index'

Error: 'list' object has no attribute 'columns'

### PR DESCRIPTION
**Pull request by colin99d**
# Description

Fixes #4526

This hits the nasdaq API directly, instead of web scraping market watch. So this is better in every way.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [ ] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deeleeramone** [comment]
```
2023 Apr 05, 13:06 (🦋) /stocks/fa/ $ sec --source FinancialModelingPrep

No filings found for ticker AAPL, consider increasing the value for --pages. Showing recent filings instead.
```

This source does not hit the correct endpoint for the function. The correct endpoint is here: https://site.financialmodelingprep.com/developer/docs/#Financial-Statements-List

**Comment by colin99d** [comment]
Im going to add the FMP endpoint, but it has some limitations, and it doesn't seem useful to me now that we are pulling directly from Nasdaq.

**Comment by colin99d** [comment]
Actually, per Jeroen it should just be deleted.

**Comment by deeleeramone** [comment]
@colin99d 

```
(🦋) /stocks/fa/ $ sec

Year will be ignored if form_group is not specified
No data found for AAPL
```

**Comment by deeleeramone** [comment]
I suggest upping the default value for `--limit` to be 100 instead of 20, thereby ensuring all results from the year and form type are returned.

There are a few items that need to be updated still:

- The help dialogue in the controller needs to be updated still.

Screenshot 2023-04-07 at 8 11 46 PM

- The description of the attribute within the StocksFundamentalAnalysis class:

Screenshot 2023-04-07 at 8 14 07 PM

The docstrings are pointing at a file that shouldn't exist anymore because the sources have both been replaced by a new one.

Screenshot 2023-04-07 at 8 16 13 PM

One item which may fall out of scope for this PR, because it is also all items in the module, is that with the new tables, the view aspect of the SDK becomes relevant and a reason to include the `_chart` version of each function.  `_chart` for all functions that returns a DataFrame can be a choice for using the interactive tables.

**Review by jmaslek — APPROVED** [review]
lgtm

**Comment by deeleeramone** [comment]
I have a question, why is there a new file called, "marketwatch_model.py", which only contains one function - which is sourced from Nasdaq?  There is already `market_watch_model`, this seems oddly confusing.

Screenshot 2023-04-11 at 2 26 05 PM

**Pull request merged**
