### PR TITLE
Improve the `stocks/search` command

### PR DESCRIPTION
**Pull request by JerBouma**
I saw this issue #4080 and found it odd that it didn't even list name and exchange. I've now made the following changes:

- When you query, it not only checks "long_name" but also "short_name" and merges the two where it prefers "short_name" if it exists.
- We were doing some mumbo jumbo with the exchanges which has now been replaced with the actual exchanges which makes a whole lot more sense.
- There is a filter in place that looks at the amount of NaN values in a row and then applies sorting to move them to the bottom, missing data usually means it has little data to being with.
- There is a `--all-exchanges` argument that's False by default. This means it only looks at United States exchanges unless this argument is added. This is beneficial since tickers without a suffix, like `.LI`, tend to have much more data available and are supported with all our other sources. These are only the tickers from United States exchanges. Generally, our functionally also breaks when you input a ticker from a different exchange. For example try something like `CC5.F` (Coca Cola in Frankfurt) and try to get fundamental data with `fa --source FinancialModelingPrep`. In an ideal world we map everything out back to `KO` but that's a multi-year project to do that well 😉 

For example, see the old:

```
(🦋) /stocks/ $ search --query microsoft

                                            Companies found on term microsoft
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃         ┃ Name                               ┃ Country       ┃ Sector     ┃ Industry                  ┃ Exchange      ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ MSF.BR  │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSF.DE  │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSF.F   │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSF2.L  │ Leverage Shares 2x Microsoft ETC A │ None          │ None       │ None                      │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSF3.L  │ Leverage Shares 3x Microsoft ETC   │ None          │ None       │ None                      │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSFS.L  │ Leverage Shares -1x Microsoft ETC  │ None          │ None       │ None                      │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSFT.BA │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSFT.MX │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ None          │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSFT    │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ United States │
├─────────┼────────────────────────────────────┼───────────────┼────────────┼───────────────────────────┼───────────────┤
│ MSFT.SN │ Microsoft Corporation              │ United States │ Technology │ Software - Infrastructure │ None          │
└─────────┴────────────────────────────────────┴───────────────┴────────────┴───────────────────────────┴───────────────┘

(🦋) /stocks/ $
```

And new which is perfect since this is exactly what you need:

```
(🦋) /stocks/ $ search --query microsoft

                                 Companies found on term microsoft                                  
┏━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃      ┃ Name                  ┃ Country       ┃ Sector     ┃ Industry                  ┃ Exchange ┃
┡━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ MSFT │ Microsoft Corporation │ United States │ Technology │ Software - Infrastructure │ NMS      │
└──────┴───────────────────────┴───────────────┴────────────┴───────────────────────────┴──────────┘
```

This more beautifully comes together when you grab something that would otherwise give you a bunch of Nones:

```
(🦋) /stocks/ $ search --exchange united_kingdom

             Companies found on an exchange in United Kingdom
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┓
┃         ┃ Name             ┃ Country     ┃ Sector ┃ Industry ┃ Exchange ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━┩
│ 0A00.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A02.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A05.L  │ Medacta Group SA │ Switzerland │        │          │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0C.L  │ Stadler Rail AG  │ Switzerland │        │          │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0D.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0E.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0F.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0H.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0I.IL │ None             │ None        │ None   │ None     │ None     │
├─────────┼──────────────────┼─────────────┼────────┼──────────┼──────────┤
│ 0A0J.IL │ None             │ None        │ None   │ None     │ None     │
└─────────┴──────────────────┴─────────────┴────────┴──────────┴──────────┘
````

Which now returns:
````
(🦋) /stocks/ $ search --exchange united_kingdom

                                             Companies found on an exchange in United Kingdom                                              
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃        ┃ Name                                     ┃ Country        ┃ Sector                 ┃ Industry                       ┃ Exchange ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ AML.L  │ Aston Martin Lagonda Global Holdings plc │ United Kingdom │ Consumer Cyclical      │ Auto Manufacturers             │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ CYBA.L │ Cyba Plc                                 │ United Kingdom │ Financial Services     │ Shell Companies                │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ D4T4.L │ D4t4 Solutions Plc                       │ United Kingdom │ Technology             │ Software - Application         │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DAL.L  │ Dalata Hotel Group plc                   │ Ireland        │ Consumer Cyclical      │ Lodging                        │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DARK.L │ Darktrace plc                            │ United Kingdom │ Technology             │ Software - Infrastructure      │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DATA.L │ GlobalData Plc                           │ United Kingdom │ Industrials            │ Consulting Services            │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DBOX.L │ Digitalbox plc                           │ United Kingdom │ Communication Services │ Internet Content & Information │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DC.L   │ Dixons Carphone plc                      │ United Kingdom │ Consumer Cyclical      │ Specialty Retail               │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DCC.L  │ DCC plc                                  │ Ireland        │ Energy                 │ Oil & Gas Refining & Marketing │ LSE      │
├────────┼──────────────────────────────────────────┼────────────────┼────────────────────────┼────────────────────────────────┼──────────┤
│ DCD.L  │ DCD Media Plc                            │ United Kingdom │ Communication Services │ Entertainment                  │ LSE      │
└────────┴──────────────────────────────────────────┴────────────────┴────────────────────────┴────────────────────────────────┴──────────┘
````

Another one for funsies:

```
(🦋) /stocks/ $ search coca-cola

                                                  Companies found on term coca-cola
┏━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃         ┃ Name                                   ┃ Country        ┃ Sector             ┃ Industry                  ┃ Exchange      ┃
┡━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ 2573.T  │ Hokkaido Coca-Cola Bottling Co.,Ltd.   │ Japan          │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ 2579.T  │ Coca-Cola Bottlers Japan Holdings Inc. │ Japan          │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ C0Q.F   │ Coca-Cola HBC AG                       │ Switzerland    │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CC5.F   │ Coca-Cola Consolidated, Inc.           │ United States  │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CCC3.DE │ The Coca-Cola Company                  │ United States  │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CCC3.F  │ The Coca-Cola Company                  │ United States  │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CCEP.AS │ Coca-Cola Europacific Partners PLC     │ United Kingdom │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CCEP.L  │ Coca-Cola Europacific Partners PLC     │ United Kingdom │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CCEP.MC │ Coca-Cola Europacific Partners PLC     │ United Kingdom │ Consumer Defensive │ Beverages - Non-Alcoholic │ None          │
├─────────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼───────────────┤
│ CCEP    │ Coca-Cola Europacific Partners PLC     │ United Kingdom │ Consumer Defensive │ Beverages - Non-Alcoholic │ United States │
└─────────┴────────────────────────────────────────┴────────────────┴────────────────────┴───────────────────────────┴───────────────┘
```

And new:

```
(🦋) /stocks/ $ search coca-cola

                                               Companies found on term coca-cola                                               
┏━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃       ┃ Name                                   ┃ Country        ┃ Sector             ┃ Industry                  ┃ Exchange ┃
┡━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━┩
│ CCEP  │ Coca-Cola Europacific Partners PLC     │ United Kingdom │ Consumer Defensive │ Beverages - Non-Alcoholic │ NYQ      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ CCHBF │ Coca-Cola HBC AG                       │ Switzerland    │                    │                           │ PNK      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ CCHGY │ Coca-Cola HBC AG                       │ Switzerland    │ Consumer Defensive │ Beverages - Non-Alcoholic │ PNK      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ CCLAF │ Coca-Cola Amatil Limited               │ Australia      │ Consumer Defensive │ Beverages - Non-Alcoholic │ PNK      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ CCLAY │ Coca-Cola Amatil Limited               │ Australia      │ Consumer Defensive │ Beverages - Non-Alcoholic │ PNK      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ CCOJY │ Coca-Cola Bottlers Japan Holdings Inc. │ Japan          │ Consumer Defensive │ Beverages - Non-Alcoholic │ PNK      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ COCSF │ Coca-Cola FEMSA, S.A.B. de C.V.        │ Mexico         │ Consumer Defensive │ Beverages - Non-Alcoholic │ PNK      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ COKE  │ Coca-Cola Consolidated, Inc.           │ United States  │ Consumer Defensive │ Beverages - Non-Alcoholic │ NMS      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ KO    │ The Coca-Cola Company                  │ United States  │ Consumer Defensive │ Beverages - Non-Alcoholic │ NYQ      │
├───────┼────────────────────────────────────────┼────────────────┼────────────────────┼───────────────────────────┼──────────┤
│ KOF   │ Coca-Cola FEMSA, S.A.B. de C.V.        │ Mexico         │ Consumer Defensive │ Beverages - Non-Alcoholic │ NYQ      │
└───────┴────────────────────────────────────────┴────────────────┴────────────────────┴───────────────────────────┴──────────┘
```

### CODE REVIEW

**Comment by jmaslek** [comment]
Anything on the guides need to be updated?

**Comment by JerBouma** [comment]
> Anything on the guides need to be updated?

Yes give me 10 min, almost ready.

**Comment by jmaslek** [comment]
okie dokie.  Tested and works on my end so ill approve.

**Comment by JerBouma** [comment]
Ok done!

**Comment by jmaslek** [comment]
> Ok done!

now fix ur failing tests

**Comment by JerBouma** [comment]
Ok done

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
> Ok done

now go to bed.  its late and ur making me tired

**Pull request merged**
