### PR TITLE
New portfolio optimization menu

### PR DESCRIPTION
**Pull request by dcajasn**
# Description

This PR updates the Portfolio Optimization menu. It adds several new portfolio optimization models that are available in Riskfolio-Lib and allows the user plots new charts for optimal portfolios: histogram, drawdown, risk contribution and correlation heatmap. Also add the option to build the efficient frontier for additional risk measures.

Some examples:
```
2022 Apr 05, 18:44 (🦋) /portfolio/po/ $ add MSFT,AMZN,TSLA,BA,T,FB,AAPL

2022 Apr 05, 18:51 (🦋) /portfolio/po/ $ hrp -p 5y --heat --pie --rc-chart --his
 --dd

 [5 Years] Hierarchical risk parity portfolio using pearson codependence,
single linkage and volatility as risk measure

     Weights      
┏━━━━━━┳━━━━━━━━━┓
┃      ┃ Value   ┃
┡━━━━━━╇━━━━━━━━━┩
│ AAPL │ 14.37 % │
├──────┼─────────┤
│ AMZN │ 14.80 % │
├──────┼─────────┤
│ BA   │  7.5 %  │
├──────┼─────────┤
│ FB   │ 10.87 % │
├──────┼─────────┤
│ MSFT │ 17.19 % │
├──────┼─────────┤
│ T    │ 28.97 % │
├──────┼─────────┤
│ TSLA │  6.28 % │
└──────┴─────────┘

Annual (by 252) expected return: 23.61%
Annual (by √252) volatility: 22.85%
Sharpe ratio: 1.0249
```
Figure_1

Figure_2

Figure_3

Figure_4

Figure_5

```
2022 Apr 05, 18:51 (🦋) /portfolio/po/ $ ef -p 5y -rm CVaR
```

frontier

# How has this been tested?

I'm still writing tests but I would like your opinion about new features.

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by JerBouma** [comment]
Hey @dcajasn,

First of all, great work. The functionalities you have added will improve the Portfolio menu by a lot. My first question would be when are you going to make an Excel sheet that people can use to set their preferences? As there are so many options, it is very relevant that this can be directly done via an Excel. **This is absolutely crucial for this menu to work.**

**A few comments:**
I want you to think carefully about each parameter and if it makes sense that they are all actually there. For example, when it comes to data collection from Yahoo Finance. Is it absolutely crucial that this is determined for each argument or could this be inside the menu as done in the "SIA" menu? Parameters that are **probably** constant between all commands should also be set accordingly within the menu.

image

I think that all of these could be set similarly to how you see it on the SIA menu:
```
  -p PERIOD, --period PERIOD
                        Period to get yfinance data from (default: 3y)
  -s START, --start START
                        Start date to get yfinance data from (default: )
  -e END, --end END     End date to get yfinance data from (default: )
  -lr, --log-returns    If use logarithmic or arithmetic returns to calculate returns (default: False)
  -f {d,w,m}, --freq {d,w,m}
                        Frequency used to calculate returns (default: d)
  -mn MAXNAN, --maxnan MAXNAN
                        Max percentage of nan values accepted per asset to be considered in the optimization process (default: 0.05)
  -th THRESHOLD, --threshold THRESHOLD
                        Value used to replace outliers that are higher to threshold in absolute value (default: 0.3)
  -mt METHOD, --method METHOD
                        Method used to fill nan values (default: time)
```

You have added a lot of parameters to each command. E.g. maxnan, threshold, method, rm, risk_free, alpha, target_return and more. I would like to invite you to include all of these parameters in the documentation and explain what each represents. E.g. what is FLPM or what is EWMA1 and EWMA2 or what is the difference between relaxed risk parity model A, B and C. It needs to abundantly clear what settings I am using and what they represent. You don't have to explain the entire mathematics as long as it makes sense for the Financial professional.

To reduce the amount of arguments, one suggestion be to create a different command that does the plotting. To achieve this, you can "store" your calculations. E.g. if I run maxsharpe, it will store as "maxsharpe1" (and the next will be "maxsharpe2" if settings change. Then I can plot pie charts of maxsharpe1 and maxsharpe2 to graphically understand the difference X parameter makes. This command could also allow for combining certain plots for example.

Could you look at the "*Other optimization techniques*" and see if they can fit in a category and if it is old commands, if they can be removed? We don't want too many functionalities if they don't even make too much sense.

**I still need to look into the theory of all the options but these are some general pointers at least.**

**Comment by dcajasn** [comment]
Hi @JerBouma, following your comments I split plot functions from portfolio optimization models. Also, I added the option to save portfolios and then make plots to compare them. I'm starting to work with the excel template to create most complex portfolios and finishing to update documentation.

**Comment by dcajasn** [comment]
Hi @JerBouma, I added riskfolio-lib modules. It is working without problems but I need to make some changes to pass flake8 pre-commit-hooks.

**Comment by JerBouma** [comment]
Just added in Excel params capabilities. Next up is making it possible to take this params to the optimization menu and run optimization commands with them.

**Comment by JerBouma** [comment]
Hey @dcajasn!

Could you provide an update on the progress of the following items we had in mind and when you expect to finish them?

- Full integration of Black-Litterman model, with the desire this is based on our Excel sheet. However, it should also work from within the terminal (even though it could be a hassle to define all those parameters for the user, that’s not a problem).
- I want the ability to show portfolio changes from a strategic level, this means the ability to define the % in stocks, real estate, bonds, infrastructure, hedge funds etc instead of the individual assets. By allowing for setting categories, this should be possible relatively easily.
- Sensitivity analysis build in that allows you to make corrections to returns to obtain a more pessimistic or optimistic view as well. If your mean variance optimisation is based on a couple stocks doing incredibly well, I would want to understand what my portfolio looks like if those stock returns or categories were tuned down. I am aware of the threshold for outliers that is currently in place, I am looking for a way to separate between asset classes. E.g. 15% return on bonds is incredible while it isn’t on stocks.
- Extra: A forward-looking approach. If I provide a model with estimates for the future for an asset class or stock, how would my portfolio change over time (e.g. the next 5, 10 and 15 years)?

**Comment by JerBouma** [comment]
@dcajasn Can you move the loading of a person's allocation to **portfolio/allocation**. We need atleast the following fields within the Excel:

- Ticker
- Asset Class (Public Equity, Private Equity, Fixed Income, Real Estate, Infrastructure, Credits, Cash and Cash Equivalents)
- Sector
- Industry
- Country
- Current invested amount (so you can determine the current portfolio as well compared to the optimized portfolio)

It is fine the current sector/industry/country parameters are randomly chosen. It is also fine to use ETFs to replicate private markets.

**Comment by dcajasn** [comment]
Hi @JerBouma,

Progress to date:
- Black Litterman model and view are ready, controller is at 50%. We need the Excel format for Black Litterman to upload matrix parameters like views (P and Q). 
- Excel function for asset class in required format is at 90%, today I’m going to push updates. I was thinking to add two columns to compare current portfolio weights (estimated from current investment amount) to selected portfolio.
- About sensitivity analysis, I’m working on a draft script that allows to select best features (factors in our case) using linear regression. On the other hand, I think that it could be better if we estimate sensitivity of each portfolio’s asset class for a group of specific factors. For example if we have two asset classes: equities and fixed income, users upload factors for equity (value, growth, etc) and fixed income (interest rates returns). Then the terminal estimate the sensitivities for each asset in equity asset class using equity factors and calculate portfolio sensitivity using a weighted sum. In the case of fixed income, the same procedure but using fixed income factors.

**Comment by JerBouma** [comment]
Hey @dcajasn,

Thank you for the update, good you are making so much progress already. **I find it important you focus primarily on the first two points.**

For the sensitivity analysis, we can do this at a later stage. When it comes to sensitivity analyses I mostly meant what happens if I alter my expected return or targets and not so much how sensitive each asset class is to different factors. This is _portfolio attribution_ which we won't focus on for some time and thus it not a priority at all.

Do you expect to be able to finish the first two points before next wednesday? (27th of April)

**Comment by dcajasn** [comment]
Hi @JerBouma,

The second point I think is finished, because now using the show command we can display weights based on sector, industry and country, segmented by currency with subtotals per currency.
I'm going to focus on finished the first point. I think that I'm going to finished that point for this weekend.

**Comment by JerBouma** [comment]
Hi @dcajasn,

I see you made some progress again, could you give me a status update? And is there anything I could help you with?

**Comment by dcajasn** [comment]
Hi @JerBouma, 

I'm still working, fixing some small bugs, updating documentation and adding the option to upload an excel with views. Now blacklitterman cmd allow us to build views using a notation similar to Matlab (better for small portfolios). To build a P matrix we separate columns by "," and rows by ";". In the case of Q matrix we only use "," because is a vector. For example, matrices P 1,0,0;0,1,0 and Q 0.1,0.2  means that the analyst expects that the first asset has a 10% annual return and second asset a 20% annual return. 
In the case of the benchmark portfolio, by default the blacklitterman cmd uses the market cap portfolio, following Black Litterman original model, but also we can change the benchmark by one of our saved portfolios. Also, we can select the objective function to run the optimization using Black Litterman inputs.

**Comment by JerBouma** [comment]
Hi @dcajasn,

Thanks for the update. Are you primarily focussed on the BL model now? Then I’ll work on the ability to load in the stocks Excel (saw that didn’t point correctly yet) and I will make the params menu work with each function. Does that sound alright to you?

**Comment by dcajasn** [comment]
I'm focus on BL now and documentation. For the excel, I was planning to do something similar to the cmd load_stocks and add two parameters to load the P and Q matrices, --filename and --folder using "\" to define a path instead of "/" because it create errors.

**Comment by JerBouma** [comment]
Great! It is actually perfectly fine to only search within the **portfolio/optimization** folder structure we have set up for now. Then, you don't really need any added complexity. So, similarly how it works with the `file` command.

**Comment by JerBouma** [comment]
> I'm focus on BL and documentation now. For the excel, I was planning to do something similar to the cmd load_stocks and add two parameters to load the P and Q matrices, --filename and --folder using "" to define a path instead of "/" because it create errors.

Hi Dany, could you push your commits? Then I can work on top of that since I am making some larger changes to the overall structure.

**Comment by JerBouma** [comment]
Hi @dcajasn,

We are almost there 💪 

Could you look into the ability to plot by sector, industry, country and asset class? E.g. if I want to see risk contributions of each sector or if I want to see my allocation to each industry? When you load in a lot of assets, it otherwise leads to meaningless graphs.

This is done with the **allocation_jeroen_equity_only.xlsx** file.

See below:
Screenshot 2022-04-26 at 11 37 46
Screenshot 2022-04-26 at 11 37 30

**Comment by dcajasn** [comment]
Hi @JerBouma, 

Sure, I'm going to add the option to plot by a specific category.

**Comment by dcajasn** [comment]
Hi @JerBouma 

I added the option to build plots for assets grouped by category for pie, heatmap and risk contribution.

**Comment by JerBouma** [comment]
Hi @dcajasn,

Thank you, looks great. Could you look into the following points:

- I am still waiting for the Black-Litterman Excel sheet, when do you expect to finish this?
- I've noticed that the `-dd` argument of `plot` doesn't work. Could you look into this? See below.
Screenshot 2022-04-28 at 10 36 01
- Could you convert the charts into the style of OpenBB? Below is our graphing style and is usually automatically applied. See `stocks/sia/cpcs` for example.
Screenshot 2022-04-28 at 10 40 25
- When you run the `show` command, you receive an error. This is most likely because it tries to categorize the column with invested values. Could you fix this?
Screenshot 2022-04-28 at 10 42 55

**Comment by dcajasn** [comment]
Hi @JerBouma, I'm going to fix the bugs asap. In the case of the Excel, I was thinking that you will design all Excels for the portfolio optimization menu like input parameters and Black Litterman, but no problem I will create and Excel for p_views and q_views.

**Comment by JerBouma** [comment]
For `-dd` if I try the following:
```
2022 Apr 29, 04:40 (🦋) /portfolio/po/ $ load 50:30:10:10 Portfolio.xlsx
2022 Apr 29, 04:40 (🦋) /portfolio/po/ $ file OpenBB_Parameters_Template v1.0.0.xlsx
Parameters:
    historic_period         : 3y
    log_returns             : 0
    return_frequency        : d
    max_nan                 : 0.05
    threshold_value         : 0.3
    nan_fill_method         : time
    risk_free               : 0.003
    significance_level      : 0.05
    risk_measure            : MV
    target_return           : -1
    target_risk             : -1
    expected_return         : hist
    covariance              : hist
    smoothing_factor_ewma   : 0.94
    long_allocation         : 1
    short_allocation        : 0

2022 Apr 29, 04:41 (🦋) /portfolio/po/ $ riskparity

 [3 Years] Risk parity portfolio based on risk budgeting approach
using volatility as risk measure

      Weights       
┏━━━━━━━┳━━━━━━━━━━┓
┃       ┃ Value    ┃
┡━━━━━━━╇━━━━━━━━━━┩
│ AAPL  │   3.24 % │
├───────┼──────────┤
│ AMZN  │   4.03 % │
├───────┼──────────┤
│ APTV  │   2.15 % │
├───────┼──────────┤
│ ASML  │   2.45 % │
├───────┼──────────┤
│ BABA  │   3.40 % │
├───────┼──────────┤
│ GOOGL │   3.49 % │
├───────┼──────────┤
│ HYG   │   9.30 % │
├───────┼──────────┤
│ IYR   │   3.95 % │
├───────┼──────────┤
│ NKE   │   3.69 % │
├───────┼──────────┤
│ PEX   │   3.84 % │
├───────┼──────────┤
│ PSP   │   3.46 % │
├───────┼──────────┤
│ REZ   │   4.04 % │
├───────┼──────────┤
│ TIP   │  26.93 % │
├───────┼──────────┤
│ TLT   │  22.75 % │
├───────┼──────────┤
│ TSM   │   3.28 % │
└───────┴──────────┘
Annual (by 252) expected return: 10.10%
Annual (by √252) volatility: 11.21%
Sharpe ratio: 0.8741

2022 Apr 29, 04:41 (🦋) /portfolio/po/ $ plot -pf RP_0 -dd
Error: 'AxesSubplot' object is not iterable
```

**Comment by dcajasn** [comment]
@JerBouma here is working well.

```
2022 Apr 29, 10:45 (🦋) /portfolio/po/ $ load 50:30:10:10 Portfolio.xlsx
2022 Apr 29, 10:45 (🦋) /portfolio/po/ $ file OpenBB_Parameters_Template v1.0.0.
xlsx
Parameters:
    historic_period         : 3y
    log_returns             : 0
    return_frequency        : d
    max_nan                 : 0.05
    threshold_value         : 0.3
    nan_fill_method         : time
    risk_free               : 0.003
    significance_level      : 0.05
    risk_measure            : MV
    target_return           : -1
    target_risk             : -1
    expected_return         : hist
    covariance              : hist
    smoothing_factor_ewma   : 0.94
    long_allocation         : 1
    short_allocation        : 0

2022 Apr 29, 10:46 (🦋) /portfolio/po/ $ riskparity

 [3 Years] Risk parity portfolio based on risk budgeting approach
using volatility as risk measure

      Weights       
┏━━━━━━━┳━━━━━━━━━━┓
┃       ┃ Value    ┃
┡━━━━━━━╇━━━━━━━━━━┩
│ AAPL  │   3.24 % │
├───────┼──────────┤
│ AMZN  │   4.03 % │
├───────┼──────────┤
│ APTV  │   2.15 % │
├───────┼──────────┤
│ ASML  │   2.45 % │
├───────┼──────────┤
│ BABA  │   3.40 % │
├───────┼──────────┤
│ GOOGL │   3.49 % │
├───────┼──────────┤
│ HYG   │   9.30 % │
├───────┼──────────┤
│ IYR   │   3.95 % │
├───────┼──────────┤
│ NKE   │   3.69 % │
├───────┼──────────┤
│ PEX   │   3.84 % │
├───────┼──────────┤
│ PSP   │   3.46 % │
├───────┼──────────┤
│ REZ   │   4.04 % │
├───────┼──────────┤
│ TIP   │  26.93 % │
├───────┼──────────┤
│ TLT   │  22.75 % │
├───────┼──────────┤
│ TSM   │   3.28 % │
└───────┴──────────┘
Annual (by 252) expected return: 10.10%
Annual (by √252) volatility: 11.21%
Sharpe ratio: 0.8741

2022 Apr 29, 10:46 (🦋) /portfolio/po/ $ plot -pf RP_0 -dd
```
Figure_1

**Comment by JerBouma** [comment]
Hi @dcajasn,

As there is a new Sprint starting today, I will merge this PR and I would like you to focus on working with Jira. Please talk which Chavi or Theodore if things are unclear. See the Epic: https://openbb.atlassian.net/jira/software/c/projects/PROD/boards/13

**Review by JerBouma — APPROVED** [review]

**Pull request merged**
