### PR TITLE
Adjust timezone for AV when interval < 1d

### LINKED ISSUE #3883: [Bug] Forex/Load --source AlphaVantage: Timestamp is wrong, five hours ahead of now.
```
2023 Jan 06, 12:45 (🦋) /forex/ $ load JPYUSD --source AlphaVantage --interval 15min

JPY-USD loaded.


2023 Jan 06, 12:46 (🦋) /forex/ $ candle
```

Screenshot 2023-01-06 at 9 47 30 AM

### PR DESCRIPTION
**Pull request by hjoaquim**
# Description

- [x] Summary of the change / bug fix.
Adjust timezone to user config on loading a fx pair from AV.

- [x] Link # issue, if applicable.
Fix #3883

- [ ] Screenshot of the feature or the bug before/after fix, if applicable.

- [x] Relevant motivation and context.
:bug: :skull_and_crossbones: 

- [x] List any dependencies that are required for this change.
NA

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works

```python
from openbb_terminal.sdk import openbb
openbb.forex.load(
    from_symbol="EUR", 
    to_symbol="USD", 
    start_date="2020-11-30", 
    end_date="2022-12-01",
    source="AlphaVantage"
)
```
TODO: 
   - [ ] Test with an interval < 1d

- [x] Check any related reports

# Checklist:

- [x] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by hjoaquim** [comment]
@deeleeramone would you please give me a help trying this out?

I don't have access to premium endpoints :tired_face:  :

```
2023 Feb 07, 13:03 (🦋) /forex/ $ load JPYUSD --source AlphaVantage --interval 15min

Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints

No historical data loaded.

Make sure you have appropriate access for the 'AlphaVantage' data source and that 'AlphaVantage' supports the requested range.

2023 Feb 07, 13:08 (🦋) /forex/ $
```

**Comment by jmaslek** [comment]
NOt a bug, but I am noticing that we don't grab adjusted when it is available: https://www.alphavantage.co/documentation/#dailyadj:

Screenshot 2023-02-07 at 7 19 37 PM

**Review by jmaslek — APPROVED** [review]
I uhhhh dont have a premium key either but it works.  Its 19:20 locally and that looks like the latest timestamp when it previously was utc

Screenshot 2023-02-07 at 7 22 36 PM

**Comment by deeleeramone** [comment]
I get no timestamp and some weird column, Date_Id

```
2023 Feb 07, 19:27 (🦋) /forex/ $ candle --raw

                                         Raw Data                                          
┏━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃            ┃ Open  ┃ High  ┃ Low   ┃ Close ┃ Date_Id ┃ Oc_High ┃ Oc_Low ┃ Ma20  ┃ Ma50  ┃
┡━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
├────────────┼───────┼───────┼───────┼───────┼─────────┼─────────┼────────┼───────┼───────┤
│ 2023-02-07 │ 0.008 │ 0.008 │ 0.008 │ 0.008 │ 6.000   │ 0.008   │ 0.008  │ 0.008 │ 0.008 │
└────────────┴───────┴───────┴───────┴───────┴─────────┴─────────┴────────┴───────┴───────┘
```


```
2023 Feb 07, 19:26 (🦋) /forex/ $ load JPYUSD --source AlphaVantage -i 5min

JPY-USD loaded.
```


Screenshot 2023-02-07 at 4 28 58 PM

**Review by jmaslek — CHANGES_REQUESTED** [review]
guess not fixed per danglewood

**Comment by hjoaquim** [comment]
> 

Guess those are just for stocks, but indeed, we might want to use it!

**Comment by hjoaquim** [comment]
> I get no timestamp and some weird column, Date_Id

I think the default behavior is to not show tz info on the `candle --raw`?
So we'll need to look to the `candle` chart itself or export it to a csv:

image

Regarding the column `Date_Id`, not sure of what it represents or if it's useful - but does not relate with our discussion on the timezone.

**Comment by hjoaquim** [comment]
^ regarding my last comment, it seems that `Date_Id` is then used on `stocks_helper.find_tendline`

**Comment by jmaslek** [comment]
> > I get no timestamp and some weird column, Date_Id
> 
> I think the default behavior is to not show tz info on the `candle --raw`? So we'll need to look to the `candle` chart itself or export it to a csv:


In qa_view.display_raw we have the following:
```
df1.index = [x.strftime("%Y-%m-%d") for x in df1.index]
```
Note this applies to all of our candle functions (doing load -i 1 on stocks then candle raw shows this as well).

The extra columns are because we dont copy the df when we do the prepare candle stuff/

Since the ticket is for tz, this solves it.  Can open a new ticket for tz in candle raw

Screenshot 2023-02-08 at 10 07 26 AM

**Review by jmaslek — APPROVED** [review]

**Comment by hjoaquim** [comment]
>  Can open a new ticket for tz in candle raw

Agreed. Will be a cool little detail we can add let's say with some flag

**Pull request merged**
