### PR TITLE
Account Menu

### PR DESCRIPTION
**Pull request by colin99d**
# Description

This PR adds the account menu. This menu lets you do the following things:

- Login to your OpenBB account
- Register for an OpenBB account (for now it just opens a browser to your current menu)
- Upload your settings and keys (keys are encrypted)
- Download your settings and keys (which are automatically loaded into the terminal
- Send your script file to the server
- Get other script files from users (not fully implemented yet)

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by jmaslek — CHANGES_REQUESTED** [review]
Need to do super deep dive

**Comment by colin99d** [comment]
> Need to do super deep dive

100%

**Comment by jmaslek** [comment]
@montezdesousa can you point this at develop?

**Comment by montezdesousa** [comment]
> @montezdesousa can you point this at develop?

will have to rename the branch later as well

**Comment by jmaslek** [comment]
> > @montezdesousa can you point this at develop?
> 
> will have to rename the branch later as well

we can hold off on the branch name check requirement for now

**Comment by Chavithra** [comment]
@colin99d @jmaslek @montezdesousa 
Closing this PR since we are not building it as defined here.

I think it will be easier to add features as there are getting defined than trying to adapt this version.

**Pull request closed without merging**
