### PR TITLE
Code Coverage

### PR DESCRIPTION
**Pull request by luqmanbello**
- Implement code coverage

### CODE REVIEW

**Comment by Chavithra** [comment]
Hi @luqmanbello,

fixed the tests.

I think we should combine "coverage" CI and tests CI.

Or something like this to avoid running the tests twice.

**Review by Chavithra — APPROVED** [review]
Looks ok to me.

**Comment by luqmanbello** [comment]
> Hi @luqmanbello,
> 
> fixed the tests.
> 
> I think we should combine "coverage" CI and tests CI.
> 
> Or something like this to avoid running the tests twice.
> 
> Thanks

Since we are not enforcing it yet, we can combine it with the unit test

**Comment by jmaslek** [comment]
Should we have the code cov depend on the check for changes so that the tests arent running when no .py files are changed?

**Comment by luqmanbello** [comment]
> Should we have the code cov depend on the check for changes so that the tests arent running when no .py files are changed?

That's what I just implemented. it will also only run on the `base-test`

**Pull request merged**
