### PR TITLE
Docs/contributing guidelines

### PR DESCRIPTION
**Pull request by hjoaquim**
Improving the contributing guidelines section on the website docs.

### CODE REVIEW

**Comment by hjoaquim** [comment]
@piiq I generated the keywords and descriptions with the help of Cursor. Is there any other custom process I should follow instead for an SEO optimized set of keywords and descriptions?

**Comment by deeleeramone** [comment]
@hjoaquim, this is good stuff. Let's port this over to the branch I'm working on.  I do have a question though, under Developer Guidelines we have Expectations for Developers, which is the same as Expectations for Contributors.  As we have separated the personas here, are we under the assumption that developers are not going to be submitting PRs but are building on top for their own purposes?

**Comment by hjoaquim** [comment]
> @hjoaquim, this is good stuff. Let's port this over to the branch I'm working on. I've merged this PR into #5720.
> 
> I do have a question though, under Developer Guidelines we have Expectations for Developers, which is the same as Expectations for Contributors. As we have separated the personas here, are we under the assumption that developers are not going to be submitting PRs but are building on top for their own purposes?

As I view it, yes, that's it!

**Comment by hjoaquim** [comment]
Closing this PR in favor of #5720.

**Pull request closed without merging**
