### PR TITLE
Fix plot look when using eval and add query to choices

### PR DESCRIPTION
**Pull request by montezdesousa**
# Description

Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3838

Screenshot 2023-01-06 at 15 45 32
nance/OpenBBTerminal/issues/3838

Test:
`economy`
`fred SOFR,AMERIBOR`
`eval spread=SOFR-AMERIBOR`
`plot spread`

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [ ] Make sure affected commands still run in terminal
- [ ] Ensure the SDK still works
- [ ] Check any related reports

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
kind of out of scope, but `eval spread=sofr-ameribor` doesn't work because it expects a match on capital SOFR.  Should we make the query upper case?

**Comment by jmaslek** [comment]
> kind of out of scope, but `eval spread=sofr-ameribor` doesn't work because it expects a match on capital SOFR. Should we make the query upper case?

actually this won't work because macro has mixed cases.  Should have a uniform way of doing these,

**Review by jmaslek — APPROVED** [review]
This does fix the bug.  The feature itself has a lot more that could be improved (*looks at who wrote feature* - jk its perfect)

**Comment by montezdesousa** [comment]
> > kind of out of scope, but `eval spread=sofr-ameribor` doesn't work because it expects a match on capital SOFR. Should we make the query upper case?
> 
> actually this won't work because macro has mixed cases. Should have a uniform way of doing these,

what's the case where it does not work?

**Comment by jmaslek** [comment]
> > > kind of out of scope, but `eval spread=sofr-ameribor` doesn't work because it expects a match on capital SOFR. Should we make the query upper case?
> > 
> > 
> > actually this won't work because macro has mixed cases. Should have a uniform way of doing these,
> 
> what's the case where it does not work?

So if you just do macro gdp, the macro will have column: `united_states_GDP`.  (note doing `eval newCol=united_states_GDP*SOFR` wont work because of mismatched indices), but we should be case insensitive

**Comment by montezdesousa** [comment]
> This does fix the bug. The feature itself has a lot more that could be improved (_looks at who wrote feature_ - jk its perfect)

I actually found another bug while running the integration test script. So if you load the same series twice it was concatenating both instead of replacing it. That was blocking `qa` menu afterwards

**Comment by montezdesousa** [comment]
> > > > kind of out of scope, but `eval spread=sofr-ameribor` doesn't work because it expects a match on capital SOFR. Should we make the query upper case?
> > > 
> > > 
> > > actually this won't work because macro has mixed cases. Should have a uniform way of doing these,
> > 
> > 
> > what's the case where it does not work?
> 
> So if you just do macro gdp, the macro will have column: `united_states_GDP`. (note doing `eval newCol=united_states_GDP*SOFR` wont work because of mismatched indices), but we should be case insensitive

got it, so we either block the user if not perfect match between indices, or we can merge the indices and apply the eval transform on the overlap of both series only

**Comment by jmaslek** [comment]
> > > > > kind of out of scope, but `eval spread=sofr-ameribor` doesn't work because it expects a match on capital SOFR. Should we make the query upper case?
> > > > 
> > > > 
> > > > actually this won't work because macro has mixed cases. Should have a uniform way of doing these,
> > > 
> > > 
> > > what's the case where it does not work?
> > 
> > 
> > So if you just do macro gdp, the macro will have column: `united_states_GDP`. (note doing `eval newCol=united_states_GDP*SOFR` wont work because of mismatched indices), but we should be case insensitive
> 
> got it, so we either block the user if not perfect match between indices, or we can merge (inner) the indices and apply the eval transform on the overlap of both series only

Yeah.  Right now I think I just loop through each dictionary and concat dfs to create a giant df, so it probably breaks at that stage. So improving that could be a future step.  But also outside the scope of this bug/pr.

**Pull request merged**
