### PR TITLE
Issue #3882 Fixed

### PR DESCRIPTION
**Pull request by MertNuhuz**
# Description

- [x] Summary of the change / bug fix.
By using the "Alpha Vantage" source, it is now possible to receive data in weekly, monthly and desired interval formats.
- [x] Link # issue, if applicable.
[Issue #3882 ](https://github.com/OpenBB-finance/OpenBBTerminal/issues/3882) fixed
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
  - Interval image
  - Weekly image
  - Monthly image

- [ ] Relevant motivation and context.
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes.
* Provide instructions so we can reproduce.
* Please also list any relevant details for your test configuration.
- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by jmaslek** [comment]
Interesting.  Does this (i.e AlphaVantage) not provide the actual adjusted close for weekly/monthly?  I know you are using the adjusted endpoint.

Screenshot 2023-01-06 at 11 06 29 PM

**Review by jmaslek — CHANGES_REQUESTED** [review]
Nice!

You need to pass the linters.  You ca get black fixed by running `black ./`

And then can you add these options to the unit tests?  If you need help, just let me know!

**Comment by MertNuhuz** [comment]
@jmaslek, i wroted tests for checking all the stock listing available sources , can you check please :)

**Comment by jmaslek** [comment]
Awesome!  It looks like mypy was still failing.

Also as of today, we are merging PRs into `develop` instead of `main`, so I changed that.  There is a chance you may need to work from a branch that starts with `feature/` to pass the name check, but let me confirm that while you update the linters.

**Comment by MertNuhuz** [comment]
@jmaslek i solved the mypy errors, fyi

**Review by jmaslek — APPROVED** [review]

**Pull request merged**
