### PR TITLE
Changes to get `a7` out

### PR DESCRIPTION
**Pull request by hjoaquim**
^

### CODE REVIEW

**Review by the-praxs — APPROVED** [review]
LGTM 🚀

**Review by IgorWounds — APPROVED** [review]

**Comment by the-praxs** [comment]
@hjoaquim please hold off the merge until the `openbb-index` extension is added via the `feature/openbb-sdk-v4`.

**Comment by hjoaquim** [comment]
@IgorWounds @the-praxs this: https://github.com/OpenBB-finance/OpenBBTerminal/pull/5697/commits/1a0005f7f6bac5d192f45c85a6ac7a939e278b82
removes `ultima` from the pyproject.toml

**Comment by the-praxs** [comment]
@hjoaquim since we are updating the versions, make sure they are reflected in the markdown files too. Thanks!

**Comment by the-praxs** [comment]
@hjoaquim i resolved the conflicts but please double check the deps in case we are missing out anything!

**Pull request merged**
