### PR TITLE
Degiro fix

### LINKED ISSUE #2120: [Bug] Login Issues with Degiro Broker integration
### Issue

When attempting to use the Degiro integration while having provided succesfully my user name, password and otp secret, login fails with this output and no other actions are allowed.

```bash
2022 Jul 21, 13:16 (🦋) /portfolio/bro/degiro/ $ login
Error: 'NoneType' object is not callable

You are now logged in !

2022 Jul 21, 13:16 (🦋) /portfolio/bro/degiro/ $ topnews
Error: 'NoneType' object is not callable

Error: 'list' object has no attribute 'DESCRIPTOR'
```

### To reproduce
```bash
export OPENBB_DG_USERNAME={} OPENBB_DG_PASSWORD={} OPENBB_DG_TOTP_SECRET={}
/Applications/OpenBB\ Terminal/OpenBB\ Terminal
portfolio/bro/degiro
login
```
- OS: macOS Monterrey
- Python version 3.6.8

### Additional
I've tried using directly the `degiro_connector` library (the one your integration is using) and it was possible to login providing the same credentials. IMO we can discard that my account has a specific issue that makes the library fail.

image

### LINKED ISSUE #2241: [Bug] Add in a test to check if logging into DEGIRO works
**Describe the bug**
After settings my log-in details, trying to log-in within the `portfolio/bro/degiro` menu doesn't work. I don't have 2FA enabled on my DEGIRO account. See the following:

```
2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ login
Error: 400 Client Error: Bad Request for url: https://trader.degiro.nl/login/secure/login

You are now logged in !
2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $ hold
Error: Connection required.

0 position found.
2022 Aug 02, 09:47 (🦋) /portfolio/bro/degiro/ $
```

I noticed that there are no tests that check if the log-in works: `defined, not tested`. **In the end the issue was that I set my _email_ instead of _username_ so the conclusion is that there needs to be a proper test and ideally, something that checks you don't input your email.**

**To Reproduce**
What I did:

1. Set my DEGIRO credentials within `keys` as follows `degiro -u EMAIL -p PASSWORD`
2. Try to log-in.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

### PR DESCRIPTION
**Pull request by hjoaquim**
# Description

- [x] Summary of the change / bug fix.
- adds arguments to companynews
- adds verification on session_id for login/logout/holds
- forces reset session_id on logout and forces the DegiroModel object to re initialize
- adds test for degiro keys 

- [x] Link # issue, if applicable.
- [x] Relevant motivation and context. 
- fixes #2241 
- fixes #2120 

- [x] Screenshot of the feature or the bug before/after fix, if applicable.
image

- [ ] (**NA**) List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 

> Need to setup degiro keys: `username` and `password` (one time password optional) 

1. `keys`
2. `/portfolio/bro/degiro/`
3. `/portfolio/bro/degiro/login`
4. `/portfolio/bro/degiro/login/holds`
5. `/portfolio/bro/degiro/login/companynews` 
6. `/portfolio/bro/degiro/login/topnews` 

* Please also list any relevant details for your test configuration.
- Developed on ubuntu 20.04 (conda install)

- [x] Make sure affected commands still run in terminal
- [x] Ensure the api still works
- [x] Check any related reports

# Checklist:

- [ ] (**NA**) Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] (**NA**) If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by hjoaquim** [comment]
Fixing/updating tests ongoing

**Comment by hjoaquim** [comment]
Reminder : ping `kgoossens` in discord as soon as this PR is merged

**Review by montezdesousa — COMMENTED** [review]
Something not working with the key setup.

In this case I have the correct keys in .env, the menu help displays `defined, test passed`. This is fine!

But, if I set my keys with the command it gives `defined, test failed`. Then if I type `help`, the new menu prompt displays `defined, test failed` as well.

image



image

**Review by Chavithra — APPROVED** [review]
Looks good to me.

**Comment by montezdesousa** [comment]
Still getting 'defined, test failed' with correct keys...

I tried `login` afterwards and I get this message:

image

**Comment by hjoaquim** [comment]
@montezdesousa you might have your account blocked due to many login attempts

Hint: you might need to do `r` / `reset` / relaunch the terminal in order to get the defined, test passed. 

In the meantime I'm investigating this, let's keep this merged as it adds some improvements.

**Pull request merged**
