### PR TITLE
refactor: Refactor code and make code more pythonic and easier to read

### PR DESCRIPTION
**Pull request by Uzaaft**
The purpose of this PR is to generally, make the OpenBBTerminal project more pythonic, as well as in general get some easy performance gains by refactoring the code to use list-comprehensions, and other more pythonic methods

# Description

- [ ] Summary of the change / bug fix.
- [ ] Link # issue, if applicable.
- [ ] Screenshot of the feature or the bug before/after fix, if applicable.
- [ ] Relevant motivation and context. 
- [ ] List any dependencies that are required for this change.

# How has this been tested?

* Please describe the tests that you ran to verify your changes. 
* Provide instructions so we can reproduce. 
* Please also list any relevant details for your test configuration.

# Checklist:

- [ ] Update [our Hugo documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).
- [ ] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [ ] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [ ] If a feature was added make sure to add it to the corresponding [scripts file](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/scripts).

# Others
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My code passes all the checks pylint, flake8, black, ... To speed up development you should run `pre-commit install`.
- [ ] New and existing unit tests pass locally with my changes. You can test this locally using `pytest tests/...`.

### CODE REVIEW

**Comment by Uzaaft** [comment]
A step towards increasing performance could also be to migrate over to https://github.com/ijl/orjson . It seems like a faster alternative to json.

**Comment by Uzaaft** [comment]
Just a heads up: 
This might become a huge PR(due to the amount of files being changes).

**Comment by DidierRLopes** [comment]
Looking forward to this improvements, and to improve my python code myself 🙌🏽 

Thanks @Uzaaft !

**Comment by Uzaaft** [comment]
Managed to fuck up a merge locally 😅
Will be opening a new PR shortly

**Comment by DidierRLopes** [comment]
ahahah it happens! Been there done that 😄

**Pull request merged**
