### PR TITLE
Feature/sdk v4 pydantic v2

### PR DESCRIPTION
**Pull request by tehcoderer**
working with pydantic v2.

new PR with upstream branch

### CODE REVIEW

**Comment by the-praxs** [comment]
Current requirements to merge this PR -
- [ ] Check the models are up-to-date
- [ ] Ensure the duplicate tests pass
- [ ] Complete this https://github.com/OpenBB-finance/OpenBBTerminal/pull/5469#issuecomment-1734085678

**Comment by hjoaquim** [comment]
> Current requirements to merge this PR -
> 
>     * [ ]  Check the models are up-to-date
> 
>     * [ ]  Ensure the duplicate tests pass
> 
>     * [ ]  Complete this [Feature/integration tests #5469 (comment)](https://github.com/OpenBB-finance/OpenBBTerminal/pull/5469#issuecomment-1734085678)

Also needs to test:
- integration / unit tests generators

**Review by IgorWounds — APPROVED** [review]
Works fine for me. The same tests fall with the non-v2 version.

**Comment by the-praxs** [comment]
Weirdly the tests fail locally for me. I don't understand the reason but since they are passing in CI, I believe this is good to go for merging!

**Review by the-praxs — APPROVED** [review]
@tehcoderer thanks for making this work. We owe you a lot!

**Review by hjoaquim — APPROVED** [review]
We :moon: at noon

**Pull request merged**
