### PR TITLE
Removing expo model from predictions until forecast menu (mac dependancy issue)

### PR DESCRIPTION
**Pull request by martinb-bb**
# Description
Removing expo smoothing from /stocks/pred/ menu for now due to issues with Mac installers.

Will sort out issue with new forecasting menu release. 

Please pull env, install with poetry and make sure we hit no other dependency issues.

### CODE REVIEW

**Review by jmaslek — APPROVED** [review]
byeeeeeeeeeeeeeeeeeee

**Comment by jmaslek** [comment]
wait you also need to take out of scripts ?

**Comment by martinb-bb** [comment]
Why not? Haha . Already in my new branch. Less confusion for people contributing in the future.

**Comment by martinb-bb** [comment]
Please make sure everything works on your end before merging.

**Comment by jmaslek** [comment]
> Please make sure everything works on your end before merging.

but that's no fun

**Comment by martinb-bb** [comment]
Live life on the edge

**Comment by jmaslek** [comment]
works for me just fine, but I didn't uninstall darts or torch and I dont really wanna mess with the env

**Pull request merged**
