### PR TITLE
Renaming `api` to `sdk`

### PR DESCRIPTION
**Pull request by hjoaquim**
# Description

This PR aims to rename/refactor `openbb api` to `openbb sdk`.

Changes:

- [x] rename `api.py` to `sdk.py`
- [x] vs-code auto refactor all `.py` files that use it
- [x] manual rename on reports (`.ipynb` files)
- [x] update documentation
- [x] update GitHub tags

# Testing

- [x] pass all unit tests
- [ ] pass all integration tests
- [x] check if reports don't break
- [x] check if dashboards don't break
- [x] check if `sdk` runs with no issues
- [ ] build a local installer and run some commands
- [x] check if website docs building/working properly

### CODE REVIEW

**Comment by hjoaquim** [comment]
@colin99d what do we need to re-generate the docs on the website?

**Comment by colin99d** [comment]
`python docs/generate.py`

**Review by Chavithra — APPROVED** [review]
Looks good to me.

**Comment by jmaslek** [comment]
Everything else is looking good.  Great work

**Pull request merged**
