### PR TITLE
Adding SDK Installation Method to Hugo

### PR DESCRIPTION
**Pull request by simmonsj330**
# Description

Simple Update to SDK documentation by adding the installation method to `_index.md` that will be populated on Hugo.

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by jose-donato — APPROVED** [review]

**Comment by simmonsj330** [comment]
We will wait until the SDK is available on PyPi to merge this.

**Comment by minhhoang1023** [comment]
@simmonsj330 nice job! The instruction is clear and easy to follow.

Agree that we should only merge it when it's on PyPi. And we should test one more time too, to make sure things all work.

**Comment by deeleeramone** [comment]
I'm going to take this section and use it as part of a re-written SDK introduction page.

**Comment by simmonsj330** [comment]
> I'm going to take this section and use it as part of a re-written SDK introduction page.

@deeleeramone @JerBouma does that mean we should delete this PR?

**Comment by JerBouma** [comment]
@andrewkenreich ?

**Comment by Chavithra** [comment]
Look like this content has been copied in the new documentation.
Closing this PR.

**Pull request closed without merging**
