### PR TITLE
New table design

### PR DESCRIPTION
**Pull request by jose-donato**
TODO:
* show toast when columns are hidden --- **fixed**
* `stocks/fa/income` - improve formatting so doesnt catch these numbers --- **fixed**
* index shouldn't have date filter --- **fixed**
image

* `stocks/fa/income -l 30` too many columns shown by default --- **fixed**
image

### CODE REVIEW

**Comment by andrewkenreich** [comment]
image


On stocks/dps/pos and a few others we can only sort on the last 2 columns and index, first 4 dont let you

**Comment by jmaslek** [comment]
Reminders for me to check:

- [ ] urls
- [ ] long entries (like fred -q {} )

**Comment by deeleeramone** [comment]
There is a need to auto-fit column width for content. 

`/econ/performance`

Screenshot 2023-03-21 at 11 49 04 PM

**Comment by deeleeramone** [comment]
The space at the top, IMO, takes up too much of my precious screen space.

Screenshot 2023-03-22 at 12 00 12 AM

Font size adjustments has unintended consequences. 

Screenshot 2023-03-22 at 12 04 33 AM

**Comment by deeleeramone** [comment]
The feature flag to turn off the interactive tables makes the terminal fail.


Screenshot 2023-03-22 at 12 20 26 AM

Enabling it returns results.

**Comment by deeleeramone** [comment]
Columns are missing, and it should not be considered "advanced" to see all the data in a table. The table needs to dynamically sized for the content and column headers should respect the boundaries of the column width.

Screenshot 2023-03-22 at 12 29 18 AM

Before:
Screenshot 2023-03-22 at 12 22 57 AM

After:
Screenshot 2023-03-22 at 12 25 18 AM

**Review by jmaslek — APPROVED** [review]

**Comment by jmaslek** [comment]
For you @jose-donato chart height:
Screenshot 2023-03-22 at 4 19 48 PM

**Comment by deeleeramone** [comment]
> For you @jose-donato chart height: Screenshot 2023-03-22 at 4 19 48 PM

Can we do away with the `watermark` now?

**Comment by jmaslek** [comment]
> Can we do away with the `watermark` now?

patience

**Comment by deeleeramone** [comment]
This doesn't actually solve the problem. The solution is to be able to scroll to the right on the PyWry window.  

Screenshot 2023-03-22 at 2 11 40 PM


> Columns are missing, and it should not be considered "advanced" to see all the data in a table. The table needs to dynamically sized for the content and column headers should respect the boundaries of the column width.
> 
> Screenshot 2023-03-22 at 12 29 18 AM
> 
> Before: Screenshot 2023-03-22 at 12 22 57 AM
>

**Pull request merged**
