### PR TITLE
Make adjustments to the guides

### PR DESCRIPTION
**Pull request by JerBouma**
This does the following:

- We were calling basic functionality "Advanced". Instead, this is now called "Guides". This comes after the "Basics" so that if you'd follow this path you will know how to work with these guides. E.g. not introduce how to export data before introducing how to even run a command.
- Smaller updates to the guides. The general story remains intact, just moved some things around or removed a bit of content that was no longer relevant.
- Updated the `about` command so that it reflects the new path.

image

### CODE REVIEW

**Comment by JerBouma** [comment]
This should be the final version (for now). Please let me know if any comments then we can put this section on done. @deeleeramone @jmaslek

**Comment by deeleeramone** [comment]
> This should be the final version (for now). Please let me know if any comments then we can put this section on done. @deeleeramone @jmaslek

The #basics section needs to be cleaned out, it also has: 
- basics#importing-and-exporting-data
- basics#expanding-the-terminal-with-api-keys

**Comment by JerBouma** [comment]
Done

**Comment by JerBouma** [comment]
> Section titles should be capitalized as a Title. Each word should be capitalized unless the word is something like, "the", "in", "a". Generally, words <= 3 letters are not capitalized in a title unless it is the first word.
> 
> Screenshot 2023-03-14 at 11 15 43 AM
> 

This is not part of this, solely "Usage of the OpenBB Terminal" and "Usage of the OpenBB SDK". Please speak with Theodore about this.

**Comment by deeleeramone** [comment]
This title does not read properly, it should be "Settings & API Keys", or "Setting API Keys"

Screenshot 2023-03-14 at 11 20 31 AM

**Comment by JerBouma** [comment]
> This title does not read properly, it should be "Settings & API Keys", or "Setting API Keys"
> 
> Screenshot 2023-03-14 at 11 20 31 AM
> 

Also not part of this, falls under James. Please see the document about it.

**Comment by deeleeramone** [comment]
> This is not part of this, solely "Usage of the OpenBB Terminal" and "Usage of the OpenBB SDK". Please speak with Theodore about this.

Other sections, like "Customization" and "Changing Sources" also have this.

**Comment by JerBouma** [comment]
What should it be renamed to

**Comment by deeleeramone** [comment]
> Also not part of this, falls under James. Please see the document about it.

Should be removed from "Guides" then.

**Comment by JerBouma** [comment]
Speak with James.

**Comment by deeleeramone** [comment]
> What should it be renamed to

The Section Titles Need to be Capitalized as a Title

**Comment by JerBouma** [comment]
Done

**Comment by deeleeramone** [comment]
`overwrite whether to automatically overwrite Excel files if prompted to (default is off).`

Is this exclusive to Excel files, or is it for all exported files?

**Comment by deeleeramone** [comment]
Last item in scope is the screenshot for: basics#explanation-of-menus

Let's update this to be current, while we're here.

**Comment by JerBouma** [comment]
Done

**Review by deeleeramone — APPROVED** [review]

**Pull request merged**
