### PR TITLE
Fixed Polygon API key authentication URL

### LINKED ISSUE #4747: [Bug] Polygon API key test failed for Basic plan keys
**Describe the bug**
When entering the Polygon API key from the Basic plan, the test fails and returns `Defined, test failed`. This is because the `check_polygon_key` function in `keys_model.py` fails to account for the recent created keys.

```python
if current_user.credentials.API_POLYGON_KEY == "REPLACE_ME":
    logger.info("Polygon key not defined")
    status = KeyStatus.NOT_DEFINED
else:
    r = request(
        f"https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2020-06-01/2020-06-17"
        f"?apiKey={current_user.credentials.API_POLYGON_KEY}"
    )
    if r.status_code in [403, 401]:
        logger.warning("Polygon key defined, test failed")
        status = KeyStatus.DEFINED_TEST_FAILED
```

When checking the URL manually it returns this error - 
`{"status":"NOT_AUTHORIZED","request_id":"1e2a4e1c68224da666232d16699b7fd7","message":"Your plan doesn't include this data timeframe. Please upgrade your plan at https://polygon.io/pricing"}`

**To Reproduce**
Enter `keys` menu and add key using the `polygon -k <YOUR_API_KEY>` command.

**Screenshots**
image

**Desktop:**

- OS: Manjaro Linux
- Python 3.10.9

**Additional context**
Authentication using the provided date is too old. This can be fixed by using the current date.

### PR DESCRIPTION
**Pull request by the-praxs**
# Description

- [x] Modified the URL to use the 1st day of the current month and year
- [x] Fixes #4747 
- [x] image

# How has this been tested?
Checking multiple keys using the command `keys\polygon -k <API_KEY>`

- [x] Make sure affected commands still run in terminal
- [x] Ensure the SDK still works
- [x] Check any related reports

# Checklist:

- [x] I have adhered to the GitFlow naming convention and my branch name is in the format of `feature/feature-name` or `hotfix/hotfix-name`.
- [x] Update [our documentation](https://openbb-finance.github.io/OpenBBTerminal/) following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/website).  Update any user guides that are affected by the changes.
- [x] Update our tests following [these guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/tests).
- [x] Make sure you are following our [CONTRIBUTING guidelines](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md).
- [x] If a feature was added make sure to add it to the corresponding [integration test script](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/miscellaneous/integration_tests_scripts).

# Others
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by the-praxs** [comment]
@hjoaquim please tell me where the Linting test is failing.

**Comment by colin99d** [comment]
> @hjoaquim please tell me where the Linting test is failing.

`openbb_terminal/keys_model.py:6:1: I001 [*] Import block is un-sorted or un-formatted`
Looks like we just need to sort the imports. To fix this run the following:
1. `pip install ruff`
2. `ruff . --fix`

Thank you for this PR!

**Comment by the-praxs** [comment]
@colin99d thank you for the info! Fixed and committed.

**Comment by colin99d** [comment]
Screenshot 2023-04-12 at 9 25 35 AM
This works for me!

**Review by colin99d — APPROVED** [review]

**Pull request merged**
